"""Additional curated local assistant knowledge for SymptoSense V60.

This module expands deterministic/offline assistant coverage for common health
questions. Content is educational, non-diagnostic, and source-linked to NHS
patient information. The assistant should still defer to emergency triage and
should not use these entries to make a diagnosis.
"""

# Row schema (kept compatible with webapp.ASSISTANT_EXTRA_SYMPTOMS):
# (ar_title, en_title, aliases, ar_answer, en_answer,
#  ar_followup, en_followup, source_url)

ASSISTANT_EXTRA_SYMPTOMS_V60 = [
    (
        "التهاب الجيوب الأنفية", "Sinusitis",
        ["جيوب انفيه", "جيوب أنفية", "التهاب الجيوب", "ضغط الجيوب", "ضغط حول العين", "وجع الجيوب",
         "sinusitis", "sinus pressure", "sinus infection", "face pressure"],
        "أعراض الجيوب قد تشمل انسداد أو سيلان الأنف مع ضغط أو ألم حول الخدين أو العينين أو الجبهة، وغالبًا تأتي بعد زكام. لا يمكن تأكيد السبب من الأعراض وحدها.",
        "Sinus symptoms can include a blocked or runny nose with pressure or pain around the cheeks, eyes, or forehead, often after a cold. Symptoms alone cannot confirm the cause.",
        "هل لديك انسداد أو إفرازات من الأنف، وكم استمرت الأعراض؟", "Do you have nasal blockage or discharge, and how long have symptoms lasted?",
        "https://www.nhs.uk/conditions/sinusitis-sinus-infection/",
    ),
    (
        "نزيف الأنف", "Nosebleed",
        ["رعاف", "نزيف الانف", "نزيف الأنف", "دمي من خشمي", "خشمي ينزف", "nosebleed", "nose bleeding"],
        "نزيف الأنف شائع وغالبًا يمكن إيقافه بالجلوس مع الميل للأمام والضغط على الجزء اللين من الأنف 10 إلى 15 دقيقة. اطلب رعاية عاجلة إذا كان النزف غزيرًا، استمر رغم الضغط، بدأ بعد إصابة قوية بالرأس، أو صاحبه ضعف أو دوخة أو صعوبة تنفس.",
        "Nosebleeds are common and can often be managed by sitting forward and pinching the soft part of the nose for 10 to 15 minutes. Seek urgent care for heavy bleeding, bleeding that does not stop, a significant head injury, weakness/dizziness, or breathing difficulty.",
        "هل توقف النزف بعد الضغط المتواصل، وهل تتناول أدوية مميعة للدم؟", "Did the bleeding stop after continuous pressure, and do you take blood-thinning medicine?",
        "https://www.nhs.uk/conditions/nosebleed/",
    ),
    (
        "جفاف الفم", "Dry mouth",
        ["جفاف الفم", "فمي ناشف", "فمي جاف", "نشوفة الفم", "dry mouth", "mouth dry"],
        "جفاف الفم قد يرتبط بالجفاف أو التنفس من الفم أو بعض الأدوية أو أسباب أخرى. جرّب شرب الماء على دفعات واهتم بنظافة الفم، ولا توقف دواءً موصوفًا بسبب الجفاف دون مراجعة مختص.",
        "Dry mouth can relate to dehydration, mouth breathing, some medicines, or other causes. Sip water regularly and maintain oral hygiene; do not stop a prescribed medicine because of dry mouth without medical advice.",
        "هل الجفاف مستمر طوال اليوم أم أكثر عند الاستيقاظ؟", "Is the dryness present all day or mainly on waking?",
        "https://www.nhs.uk/symptoms/dry-mouth/",
    ),
    (
        "رائحة الفم", "Bad breath",
        ["ريحة الفم", "رائحة الفم", "نفسي ريحته", "ريحة فمي", "bad breath", "halitosis"],
        "رائحة الفم قد ترتبط بنظافة الفم والأسنان أو اللثة أو جفاف الفم أو بعض الأطعمة وأسباب أخرى. إذا استمرت رغم العناية اليومية أو معها ألم أسنان أو نزف أو تورم باللثة، ففحص الأسنان مناسب.",
        "Bad breath can relate to oral hygiene, teeth or gum problems, dry mouth, foods, or other causes. If it persists despite daily oral care or comes with tooth pain or bleeding/swollen gums, dental review is appropriate.",
        "هل معها نزيف لثة أو ألم أسنان أو جفاف بالفم؟", "Is there gum bleeding, tooth pain, or dry mouth?",
        "https://www.nhs.uk/symptoms/bad-breath/",
    ),
    (
        "عسر الهضم", "Indigestion",
        ["عسر الهضم", "ثقل بعد الاكل", "ثقل بعد الأكل", "تجشؤ بعد الاكل", "نفخة بعد الاكل", "indigestion", "dyspepsia", "full after eating"],
        "عسر الهضم قد يظهر كحرقة أو امتلاء وانتفاخ أو غثيان وتجشؤ بعد الأكل. راجع مختصًا إذا تكرر كثيرًا أو صاحبه ألم شديد، صعوبة بلع، قيء متكرر، نزول وزن غير مقصود، أو دم في القيء أو البراز.",
        "Indigestion may feel like heartburn, fullness, bloating, nausea, or burping after food. Seek medical review if it keeps recurring or comes with severe pain, swallowing difficulty, repeated vomiting, unintentional weight loss, or blood in vomit/stool.",
        "هل الأعراض تأتي بعد وجبات محددة أو عند الاستلقاء؟", "Do symptoms happen after particular meals or when lying down?",
        "https://www.nhs.uk/conditions/indigestion/",
    ),
    (
        "تسمم غذائي", "Food poisoning",
        ["تسمم غذائي", "اكلت شي وخرب بطني", "أكلت شي وخرب بطني", "استفراغ واسهال بعد الاكل", "food poisoning", "food poisoning symptoms"],
        "التسمم الغذائي غالبًا يسبب غثيانًا أو قيئًا أو إسهالًا وألم بطن وقد يبدأ بعد ساعات أو أيام من الطعام الملوث. أهم شيء تعويض السوائل؛ اطلب تقييمًا إذا لم تستطع الاحتفاظ بالسوائل، ظهر دم، أو استمر القيء أو الإسهال بشكل مقلق.",
        "Food poisoning commonly causes nausea/vomiting, diarrhoea, and tummy pain and may start hours or days after contaminated food. Fluids are important; seek care if you cannot keep fluids down, see blood, or vomiting/diarrhoea persists.",
        "هل تستطيع الاحتفاظ بالسوائل، وهل يوجد دم أو حرارة مرتفعة؟", "Can you keep fluids down, and is there blood or a high temperature?",
        "https://www.nhs.uk/conditions/food-poisoning/",
    ),
    (
        "عدم تحمل الطعام", "Food intolerance",
        ["عدم تحمل الطعام", "طعام يتعب بطني", "اكل معين ينفخني", "أكل معين ينفخني", "food intolerance", "food makes me bloated"],
        "عدم تحمل بعض الأطعمة قد يسبب انتفاخًا أو إسهالًا أو ألم بطن بعد الطعام، وهو يختلف عن حساسية الطعام. لا تحذف مجموعات غذائية مهمة لفترة طويلة دون توجيه؛ تتبع الطعام والأعراض قد يساعد على ملاحظة النمط.",
        "Food intolerance can cause bloating, diarrhoea, or tummy pain after certain foods and is different from food allergy. Avoid long-term restrictive diets without guidance; a food-and-symptom diary can help identify patterns.",
        "هل يتكرر بعد نفس الطعام، وهل يوجد تورم أو صفير أو صعوبة تنفس؟", "Does it recur after the same food, and is there swelling, wheeze, or breathing difficulty?",
        "https://www.nhs.uk/conditions/food-intolerance/",
    ),
    (
        "حساسية الأنف", "Hay fever / allergic rhinitis",
        ["حساسية الانف", "حساسية الأنف", "عطاس كثير", "رشح تحسس", "حساسية الربيع", "hay fever", "allergic rhinitis", "pollen allergy"],
        "حساسية الأنف قد تسبب عطاسًا وسيلانًا أو انسدادًا بالأنف مع حكة أو دموع بالعينين، وقد تستمر أكثر من الزكام العادي. إذا أثرت كثيرًا على النوم أو النشاط أو صاحبها صفير أو ضيق نفس فراجع مختصًا.",
        "Allergic rhinitis can cause sneezing, a runny/blocked nose, and itchy or watery eyes, often lasting longer than a typical cold. Seek review if it significantly affects sleep/daily life or comes with wheeze or breathlessness.",
        "هل تزداد الأعراض في موسم أو مكان معين أو مع الغبار؟", "Are symptoms worse in a particular season/place or around dust?",
        "https://www.nhs.uk/conditions/hay-fever/",
    ),
    (
        "عدم انتظام الدورة", "Irregular periods",
        ["الدورة غير منتظمة", "دورتي غير منتظمه", "الدوره تتقدم وتتأخر", "الدورة تتقدم وتتأخر", "irregular periods", "irregular menstrual cycle"],
        "تغيّر مواعيد الدورة قد يحدث مع الضغط النفسي أو تغيّر الوزن أو وسائل منع الحمل أو مراحل عمرية مختلفة، وله أسباب أخرى أيضًا. إذا تغيّر نمطك المعتاد بوضوح أو استمر عدم الانتظام فالتقييم الطبي يساعد على معرفة السبب.",
        "Period timing can change with stress, weight changes, contraception, life stage, and other causes. If your usual pattern has clearly changed or irregularity persists, medical review can help identify the reason.",
        "منذ متى أصبحت الدورة غير منتظمة، وهل يوجد احتمال حمل؟", "How long have your periods been irregular, and is pregnancy possible?",
        "https://www.nhs.uk/symptoms/irregular-periods/",
    ),
    (
        "تأخر الدورة", "Missed or late period",
        ["الدورة متأخرة", "دورتي متأخره", "تأخرت الدورة", "ما نزلت الدورة", "missed period", "late period", "period late"],
        "تأخر الدورة له أسباب متعددة، والحمل أحد الاحتمالات إذا كان ممكنًا. إذا تأخرت الدورة بشكل متكرر أو فاتتك عدة دورات، أو ظهرت أعراض أخرى مثل تغيّر وزن واضح أو تعب مستمر، فالتقييم الطبي مناسب.",
        "A late or missed period has many possible causes, including pregnancy when relevant. If periods repeatedly go missing or several are missed, or there are other symptoms such as major weight change or persistent tiredness, medical review is appropriate.",
        "كم يوم تأخرت عن موعدك المعتاد، وهل يوجد احتمال حمل؟", "How many days late is it compared with your usual cycle, and is pregnancy possible?",
        "https://www.nhs.uk/symptoms/missed-or-late-periods/",
    ),
    (
        "التعرق الليلي", "Night sweats",
        ["تعرق ليلي", "عرق بالليل", "اصحى معرق", "أصحى معرق", "اصحى معرق بالليل", "أصحى معرق بالليل", "night sweats", "sweating at night"],
        "التعرق ليلًا قد يكون طبيعيًا إذا كانت الغرفة أو الأغطية حارة، لكن التعرق الذي يبلل الملابس أو الفراش بشكل متكرر يستحق التقييم، خصوصًا إذا صاحبه حرارة أو سعال أو نزول وزن غير مقصود.",
        "Night sweating can be normal if the room or bedding is too warm, but repeated soaking night sweats deserve assessment, especially with fever, cough, or unintentional weight loss.",
        "هل يحدث رغم أن الغرفة باردة، وهل يصاحبه حرارة أو فقدان وزن؟", "Does it happen even in a cool room, and is there fever or weight loss?",
        "https://www.nhs.uk/symptoms/night-sweats/",
    ),
    (
        "تورم القدمين أو الساقين", "Swollen ankles, feet or legs",
        ["تورم القدم", "تورم الرجل", "تورم الساق", "رجولي منتفخه", "قدمي متورمه", "swollen ankles", "swollen feet", "leg swelling", "oedema", "edema"],
        "تورم القدمين أو الساقين قد يرتبط بالجلوس أو الوقوف الطويل، الحمل، بعض الأدوية، إصابة أو أسباب صحية أخرى. التورم المفاجئ أو الشديد، خصوصًا في جهة واحدة، أو مع احمرار/سخونة يحتاج تقييمًا سريعًا؛ ومع ضيق نفس أو ألم صدر اطلب الطوارئ.",
        "Swollen feet or legs can relate to prolonged sitting/standing, pregnancy, some medicines, injury, or other health causes. Sudden/severe swelling, especially on one side or with redness/heat, needs prompt review; swelling with breathlessness or chest pain is an emergency.",
        "هل التورم في جهة واحدة أم الجهتين، وهل بدأ فجأة؟", "Is the swelling on one side or both, and did it start suddenly?",
        "https://www.nhs.uk/conditions/oedema/",
    ),
    (
        "ألم الكعب", "Heel pain",
        ["ألم الكعب", "الم الكعب", "كعبي يوجعني", "وجع تحت الكعب", "heel pain", "pain under heel"],
        "ألم الكعب قد ينتج عن إجهاد أو مشكلات بالأنسجة حول القدم، ولا يمكن تحديد السبب من مكان الألم وحده. راجع مختصًا إذا كان شديدًا أو مستمرًا أو يمنع المشي، أو إذا بدأ بعد إصابة قوية.",
        "Heel pain can result from overuse or problems in tissues around the foot; location alone cannot identify the cause. Seek review if pain is severe, persistent, stops you walking, or followed a significant injury.",
        "هل الألم أسوأ مع أول خطوات بعد الراحة، وهل سبقته إصابة؟", "Is it worse with the first steps after rest, and was there an injury?",
        "https://www.nhs.uk/symptoms/foot-pain/heel-pain/",
    ),
    (
        "ألم الركبة", "Knee pain",
        ["الم الركبه", "ألم الركبة", "ركبتي توجعني", "وجع الركبه", "knee pain", "knee hurts"],
        "ألم الركبة له أسباب كثيرة مثل الإجهاد أو الإصابة أو مشكلات المفصل. إذا كانت الركبة تقفل أو تخونك أو متورمة جدًا أو لا تستطيع تحميل الوزن عليها، أو كانت حارة وحمراء مع حرارة بالجسم، فاطلب تقييمًا عاجلًا.",
        "Knee pain has many causes, including overuse, injury, and joint problems. Seek urgent assessment if the knee locks/gives way, is very swollen, you cannot bear weight, or it is hot/red with fever.",
        "هل بدأ بعد إصابة، وهل يوجد تورم أو قفل أو عدم ثبات؟", "Did it start after an injury, and is there swelling, locking, or instability?",
        "https://www.nhs.uk/symptoms/knee-pain/",
    ),
    (
        "ألم الكتف", "Shoulder pain",
        ["ألم الكتف", "الم الكتف", "كتفي يوجعني", "كتفي يعورني", "shoulder pain", "shoulder hurts"],
        "ألم الكتف قد يكون من إجهاد أو مشكلة في الأوتار أو المفصل أو إصابة. إذا كان الألم شديدًا فجأة، لا تستطيع تحريك الذراع، تغيّر شكل الكتف، أو ظهر تنميل مستمر أو فقدان إحساس فاطلب تقييمًا عاجلًا.",
        "Shoulder pain can come from overuse, tendon/joint problems, or injury. Seek urgent care for sudden severe pain, inability to move the arm, deformity, persistent pins-and-needles, or loss of feeling.",
        "هل تستطيع رفع الذراع فوق مستوى الكتف، وهل سبق الألم سقوط أو إصابة؟", "Can you raise the arm above shoulder level, and did the pain follow a fall or injury?",
        "https://www.nhs.uk/symptoms/shoulder-pain/",
    ),
    (
        "ألم الرسغ", "Wrist pain",
        ["ألم الرسغ", "الم الرسغ", "معصمي يوجعني", "وجع المعصم", "wrist pain", "wrist hurts"],
        "ألم الرسغ قد يحدث بعد إجهاد أو إصابة أو التهاب أو ضغط على الأعصاب. إذا كان شديدًا بعد إصابة، تغيّر شكل الرسغ، فقدت الإحساس، أو لا تستطيع تحريكه أو الإمساك بالأشياء، فاطلب تقييمًا عاجلًا.",
        "Wrist pain can follow overuse, injury, inflammation, or nerve pressure. Seek urgent assessment for severe post-injury pain, deformity, loss of feeling, or inability to move the wrist or grip objects.",
        "هل يوجد تنميل بالأصابع أو ضعف في القبضة، وهل سبقته إصابة؟", "Is there finger numbness or weak grip, and was there an injury?",
        "https://www.nhs.uk/symptoms/hand-pain/wrist-pain/",
    ),
    (
        "ألم الثدي", "Breast pain",
        ["الم الثدي", "ألم الثدي", "وجع الثدي", "صدري يعورني من الثدي", "breast pain", "sore breast"],
        "ألم الثدي شائع وغالبًا لا يكون بسبب مشكلة خطيرة، وقد يرتبط بالدورة أو الهرمونات أو شد عضلي أو أسباب أخرى. يحتاج تقييمًا أسرع إذا كان معه احمرار وسخونة وتورم، كتلة صلبة، إفراز دموي من الحلمة، أو تغير واضح في شكل أو جلد الثدي.",
        "Breast pain is common and is often not serious; it can relate to periods/hormones, muscle strain, or other causes. Seek prompt review for redness/heat/swelling, a hard lump, blood-stained nipple discharge, or a clear breast/skin change.",
        "هل الألم مرتبط بموعد الدورة، وهل يوجد كتلة أو تغير بالجلد أو الحلمة؟", "Does pain relate to your period, and is there a lump or nipple/skin change?",
        "https://www.nhs.uk/symptoms/breast-pain/",
    ),
    (
        "كتلة في الثدي", "Breast lump",
        ["كتله في الثدي", "كتلة في الثدي", "كتلة بالصدر", "لقيت كتلة في الثدي", "breast lump", "lump in breast"],
        "أي كتلة جديدة في الثدي أو الإبط تستحق فحصًا طبيًا حتى لو لم تكن مؤلمة. معظم الكتل ليست خطيرة، لكن لا يمكن معرفة السبب باللمس أو الوصف وحده، لذلك لا تحاول تشخيصها بنفسك.",
        "Any new lump in the breast or armpit should be medically checked even if it is painless. Most lumps are not serious, but the cause cannot be identified from touch or description alone, so do not self-diagnose it.",
        "منذ متى لاحظت الكتلة، وهل يوجد تغير في الحلمة أو الجلد أو إفراز؟", "How long has the lump been present, and is there any nipple/skin change or discharge?",
        "https://www.nhs.uk/symptoms/breast-lump/",
    ),
    (
        "نزف من المستقيم", "Rectal bleeding",
        ["دم مع البراز", "دم في البراز", "نزيف من الشرج", "دم على المناديل", "rectal bleeding", "blood in stool", "blood on toilet paper"],
        "وجود دم مع البراز له أسباب متعددة ولا ينبغي افتراض السبب. إذا كان النزف غزيرًا أو مستمرًا، أو كانت هناك جلطات كبيرة أو دوخة/إغماء فاطلب مساعدة عاجلة؛ وإذا تكرر أو استمر فاحجز تقييمًا طبيًا.",
        "Blood with stool has several possible causes and should not be self-diagnosed. Seek urgent help for heavy/non-stop bleeding, large clots, dizziness or fainting; recurrent or persistent bleeding should be medically assessed.",
        "هل الدم أحمر فاتح أم داكن/أسود، وهل النزف كثير أو متكرر؟", "Is the blood bright red or dark/black, and is the bleeding heavy or recurrent?",
        "https://www.nhs.uk/symptoms/bleeding-from-the-bottom-rectal-bleeding/",
    ),
    (
        "فقدان أو تغير حاسة الشم", "Lost or changed sense of smell",
        ["فقدت الشم", "ما اشم", "ما أشم", "تغير الشم", "ريحة الاشياء تغيرت", "lost smell", "loss of smell", "changed smell", "anosmia"],
        "فقدان أو تغير الشم قد يحدث مع الزكام أو التهابات الجيوب أو الحساسية أو أسباب أخرى، وغالبًا يتحسن مع الوقت. إذا لم يعد الشم لطبيعته خلال أسابيع أو لم يكن هناك سبب واضح، فالتقييم الطبي مناسب.",
        "Loss or change of smell can happen with colds, sinusitis, allergies, or other causes and often improves with time. If it does not return over a few weeks or there is no clear reason, medical review is appropriate.",
        "هل بدأ مع زكام أو انسداد بالأنف، وهل فقدان الشم كامل أم جزئي؟", "Did it start with a cold or blocked nose, and is the smell loss complete or partial?",
        "https://www.nhs.uk/symptoms/lost-or-changed-sense-smell/",
    ),
    (
        "صرير الأسنان أو شد الفك", "Teeth grinding / jaw clenching",
        ["اصر على اسناني", "أصر على أسناني", "اضغط على اسناني", "أضغط على أسناني", "شد الفك", "صرير الاسنان", "صرير الأسنان", "teeth grinding", "bruxism", "jaw clenching"],
        "صرير الأسنان أو شد الفك قد يرتبط بالتوتر أو النوم أو عادات أخرى، وقد يسبب ألمًا بالفك أو صداعًا أو حساسية بالأسنان. إذا سبب ألمًا متكررًا أو تلفًا بالأسنان أو أخبرك أحد أنك تطحن أسنانك أثناء النوم، فمراجعة طبيب الأسنان مناسبة.",
        "Teeth grinding or jaw clenching can relate to stress, sleep, or other factors and may cause jaw pain, headache, or tooth sensitivity. Dental review is appropriate if it causes repeated pain, tooth damage, or happens during sleep.",
        "هل يحدث أكثر أثناء النوم، وهل لديك ألم بالفك صباحًا أو صداع؟", "Is it mainly during sleep, and do you wake with jaw pain or headache?",
        "https://www.nhs.uk/symptoms/teeth-grinding/",
    ),
    (
        "طعم معدني في الفم", "Metallic taste",
        ["طعم معدني", "طعم حديد", "طعم معدن في الفم", "احس بطعم حديد", "metallic taste", "metal taste"],
        "الطعم المعدني قد يحدث مع مشكلات اللثة أو بعض الأدوية أو الزكام والجيوب أو عسر الهضم أو الحمل، وأحيانًا دون سبب واضح. لا توقف دواءً موصوفًا من نفسك؛ راجع مختصًا إذا استمر الطعم أو لم يكن له سبب واضح.",
        "A metallic taste can happen with gum problems, some medicines, colds/sinus issues, indigestion, pregnancy, or sometimes no obvious cause. Do not stop prescribed medicine on your own; seek review if it persists or has no clear explanation.",
        "هل بدأ بعد دواء جديد أو زكام، وهل توجد مشكلة بالأسنان أو اللثة؟", "Did it start after a new medicine or cold, and are there dental or gum problems?",
        "https://www.nhs.uk/symptoms/metallic-taste/",
    ),
    (
        "الزكام", "Common cold",
        ["زكام", "رشح", "نزله برد", "نزلة برد", "برد", "common cold", "cold symptoms", "runny nose cold"],
        "الزكام غالبًا يبدأ تدريجيًا مع انسداد أو سيلان الأنف وعطاس وألم حلق أو سعال خفيف، وعادة يتحسن خلال أسبوع إلى أسبوعين. اطلب تقييمًا إذا ظهرت صعوبة تنفس، ألم صدر، تدهور واضح، أو استمرت الأعراض بشكل غير معتاد.",
        "A common cold usually develops gradually with a blocked/runny nose, sneezing, sore throat, or mild cough and often improves within 1 to 2 weeks. Seek review for breathing difficulty, chest pain, clear worsening, or unusually persistent symptoms.",
        "منذ متى بدأت الأعراض، وهل لديك حرارة مرتفعة أو ضيق تنفس؟", "How long have symptoms been present, and is there a high fever or breathlessness?",
        "https://www.nhs.uk/conditions/common-cold/",
    ),
    (
        "ألم المفاصل", "Joint pain",
        ["الم المفاصل", "ألم المفاصل", "مفاصلي توجعني", "وجع المفاصل", "joint pain", "aching joints"],
        "ألم المفاصل قد يأتي من إجهاد أو إصابة أو التهاب أو أسباب أخرى، ولا تكفي الأعراض وحدها لتحديد النوع. إذا كان المفصل أحمر وحارًا ومتورمًا مع حرارة بالجسم، أو لا تستطيع استخدامه بعد إصابة، فاطلب تقييمًا سريعًا.",
        "Joint pain can follow overuse, injury, inflammation, or other causes, and symptoms alone cannot identify the type. Seek prompt review for a hot/red/swollen joint with fever, or inability to use the joint after injury.",
        "هل الألم في مفصل واحد أم عدة مفاصل، وهل يوجد تورم أو تيبس صباحي؟", "Is the pain in one joint or several, and is there swelling or morning stiffness?",
        "https://www.nhs.uk/symptoms/joint-pain/",
    ),
]


# Common modifier/context combinations that should be answered as a full phrase
# rather than reduced to a single keyword.
ASSISTANT_CONTEXT_PATTERNS_V60 = [
    {
        "ar_any": ["دوخه", "دوار", "ادوخ", "دايخ"],
        "ar_context": ["لما اقوم", "لما أقوم", "بعد ما اقوم", "بعد ما أقوم", "عند الوقوف", "اذا وقفت", "إذا وقفت"],
        "en_any": ["dizzy", "dizziness", "lightheaded"],
        "en_context": ["when i stand", "after standing", "standing up"],
        "ar": "الدوخة عند الوقوف قد تحدث مع هبوط ضغط مؤقت أو الجفاف أو أسباب أخرى. انهض ببطء واشرب سوائل بشكل مناسب، وإذا حدث إغماء أو ألم صدر أو خفقان شديد أو تكررت كثيرًا فاطلب تقييمًا طبيًا. هل تقيس ضغطك أو بدأت دواءً جديدًا مؤخرًا؟ هذه معلومات توعوية وليست تشخيصًا.",
        "en": "Dizziness on standing can happen with a temporary blood-pressure drop, dehydration, or other causes. Stand up gradually and keep appropriately hydrated; seek care if you faint, have chest pain/severe palpitations, or it keeps recurring. Have you checked your blood pressure or started a new medicine recently? This is educational information, not a diagnosis.",
    },
    {
        "ar_any": ["صداع", "راسي يوجعني", "راسي يعورني"],
        "ar_context": ["بعد الشاشه", "بعد الشاشة", "مع الجوال", "بعد الكمبيوتر", "من الكمبيوتر", "بعد اللابتوب"],
        "en_any": ["headache", "head hurts"],
        "en_context": ["after screen", "from screen", "computer", "phone screen"],
        "ar": "الصداع بعد وقت طويل أمام الشاشة قد يرتبط بإجهاد العين أو شد الرقبة أو قلة النوم/السوائل، لكنه ليس سببًا مؤكدًا. جرّب فترات راحة من الشاشة وتعديل الإضاءة والوضعية. إذا كان الصداع مفاجئًا وشديدًا جدًا أو معه ضعف أو تشوش أو فقدان رؤية فاطلب رعاية عاجلة. هذه معلومات توعوية وليست تشخيصًا.",
        "en": "Headache after prolonged screen use can relate to eye strain, neck tension, poor sleep, or hydration, but this is not a confirmed cause. Try screen breaks and adjust lighting/posture. Seek urgent care for a sudden extremely severe headache or one with weakness, confusion, or vision loss. This is educational information, not a diagnosis.",
    },
    {
        "ar_any": ["خفقان", "دقات قلبي", "نبضي سريع"],
        "ar_context": ["بعد القهوه", "بعد القهوة", "مع القهوه", "مع القهوة", "بعد الكافيين", "مشروب طاقه", "مشروب طاقة"],
        "en_any": ["palpitations", "heart racing", "fast heartbeat"],
        "en_context": ["after coffee", "caffeine", "energy drink"],
        "ar": "قد يزيد الكافيين أو مشروبات الطاقة الإحساس بالخفقان عند بعض الأشخاص، لكن لا ينبغي افتراض أنه السبب الوحيد. إذا صاحبه ألم صدر أو ضيق نفس أو إغماء/قرب إغماء فاطلب مساعدة عاجلة، وإذا يتكرر كثيرًا فراجع مختصًا. هذه معلومات توعوية وليست تشخيصًا.",
        "en": "Caffeine or energy drinks can make palpitations more noticeable for some people, but they should not be assumed to be the only cause. Seek urgent help with chest pain, breathlessness, fainting/near-fainting, and arrange review if episodes keep recurring. This is educational information, not a diagnosis.",
    },
    {
        "ar_any": ["حرقان", "حرقة", "حموضه", "حموضة", "ارتجاع"],
        "ar_context": ["بعد الاكل", "بعد الأكل", "بعد الوجبه", "بعد الوجبة", "وقت النوم", "لما انام", "لما أنام"],
        "en_any": ["heartburn", "acid reflux", "burning chest"],
        "en_context": ["after eating", "after meals", "when lying down", "at night"],
        "ar": "الحرقة بعد الأكل أو عند الاستلقاء قد تتوافق مع عسر الهضم أو ارتجاع الحمض، لكن الأعراض وحدها لا تؤكد السبب. لاحظ الأطعمة أو التوقيت الذي يزيدها، وراجع مختصًا إذا تتكرر كثيرًا أو معها صعوبة بلع أو قيء متكرر أو نزول وزن. ألم الصدر الشديد أو الجديد يحتاج تقييمًا عاجلًا. هذه معلومات توعوية وليست تشخيصًا.",
        "en": "Heartburn after meals or when lying down can fit indigestion or acid reflux, but symptoms alone do not confirm the cause. Note food/timing triggers and seek review if it is frequent or comes with swallowing difficulty, repeated vomiting, or weight loss. New or severe chest pain needs urgent assessment. This is educational information, not a diagnosis.",
    },
    {
        "ar_any": ["سعال", "كحه", "كحة"],
        "ar_context": ["بالليل", "وقت النوم", "لما انام", "لما أنام", "ليل"],
        "en_any": ["cough"],
        "en_context": ["at night", "night cough", "when lying down"],
        "ar": "السعال الذي يزيد ليلًا قد يرتبط بتهيج الأنف والحلق أو الربو أو الارتجاع أو أسباب أخرى، لذلك يحتاج للسياق. إذا كان معه ضيق نفس شديد أو زرقة أو دم مع السعال فاطلب رعاية عاجلة. هل يوجد صفير أو انسداد أنف أو حرقة معدة؟ هذه معلومات توعوية وليست تشخيصًا.",
        "en": "A cough that is worse at night can relate to nasal/throat irritation, asthma, reflux, or other causes, so context matters. Seek urgent care for severe breathlessness, blue/grey lips, or coughing up blood. Is there wheeze, nasal blockage, or heartburn? This is educational information, not a diagnosis.",
    },
    {
        "ar_any": ["تنميل", "خدر", "نمل"],
        "ar_context": ["بعد الجلسه", "بعد الجلسة", "بعد ما جلست", "لما اجلس", "لما أجلس", "بعد النوم"],
        "en_any": ["numbness", "pins and needles", "tingling"],
        "en_context": ["after sitting", "after sleeping", "when sitting"],
        "ar": "التنميل القصير بعد ضغط على طرف أثناء الجلوس أو النوم قد يتحسن عند تغيير الوضعية، لكن التنميل المستمر أو المتكرر يحتاج تقييمًا. إذا بدأ فجأة مع ضعف بجهة واحدة أو صعوبة كلام أو تغير رؤية فهذه علامة طارئة. هذه معلومات توعوية وليست تشخيصًا.",
        "en": "Brief tingling after pressure on a limb while sitting or sleeping may settle after changing position, but persistent or recurrent numbness needs assessment. Sudden numbness with one-sided weakness, speech trouble, or vision change is an emergency. This is educational information, not a diagnosis.",
    },
    {
        "ar_any": ["غثيان", "لوعه", "لوعة"],
        "ar_context": ["بعد الاكل", "بعد الأكل", "بعد الوجبه", "بعد الوجبة"],
        "en_any": ["nausea", "nauseous"],
        "en_context": ["after eating", "after meals"],
        "ar": "الغثيان بعد الأكل قد يحدث مع عسر الهضم أو التهاب معدة أو عدوى غذائية أو عدم تحمل بعض الأطعمة وأسباب أخرى. راقب هل يتكرر مع طعام محدد، واطلب تقييمًا إذا كان القيء متكررًا أو لا تستطيع الاحتفاظ بالسوائل أو يوجد ألم شديد أو دم. هذه معلومات توعوية وليست تشخيصًا.",
        "en": "Nausea after eating can occur with indigestion, stomach irritation, food-borne illness, food intolerance, or other causes. Notice whether it repeats after a particular food, and seek care for repeated vomiting, inability to keep fluids down, severe pain, or blood. This is educational information, not a diagnosis.",
    },
    {
        "ar_any": ["جفاف الفم", "فمي ناشف", "فمي جاف"],
        "ar_context": ["بالليل", "الصباح", "لما اصحى", "لما أصحى", "بعد النوم"],
        "en_any": ["dry mouth"],
        "en_context": ["at night", "in the morning", "when i wake", "after sleep"],
        "ar": "جفاف الفم عند الاستيقاظ قد يرتبط بالتنفس من الفم أثناء النوم أو انسداد الأنف أو الجفاف أو أسباب أخرى. جرّب شرب الماء بانتظام وراقب وجود شخير أو انسداد أنف. إذا استمر لأسابيع أو صعّب الأكل والكلام فراجع مختصًا. هذه معلومات توعوية وليست تشخيصًا.",
        "en": "Dry mouth on waking can relate to mouth breathing during sleep, nasal blockage, dehydration, or other causes. Keep hydrated and note snoring or nasal blockage. If it lasts for weeks or makes eating/talking difficult, seek review. This is educational information, not a diagnosis.",
    },
    {
        "ar_any": ["صداع", "شقيقه", "شقيقة"],
        "ar_context": ["مع الدوره", "مع الدورة", "قبل الدوره", "قبل الدورة", "وقت الدوره", "وقت الدورة"],
        "en_any": ["headache", "migraine"],
        "en_context": ["during period", "before period", "with my period", "menstrual"],
        "ar": "الصداع أو الشقيقة قد يتغيران حول موعد الدورة لدى بعض الأشخاص بسبب تغيرات هرمونية، لكن الصداع له أسباب متعددة. سجّل توقيته وشدته وهل يتكرر مع كل دورة، واطلب تقييمًا إذا كان جديدًا أو مختلفًا جدًا أو شديدًا أو معه أعراض عصبية. هذه معلومات توعوية وليست تشخيصًا.",
        "en": "Headache or migraine can change around periods for some people because of hormonal shifts, but headaches have many causes. Track timing/severity and whether it repeats each cycle; seek review for a new, very different, severe headache or neurological symptoms. This is educational information, not a diagnosis.",
    },
    {
        "ar_any": ["الم الكعب", "ألم الكعب", "كعبي يوجعني"],
        "ar_context": ["اول ما اقوم", "أول ما أقوم", "اول خطوات", "أول خطوات", "بعد النوم", "بعد الراحه", "بعد الراحة"],
        "en_any": ["heel pain"],
        "en_context": ["first steps", "after rest", "when i wake"],
        "ar": "ألم الكعب الذي يكون أوضح مع أول خطوات بعد الراحة قد يظهر مع مشكلات شائعة في أنسجة باطن القدم، لكن لا يمكن تأكيد السبب دون فحص. إذا استمر أكثر من أسبوعين أو كان شديدًا أو معه تنميل أو بدأ بعد إصابة فراجع مختصًا. هذه معلومات توعوية وليست تشخيصًا.",
        "en": "Heel pain that is worse on the first steps after rest can occur with common problems in tissues under the foot, but the cause cannot be confirmed without assessment. Seek review if it lasts over 2 weeks, is severe, includes numbness, or followed an injury. This is educational information, not a diagnosis.",
    },
]
