"""Search topics added in V249: common everyday complaints that previously fell through to a
generic answer. Each entry has what it is, possible causes, self-care, when to worry and when to
see a clinician. Sources fetched and read on 2026-10-07 (NHS / MedlinePlus). No diagnoses, no doses.

CLINICAL REVIEW: wording is conservative and follows the cited pages, but a licensed clinician
should sign off before broad promotion (see /admin/clinical-review and MEDICAL_REVIEW_NEEDED.md).
"""

_VERIFIED = "2026-10-07"


def _src(name, title, org, url):
    return [{"name": name, "title": title, "organization": org, "source_name": org, "url": url, "last_verified": _VERIFIED}]


EXTRA_SEARCH_KB_V8 = {
    "anxiety": {
        "emoji": "🩺", "category": "symptom",
        "aliases": ["القلق", "قلق", "توتر", "قلق وتوتر", "احس بقلق", "قلبي يدق من التوتر", "Anxiety", "anxious", "feeling anxious", "stress and worry"],
        "sources": _src("Generalised anxiety disorder — NHS", "Generalised anxiety disorder overview", "NHS",
                        "https://www.nhs.uk/mental-health/conditions/generalised-anxiety-disorder/overview/"),
        "causes_label": {"ar": "أسباب محتملة", "en": "Possible causes"},
        "ar": {"title": "القلق",
               "what": "القلق شعور بالتوتر أو الخوف يصعب التحكم فيه، وقد يصاحبه خفقان وتوتر عضلي ودوخة واضطراب في النوم وتعب. الشعور بالقلق أحيانًا طبيعي.",
               "causes": ["ضغوط الحياة أو العمل", "قلة النوم", "الكافيين", "اضطراب قلق مستمر يحتاج تقييمًا"],
               "self_care": "جرّب التنفس البطيء والمشي والنوم الكافي والأكل المنتظم، وقلّل الكافيين، وتحدث مع شخص تثق به.",
               "worry": "اطلب مساعدة عاجلة إذا ظهرت أفكار لإيذاء نفسك، أو ألم صدر شديد، أو ضيق نفس شديد؛ في السعودية الإسعاف 997 وخط الصحة 937.",
               "doctor": "راجع طبيبًا أو مختصًا نفسيًا إذا استمر القلق وأثّر على يومك أو نومك أو عملك أو لم يخفّ بما تفعله.",
               "follow_up": "منذ متى تشعر بهذا القلق، وهل يؤثر على نومك أو عملك؟"},
        "en": {"title": "Anxiety",
               "what": "Anxiety is a feeling of worry or fear that can be hard to control. It can come with a racing heart, muscle tension, dizziness, poor sleep and tiredness. Feeling anxious sometimes is normal.",
               "causes": ["Life or work stress", "Poor sleep", "Caffeine", "An ongoing anxiety condition that needs assessment"],
               "self_care": "Try slow breathing, walking, enough sleep and regular meals, cut back on caffeine, and talk to someone you trust.",
               "worry": "Get urgent help for thoughts of harming yourself, severe chest pain or severe breathlessness; in Saudi Arabia call 997 (ambulance) or 937 (health line).",
               "doctor": "See a doctor or mental-health professional if anxiety lasts, affects your sleep, work or daily life, or does not ease with self-help.",
               "follow_up": "How long have you felt this anxious, and is it affecting your sleep or work?"},
    },
    "rash": {
        "emoji": "🩺", "category": "symptom",
        "aliases": ["الطفح الجلدي", "طفح جلدي", "طفح", "حبوب في الجلد", "احمرار في الجلد", "حبوب حمراء", "Rash", "skin rash", "red spots on skin", "skin irritation"],
        "sources": _src("Rashes — MedlinePlus", "Rashes", "MedlinePlus", "https://medlineplus.gov/rashes.html"),
        "causes_label": {"ar": "أسباب محتملة", "en": "Possible causes"},
        "ar": {"title": "الطفح الجلدي",
               "what": "الطفح الجلدي منطقة من الجلد متهيجة أو متورمة، وقد تكون حمراء أو حاكّة أو مؤلمة، وقد تظهر فيها بثور.",
               "causes": ["التهاب الجلد التماسي من مادة مهيّجة", "حساسية", "حالات جلدية مزمنة كالإكزيما", "بعض الأمراض الطبية"],
               "self_care": "ابتعد عن المادة المشتبهة، وتجنب الحك، واستخدم مرطبًا لطيفًا أو كمادات باردة، واسأل الصيدلي قبل استخدام أي كريم.",
               "worry": "اطلب رعاية عاجلة إذا ترافق الطفح مع تورم الوجه أو الشفاه أو اللسان أو صعوبة التنفس، أو مع حمى وتدهور سريع.",
               "doctor": "راجع طبيبًا إذا كان الطفح شديدًا أو لا يزول أو انتشر أو ترافق مع أعراض أخرى.",
               "follow_up": "منذ متى ظهر الطفح، وهل بدأت دواءً أو منتجًا أو طعامًا جديدًا قبله؟"},
        "en": {"title": "Rash",
               "what": "A rash is an area of irritated or swollen skin. It may be red, itchy or painful and can blister.",
               "causes": ["Contact dermatitis from an irritant", "Allergy", "Long-term skin conditions such as eczema", "Some medical conditions"],
               "self_care": "Avoid the suspected trigger, try not to scratch, use a gentle moisturiser or a cool compress, and ask a pharmacist before using any cream.",
               "worry": "Get urgent care if the rash comes with swelling of the face, lips or tongue, trouble breathing, or fever with quick worsening.",
               "doctor": "See a clinician if the rash is bad, does not go away, spreads, or comes with other symptoms.",
               "follow_up": "When did the rash start, and did you start a new medicine, product or food before it?"},
    },
    "joint_pain": {
        "emoji": "🩺", "category": "symptom",
        "aliases": ["الم المفاصل", "ألم المفاصل", "وجع المفاصل", "مفاصلي تعورني", "الم في المفصل", "ركبتي تعورني", "Joint pain", "aching joints", "sore joints"],
        "sources": _src("Joint pain — NHS", "Joint pain", "NHS", "https://www.nhs.uk/conditions/joint-pain/"),
        "causes_label": {"ar": "أسباب محتملة", "en": "Possible causes"},
        "ar": {"title": "ألم المفاصل",
               "what": "ألم المفاصل شائع، خصوصًا مع التقدم في العمر، وقد يصيب مفصلًا واحدًا أو عدة مفاصل.",
               "causes": ["إجهاد أو التواء", "خشونة المفاصل", "التهاب الأكياس الزلالية", "التهاب المفاصل بأنواعه أو النقرس", "عدوى في المفصل"],
               "self_care": "أرح المفصل دون إيقاف الحركة كليًا، وضع كمادة باردة ملفوفة بقماش لمدة تصل إلى 20 دقيقة، واسأل الصيدلي أو الطبيب عن مسكن مناسب، وحافظ على وزن ونشاط مناسبين.",
               "worry": "اطلب رعاية عاجلة إذا كان الألم شديدًا بعد سقوط أو إصابة، أو لا تستطيع المشي أو تحميل الوزن، أو ظهر تنميل بعد إصابة، أو كان المفصل ساخنًا ومتورمًا مع حمى.",
               "doctor": "راجع طبيبًا إذا منع الألم نشاطك أو نومك، أو ساء أو تكرر، أو استمر بعد أسبوعين من العناية المنزلية، أو دامت تصلبات الصباح أكثر من 30 دقيقة.",
               "follow_up": "أي مفصل يؤلمك، وهل يوجد تورم أو احمرار أو سخونة أو إصابة سابقة؟"},
        "en": {"title": "Joint pain",
               "what": "Joint pain is common, especially as you get older, and can affect one joint or several.",
               "causes": ["Sprain or strain", "Osteoarthritis", "Bursitis", "Other types of arthritis or gout", "Joint infection"],
               "self_care": "Rest the joint without stopping movement completely, use a cold pack wrapped in a cloth for up to 20 minutes, ask a pharmacist or doctor about suitable pain relief, and keep a healthy weight and activity level.",
               "worry": "Get urgent care for severe pain after a fall or injury, if you cannot walk or put weight on it, for tingling or numbness after an injury, or if the joint is hot and swollen with a fever.",
               "doctor": "See a clinician if pain stops you doing things or sleeping, gets worse or keeps returning, lasts beyond two weeks of home care, or morning stiffness lasts over 30 minutes.",
               "follow_up": "Which joint hurts, and is there swelling, redness, warmth or a past injury?"},
    },
    "common_cold": {
        "emoji": "🩺", "category": "symptom",
        "aliases": ["الزكام ونزلة البرد", "الزكام", "زكام", "الرشح", "رشح", "نزلة برد", "سيلان الانف", "انسداد الانف", "العطاس", "عطاس", "Common cold", "cold", "runny nose", "blocked nose", "sneezing", "stuffy nose"],
        "sources": _src("Common cold — NHS", "Common cold", "NHS", "https://www.nhs.uk/conditions/common-cold/"),
        "causes_label": {"ar": "أسباب محتملة", "en": "Possible causes"},
        "ar": {"title": "الزكام ونزلة البرد",
               "what": "نزلة البرد عدوى فيروسية شائعة تسبب سيلان الأنف أو انسداده وعطاسًا والتهاب حلق وسعالًا وتعبًا، وتظهر تدريجيًا وتستمر عادة من أسبوع إلى أسبوعين.",
               "causes": ["عدوى فيروسية", "مخالطة مصاب", "حساسية الأنف قد تشبه الأعراض"],
               "self_care": "ارتح واشرب سوائل كافية، وجرّب غرغرة الماء المالح أو بخار الماء للاحتقان، واسأل الصيدلي عن مسكنات أو مزيلات احتقان مناسبة لحالتك، وابقَ في البيت إذا كانت الحرارة مرتفعة.",
               "worry": "اطلب رعاية عاجلة إذا ظهر ضيق نفس أو ألم في الصدر.",
               "doctor": "راجع طبيبًا إذا استمرت الحرارة أكثر من 3 أيام، أو ساءت الأعراض، أو لم تتحسن بعد 10 أيام، أو استمر السعال أكثر من 3 أسابيع، أو كان لديك مرض مزمن أو ضعف مناعة.",
               "follow_up": "منذ كم يوم بدأت الأعراض، وهل معها حرارة أو ضيق نفس؟"},
        "en": {"title": "Common cold",
               "what": "A cold is a common viral infection causing a runny or blocked nose, sneezing, sore throat, cough and tiredness. It builds up gradually and usually lasts one to two weeks.",
               "causes": ["Viral infection", "Contact with someone who is ill", "Nasal allergy can look similar"],
               "self_care": "Rest and drink enough fluids, try salt-water gargles or steam for congestion, ask a pharmacist about suitable pain relief or decongestants for you, and stay home if you have a high temperature.",
               "worry": "Get urgent care if you become short of breath or have chest pain.",
               "doctor": "See a clinician if a high temperature lasts over 3 days, symptoms get worse, you are no better after 10 days, a cough lasts over 3 weeks, or you have a long-term condition or weakened immunity.",
               "follow_up": "How many days have the symptoms lasted, and is there a fever or breathlessness?"},
    },
    "weight_loss": {
        "emoji": "🩺", "category": "symptom",
        "aliases": ["نقص الوزن غير المقصود", "نقص الوزن", "نزول الوزن", "خسرت وزن بدون سبب", "فقدان الوزن غير المبرر", "وزني ينزل", "Unintentional weight loss", "weight loss", "losing weight without trying", "unexplained weight loss"],
        "sources": _src("Unintentional weight loss — NHS", "Unintentional weight loss", "NHS", "https://www.nhs.uk/conditions/unintentional-weight-loss/"),
        "causes_label": {"ar": "أسباب محتملة", "en": "Possible causes"},
        "ar": {"title": "نقص الوزن غير المقصود",
               "what": "هو نزول الوزن دون تغيير مقصود في الأكل أو النشاط، وقد يرتبط بالتوتر أو بحالات طبية تحتاج تقييمًا.",
               "causes": ["القلق أو الاكتئاب", "مشاكل الجهاز الهضمي", "فرط نشاط الغدة الدرقية أو السكري من النوع الأول", "قلة الشهية أو سوء التغذية", "بعض الأدوية"],
               "self_care": "دوّن وزنك وأكلك وأي أعراض معه، ولا تبدأ حمية أو مكملات قبل معرفة السبب.",
               "worry": "اطلب تقييمًا سريعًا إذا ترافق مع دم في البراز أو القيء، أو ألم مستمر، أو صعوبة في البلع، أو حمى مستمرة.",
               "doctor": "راجع طبيبًا إذا استمر نزول وزنك دون تغيير في أكلك ونشاطك؛ أي نقص وزن غير مفسَّر يستحق التقييم.",
               "follow_up": "كم كيلو نقص وزنك وخلال كم شهر، وهل تغيّرت شهيتك؟"},
        "en": {"title": "Unintentional weight loss",
               "what": "Losing weight without changing your diet or activity on purpose. It can reflect stress or a medical condition that needs assessment.",
               "causes": ["Anxiety or depression", "Digestive problems", "An overactive thyroid or type 1 diabetes", "Poor appetite or nutrition", "Some medicines"],
               "self_care": "Keep a note of your weight, eating and any other symptoms, and do not start a diet or supplements before the cause is known.",
               "worry": "Seek prompt assessment if it comes with blood in stool or vomit, persistent pain, trouble swallowing, or an ongoing fever.",
               "doctor": "See a clinician if you keep losing weight without changing your diet or activity; any unexplained weight loss is worth assessing.",
               "follow_up": "How much weight have you lost over how many months, and has your appetite changed?"},
    },
    "itching": {
        "emoji": "🩺", "category": "symptom",
        "aliases": ["الحكة", "حكة", "حكة الجلد", "هرش الجلد", "جلدي يحكني", "جلدي يهرش", "Itching", "itchy skin", "itch", "skin itching"],
        "sources": _src("Itchy skin — NHS", "Itchy skin", "NHS", "https://www.nhs.uk/conditions/itching/"),
        "causes_label": {"ar": "أسباب محتملة", "en": "Possible causes"},
        "ar": {"title": "حكة الجلد",
               "what": "الحكة إحساس يدفعك لحك الجلد، وقد تظهر مع طفح أو بدونه.",
               "causes": ["جفاف الجلد أو الحرارة", "حساسية أو شرى", "إكزيما أو صدفية", "عدوى فطرية أو جرب", "أحيانًا أمراض الغدة الدرقية أو الكبد أو الكلى"],
               "self_care": "اضغط بلطف بدل الحك، واستخدم كمادات باردة ومرطبًا بلا عطر، واستحم بماء فاتر، وقصّ أظافرك، والبس قطنًا فضفاضًا.",
               "worry": "اطلب رعاية عاجلة إذا ظهرت الحكة مع تورم الوجه أو الشفاه أو اللسان أو صعوبة في التنفس.",
               "doctor": "راجع طبيبًا إذا شملت الحكة كامل الجسم أو كانت شديدة أو أثّرت على حياتك، أو لم تتحسن أو تكررت، أو ظهر معها طفح أو كتلة أو تورم، أو أثناء الحمل.",
               "follow_up": "في أي مكان الحكة، وهل يوجد طفح، وهل بدأت دواءً أو صابونًا جديدًا؟"},
        "en": {"title": "Itchy skin",
               "what": "Itching is the urge to scratch the skin. It can happen with or without a rash.",
               "causes": ["Dry skin or heat", "Allergy or hives", "Eczema or psoriasis", "Fungal infection or scabies", "Sometimes thyroid, liver or kidney problems"],
               "self_care": "Pat the skin instead of scratching, use cool compresses and an unperfumed moisturiser, bathe in lukewarm water, keep nails short, and wear loose cotton.",
               "worry": "Get urgent care if itching comes with swelling of the face, lips or tongue, or trouble breathing.",
               "doctor": "See a clinician if itching covers your whole body, is severe or affects daily life, does not improve or keeps returning, comes with a new rash, lump or swelling, or happens in pregnancy.",
               "follow_up": "Where is the itch, is there a rash, and did you start a new medicine or soap?"},
    },
    "leg_swelling": {
        "emoji": "🩺", "category": "symptom",
        "aliases": ["تورم الساقين والقدمين", "تورم الرجل", "تورم القدمين", "تورم الساقين", "انتفاخ الرجول", "رجولي منتفخة", "Leg swelling", "Swollen legs and feet", "swollen legs", "swollen feet", "swollen ankles", "edema"],
        "sources": _src("Edema — MedlinePlus", "Edema", "MedlinePlus", "https://medlineplus.gov/edema.html"),
        "causes_label": {"ar": "أسباب محتملة", "en": "Possible causes"},
        "ar": {"title": "تورم الساقين والقدمين",
               "what": "التورم (الوذمة) تجمع سوائل في الأنسجة، ويظهر غالبًا في القدمين والكاحلين والساقين.",
               "causes": ["الوقوف أو الجلوس الطويل خصوصًا في الجو الحار", "الملح الزائد", "الحمل", "بعض الأدوية", "أمراض القلب أو الكلى أو الكبد"],
               "self_care": "ارفع ساقيك أثناء الجلوس، وقلل الملح، وتحرك بانتظام؛ ولا توقف أي دواء دون استشارة الطبيب.",
               "worry": "اطلب رعاية عاجلة إذا ظهر التورم فجأة في ساق واحدة مع ألم أو احمرار، أو مع ضيق نفس أو ألم في الصدر.",
               "doctor": "راجع طبيبًا إذا كان التورم جديدًا أو يزداد أو لا يزول، أو ترافق مع ضيق نفس أو زيادة وزن سريعة أو قلة بول، لأنه قد يرتبط بمشكلة في القلب أو الكلى أو الكبد.",
               "follow_up": "هل التورم في الساقين معًا أم ساق واحدة، ومنذ متى، وهل معه ضيق نفس؟"},
        "en": {"title": "Swollen legs and feet",
               "what": "Swelling (oedema) is fluid collecting in the tissues, most often in the feet, ankles and legs.",
               "causes": ["Long periods of standing or sitting, especially in hot weather", "Too much salt", "Pregnancy", "Some medicines", "Heart, kidney or liver disease"],
               "self_care": "Raise your legs when sitting, cut down on salt and keep moving; do not stop any medicine without asking your doctor.",
               "worry": "Get urgent care if swelling appears suddenly in one leg with pain or redness, or comes with breathlessness or chest pain.",
               "doctor": "See a clinician if swelling is new, increasing or not going away, or comes with breathlessness, rapid weight gain or passing less urine, as it can relate to the heart, kidneys or liver.",
               "follow_up": "Are both legs swollen or just one, since when, and is there any breathlessness?"},
    },
}
