"""V62 high-frequency bilingual search topics for SymptoSense."""

REVIEW_DATE = "2026-09-20"

def src(org, title, url):
    return {"name":f"{title} — {org}","title":title,"organization":org,"source_name":org,"url":url,"last_verified":REVIEW_DATE}

def topic(emoji, aliases, source, ar_title, ar_what, ar_causes, ar_worry, ar_doctor, en_title, en_what, en_causes, en_worry, en_doctor):
    return {
        "emoji":emoji,"category":"symptom","aliases":aliases,"sources":[source],"last_reviewed":REVIEW_DATE,
        "population_scope":"general educational information; age, pregnancy, medicines, and medical history can change interpretation",
        "causes_label":{"ar":"أسباب أو سياقات محتملة","en":"Possible causes or contexts"},
        "ar":{"title":ar_title,"what":ar_what,"causes":ar_causes,"worry":ar_worry,"doctor":ar_doctor},
        "en":{"title":en_title,"what":en_what,"causes":en_causes,"worry":en_worry,"doctor":en_doctor},
    }

EXTRA_SEARCH_KB_V4 = {
"low_back_pain": topic("🧍",["الم اسفل الظهر","وجع الظهر من تحت","ظهري يوجع بعد الجلوس","lower back pain","low back pain"],src("NHS","Back pain","https://www.nhs.uk/conditions/back-pain/"),"ألم أسفل الظهر","ألم أسفل الظهر شائع وغالبًا يتحسن، وقد يرتبط بإجهاد أو حركة أو وضعية.",["شد أو إجهاد عضلي","وضعيات أو حمل متكرر","أسباب أقل شيوعًا"],"ضعف شديد بالساقين أو فقد التحكم بالبول/البراز أو خدر بمنطقة العجان يحتاج تقييمًا عاجلًا.","راجع مختصًا إذا استمر عدة أسابيع أو أعاق نشاطك.","Low back pain","Low back pain is common and often improves; it can relate to strain, movement, or posture.",["Muscle strain","Posture or repeated loading","Less common causes"],"Severe leg weakness, bladder/bowel control loss, or saddle numbness needs urgent assessment.","Seek review if it lasts weeks or limits daily activity."),
"knee_pain_common": topic("🦵",["الم الركبة","ركبتي توجع","الم ركبة بعد المشي","knee pain","knee ache"],src("NHS","Knee pain","https://www.nhs.uk/symptoms/knee-pain/"),"ألم الركبة","ألم الركبة قد ينتج عن إجهاد أو إصابة بسيطة أو أسباب مفصلية مختلفة.",["إجهاد أو نشاط متكرر","إصابة بسيطة","أسباب مفصلية أو التهابية"],"عدم القدرة على تحميل الوزن أو تورم شديد أو ركبة حارة وحمراء مع حرارة يحتاج تقييمًا عاجلًا.","راجع مختصًا إذا لم يتحسن خلال أسابيع أو كان شديدًا.","Knee pain","Knee pain may follow overuse, minor injury, or different joint conditions.",["Overuse","Minor injury","Joint or inflammatory causes"],"Inability to bear weight, major swelling, or a hot red knee with fever needs urgent assessment.","Seek review if severe or not improving within weeks."),
"shoulder_pain_common": topic("💪",["الم الكتف","كتفي يوجع","الم كتف بعد رفع اليد","shoulder pain","shoulder ache"],src("NHS","Shoulder pain","https://www.nhs.uk/symptoms/shoulder-pain/"),"ألم الكتف","قد يرتبط ألم الكتف بإجهاد أو التهاب أو تيبس أو إصابة، ولا يمكن تحديد السبب من الألم وحده.",["إجهاد متكرر","التهاب أوتار أو جراب","تيبس أو إصابة"],"ألم شديد مفاجئ مع عدم القدرة على تحريك الذراع أو تغير شكل الكتف يحتاج تقييمًا عاجلًا.","راجع مختصًا إذا لم يبدأ التحسن خلال نحو أسبوعين.","Shoulder pain","Shoulder pain can relate to overuse, inflammation, stiffness, or injury; pain alone does not identify the cause.",["Overuse","Tendon/bursa irritation","Stiffness or injury"],"Sudden severe pain with inability to move the arm or deformity needs urgent assessment.","Seek review if improvement does not begin within about two weeks."),
"stye": topic("👁️",["شعيرة العين","دمل الجفن","حبة في الجفن","stye","eyelid lump"],src("NHS","Stye","https://www.nhs.uk/conditions/stye/"),"شعيرة الجفن","كتلة صغيرة مؤلمة في الجفن غالبًا بسبب التهاب بصيلة رمش أو غدة صغيرة.",["التهاب بصيلة رمش","التهاب غدة بالجفن"],"تأثر الرؤية أو تورم واحمرار ممتد حول العين يحتاج تقييمًا سريعًا.","يمكن استخدام كمادة دافئة، ولا تعصرها. راجع مختصًا إذا لم تتحسن.","Stye","A stye is a small painful eyelid lump, often from an infected eyelash follicle or gland.",["Eyelash follicle infection","Eyelid gland infection"],"Vision change or spreading swelling/redness needs prompt assessment.","Warm compresses may help; do not squeeze it. Seek review if not improving."),
"ringworm": topic("⭕",["سعفة","فطريات دائرية","طفح دائري يحك","ringworm","tinea"],src("NHS","Ringworm","https://www.nhs.uk/conditions/ringworm/"),"السعفة","عدوى فطرية شائعة قد تظهر كطفح دائري متقشر أو حاك.",["فطريات جلدية","ملامسة جلد/أسطح ملوثة"],"إصابة فروة الرأس أو انتشار واسع أو علامات عدوى ثانوية تحتاج تقييمًا.","استشر الصيدلي أو الطبيب إذا لم تتحسن أو كانت بفروة الرأس.","Ringworm","A common fungal infection that may cause a circular scaly itchy rash.",["Dermatophyte fungi","Skin/surface contact"],"Scalp involvement, widespread disease, or secondary infection needs review.","Ask a pharmacist or clinician if persistent or on the scalp."),
"cold_sore": topic("💋",["قرحة برد","حبة حرارة بالشفايف","فقاعات حول الفم","cold sore","fever blister"],src("NHS","Cold sores","https://www.nhs.uk/conditions/cold-sores/"),"قرحة البرد","غالبًا تبدأ بوخز أو حكة ثم تظهر فقاعات مؤلمة حول الشفاه أو الوجه.",["فيروس الهربس البسيط","إعادة تنشيط الفيروس"],"إذا كانت قرب العين أو كان لديك ضعف مناعة فاطلب تقييمًا طبيًا.","تجنب لمسها ومشاركة الأدوات الشخصية وراجع مختصًا إذا كانت كبيرة أو متكررة.","Cold sore","Often starts with tingling or itching followed by painful blisters around the lips/face.",["Herpes simplex virus","Viral reactivation"],"Eye-area involvement or immunocompromise needs medical assessment.","Avoid touching/sharing personal items and seek review if large or recurrent."),
"ingrown_toenail": topic("🦶",["ظفر داخل اللحم","ظفر نامي","الظفر داخل الجلد","ingrown toenail"],src("NHS","Ingrown toenail","https://www.nhs.uk/conditions/ingrown-toenail/"),"ظفر نامٍ للداخل","يدخل طرف الظفر في الجلد فيسبب ألمًا واحمرارًا أو تورمًا.",["قص الظفر بشكل غير مناسب","حذاء ضيق","شكل الظفر"],"قيح أو احمرار منتشر أو حمى، خصوصًا مع السكري، يحتاج تقييمًا.","حافظ على نظافة القدم ولا تقص الزوايا بعمق، وراجع مختصًا إذا استمر.","Ingrown toenail","The nail edge grows into the skin, causing pain, redness, or swelling.",["Improper trimming","Tight shoes","Nail shape"],"Pus, spreading redness, or fever, especially with diabetes, needs review.","Keep the foot clean and avoid digging into corners; seek review if persistent."),
"fungal_nail": topic("🦶",["فطريات الاظافر","ظفر اصفر سميك","الظفر تغير لونه","fungal nail","nail fungus"],src("NHS","Fungal nail infection","https://www.nhs.uk/conditions/fungal-nail-infection/"),"فطريات الأظافر","قد يصبح الظفر سميكًا أو متغير اللون أو هشًا بسبب عدوى فطرية.",["عدوى فطرية","رطوبة مزمنة","امتداد فطريات القدم"],"ألم شديد أو التهاب محيط بالظفر أو وجود سكري يستدعي تقييمًا مبكرًا.","حافظ على القدم جافة ونظيفة واطلب نصيحة صيدلي/طبيب إذا استمرت.","Fungal nail infection","Nails may become thick, discolored, or brittle because of fungal infection.",["Fungal infection","Chronic dampness","Spread from athlete's foot"],"Severe pain, surrounding infection, or diabetes warrants early assessment.","Keep feet clean/dry and seek pharmacist/medical advice if persistent."),
"warts": topic("🔘",["ثؤلول","ثآليل","حبة خشنة باليد","wart","verruca"],src("NHS","Warts and verrucas","https://www.nhs.uk/conditions/warts-and-verrucas/"),"الثآليل","نتوءات جلدية صغيرة وخشنة غالبًا، وقد تظهر في اليدين أو القدمين.",["فيروسات HPV جلدية","انتقال عبر الجلد أو الأسطح"],"الثؤلول الذي ينزف أو يتغير أو يوجد على الوجه/الأعضاء التناسلية يحتاج تقييمًا.","لا تعبث به واطلب نصيحة إذا كان مؤلمًا أو متكررًا.","Warts and verrucas","Small rough skin lumps, often on hands or feet.",["Cutaneous HPV viruses","Skin/surface transmission"],"Bleeding, changing, facial, or genital lesions need medical review.","Avoid picking and seek advice if painful or recurrent."),
"pms": topic("🌸",["اعراض قبل الدورة","قبل الدورة اعصب","نفخة قبل الدورة","pms","premenstrual syndrome"],src("ACOG","Premenstrual Syndrome (PMS)","https://www.acog.org/womens-health/faqs/premenstrual-syndrome"),"أعراض ما قبل الدورة (PMS)","قد تظهر أعراض مزاجية وجسدية في الأيام السابقة للدورة وتخف بعد بدايتها.",["تغيرات هرمونية مرتبطة بالدورة","اختلاف الاستجابة من شخص لآخر"],"أفكار إيذاء النفس أو تدهور مزاج شديد يحتاج مساعدة عاجلة.","تتبعي الأعراض مع الدورة وراجعي مختصًا إذا أثرت على حياتك.","Premenstrual syndrome (PMS)","Physical and mood symptoms can recur before a period and ease after it starts.",["Cycle-related hormonal changes","Individual sensitivity"],"Self-harm thoughts or severe mood deterioration need urgent help.","Track symptoms against cycle timing and seek review if daily life is affected."),
"heavy_periods": topic("🩸",["دورة غزيرة","نزيف الدورة كثير","الدورة قوية مرة","heavy periods","heavy menstrual bleeding"],src("ACOG","Heavy Menstrual Bleeding","https://www.acog.org/womens-health/faqs/heavy-menstrual-bleeding"),"غزارة الدورة","الغزارة قد تكون نزفًا أكثر أو أطول من المعتاد ويمكن أن تؤثر في النشاط أو تسبب فقر دم.",["تغيرات هرمونية","أسباب رحمية","اضطرابات نزف أو أدوية"],"نزيف شديد مع دوخة أو إغماء أو ضيق نفس يحتاج تقييمًا عاجلًا.","راجعي مختصًا إذا أثرت على حياتك أو استمرت أكثر من المعتاد.","Heavy menstrual bleeding","Bleeding can be heavier or longer than usual and may affect daily life or cause anemia.",["Hormonal causes","Uterine causes","Bleeding disorders or medicines"],"Heavy bleeding with dizziness, fainting, or shortness of breath needs urgent assessment.","Seek review if it affects daily life or lasts longer than usual."),
"irregular_periods": topic("📅",["دورة غير منتظمة","الدورة تتاخر","الدورة تنقطع وترجع","irregular periods","missed periods"],src("NHS","Irregular periods","https://www.nhs.uk/symptoms/irregular-periods/"),"عدم انتظام الدورة","تغير الفاصل بين الدورات أو تغير نمطك المعتاد قد يحدث لأسباب متعددة.",["التوتر وتغير الوزن","الحمل أو وسائل منع الحمل","البلوغ أو قرب سن اليأس","حالات هرمونية"],"نزف شديد أو ألم حوض حاد أو احتمال حمل مع ألم شديد يحتاج تقييمًا عاجلًا.","تتبعي المواعيد وراجعي مختصًا إذا تغير نمطك المعتاد أو طال الانقطاع.","Irregular periods","Changes in cycle timing can happen for many reasons.",["Stress and weight change","Pregnancy or contraception","Puberty/perimenopause","Hormonal conditions"],"Heavy bleeding, severe pelvic pain, or possible pregnancy with severe pain needs urgent assessment.","Track cycle dates and seek review if your usual pattern changes or periods stop for a prolonged time."),
"vaginal_thrush": topic("🌼",["فطريات مهبلية","حكة مع افرازات بيضاء","التهاب فطري مهبلي","vaginal thrush","yeast infection"],src("NHS","Thrush in men and women","https://www.nhs.uk/conditions/thrush-in-men-and-women/"),"فطريات المهبل","قد تسبب حكة وتهيجًا مع إفرازات بيضاء سميكة، لكن الأعراض قد تشبه أسبابًا أخرى.",["زيادة نمو Candida","تغير توازن البيئة الطبيعية","مضادات حيوية أو عوامل أخرى"],"حمى أو ألم حوض شديد أو أعراض أول مرة/حمل تحتاج تقييمًا.","راجعي مختصًا إذا كانت أول مرة أو لم تكوني متأكدة من السبب أو كانت متكررة.","Vaginal thrush","Can cause itching/irritation with thick white discharge, but other conditions may look similar.",["Candida overgrowth","Changed local balance","Antibiotics or other factors"],"Fever, severe pelvic pain, first episode, or pregnancy needs medical review.","Seek review if this is the first episode, the cause is uncertain, or it recurs."),
"bacterial_vaginosis": topic("🧫",["اختلال بكتيريا المهبل","ريحة سمكية","افرازات رمادية برائحة","bacterial vaginosis","bv"],src("NHS","Bacterial vaginosis","https://www.nhs.uk/conditions/bacterial-vaginosis/"),"اختلال البكتيريا المهبلية (BV)","سبب شائع لتغير الإفرازات ورائحتها، وغالبًا تكون الإفرازات رقيقة مع رائحة قوية.",["اختلال توازن البكتيريا الطبيعية"],"الحمل أو ألم الحوض أو حرارة أو نزيف غير معتاد يحتاج تقييمًا.","راجعي مختصًا للتأكد من السبب، خصوصًا إذا كانت الأعراض جديدة أو أثناء الحمل.","Bacterial vaginosis (BV)","A common cause of changed discharge and odor, often thin discharge with a strong smell.",["Imbalance in normal vaginal bacteria"],"Pregnancy, pelvic pain, fever, or unusual bleeding warrants assessment.","Seek clinical review to confirm the cause, especially with new symptoms or pregnancy."),
"anal_fissure": topic("🩸",["شق شرجي","الم قوي وقت التبرز","دم احمر مع الم بعد التبرز","anal fissure"],src("NHS","Anal fissure","https://www.nhs.uk/conditions/anal-fissure/"),"الشق الشرجي","تمزق صغير قد يسبب ألمًا حادًا أثناء التبرز وحرقانًا بعده مع دم أحمر فاتح.",["إمساك أو براز صلب","الحزق"],"نزيف غزير أو براز أسود أو دوخة/إغماء يحتاج تقييمًا عاجلًا.","حافظ على ليونة البراز وراجع مختصًا إذا لم يتحسن أو تكرر النزيف.","Anal fissure","A small tear can cause sharp pain with bowel movements, burning afterward, and bright red blood.",["Constipation or hard stool","Straining"],"Heavy bleeding, black stool, dizziness, or fainting needs urgent assessment.","Keep stools soft and seek review if it does not improve or bleeding recurs."),
"indigestion": topic("🫃",["عسر هضم","ثقل بعد الاكل","تكريع وانتفاخ بعد الاكل","indigestion","dyspepsia"],src("NHS","Indigestion","https://www.nhs.uk/conditions/indigestion/"),"عسر الهضم","قد يسبب حرقة أو امتلاء وانتفاخًا وغثيانًا وتجشؤًا، غالبًا بعد الأكل أو الشرب.",["ارتجاع حمضي","وجبات كبيرة أو محفزات غذائية","بعض الأدوية"],"قيء دموي أو براز أسود أو ألم شديد أو فقد وزن غير مفسر يحتاج تقييمًا.","راجع مختصًا إذا كانت الأعراض متكررة أو مستمرة أو تزداد.","Indigestion","Can cause heartburn, fullness, bloating, nausea, and burping, often after food or drink.",["Acid reflux","Large meals or food triggers","Some medicines"],"Vomiting blood, black stool, severe pain, or unexplained weight loss needs assessment.","Seek review if symptoms are recurrent, persistent, or worsening."),
"dry_mouth": topic("💧",["جفاف الفم","فمي ناشف","حلقي وفمي ناشف الصباح","dry mouth","xerostomia"],src("NHS","Dry mouth","https://www.nhs.uk/symptoms/dry-mouth/"),"جفاف الفم","جفاف الفم شائع وقد يرتبط بالجفاف أو أدوية أو التنفس من الفم أو القلق.",["الجفاف","بعض الأدوية","التنفس من الفم","القلق"],"جفاف شديد مع قلة بول أو دوخة واضحة يحتاج تقييمًا.","اشرب سوائل بانتظام وراجع مختصًا إذا استمر أو ترافق مع عطش وتبول متكرر.","Dry mouth","Dry mouth is common and may relate to dehydration, medicines, mouth breathing, or anxiety.",["Dehydration","Some medicines","Mouth breathing","Anxiety"],"Severe dryness with reduced urination or marked dizziness needs assessment.","Sip fluids regularly and seek review if persistent or with excessive thirst/urination."),
"nosebleed": topic("👃",["رعاف","نزيف الانف","دم من الانف","nosebleed","epistaxis"],src("NHS","Nosebleed","https://www.nhs.uk/conditions/nosebleed/"),"نزيف الأنف","الرعاف شائع وغالبًا بسيط، وقد يحدث مع جفاف أو تهيج أو إصابة بسيطة.",["جفاف وتهيج الأنف","العبث بالأنف","إصابة بسيطة","أدوية أو اضطرابات نزف أحيانًا"],"إذا استمر أكثر من 10–15 دقيقة رغم الضغط أو كان غزيرًا أو بعد إصابة رأس أو مع دوخة فاطلب رعاية عاجلة.","اجلس للأمام واضغط على الجزء اللين من الأنف؛ راجع مختصًا إذا تكرر كثيرًا.","Nosebleed","Nosebleeds are common and often minor, sometimes related to dryness, irritation, or minor injury.",["Nasal dryness/irritation","Nose picking","Minor injury","Sometimes medicines/bleeding disorders"],"Bleeding lasting over 10–15 minutes despite pressure, heavy bleeding, head injury, or dizziness needs urgent care.","Sit forward and pinch the soft part of the nose; seek review if recurrent."),
"breast_pain": topic("🌷",["الم الثدي","حساسية الثدي قبل الدورة","ثديي يوجع","breast pain","breast tenderness"],src("NHS","Breast pain","https://www.nhs.uk/symptoms/breast-pain/"),"ألم الثدي","ألم الثدي شائع وغالبًا يرتبط بالدورة، لكنه قد يرتبط بإصابة أو دواء أو أسباب أخرى.",["تغيرات الدورة","إصابة الرقبة/الكتف/الصدر","بعض الأدوية","حمل أو التهاب"],"كتلة صلبة ثابتة أو تغير شكل الثدي أو إفراز دموي أو احمرار وسخونة مع حرارة يحتاج تقييمًا سريعًا.","راقبي ارتباط الألم بالدورة وراجعي مختصًا إذا لم يتحسن أو ظهرت تغيرات جديدة.","Breast pain","Breast pain is common and often linked to periods, but can also relate to injury, medicines, or other causes.",["Cycle changes","Neck/shoulder/chest strain","Some medicines","Pregnancy or inflammation"],"A fixed hard lump, breast-shape change, bloody discharge, or red hot breast with fever needs prompt assessment.","Track relation to the cycle and seek review if persistent or new breast changes appear."),
"simple_sore_throat": topic("🗣️",["الم حلق","حلقي يوجع","البلع يوجع","حكة بالحلق","sore throat","scratchy throat"],src("NHS","Sore throat","https://www.nhs.uk/symptoms/sore-throat/"),"ألم الحلق","ألم الحلق شائع وغالبًا يتحسن خلال نحو أسبوع، وعادة يرتبط بعدوى فيروسية أو تهيج.",["نزلة برد أو إنفلونزا","التهاب لوز أو حنجرة","تدخين أو تهيج","أحيانًا عدوى بكتيرية"],"صعوبة التنفس أو عدم القدرة على البلع أو سيلان اللعاب أو تدهور سريع يحتاج طوارئ.","اشرب سوائل وارتَح، وراجع مختصًا إذا لم يتحسن خلال أسبوع أو كان شديدًا/متكررًا.","Sore throat","Sore throat is very common and often improves within about a week, usually from viral infection or irritation.",["Cold or flu","Tonsillitis/laryngitis","Smoke/irritation","Sometimes bacterial infection"],"Breathing difficulty, inability to swallow, drooling, or rapid deterioration needs emergency care.","Drink fluids, rest, and seek review if not improving within a week or if severe/recurrent."),
}
