"""V74 bilingual health-search expansion with broader specialty sources."""
REVIEW_DATE = "2026-09-21"


def src(source_name, organization, title, url):
    return {
        "name": f"{title} — {source_name}", "title": title,
        "organization": organization, "source_name": source_name,
        "url": url, "last_verified": REVIEW_DATE,
    }


def topic(emoji, aliases, source, ar_title, ar_what, ar_causes, ar_worry, ar_doctor,
          en_title, en_what, en_causes, en_worry, en_doctor):
    return {
        "emoji": emoji, "category": "symptom", "aliases": aliases,
        "sources": [source], "last_reviewed": REVIEW_DATE,
        "population_scope": "general educational information; age, pregnancy, medicines, and medical history can change interpretation",
        "causes_label": {"ar": "أسباب أو سياقات محتملة", "en": "Possible causes or contexts"},
        "ar": {"title": ar_title, "what": ar_what, "causes": ar_causes, "worry": ar_worry, "doctor": ar_doctor},
        "en": {"title": en_title, "what": en_what, "causes": en_causes, "worry": en_worry, "doctor": en_doctor},
    }

NIDCR = "National Institute of Dental and Craniofacial Research"
NIDCD = "National Institute on Deafness and Other Communication Disorders"
NHS = "National Health Service"

EXTRA_SEARCH_KB_V6 = {
    "tooth_decay": topic("🦷", ["تسوس الأسنان","تسوس الاسنان","حفرة بالسن","حساسية الأسنان","tooth decay","cavity","tooth sensitivity"], src("NIDCR",NIDCR,"Tooth Decay","https://www.nidcr.nih.gov/health-info/tooth-decay"), "تسوس الأسنان", "قد يبدأ دون أعراض ثم يسبب حساسية أو ألمًا أو حفرة/بقعة في السن.", ["تراكم البلاك والأحماض","السكريات المتكررة وعوامل صحة الفم"], "تورم الوجه أو الفك، حرارة، أو صعوبة البلع/التنفس تحتاج تقييمًا سريعًا.", "احجز فحص أسنان إذا استمرت الحساسية أو الألم أو لاحظت حفرة واضحة.", "Tooth decay", "It may start without symptoms and later cause sensitivity, pain, or a visible cavity/spot.", ["Plaque and acid damage","Frequent sugars and oral-health factors"], "Facial/jaw swelling, fever, or swallowing/breathing difficulty needs prompt assessment.", "Arrange a dental check if sensitivity or pain persists or you notice a cavity."),
    "bruxism": topic("😬", ["صرير الأسنان","طحن الأسنان","اطحن اسناني بالنوم","أطحن أسناني بالنوم","bruxism","teeth grinding","teeth clenching"], src("NIDCR",NIDCR,"Bruxism","https://www.nidcr.nih.gov/health-info/bruxism"), "صرير أو ضغط الأسنان", "قد يحدث أثناء النوم أو اليقظة ويسبب تعب الفك أو صداعًا أو تآكلًا بالأسنان.", ["التوتر","عوامل النوم","بعض الأدوية أو عوامل الفك"], "ألم شديد أو كسر سن أو صعوبة فتح الفم يحتاج تقييمًا.", "راجع طبيب الأسنان إذا كان متكررًا أو يسبب ألمًا صباحيًا أو تآكل الأسنان.", "Bruxism", "Grinding or clenching can occur during sleep or wakefulness and may cause jaw fatigue, headaches, or tooth wear.", ["Stress","Sleep factors","Some medicines or jaw factors"], "Severe pain, tooth fracture, or difficulty opening the mouth needs assessment.", "See a dentist if it is frequent or causes morning pain or tooth wear."),
    "burning_mouth": topic("👄", ["حرقة الفم","حرقان اللسان","لساني يحرق","burning mouth","burning tongue"], src("NIDCR",NIDCR,"Burning Mouth","https://www.nidcr.nih.gov/health-info/burning-mouth"), "حرقة الفم أو اللسان", "الحرقة المستمرة قد تكون لها أسباب عصبية أو فموية أو طبية متعددة ولا تُحسم من العرض وحده.", ["جفاف الفم","عدوى فموية","أدوية أو نقص عناصر","متلازمة حرقة الفم"], "قرحة أو بقعة لا تلتئم، صعوبة بلع أو تورم يحتاج تقييمًا.", "راجع طبيب الأسنان أو الطبيب إذا استمرت الحرقة دون سبب واضح.", "Burning mouth or tongue", "Persistent burning can have neurological, oral, or medical causes and cannot be determined from the symptom alone.", ["Dry mouth","Oral infection","Medicines or deficiencies","Burning mouth syndrome"], "A non-healing ulcer/patch, swallowing difficulty, or swelling needs assessment.", "See a dentist or clinician if burning persists without a clear cause."),
    "salivary_gland_swelling": topic("💧", ["تورم الغدة اللعابية","انتفاخ تحت الفك وقت الاكل","انتفاخ تحت الفك وقت الأكل","salivary gland swelling","swelling under jaw with meals"], src("NIDCR",NIDCR,"Saliva and Salivary Gland Disorders","https://www.nidcr.nih.gov/health-info/saliva-salivary-gland-disorders"), "تورم الغدد اللعابية مع الأكل", "تورم أو ألم تحت الفك أو قرب الأذن يزداد مع الوجبات قد يرتبط بانسداد قناة لعابية أو اضطراب بالغدة.", ["حصوة بالقناة اللعابية","التهاب أو اضطرابات الغدد اللعابية"], "حمى أو قيح أو تورم سريع أو صعوبة البلع/التنفس يحتاج تقييمًا عاجلًا.", "راجع طبيب الأسنان أو الأنف والأذن أو الطبيب إذا تكرر مع الوجبات أو استمر.", "Salivary gland swelling with meals", "Swelling or pain under the jaw or near the ear that worsens with meals can fit salivary-duct obstruction or another gland disorder.", ["Salivary duct stone","Infection or other gland disorders"], "Fever, pus, rapid swelling, or swallowing/breathing difficulty needs urgent assessment.", "Seek dental, ENT, or medical assessment if it recurs with meals or persists."),
    "tinnitus": topic("👂", ["طنين الأذن","طنين الاذن","ازيز بالاذن","أزيز بالأذن","tinnitus","ringing in ears","buzzing in ear"], src("NIDCD",NIDCD,"Tinnitus","https://www.nidcd.nih.gov/health/tinnitus"), "طنين الأذن", "هو سماع رنين أو أزيز أو صوت دون مصدر خارجي، وقد يكون مؤقتًا أو مستمرًا وله أسباب متعددة.", ["التعرض للضوضاء","تغيرات السمع","شمع الأذن أو بعض الأدوية"], "فقد سمع مفاجئ، طنين نابض مع النبض، أو أعراض عصبية جديدة يحتاج تقييمًا سريعًا.", "راجع مختصًا إذا استمر أو ازداد أو كان في جهة واحدة أو أثر على النوم والتركيز.", "Tinnitus", "Hearing ringing, buzzing, or another sound without an external source can be temporary or persistent and has many causes.", ["Noise exposure","Hearing changes","Earwax or some medicines"], "Sudden hearing loss, pulsatile tinnitus, or new neurological symptoms needs prompt assessment.", "Seek review if it persists, worsens, is one-sided, or affects sleep/concentration."),
    "heat_rash": topic("🌡️", ["طفح من الحر","حبوب من الحر","حمو النيل","heat rash","prickly heat"], src("NHS",NHS,"Heat rash (prickly heat)","https://www.nhs.uk/conditions/heat-rash-prickly-heat/"), "الطفح الحراري", "حبوب صغيرة مع حكة أو إحساس لاذع قد تظهر مع الحر والتعرق.", ["الحرارة والتعرق","انسداد قنوات العرق"], "حمى أو ألم شديد أو قيح أو انتشار سريع يحتاج تقييمًا.", "حافظ على برودة وجفاف الجلد واطلب المشورة إذا لم يتحسن.", "Heat rash", "Small itchy or prickly bumps can appear with heat and sweating.", ["Heat and sweating","Blocked sweat ducts"], "Fever, severe pain, pus, or rapid spread needs assessment.", "Keep skin cool and dry and seek advice if it does not improve."),
    "sunburn": topic("☀️", ["حرق شمس","انحرقت من الشمس","جلدي محروق من الشمس","sunburn","sun burned skin"], src("NHS",NHS,"Sunburn","https://www.nhs.uk/conditions/sunburn/"), "حرق الشمس", "قد يسبب احمرارًا وألمًا بالجلد بعد التعرض للأشعة فوق البنفسجية، وقد تظهر فقاعات إذا كان أشد.", ["التعرض الزائد للشمس أو الأشعة فوق البنفسجية"], "فقاعات واسعة، تورم شديد، دوخة أو علامات ضربة حرارة تحتاج تقييمًا سريعًا.", "ابتعد عن الشمس وبرّد الجلد بلطف واشرب السوائل.", "Sunburn", "UV exposure can cause red, painful skin and may blister when more severe.", ["Excess sun or UV exposure"], "Extensive blistering, severe swelling, dizziness, or heat-illness signs need prompt assessment.", "Get out of the sun, cool the skin gently, and hydrate."),
    "insect_bites": topic("🦟", ["قرصة حشرة","لدغة حشرة","انتفاخ بعد لدغة","insect bite","bug bite","insect sting"], src("NHS",NHS,"Insect bites and stings","https://www.nhs.uk/conditions/insect-bites-and-stings/"), "قرصات ولسعات الحشرات", "غالبًا تسبب حبة أو تورمًا موضعيًا مع حكة أو ألم بسيط.", ["تفاعل موضعي مع اللدغة أو اللسعة","حساسية أو عدوى أحيانًا"], "صعوبة تنفس أو تورم اللسان/الحلق أو دوخة شديدة يستدعي الطوارئ.", "نظف المنطقة وتجنب الحك واطلب المشورة إذا زاد الاحمرار أو الألم.", "Insect bites and stings", "They often cause a local itchy or mildly painful lump or swelling.", ["Local bite/sting reaction","Occasional allergy or infection"], "Breathing difficulty, tongue/throat swelling, or severe dizziness is an emergency.", "Clean the area, avoid scratching, and seek advice if redness or pain increases."),
    "boils": topic("🩹", ["دمل","خراج جلدي","حبة كبيرة فيها صديد","boil","skin abscess"], src("NHS",NHS,"Boils","https://www.nhs.uk/conditions/boils/"), "الدمامل", "الدمل كتلة جلدية مؤلمة مملوءة بالقيح نتيجة عدوى حول بصيلة شعر غالبًا.", ["عدوى بكتيرية بالجلد أو بصيلة الشعر"], "حمى أو انتشار احمرار سريع أو دمل بالوجه أو ضعف مناعة يحتاج تقييمًا.", "لا تعصره؛ اطلب المشورة إذا كان كبيرًا أو شديد الألم أو لا يتحسن.", "Boils", "A boil is a painful pus-filled skin lump, usually from infection around a hair follicle.", ["Bacterial skin or hair-follicle infection"], "Fever, rapidly spreading redness, a facial boil, or immunocompromise needs assessment.", "Do not squeeze it; seek advice if large, very painful, or not improving."),
    "chilblains": topic("🧦", ["شرث","تورم الاصابع من البرد","حكة الأصابع مع البرد","chilblains","itchy toes after cold"], src("NHS",NHS,"Chilblains","https://www.nhs.uk/conditions/chilblains/"), "تورمات البرد (الشرث)", "قد تظهر بقع حاكة أو مؤلمة ومتورمة على الأصابع بعد التعرض للبرد.", ["استجابة الأوعية الصغيرة للبرد ثم الدفء"], "تقرح أو صديد أو اسوداد الأصابع أو ألم شديد مستمر يحتاج تقييمًا.", "حافظ على الدفء تدريجيًا وراجع الطبيب إذا لم تتحسن أو تكررت كثيرًا.", "Chilblains", "Itchy, painful, swollen patches can appear on digits after cold exposure.", ["Small-vessel response to cold and rewarming"], "Ulceration, pus, blackening, or severe persistent pain needs assessment.", "Warm gradually and seek review if they do not improve or recur often."),
    "catarrh": topic("🤧", ["مخاط خلف الانف","مخاط خلف الأنف","مخاط ينزل للحلق","بلغم عالق بالحلق","catarrh","post nasal drip"], src("NHS",NHS,"Catarrh","https://www.nhs.uk/conditions/catarrh/"), "المخاط خلف الأنف والاحتقان", "قد يسبب إحساسًا بمخاط عالق أو نازل خلف الحلق مع انسداد الأنف والتنحنح.", ["نزلات البرد","الحساسية","تهيج الأنف أو الجيوب"], "ضيق تنفس شديد أو تورم وجه سريع مع حرارة يحتاج تقييمًا عاجلًا.", "السوائل وغسل الأنف بالمحلول الملحي قد يساعدان؛ راجع مختصًا إذا استمر لأسابيع.", "Catarrh / post-nasal mucus", "Can cause a mucus sensation or drainage down the throat with nasal blockage and throat clearing.", ["Colds","Allergy","Nasal or sinus irritation"], "Severe breathing difficulty or rapidly progressive facial swelling with fever needs urgent assessment.", "Fluids and saline nasal rinsing may help; seek review if it persists for weeks."),
    "hyperhidrosis": topic("💦", ["تعرق مفرط","اتعرق كثير بدون سبب","أتعرق كثير بدون سبب","يدي تعرق كثير","hyperhidrosis","excessive sweating"], src("NHS",NHS,"Excessive sweating (hyperhidrosis)","https://www.nhs.uk/conditions/excessive-sweating-hyperhidrosis/"), "التعرق المفرط", "هو التعرق أكثر مما يحتاجه الجسم للتبريد وقد يصيب مناطق محددة أو الجسم بشكل أوسع.", ["فرط تعرق أولي","أدوية أو حالات صحية أخرى"], "تعرق مفاجئ مع ألم صدر أو ضيق نفس أو إغماء يحتاج تقييمًا عاجلًا.", "راجع الطبيب إذا بدأ فجأة أو يزعج حياتك أو يحدث ليلًا دون سبب واضح.", "Excessive sweating", "Sweating more than the body needs for cooling can affect specific areas or be more generalized.", ["Primary hyperhidrosis","Medicines or other health conditions"], "Sudden sweating with chest pain, breathlessness, or fainting needs urgent assessment.", "Seek review if it starts suddenly, disrupts life, or occurs at night without a clear reason."),
    "frozen_shoulder": topic("🦾", ["كتف متجمد","كتفي متيبس","ما اقدر ارفع يدي بسبب الكتف","frozen shoulder","stiff shoulder"], src("NHS",NHS,"Frozen shoulder","https://www.nhs.uk/conditions/frozen-shoulder/"), "الكتف المتجمد", "يسبب ألمًا وتيبسًا تدريجيًا مع محدودية واضحة في حركة الكتف.", ["التهاب وشد محفظة مفصل الكتف","قد يظهر بعد قلة الحركة أو دون سبب واضح"], "إصابة قوية، تشوه، ضعف مفاجئ أو ألم كتف مع أعراض صدرية يحتاج تقييمًا سريعًا.", "راجع الطبيب أو العلاج الطبيعي إذا استمر التيبس أو حدّ من الحركة.", "Frozen shoulder", "It causes gradually increasing pain and stiffness with clear restriction of shoulder movement.", ["Inflammation/tightening of the shoulder capsule","May follow immobility or have no clear trigger"], "Major injury, deformity, sudden weakness, or shoulder pain with chest symptoms needs prompt assessment.", "See a clinician or physiotherapist if stiffness persists or limits movement."),
    "repetitive_strain_injury": topic("⌨️", ["إجهاد متكرر","الم من استخدام الماوس","ألم من استخدام الماوس","يدي تنمل من الكمبيوتر","repetitive strain injury","RSI","pain from mouse use"], src("NHS",NHS,"Repetitive strain injury (RSI)","https://www.nhs.uk/conditions/repetitive-strain-injury-rsi/"), "إصابة الإجهاد المتكرر", "قد يظهر ألم أو تيبس أو وخز مرتبط بحركات متكررة في الدراسة أو العمل.", ["تكرار الحركة","وضعية غير مريحة","حمل متكرر على العضلات والأوتار"], "ضعف مفاجئ أو فقد إحساس واضح أو تورم شديد يحتاج تقييمًا.", "خفف المحفز مؤقتًا وحسّن الوضعية وفترات الراحة وراجع مختصًا إذا استمر.", "Repetitive strain injury", "Pain, stiffness, or tingling can be linked to repeated movements at work or study.", ["Repeated movement","Awkward posture","Repeated muscle/tendon load"], "Sudden weakness, marked sensory loss, or severe swelling needs assessment.", "Reduce the trigger temporarily, improve ergonomics and breaks, and seek review if persistent."),
    "shin_splints": topic("🏃", ["ألم قصبة الساق بعد الجري","الم قصبة الساق بعد الجري","وجع الساق مع الركض","shin splints","shin pain after running"], src("NHS",NHS,"Shin splints","https://www.nhs.uk/conditions/shin-splints/"), "ألم قصبة الساق مع الرياضة", "ألم على طول القصبة بعد الجري أو زيادة التمرين قد يتوافق مع shin splints.", ["زيادة الحمل الرياضي بسرعة","أسطح الجري أو الحذاء أو الميكانيكا الحركية"], "عدم القدرة على تحمل الوزن أو تورم شديد أو ألم شديد موضّع بعد إصابة يحتاج تقييمًا.", "أوقف النشاط المسبب مؤقتًا وارجع تدريجيًا بعد التحسن.", "Shin splints", "Pain along the shin after running or increased training can fit shin splints.", ["Rapid training-load increase","Running surface, footwear, or movement mechanics"], "Inability to bear weight, marked swelling, or severe focal pain after injury needs assessment.", "Pause the provoking activity and return gradually after improvement."),
    "missed_period": topic("🗓️", ["الدورة متأخرة","الدوره متاخره","ما نزلت الدورة","غياب الدورة","missed period","late period"], src("NHS",NHS,"Missed or late periods","https://www.nhs.uk/symptoms/missed-or-late-periods/"), "تأخر أو غياب الدورة", "تأخر الدورة شائع وله أسباب كثيرة، ولا يعني سببًا واحدًا بعينه.", ["الحمل","التوتر أو تغير الوزن","الرياضة الشديدة","موانع الحمل أو حالات هرمونية"], "ألم شديد أسفل البطن مع نزيف أو دوخة/إغماء مع احتمال حمل يحتاج تقييمًا عاجلًا.", "إذا كان الحمل ممكنًا فاختبار الحمل خطوة أولى مناسبة؛ راجعي الطبيب إذا تكرر الغياب.", "Missed or late period", "Late periods are common and have many possible causes rather than one single explanation.", ["Pregnancy","Stress or weight change","Intense exercise","Contraception or hormonal conditions"], "Severe lower-abdominal pain with bleeding or dizziness/fainting when pregnancy is possible needs urgent assessment.", "If pregnancy is possible, a pregnancy test is a reasonable first step; seek review if missed periods recur."),
    "vaginal_dryness": topic("🌸", ["جفاف مهبلي","جفاف بالمهبل","المنطقة جافة","vaginal dryness"], src("NHS",NHS,"Vaginal dryness","https://www.nhs.uk/symptoms/vaginal-dryness/"), "الجفاف المهبلي", "قد يسبب انزعاجًا أو حكة أو ألمًا أثناء العلاقة وله أسباب هرمونية ودوائية وموضعية متعددة.", ["تغيرات هرمونية","بعض الأدوية","مهيجات موضعية أو عوامل أخرى"], "نزيف غير معتاد أو ألم حوض شديد أو إفرازات مع حرارة يحتاج تقييمًا.", "تجنبي المنتجات المعطرة المهيجة وناقشي خيارات الترطيب أو المزلقات المناسبة مع مختص إذا استمر.", "Vaginal dryness", "It can cause discomfort, itching, or pain during sex and has multiple hormonal, medicine-related, and local causes.", ["Hormonal changes","Some medicines","Local irritants or other factors"], "Unusual bleeding, severe pelvic pain, or discharge with fever needs assessment.", "Avoid irritating perfumed products and discuss suitable moisturizers or lubricants with a clinician if persistent."),
    "mouth_ulcers": topic("👄", ["قرحة بالفم","تقرحات الفم","قرحة باللسان","mouth ulcer","canker sore"], src("NHS",NHS,"Mouth ulcers","https://www.nhs.uk/conditions/mouth-ulcers/"), "قرح الفم", "شائعة وغالبًا تلتئم خلال أسبوع أو أسبوعين، وقد تظهر بعد احتكاك أو عض الخد أو التوتر وعوامل أخرى.", ["رض أو احتكاك موضعي","توتر أو تهيج","عوامل غذائية أو دوائية أحيانًا"], "قرحة تستمر أكثر من 3 أسابيع أو تنزف أو تكبر أو ترافقها كتلة/صعوبة بلع تحتاج فحصًا.", "تجنب المهيجات وحافظ على نظافة الفم وراجع طبيبًا أو طبيب أسنان إذا استمرت أكثر من 3 أسابيع.", "Mouth ulcers", "They are common and often heal within one or two weeks, sometimes after irritation, cheek biting, stress, or other factors.", ["Local trauma or irritation","Stress or irritation","Sometimes nutritional or medicine-related factors"], "An ulcer lasting over 3 weeks, bleeding, enlarging, or accompanied by a lump/swallowing difficulty needs assessment.", "Avoid irritants, maintain oral hygiene, and seek medical or dental review if it lasts over 3 weeks."),
}
