"""Bilingual educational search/assistant additions. Sources checked 2026-09-17.
No diagnostic scores, treatment doses, or user data are stored here.
"""

EXTRA_SEARCH_KB = {'constipation': {'emoji': '🩺',
                  'category': 'symptom',
                  'aliases': ['الإمساك',
                              'Constipation',
                              'امساك',
                              'صعوبة التبرز',
                              'براز قاسي',
                              'ما اقدر اتبرز',
                              'hard stools',
                              'difficulty passing stool',
                              'constipated'],
                  'sources': [{'name': 'Constipation — NHS',
                               'title': 'Constipation',
                               'organization': 'NHS',
                               'source_name': 'NHS',
                               'url': 'https://www.nhs.uk/conditions/constipation/',
                               'last_verified': '2026-09-17'}],
                  'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
                  'ar': {'title': 'الإمساك',
                         'what': 'الإمساك قد يظهر كبراز صلب أو صعوبة التبرز أو قلة التبرز عن المعتاد.',
                         'causes': ['قلة الألياف أو السوائل', 'قلة الحركة', 'بعض الأدوية'],
                         'self_care': 'زد الألياف تدريجيًا، واشرب سوائل بحسب احتياجك وقيودك الطبية، وحافظ على '
                                      'الحركة.',
                         'worry': 'اطلب تقييمًا سريعًا عند وجود دم بالبراز أو ألم بطني مستمر.',
                         'doctor': 'راجع مختصًا إذا استمر الإمساك أو تكرر، خصوصًا مع نقص وزن غير مقصود.',
                         'follow_up': 'منذ متى تغير التبرز؟'},
                  'en': {'title': 'Constipation',
                         'what': 'Constipation can mean hard stools, straining, or passing stool less often than '
                                 'usual.',
                         'causes': ['Low fibre or fluid intake', 'Inactivity', 'Some medicines'],
                         'self_care': 'Increase fibre gradually, drink according to your needs and medical '
                                      'restrictions, and stay active.',
                         'worry': 'Seek prompt assessment for blood in stool or persistent abdominal pain.',
                         'doctor': 'Seek review if constipation persists or recurs, especially with unintentional '
                                   'weight loss.',
                         'follow_up': 'When did your bowel pattern change?'}},
 'bloating': {'emoji': '🩺',
              'category': 'symptom',
              'aliases': ['انتفاخ البطن',
                          'Bloating',
                          'غازات',
                          'بطني منفوخ',
                          'نفخة البطن',
                          'انتفاخ بعد الاكل',
                          'trapped wind',
                          'bloated stomach',
                          'bloating after eating'],
              'sources': [{'name': 'Bloating — NHS',
                           'title': 'Bloating',
                           'organization': 'NHS',
                           'source_name': 'NHS',
                           'url': 'https://www.nhs.uk/conditions/bloating/',
                           'last_verified': '2026-09-17'}],
              'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
              'ar': {'title': 'انتفاخ البطن',
                     'what': 'الانتفاخ شعور بامتلاء البطن؛ وقد يزيد بعد الأكل بسبب الغازات أو ابتلاع الهواء.',
                     'causes': ['الغازات', 'الإمساك', 'عدم تحمل بعض الأطعمة'],
                     'self_care': 'جرّب وجبات أصغر، والأكل ببطء، وتقليل المشروبات الغازية.',
                     'worry': 'الألم المفاجئ الشديد أو قيء الدم يستدعي الطوارئ؛ وعدم خروج البراز أو الغازات يحتاج '
                              'تقييمًا عاجلًا.',
                     'doctor': 'راجع مختصًا إذا تكرر الانتفاخ أو ترافق مع نقص وزن.',
                     'follow_up': 'هل يرتبط الانتفاخ بطعام معين؟'},
              'en': {'title': 'Bloating',
                     'what': 'Bloating is abdominal fullness; gas or swallowed air can make it worse after meals.',
                     'causes': ['Gas', 'Constipation', 'Food intolerance'],
                     'self_care': 'Try smaller meals, eat slowly, and reduce fizzy drinks.',
                     'worry': 'Sudden severe pain or vomiting blood needs emergency care; inability to pass stool '
                              'or wind needs urgent assessment.',
                     'doctor': 'Seek review for recurring bloating or weight loss.',
                     'follow_up': 'Does a particular food trigger it?'},
              'context_questions': {'ar': ['ليش بطني ينتفخ بعد الاكل', 'بطني ينتفخ بعد الأكل'],
                                    'en': ['why am I bloated after eating', 'why do I get bloating after meals']}},
 'reflux': {'emoji': '🩺',
            'category': 'symptom',
            'aliases': ['حرقة المعدة',
                        'Acid reflux',
                        'حموضة',
                        'ارتجاع المريء',
                        'حرقة بعد الاكل',
                        'طعم حامض بالفم',
                        'heartburn',
                        'acid reflux after eating',
                        'sour taste in mouth'],
            'sources': [{'name': 'Acid reflux — NHS',
                         'title': 'Acid reflux',
                         'organization': 'NHS',
                         'source_name': 'NHS',
                         'url': 'https://www.nhs.uk/conditions/heartburn-and-acid-reflux/',
                         'last_verified': '2026-09-17'},
                        {'name': 'Heart attack warning signs — NHS',
                         'title': 'Heart attack warning signs',
                         'organization': 'NHS',
                         'source_name': 'NHS',
                         'url': 'https://www.nhs.uk/conditions/heart-attack/',
                         'last_verified': '2026-09-17'}],
            'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
            'ar': {'title': 'حرقة المعدة',
                   'what': 'قد يسبب رجوع حمض المعدة حرقة وطعمًا حامضًا، وتزداد الأعراض أحيانًا بعد الأكل أو '
                           'الاستلقاء.',
                   'causes': ['بعض الأطعمة', 'التدخين', 'بعض الأدوية'],
                   'self_care': 'تناول وجبات أصغر وتجنب الأكل قرب النوم، واسأل الصيدلي عن الخيارات المناسبة.',
                   'worry': 'لا تفترض أن ألم الصدر الجديد أو الشديد مجرد حموضة؛ اطلب تقييمًا عاجلًا.',
                   'doctor': 'راجع مختصًا عند صعوبة البلع أو نقص الوزن أو الحرقة المتكررة.',
                   'follow_up': 'هل تزداد الحرقة بعد الوجبات أو الاستلقاء؟'},
            'en': {'title': 'Acid reflux',
                   'what': 'Stomach acid returning upwards can cause burning and a sour taste, sometimes worse '
                           'after meals or lying down.',
                   'causes': ['Food triggers', 'Smoking', 'Some medicines'],
                   'self_care': 'Eat smaller meals, avoid eating near bedtime, and ask a pharmacist about '
                                'suitable options.',
                   'worry': 'Do not assume new or severe chest pain is reflux; seek urgent assessment.',
                   'doctor': 'Seek review for swallowing difficulty, weight loss, or frequent heartburn.',
                   'follow_up': 'Is it worse after meals or lying down?'},
            'context_questions': {'ar': ['ليش تجيني حموضة بعد الاكل', 'حموضة بعد الاكل', 'حرقة عند الاستلقاء'],
                                  'en': ['why do I get heartburn after eating', 'heartburn when lying down']}},
 'diarrhea': {'emoji': '🩺',
              'category': 'symptom',
              'aliases': ['الإسهال',
                          'Diarrhoea',
                          'اسهال',
                          'براز مائي',
                          'اسهال وترجيع',
                          'إسهال وقيء',
                          'diarrhea',
                          'watery stools',
                          'diarrhoea and vomiting'],
              'sources': [{'name': 'Diarrhoea — NHS',
                           'title': 'Diarrhoea',
                           'organization': 'NHS',
                           'source_name': 'NHS',
                           'url': 'https://www.nhs.uk/symptoms/diarrhoea-and-vomiting/',
                           'last_verified': '2026-09-17'}],
              'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
              'ar': {'title': 'الإسهال',
                     'what': 'الإسهال هو براز رخو أو مائي؛ تعويض السوائل مهم لتجنب الجفاف.',
                     'causes': ['عدوى معوية', 'طعام ملوث', 'بعض الأدوية'],
                     'self_care': 'خذ رشفات صغيرة متكررة، واسأل الصيدلي عن محلول الإماهة.',
                     'worry': 'اطلب مساعدة عاجلة عند الدم أو تعذر الاحتفاظ بالسوائل؛ التشوش أو الألم المفاجئ '
                              'الشديد يستدعي الطوارئ.',
                     'doctor': 'راجع مختصًا إذا استمر الإسهال أكثر من أسبوع، وأبكر عند الرضع أو علامات الجفاف.',
                     'follow_up': 'هل تستطيع شرب السوائل والاحتفاظ بها؟'},
              'en': {'title': 'Diarrhoea',
                     'what': 'Diarrhoea means loose or watery stools; replacing fluids helps prevent dehydration.',
                     'causes': ['Gut infection', 'Contaminated food', 'Some medicines'],
                     'self_care': 'Take frequent small sips and ask a pharmacist about oral rehydration solution.',
                     'worry': 'Seek urgent help for blood or inability to keep fluids down; confusion or sudden '
                              'severe pain needs emergency care.',
                     'doctor': 'Seek review if it lasts over a week, sooner for infants or dehydration.',
                     'follow_up': 'Can you keep fluids down?'}},
 'hair_loss': {'emoji': '🩺',
               'category': 'symptom',
               'aliases': ['تساقط الشعر',
                           'Hair loss',
                           'شعري يتساقط',
                           'شعري يطيح',
                           'شعري يتساقط كثير',
                           'فراغات الشعر',
                           'hair shedding',
                           'my hair is falling out',
                           'thinning hair'],
               'sources': [{'name': 'Hair loss — NHS',
                            'title': 'Hair loss',
                            'organization': 'NHS',
                            'source_name': 'NHS',
                            'url': 'https://www.nhs.uk/symptoms/hair-loss/',
                            'last_verified': '2026-09-17'}],
               'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
               'ar': {'title': 'تساقط الشعر',
                      'what': 'تساقط الشعر له أسباب متعددة، وبعضه مؤقت؛ لا يثبت وحده نقص فيتامين معين.',
                      'causes': ['الوراثة', 'الضغط النفسي أو مرض سابق', 'نقص الحديد أو فقدان الوزن'],
                      'self_care': 'ناقش السبب قبل بدء مكملات أو علاجات للشعر.',
                      'worry': 'التساقط وحده ليس عادة حالة طارئة.',
                      'doctor': 'اطلب تقييمًا إذا كان التساقط يثير القلق أو يؤثر في حياتك.',
                      'follow_up': 'هل التساقط منتشر أم في بقع؟'},
               'en': {'title': 'Hair loss',
                      'what': 'Hair loss has several causes and may be temporary; it does not prove a specific '
                              'vitamin deficiency.',
                      'causes': ['Inherited patterns',
                                 'Stress or recent illness',
                                 'Iron deficiency or weight loss'],
                      'self_care': 'Discuss the cause before starting supplements or hair treatments.',
                      'worry': 'Hair loss alone is usually not an emergency.',
                      'doctor': 'Seek assessment if hair loss worries you or affects your wellbeing.',
                      'follow_up': 'Is the loss widespread or patchy?'}},
 'period_pain': {'emoji': '🩺',
                 'category': 'symptom',
                 'aliases': ['ألم الدورة',
                             'Period pain',
                             'تقلصات الدورة',
                             'مغص الدورة',
                             'دورتي توجعني',
                             'الم الدوره',
                             'menstrual cramps',
                             'painful periods',
                             'period cramps'],
                 'sources': [{'name': 'Period pain — NHS',
                              'title': 'Period pain',
                              'organization': 'NHS',
                              'source_name': 'NHS',
                              'url': 'https://www.nhs.uk/symptoms/period-pain/',
                              'last_verified': '2026-09-17'}],
                 'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
                 'ar': {'title': 'ألم الدورة',
                        'what': 'تقلصات الرحم قد تسبب ألمًا مع بداية الدورة، لكن الألم المعطل للنشاط يحتاج '
                                'تقييمًا.',
                        'causes': ['تقلصات الدورة', 'بطانة الرحم المهاجرة', 'أسباب نسائية أخرى'],
                        'self_care': 'قد تساعد كمادة دافئة ملفوفة بقماش وحركة لطيفة.',
                        'worry': 'اطلب تقييمًا عاجلًا للألم الشديد أو الأسوأ من المعتاد الذي لا يتحسن.',
                        'doctor': 'راجع مختصًا عند زيادة الألم أو غزارة الدورة أو نزف بين الدورات.',
                        'follow_up': 'هل يمنعك الألم من أنشطتك المعتادة؟'},
                 'en': {'title': 'Period pain',
                        'what': 'Uterine contractions can cause cramps near the start of a period; disabling pain '
                                'deserves assessment.',
                        'causes': ['Menstrual contractions', 'Endometriosis', 'Other gynaecological causes'],
                        'self_care': 'A wrapped warm pack and gentle activity may help.',
                        'worry': 'Seek urgent assessment for severe or unusually worse pain that does not '
                                 'improve.',
                        'doctor': 'Seek review for worsening pain, heavy periods, or bleeding between periods.',
                        'follow_up': 'Does the pain stop your usual activities?'},
                 'context_questions': {'ar': ['كيف اخفف مغص الدورة', 'وش اسوي لألم الدورة'],
                                       'en': ['how can I ease period cramps', 'what helps menstrual cramps']}},
 'palpitations': {'emoji': '🩺',
                  'category': 'symptom',
                  'aliases': ['خفقان القلب',
                              'Heart palpitations',
                              'قلبي يدق بسرعة',
                              'دقات قلبي سريعة',
                              'خفقان بعد القهوة',
                              'نبضي سريع',
                              'racing heartbeat',
                              'heart fluttering',
                              'palpitations after coffee'],
                  'sources': [{'name': 'Heart palpitations — NHS',
                               'title': 'Heart palpitations',
                               'organization': 'NHS',
                               'source_name': 'NHS',
                               'url': 'https://www.nhs.uk/symptoms/heart-palpitations/',
                               'last_verified': '2026-09-17'}],
                  'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
                  'ar': {'title': 'خفقان القلب',
                         'what': 'الخفقان شعور أوضح أو غير معتاد بضربات القلب. قد يثيره الكافيين، لكن تكراره '
                                 'يحتاج تقييمًا.',
                         'causes': ['الكافيين أو قلة النوم', 'التوتر', 'اضطراب نظم القلب'],
                         'self_care': 'قلل المحفزات التي تلاحظ ارتباطها بالخفقان.',
                         'worry': 'الخفقان المستمر أو المصحوب بألم صدر أو ضيق تنفس أو إغماء يستدعي الطوارئ.',
                         'doctor': 'راجع مختصًا إذا تكرر أو استمر عدة دقائق.',
                         'follow_up': 'كم تستمر النوبة؟'},
                  'en': {'title': 'Heart palpitations',
                         'what': 'Palpitations are noticeable or unusual heartbeats. Caffeine can trigger them, '
                                 'but recurring episodes need assessment.',
                         'causes': ['Caffeine or poor sleep', 'Stress', 'Heart rhythm problems'],
                         'self_care': 'Reduce triggers you notice are associated with episodes.',
                         'worry': 'Persistent palpitations or palpitations with chest pain, breathlessness, or '
                                  'fainting need emergency care.',
                         'doctor': 'Seek review if episodes recur or last several minutes.',
                         'follow_up': 'How long does an episode last?'},
                  'context_questions': {'ar': ['ليش قلبي يدق بسرعة بعد القهوة', 'خفقان بعد شرب القهوة'],
                                        'en': ['why does my heart race after coffee',
                                               'palpitations after drinking coffee']}},
 'tingling': {'emoji': '🩺',
              'category': 'symptom',
              'aliases': ['تنميل الأطراف',
                          'Pins and needles',
                          'تنميل اليد',
                          'تنميل الرجل',
                          'يدي تنمل',
                          'تنميل بعد النوم',
                          'tingling hands',
                          'numb feet',
                          'pins and needles after sleeping'],
              'sources': [{'name': 'Pins and needles — NHS',
                           'title': 'Pins and needles',
                           'organization': 'NHS',
                           'source_name': 'NHS',
                           'url': 'https://www.nhs.uk/symptoms/pins-and-needles/',
                           'last_verified': '2026-09-17'},
                          {'name': 'Stroke warning signs — NHS',
                           'title': 'Stroke warning signs',
                           'organization': 'NHS',
                           'source_name': 'NHS',
                           'url': 'https://www.nhs.uk/conditions/stroke/symptoms/',
                           'last_verified': '2026-09-17'}],
              'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
              'ar': {'title': 'تنميل الأطراف',
                     'what': 'قد يحدث وخز مؤقت بعد الضغط على طرف أثناء النوم أو الجلوس؛ الاستمرار يحتاج فحصًا.',
                     'causes': ['ضغط مؤقت على الأعصاب', 'عصب مضغوط', 'اعتلال الأعصاب'],
                     'self_care': 'غيّر الوضعية برفق وتجنب الضغط المستمر على الطرف.',
                     'worry': 'ظهور ضعف مفاجئ أو اضطراب كلام مع التنميل يستدعي الطوارئ.',
                     'doctor': 'راجع مختصًا إذا استمر التنميل أو تكرر.',
                     'follow_up': 'هل يزول عند تغيير الوضعية؟'},
              'en': {'title': 'Pins and needles',
                     'what': 'Temporary tingling may follow pressure on a limb while sleeping or sitting; '
                             'persistent symptoms need assessment.',
                     'causes': ['Temporary nerve pressure', 'A trapped nerve', 'Nerve damage'],
                     'self_care': 'Change position gently and avoid prolonged pressure on the limb.',
                     'worry': 'Sudden weakness or speech difficulty with numbness needs emergency care.',
                     'doctor': 'Seek review for persistent or recurring tingling.',
                     'follow_up': 'Does changing position relieve it?'}},
 'back_pain': {'emoji': '🩺',
               'category': 'symptom',
               'aliases': ['ألم الظهر',
                           'Back pain',
                           'ظهري يوجعني',
                           'الم اسفل الظهر',
                           'وجع الظهر',
                           'ألم أسفل الظهر',
                           'lower back pain',
                           'my back hurts',
                           'backache'],
               'sources': [{'name': 'Back pain — NHS',
                            'title': 'Back pain',
                            'organization': 'NHS',
                            'source_name': 'NHS',
                            'url': 'https://www.nhs.uk/conditions/back-pain/',
                            'last_verified': '2026-09-17'}],
               'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
               'ar': {'title': 'ألم الظهر',
                      'what': 'ألم الظهر شائع وقد يرتبط بشد عضلي؛ لا يمكن تحديد سببه من مكان الألم وحده.',
                      'causes': ['شد عضلي', 'مشكلات الأقراص', 'تهيج عصب'],
                      'self_care': 'حافظ على حركة مريحة وتجنب البقاء في السرير طويلًا.',
                      'worry': 'اطلب الطوارئ عند ضعف أو تنميل الساقين معًا، أو فقدان إحساس حول الأعضاء التناسلية، '
                               'أو تغير التحكم بالبول أو البراز.',
                      'doctor': 'راجع مختصًا إذا استمر أو عطّل النشاط.',
                      'follow_up': 'هل يمتد الألم إلى الساق؟'},
               'en': {'title': 'Back pain',
                      'what': 'Back pain is common and may follow muscle strain; its location alone does not '
                              'establish the cause.',
                      'causes': ['Muscle strain', 'Disc problems', 'Nerve irritation'],
                      'self_care': 'Stay gently active and avoid prolonged bed rest.',
                      'worry': 'Emergency care is needed for weakness or numbness in both legs, genital numbness, '
                               'or altered bladder or bowel control.',
                      'doctor': 'Seek review for persistent or disabling pain.',
                      'follow_up': 'Does pain travel down a leg?'}},
 'neck_pain': {'emoji': '🩺',
               'category': 'symptom',
               'aliases': ['ألم الرقبة',
                           'Neck pain',
                           'رقبتي توجعني',
                           'شد الرقبة',
                           'تيبس الرقبة',
                           'وجع الرقبة',
                           'stiff neck',
                           'neck stiffness',
                           'my neck hurts'],
               'sources': [{'name': 'Neck pain — NHS',
                            'title': 'Neck pain',
                            'organization': 'NHS',
                            'source_name': 'NHS',
                            'url': 'https://www.nhs.uk/symptoms/neck-pain-and-stiff-neck/',
                            'last_verified': '2026-09-17'},
                           {'name': 'Meningitis warning signs — NHS',
                            'title': 'Meningitis warning signs',
                            'organization': 'NHS',
                            'source_name': 'NHS',
                            'url': 'https://www.nhs.uk/conditions/meningitis/',
                            'last_verified': '2026-09-17'}],
               'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
               'ar': {'title': 'ألم الرقبة',
                      'what': 'قد يرتبط ألم الرقبة بوضعية النوم أو الجلوس أو شد العضلات.',
                      'causes': ['وضعية غير مريحة', 'إصابة', 'ضغط على عصب'],
                      'self_care': 'حرك الرقبة بلطف ضمن حدود الراحة وخذ فواصل من الجلوس.',
                      'worry': 'تيبس الرقبة مع حمى وصداع شديد يستدعي الطوارئ فورًا.',
                      'doctor': 'راجع مختصًا إذا استمر الألم أو ظهر وخز أو برودة بالذراع.',
                      'follow_up': 'هل بدأ بعد إصابة أو وضعية نوم؟'},
               'en': {'title': 'Neck pain',
                      'what': 'Neck pain can follow sleep position, posture, or muscle strain.',
                      'causes': ['Awkward position', 'Injury', 'A trapped nerve'],
                      'self_care': 'Move gently within comfort and take breaks from prolonged sitting.',
                      'worry': 'Neck stiffness with fever and severe headache needs immediate emergency care.',
                      'doctor': 'Seek review for persistent pain or arm tingling or coldness.',
                      'follow_up': 'Did it start after injury or an awkward sleep position?'}},
 'toothache': {'emoji': '🩺',
               'category': 'symptom',
               'aliases': ['ألم الأسنان',
                           'Toothache',
                           'ضرس يوجعني',
                           'ضرسي يوجعني',
                           'وجع الاسنان',
                           'الم الضرس',
                           'tooth pain',
                           'my tooth hurts',
                           'dental pain'],
               'sources': [{'name': 'Toothache — NHS',
                            'title': 'Toothache',
                            'organization': 'NHS',
                            'source_name': 'NHS',
                            'url': 'https://www.nhs.uk/symptoms/toothache/',
                            'last_verified': '2026-09-17'}],
               'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
               'ar': {'title': 'ألم الأسنان',
                      'what': 'ألم الأسنان يحتاج تقييم طبيب أسنان لتحديد السبب وعلاجه.',
                      'causes': ['تسوس', 'خراج أو مشكلة لثة', 'سن متشقق'],
                      'self_care': 'تجنب المضغ على السن المؤلم والأطعمة شديدة السخونة أو البرودة.',
                      'worry': 'تورم الفم أو الرقبة مع صعوبة التنفس أو البلع يستدعي الطوارئ.',
                      'doctor': 'راجع طبيب الأسنان إذا استمر الألم أكثر من يومين أو ظهر تورم أو حمى.',
                      'follow_up': 'هل يوجد تورم حول السن؟'},
               'en': {'title': 'Toothache',
                      'what': 'A dentist can identify and treat the cause of tooth pain.',
                      'causes': ['Decay', 'Abscess or gum problems', 'A cracked tooth'],
                      'self_care': 'Avoid chewing on the painful tooth and very hot or cold foods.',
                      'worry': 'Mouth or neck swelling with breathing or swallowing difficulty needs emergency '
                               'care.',
                      'doctor': 'See a dentist for pain over two days, swelling, or fever.',
                      'follow_up': 'Is there swelling around the tooth?'}},
 'earache': {'emoji': '🩺',
             'category': 'symptom',
             'aliases': ['وجع اذن', 'وجع في الاذن', 'الم في الاذن', 'ألم الأذن',
                         'Earache',
                         'اذني توجعني',
                         'وجع الاذن',
                         'الم الاذن',
                         'الم الاذنين',
                         'ear pain',
                         'my ear hurts',
                         'aching ear'],
             'sources': [{'name': 'Earache — NHS',
                          'title': 'Earache',
                          'organization': 'NHS',
                          'source_name': 'NHS',
                          'url': 'https://www.nhs.uk/symptoms/earache/',
                          'last_verified': '2026-09-17'}],
             'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
             'ar': {'title': 'ألم الأذن',
                    'what': 'ألم الأذن له أسباب متعددة، وقد يحتاج فحص الأذن لتحديدها.',
                    'causes': ['عدوى', 'تراكم الشمع', 'ألم ممتد من الأسنان أو الحلق'],
                    'self_care': 'لا تدخل أعوادًا أو أدوات داخل الأذن.',
                    'worry': 'اطلب تقييمًا عاجلًا عند تورم حول الأذن أو خروج سائل أو تغير السمع.',
                    'doctor': 'راجع مختصًا إذا لم يتحسن خلال بضعة أيام أو ترافق مع حمى.',
                    'follow_up': 'هل تغير السمع أو خرج سائل؟'},
             'en': {'title': 'Earache',
                    'what': 'Ear pain has several causes; an ear examination may be needed.',
                    'causes': ['Infection', 'Wax build-up', 'Referred dental or throat pain'],
                    'self_care': 'Do not put cotton buds or other objects inside the ear.',
                    'worry': 'Seek urgent assessment for swelling around the ear, discharge, or hearing changes.',
                    'doctor': 'Seek review if it does not improve within a few days or comes with fever.',
                    'follow_up': 'Has hearing changed or fluid appeared?'}},
 'tinnitus': {'emoji': '🩺',
              'category': 'symptom',
              'aliases': ['طنين الأذن',
                          'Tinnitus',
                          'صفير الاذن',
                          'اذني تصفر',
                          'ازيز الاذن',
                          'طنين',
                          'ringing in ears',
                          'buzzing in ears',
                          'ear ringing'],
              'sources': [{'name': 'Tinnitus — NHS',
                           'title': 'Tinnitus',
                           'organization': 'NHS',
                           'source_name': 'NHS',
                           'url': 'https://www.nhs.uk/conditions/tinnitus/',
                           'last_verified': '2026-09-17'}],
              'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
              'ar': {'title': 'طنين الأذن',
                     'what': 'الطنين سماع صوت دون مصدر خارجي، مثل الصفير أو الأزيز.',
                     'causes': ['ضعف السمع', 'مشكلات بالأذن', 'بعض الأدوية'],
                     'self_care': 'تجنب الضوضاء العالية واهتم بالنوم؛ قد يساعد صوت خلفي هادئ.',
                     'worry': 'الطنين مع فقدان سمع مفاجئ أو ضعف بالوجه أو بعد إصابة رأس يستدعي الطوارئ.',
                     'doctor': 'اطلب موعدًا عاجلًا إذا تزامن الصوت مع النبض، وراجع مختصًا عند استمراره.',
                     'follow_up': 'هل الصوت متزامن مع نبضك؟'},
              'en': {'title': 'Tinnitus',
                     'what': 'Tinnitus means hearing a sound without an external source, such as ringing or '
                             'buzzing.',
                     'causes': ['Hearing loss', 'Ear problems', 'Some medicines'],
                     'self_care': 'Avoid loud noise and support sleep; gentle background sound may help.',
                     'worry': 'Tinnitus with sudden hearing loss, facial weakness, or after head injury needs '
                              'emergency care.',
                     'doctor': 'Seek an urgent appointment for pulse-synchronous noise and review for persistent '
                               'tinnitus.',
                     'follow_up': 'Does the sound follow your pulse?'}},
 'insomnia': {'emoji': '🩺',
              'category': 'symptom',
              'aliases': ['مشاكل النوم', 'اضطراب النوم', 'sleep problems', 'poor sleep', 'الأرق',
                          'Insomnia',
                          'ما اقدر انام',
                          'صعوبة النوم',
                          'نومي متقطع',
                          'اصحى كثير بالليل',
                          'cannot sleep',
                          'trouble sleeping',
                          'waking at night'],
              'sources': [{'name': 'Insomnia — NHS',
                           'title': 'Insomnia',
                           'organization': 'NHS',
                           'source_name': 'NHS',
                           'url': 'https://www.nhs.uk/conditions/insomnia/',
                           'last_verified': '2026-09-17'}],
              'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
              'ar': {'title': 'الأرق',
                     'what': 'الأرق قد يشمل صعوبة بدء النوم أو الاستمرار فيه مع تعب نهاري.',
                     'causes': ['التوتر', 'الكافيين', 'تغير مواعيد النوم'],
                     'self_care': 'ثبّت وقت الاستيقاظ، وقلل الكافيين مساءً، واجعل غرفة النوم هادئة. لا تقد عند '
                                  'النعاس.',
                     'worry': 'تجنب استخدام المنومات دون مشورة مختص.',
                     'doctor': 'راجع مختصًا إذا استمر الأرق أو أثر في حياتك رغم تعديل العادات.',
                     'follow_up': 'هل المشكلة في بدء النوم أم الاستيقاظ المتكرر؟'},
              'en': {'title': 'Insomnia',
                     'what': 'Insomnia can involve difficulty falling or staying asleep with daytime tiredness.',
                     'causes': ['Stress', 'Caffeine', 'Changing sleep schedules'],
                     'self_care': 'Keep a regular wake time, reduce evening caffeine, and keep the bedroom quiet. '
                                  'Do not drive when sleepy.',
                     'worry': 'Avoid using sleeping medicines without professional advice.',
                     'doctor': 'Seek review if insomnia persists or affects daily life despite habit changes.',
                     'follow_up': 'Is the problem falling asleep or waking repeatedly?'},
              'context_questions': {'ar': ['وش اسوي اذا ما اقدر انام', 'كيف احسن نومي'],
                                    'en': ['what can I do if I cannot sleep', 'how can I improve my sleep']}},
 'excessive_thirst': {'emoji': '🩺',
                      'category': 'symptom',
                      'aliases': ['العطش الزائد',
                                  'Excessive thirst',
                                  'عطشان طول الوقت',
                                  'عطش مستمر',
                                  'اشرب كثير ولسى عطشان',
                                  'كثرة العطش',
                                  'always thirsty',
                                  'constant thirst',
                                  'thirsty all the time'],
                      'sources': [{'name': 'Excessive thirst — NHS',
                                   'title': 'Excessive thirst',
                                   'organization': 'NHS',
                                   'source_name': 'NHS',
                                   'url': 'https://www.nhs.uk/symptoms/thirst/',
                                   'last_verified': '2026-09-17'}],
                      'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
                      'ar': {'title': 'العطش الزائد',
                             'what': 'العطش المستمر رغم شرب السوائل يحتاج معرفة السبب، ولا يثبت السكري وحده.',
                             'causes': ['فقد السوائل', 'أطعمة مالحة', 'بعض الأدوية أو السكري'],
                             'self_care': 'اشرب بحسب حاجتك وقيودك الطبية وقلل الكافيين.',
                             'worry': 'قلة البول والدوخة قد تعني الجفاف وتحتاج تقييمًا.',
                             'doctor': 'راجع مختصًا إذا استمر عدة أيام أو صاحبه تبول متكرر.',
                             'follow_up': 'هل زاد التبول أيضًا؟'},
                      'en': {'title': 'Excessive thirst',
                             'what': 'Persistent thirst despite drinking needs assessment; it does not by itself '
                                     'establish diabetes.',
                             'causes': ['Fluid loss', 'Salty food', 'Some medicines or diabetes'],
                             'self_care': 'Drink according to your needs and medical restrictions and reduce '
                                          'caffeine.',
                             'worry': 'Reduced urination and dizziness may indicate dehydration and need '
                                      'assessment.',
                             'doctor': 'Seek review if it lasts several days or comes with frequent urination.',
                             'follow_up': 'Are you also urinating more often?'}},
 'urinary_symptoms': {'emoji': '🩺',
                      'category': 'symptom',
                      'aliases': ['حرقة البول',
                                  'Painful urination',
                                  'حرقان البول',
                                  'ألم عند التبول',
                                  'كثرة التبول',
                                  'اتبول كثير',
                                  'burning urination',
                                  'frequent urination',
                                  'pain when peeing'],
                      'sources': [{'name': 'Painful urination — NHS',
                                   'title': 'Painful urination',
                                   'organization': 'NHS',
                                   'source_name': 'NHS',
                                   'url': 'https://www.nhs.uk/conditions/urinary-tract-infections-utis/',
                                   'last_verified': '2026-09-17'}],
                      'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
                      'ar': {'title': 'حرقة البول',
                             'what': 'الحرقة أو زيادة التبول قد ترافق التهاب المسالك، لكن الأعراض وحدها لا تؤكد '
                                     'السبب.',
                             'causes': ['التهاب المسالك البولية أحد الاحتمالات'],
                             'self_care': 'اهتم بالسوائل وفق قيودك الطبية ولا تبدأ مضادًا حيويًا من نفسك.',
                             'worry': 'اطلب تقييمًا عاجلًا عند الحمى أو ألم الخاصرة أو الدم، وكذلك أثناء الحمل. '
                                      'التشوش يستدعي الطوارئ.',
                             'doctor': 'راجع مختصًا عند استمرار الأعراض أو تكررها؛ الأطفال والرجال يحتاجون '
                                       'تقييمًا مبكرًا.',
                             'follow_up': 'هل يوجد حمى أو ألم في الخاصرة؟'},
                      'en': {'title': 'Painful urination',
                             'what': 'Burning or frequent urination can accompany a urinary infection, but '
                                     'symptoms alone do not confirm it.',
                             'causes': ['A urinary tract infection is one possibility'],
                             'self_care': 'Maintain fluids within medical restrictions; do not self-start '
                                          'antibiotics.',
                             'worry': 'Seek urgent assessment for fever, flank pain, blood, or pregnancy. '
                                      'Confusion needs emergency care.',
                             'doctor': 'Seek review for persistent or recurring symptoms; children and men need '
                                       'prompt assessment.',
                             'follow_up': 'Is there fever or flank pain?'}},
 'hives': {'emoji': '🩺',
           'category': 'symptom',
           'aliases': ['الشرى',
                       'Hives',
                       'ارتكاريا',
                       'الارتيكاريا',
                       'طفح مرتفع وحكة',
                       'شرى',
                       'urticaria',
                       'raised itchy rash',
                       'nettle rash'],
           'sources': [{'name': 'Hives — NHS',
                        'title': 'Hives',
                        'organization': 'NHS',
                        'source_name': 'NHS',
                        'url': 'https://www.nhs.uk/conditions/hives/',
                        'last_verified': '2026-09-17'}],
           'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
           'ar': {'title': 'الشرى',
                  'what': 'الشرى طفح مرتفع وحاك؛ لا يمكن تأكيد نوع الطفح من الوصف وحده.',
                  'causes': ['بعض الأطعمة أو الأدوية', 'لسعات', 'عدوى أو محفزات أخرى'],
                  'self_care': 'تجنب المحفز المعروف واسأل الصيدلي عن العلاج المناسب.',
                  'worry': 'تورم اللسان أو الحلق أو صعوبة التنفس يستدعي الطوارئ فورًا.',
                  'doctor': 'اطلب مراجعة عاجلة إذا انتشر الطفح أو ترافق مع حمى أو لم يتحسن خلال يومين.',
                  'follow_up': 'هل بدأ بعد طعام أو دواء جديد؟'},
           'en': {'title': 'Hives',
                  'what': 'Hives are raised itchy patches; a description alone cannot confirm the rash type.',
                  'causes': ['Some foods or medicines', 'Stings', 'Infection or other triggers'],
                  'self_care': 'Avoid known triggers and ask a pharmacist about suitable treatment.',
                  'worry': 'Tongue or throat swelling or difficulty breathing needs immediate emergency care.',
                  'doctor': 'Seek urgent review for spreading rash, fever, or no improvement within two days.',
                  'follow_up': 'Did it begin after a new food or medicine?'}},
 'mouth_ulcers': {'emoji': '🩺',
                  'category': 'symptom',
                  'aliases': ['تقرحات الفم',
                              'Mouth ulcers',
                              'قرحة الفم',
                              'حبة داخل الفم',
                              'تقرحات اللسان',
                              'قرح الفم',
                              'mouth sore',
                              'canker sore',
                              'tongue ulcer'],
                  'sources': [{'name': 'Mouth ulcers — NHS',
                               'title': 'Mouth ulcers',
                               'organization': 'NHS',
                               'source_name': 'NHS',
                               'url': 'https://www.nhs.uk/conditions/mouth-ulcers/',
                               'last_verified': '2026-09-17'}],
                  'causes_label': {'ar': 'أسباب محتملة', 'en': 'Possible causes'},
                  'ar': {'title': 'تقرحات الفم',
                         'what': 'قرح الفم شائعة وغالبًا تتحسن، لكن القرحة المستمرة تحتاج فحصًا.',
                         'causes': ['عض الخد أو احتكاك الأسنان', 'التوتر', 'أسباب أخرى عند التكرار'],
                         'self_care': 'استخدم فرشاة ناعمة وتجنب الأطعمة التي تهيج القرحة.',
                         'worry': 'اطلب مراجعة إذا زاد الاحمرار أو الألم أو حدث نزف.',
                         'doctor': 'راجع طبيبًا أو طبيب أسنان إذا استمرت أكثر من ثلاثة أسابيع.',
                         'follow_up': 'منذ متى ظهرت القرحة؟'},
                  'en': {'title': 'Mouth ulcers',
                         'what': 'Mouth ulcers are common and often improve, but a persistent ulcer needs '
                                 'examination.',
                         'causes': ['Cheek biting or dental irritation', 'Stress', 'Other causes when recurrent'],
                         'self_care': 'Use a soft toothbrush and avoid foods that irritate the ulcer.',
                         'worry': 'Seek review for increasing redness, pain, or bleeding.',
                         'doctor': 'See a doctor or dentist if it lasts more than three weeks.',
                         'follow_up': 'How long has the ulcer been present?'}},
 'vitamin_d': {'emoji': '🧪',
               'category': 'test',
               'aliases': ['تحليل فيتامين د',
                           'Vitamin D test',
                           'فيتامين د',
                           'نقص فيتامين د',
                           '25 OH D',
                           'vitamin d',
                           '25 hydroxyvitamin d',
                           '25(OH)D'],
               'sources': [{'name': 'Vitamin D test — MedlinePlus',
                            'title': 'Vitamin D test',
                            'organization': 'U.S. National Library of Medicine',
                            'source_name': 'MedlinePlus',
                            'url': 'https://medlineplus.gov/lab-tests/vitamin-d-test/',
                            'last_verified': '2026-09-17'}],
               'causes_label': {'ar': 'عوامل قد تؤثر في النتيجة', 'en': 'Factors that may affect the result'},
               'ar': {'title': 'تحليل فيتامين د',
                      'what': 'يقيس غالبًا 25(OH)D لتقييم مستوى فيتامين د، المهم لصحة العظام.',
                      'causes': ['التغذية والتعرض للشمس', 'مشكلات الامتصاص', 'المكملات'],
                      'self_care': 'أرسل القيمة والوحدة والمدى المرجعي لتوضيح النتيجة، واتبع تعليمات المختبر قبل '
                                   'الفحص.',
                      'worry': 'لا تغيّر دواءً أو تبدأ جرعات علاجية بناءً على رقم منفرد.',
                      'doctor': 'ناقش النتيجة غير الطبيعية مع المختص مع ذكر الأعراض والأدوية.',
                      'follow_up': 'ما القيمة والوحدة والمدى المرجعي في التقرير؟'},
               'en': {'title': 'Vitamin D test',
                      'what': 'Usually measures 25(OH)D to assess vitamin D status, important for bone health.',
                      'causes': ['Diet and sunlight', 'Absorption problems', 'Supplements'],
                      'self_care': 'Share the value, unit, and reference range for explanation; follow the '
                                   'laboratory preparation instructions.',
                      'worry': 'Do not change medicines or start treatment doses based on a single value.',
                      'doctor': 'Discuss abnormal results with a clinician alongside symptoms and medicines.',
                      'follow_up': 'What value, unit, and reference range does the report show?'}},
 'vitamin_b12': {'emoji': '🧪',
                 'category': 'test',
                 'aliases': ['تحليل فيتامين ب12',
                             'Vitamin B12 test',
                             'فيتامين ب12',
                             'بي 12',
                             'نقص ب12',
                             'b12',
                             'vitamin b12',
                             'cobalamin'],
                 'sources': [{'name': 'Vitamin B12 test — MedlinePlus',
                              'title': 'Vitamin B12 test',
                              'organization': 'U.S. National Library of Medicine',
                              'source_name': 'MedlinePlus',
                              'url': 'https://medlineplus.gov/lab-tests/vitamin-b-test/',
                              'last_verified': '2026-09-17'}],
                 'causes_label': {'ar': 'عوامل قد تؤثر في النتيجة', 'en': 'Factors that may affect the result'},
                 'ar': {'title': 'تحليل فيتامين ب12',
                        'what': 'يساعد في تقييم فيتامين ب12 المرتبط بوظائف الأعصاب وتكوين خلايا الدم.',
                        'causes': ['قلة المدخول', 'ضعف الامتصاص', 'بعض الأدوية'],
                        'self_care': 'أرسل القيمة والوحدة والمدى المرجعي لتوضيح النتيجة، واتبع تعليمات المختبر '
                                     'قبل الفحص.',
                        'worry': 'لا تغيّر دواءً أو تبدأ جرعات علاجية بناءً على رقم منفرد.',
                        'doctor': 'ناقش النتيجة غير الطبيعية مع المختص مع ذكر الأعراض والأدوية.',
                        'follow_up': 'ما القيمة والوحدة والمدى المرجعي في التقرير؟'},
                 'en': {'title': 'Vitamin B12 test',
                        'what': 'Helps assess B12, which supports nerve function and blood cell formation.',
                        'causes': ['Low intake', 'Poor absorption', 'Some medicines'],
                        'self_care': 'Share the value, unit, and reference range for explanation; follow the '
                                     'laboratory preparation instructions.',
                        'worry': 'Do not change medicines or start treatment doses based on a single value.',
                        'doctor': 'Discuss abnormal results with a clinician alongside symptoms and medicines.',
                        'follow_up': 'What value, unit, and reference range does the report show?'}},
 'ferritin': {'emoji': '🧪',
              'category': 'test',
              'aliases': ['مخزون الحديد',
                          'Ferritin',
                          'فيريتين',
                          'تحليل مخزون الحديد',
                          'الفيريتين',
                          'serum ferritin',
                          'iron stores',
                          'ferritin test'],
              'sources': [{'name': 'Ferritin — MedlinePlus',
                           'title': 'Ferritin',
                           'organization': 'U.S. National Library of Medicine',
                           'source_name': 'MedlinePlus',
                           'url': 'https://medlineplus.gov/lab-tests/ferritin-blood-test/',
                           'last_verified': '2026-09-17'}],
              'causes_label': {'ar': 'عوامل قد تؤثر في النتيجة', 'en': 'Factors that may affect the result'},
              'ar': {'title': 'مخزون الحديد',
                     'what': 'الفيريتين بروتين يخزن الحديد. انخفاضه قد يشير لقلة المخزون، وارتفاعه لا يعني دائمًا '
                             'زيادة الحديد.',
                     'causes': ['نقص الحديد', 'الالتهاب', 'أمراض الكبد'],
                     'self_care': 'أرسل القيمة والوحدة والمدى المرجعي لتوضيح النتيجة، واتبع تعليمات المختبر قبل '
                                  'الفحص.',
                     'worry': 'لا تغيّر دواءً أو تبدأ جرعات علاجية بناءً على رقم منفرد.',
                     'doctor': 'ناقش النتيجة غير الطبيعية مع المختص مع ذكر الأعراض والأدوية.',
                     'follow_up': 'ما القيمة والوحدة والمدى المرجعي في التقرير؟'},
              'en': {'title': 'Ferritin',
                     'what': 'Ferritin stores iron. Low levels may suggest depleted stores; high levels do not '
                             'always mean iron overload.',
                     'causes': ['Iron deficiency', 'Inflammation', 'Liver disease'],
                     'self_care': 'Share the value, unit, and reference range for explanation; follow the '
                                  'laboratory preparation instructions.',
                     'worry': 'Do not change medicines or start treatment doses based on a single value.',
                     'doctor': 'Discuss abnormal results with a clinician alongside symptoms and medicines.',
                     'follow_up': 'What value, unit, and reference range does the report show?'}},
 'hba1c': {'emoji': '🧪',
           'category': 'test',
           'aliases': ['السكر التراكمي',
                       'HbA1c',
                       'تحليل السكر التراكمي',
                       'التراكمي',
                       'الهيموجلوبين السكري',
                       'a1c',
                       'glycated hemoglobin',
                       'hemoglobin a1c'],
           'sources': [{'name': 'HbA1c — MedlinePlus',
                        'title': 'HbA1c',
                        'organization': 'U.S. National Library of Medicine',
                        'source_name': 'MedlinePlus',
                        'url': 'https://medlineplus.gov/lab-tests/hemoglobin-a1c-hba1c-test/',
                        'last_verified': '2026-09-17'}],
           'causes_label': {'ar': 'عوامل قد تؤثر في النتيجة', 'en': 'Factors that may affect the result'},
           'ar': {'title': 'السكر التراكمي',
                  'what': 'يعكس متوسط سكر الدم خلال شهرين إلى ثلاثة أشهر، وليس قراءة السكر اللحظية.',
                  'causes': ['مستويات السكر', 'حالات تؤثر في عمر خلايا الدم'],
                  'self_care': 'أرسل القيمة والوحدة والمدى المرجعي لتوضيح النتيجة، واتبع تعليمات المختبر قبل '
                               'الفحص.',
                  'worry': 'لا تغيّر دواءً أو تبدأ جرعات علاجية بناءً على رقم منفرد.',
                  'doctor': 'ناقش النتيجة غير الطبيعية مع المختص مع ذكر الأعراض والأدوية.',
                  'follow_up': 'ما القيمة والوحدة والمدى المرجعي في التقرير؟'},
           'en': {'title': 'HbA1c',
                  'what': 'Reflects average blood glucose over two to three months, rather than a current glucose '
                          'reading.',
                  'causes': ['Glucose levels', 'Conditions affecting blood cell lifespan'],
                  'self_care': 'Share the value, unit, and reference range for explanation; follow the laboratory '
                               'preparation instructions.',
                  'worry': 'Do not change medicines or start treatment doses based on a single value.',
                  'doctor': 'Discuss abnormal results with a clinician alongside symptoms and medicines.',
                  'follow_up': 'What value, unit, and reference range does the report show?'}},
 'tsh': {'emoji': '🧪',
         'category': 'test',
         'aliases': ['تحليل الغدة TSH',
                     'TSH test',
                     'تحليل tsh',
                     'الهرمون المنبه للغدة',
                     'هرمون الغدة',
                     'tsh',
                     'thyroid stimulating hormone',
                     'thyrotropin'],
         'sources': [{'name': 'TSH test — MedlinePlus',
                      'title': 'TSH test',
                      'organization': 'U.S. National Library of Medicine',
                      'source_name': 'MedlinePlus',
                      'url': 'https://medlineplus.gov/lab-tests/tsh-thyroid-stimulating-hormone-test/',
                      'last_verified': '2026-09-17'}],
         'causes_label': {'ar': 'عوامل قد تؤثر في النتيجة', 'en': 'Factors that may affect the result'},
         'ar': {'title': 'تحليل الغدة TSH',
                'what': 'يقيس الهرمون المنبه للغدة الدرقية. يساعد في تقييم وظيفتها ولا يحدد سبب الاضطراب وحده.',
                'causes': ['وظيفة الغدة', 'الأدوية والمكملات', 'الحمل'],
                'self_care': 'أرسل القيمة والوحدة والمدى المرجعي لتوضيح النتيجة، واتبع تعليمات المختبر قبل الفحص.',
                'worry': 'لا تغيّر دواءً أو تبدأ جرعات علاجية بناءً على رقم منفرد.',
                'doctor': 'ناقش النتيجة غير الطبيعية مع المختص مع ذكر الأعراض والأدوية.',
                'follow_up': 'ما القيمة والوحدة والمدى المرجعي في التقرير؟'},
         'en': {'title': 'TSH test',
                'what': 'Measures thyroid-stimulating hormone. It helps assess thyroid function but cannot '
                        'establish the cause of a disorder alone.',
                'causes': ['Thyroid function', 'Medicines and supplements', 'Pregnancy'],
                'self_care': 'Share the value, unit, and reference range for explanation; follow the laboratory '
                             'preparation instructions.',
                'worry': 'Do not change medicines or start treatment doses based on a single value.',
                'doctor': 'Discuss abnormal results with a clinician alongside symptoms and medicines.',
                'follow_up': 'What value, unit, and reference range does the report show?'}},
 'creatinine': {'emoji': '🧪',
                'category': 'test',
                'aliases': ['تحليل الكرياتينين',
                            'Creatinine test',
                            'كرياتينين',
                            'الكرياتينين',
                            'تحليل وظائف الكلى',
                            'creatinine',
                            'serum creatinine',
                            'kidney function test'],
                'sources': [{'name': 'Creatinine test — MedlinePlus',
                             'title': 'Creatinine test',
                             'organization': 'U.S. National Library of Medicine',
                             'source_name': 'MedlinePlus',
                             'url': 'https://medlineplus.gov/lab-tests/creatinine-test/',
                             'last_verified': '2026-09-17'}],
                'causes_label': {'ar': 'عوامل قد تؤثر في النتيجة', 'en': 'Factors that may affect the result'},
                'ar': {'title': 'تحليل الكرياتينين',
                       'what': 'الكرياتينين ناتج من العضلات تتخلص منه الكلى؛ يفسر عادة مع eGFR ونتائج أخرى.',
                       'causes': ['وظيفة الكلى', 'الكتلة العضلية', 'النشاط والغذاء'],
                       'self_care': 'أرسل القيمة والوحدة والمدى المرجعي لتوضيح النتيجة، واتبع تعليمات المختبر قبل '
                                    'الفحص.',
                       'worry': 'لا تغيّر دواءً أو تبدأ جرعات علاجية بناءً على رقم منفرد.',
                       'doctor': 'ناقش النتيجة غير الطبيعية مع المختص مع ذكر الأعراض والأدوية.',
                       'follow_up': 'ما القيمة والوحدة والمدى المرجعي في التقرير؟'},
                'en': {'title': 'Creatinine test',
                       'what': 'Creatinine is muscle waste cleared by the kidneys; it is usually interpreted with '
                               'eGFR and other results.',
                       'causes': ['Kidney function', 'Muscle mass', 'Activity and diet'],
                       'self_care': 'Share the value, unit, and reference range for explanation; follow the '
                                    'laboratory preparation instructions.',
                       'worry': 'Do not change medicines or start treatment doses based on a single value.',
                       'doctor': 'Discuss abnormal results with a clinician alongside symptoms and medicines.',
                       'follow_up': 'What value, unit, and reference range does the report show?'}}}
