"""V73 bilingual health-search expansion for common everyday symptoms."""
REVIEW_DATE = "2026-09-21"

def src(title, url):
    return {"name":f"{title} — NHS","title":title,"organization":"National Health Service","source_name":"NHS","url":url,"last_verified":REVIEW_DATE}

def topic(emoji, aliases, source, ar_title, ar_what, ar_causes, ar_worry, ar_doctor, en_title, en_what, en_causes, en_worry, en_doctor):
    return {
        "emoji":emoji,"category":"symptom","aliases":aliases,"sources":[source],"last_reviewed":REVIEW_DATE,
        "population_scope":"general educational information; age, pregnancy, medicines, and medical history can change interpretation",
        "causes_label":{"ar":"أسباب أو سياقات محتملة","en":"Possible causes or contexts"},
        "ar":{"title":ar_title,"what":ar_what,"causes":ar_causes,"worry":ar_worry,"doctor":ar_doctor},
        "en":{"title":en_title,"what":en_what,"causes":en_causes,"worry":en_worry,"doctor":en_doctor},
    }

EXTRA_SEARCH_KB_V5 = {
    "earwax_build_up": topic("👂",["شمع الاذن","شمع الأذن","اذني مسدودة","أذني مسدودة","نقص السمع بسبب الشمع","earwax","blocked ear","earwax build up"],src("Earwax build-up","https://www.nhs.uk/conditions/earwax-build-up/"),"تراكم شمع الأذن","قد يسبب الشمع المتراكم انسدادًا أو نقصًا في السمع أو طنينًا وأحيانًا دوخة.",["زيادة أو انحشار الشمع","إدخال أعواد أو أدوات داخل الأذن قد يدفع الشمع للداخل"],"فقد السمع المفاجئ، ألم شديد، نزف أو إفرازات، أو دوخة شديدة يحتاج تقييمًا سريعًا.","لا تدخل أعوادًا داخل الأذن، واستشر الصيدلي أو الطبيب إذا استمر الانسداد أو ضعف السمع.","Earwax build-up","Built-up earwax can cause blocked ears, reduced hearing, tinnitus and sometimes dizziness.",["Excess/impacted earwax","Putting cotton buds or objects in the ear can push wax deeper"],"Sudden hearing loss, severe pain, bleeding/discharge, or severe vertigo needs prompt assessment.","Do not insert objects into the ear; seek pharmacist/medical advice if blockage or hearing loss persists."),
    "floaters_flashes": topic("👁️",["ذبابات العين","نقاط سوداء تتحرك","ومضات بالعين","اشوف وميض","أشوف وميض","eye floaters","flashes in vision"],src("Floaters and flashes in the eyes","https://www.nhs.uk/symptoms/floaters-and-flashes-in-the-eyes/"),"عوامات وومضات العين","قد تظهر نقاط أو خيوط عائمة أو ومضات في الرؤية. بعضها شائع، لكن البداية المفاجئة تحتاج تقييمًا للعين.",["تغيرات في الجسم الزجاجي","تمزق أو انفصال شبكي في بعض الحالات"],"ظهور مفاجئ أو زيادة كبيرة، ستارة/ظل، تشوش رؤية أو ألم بالعين يحتاج تقييمًا عاجلًا.","إذا كانت جديدة أو زادت فجأة فاطلب تقييمًا عاجلًا للعين.","Eye floaters and flashes","Moving spots/threads or flashes can occur in vision. Some are common, but sudden new symptoms need eye assessment.",["Vitreous changes","Retinal tear/detachment in some cases"],"Sudden onset/increase, curtain or shadow, blurred vision, or eye pain needs urgent assessment.","Seek urgent eye assessment if new or suddenly worse."),
    "hiccups": topic("🫢",["حازوقة","فواق","الحازوقة ما توقف","hiccups","persistent hiccups"],src("Hiccups","https://www.nhs.uk/symptoms/hiccups/"),"الحازوقة","الحازوقة شائعة وغالبًا تختفي خلال دقائق دون علاج.",["الأكل أو الشرب","محفزات مؤقتة","أحيانًا لا يوجد سبب واضح"],"استمرارها أكثر من 48 ساعة أو تكرارها بشكل يؤثر على حياتك يحتاج تقييمًا.","راجع الطبيب إذا استمرت أكثر من 48 ساعة أو كانت تتكرر كثيرًا.","Hiccups","Hiccups are common and usually stop within minutes without treatment.",["Eating or drinking","Temporary triggers","Sometimes no clear cause"],"Hiccups lasting more than 48 hours or repeatedly affecting daily life need assessment.","See a clinician if they last over 48 hours or keep recurring."),
    "bad_breath": topic("🦷",["ريحة الفم","رائحة الفم","نفس ريحته","bad breath","halitosis"],src("Bad breath","https://www.nhs.uk/symptoms/bad-breath/"),"رائحة الفم","رائحة الفم شائعة وغالبًا ترتبط بصحة الفم والأسنان أو جفاف الفم.",["مشكلات الأسنان أو اللثة","جفاف الفم","التدخين أو أطعمة","التهاب اللوز أو الارتجاع أحيانًا"],"تورم الوجه أو صعوبة البلع/التنفس مع ألم أو التهاب يحتاج تقييمًا سريعًا.","حافظ على تنظيف الأسنان واللسان والخيط، وراجع طبيب الأسنان إذا استمرت لأسابيع أو معها ألم/نزف لثة.","Bad breath","Bad breath is common and often relates to dental/oral health or dry mouth.",["Dental or gum problems","Dry mouth","Smoking or foods","Sometimes tonsillitis or reflux"],"Facial swelling or swallowing/breathing difficulty with dental symptoms needs prompt assessment.","Maintain oral hygiene and see a dentist if it persists for weeks or comes with gum pain/bleeding."),
    "oral_thrush": topic("👄",["فطريات الفم","بقع بيضاء بالفم","لسان ابيض ما يروح","لسان أبيض ما يروح","oral thrush","white patches in mouth"],src("Oral thrush (mouth thrush)","https://www.nhs.uk/conditions/oral-thrush-mouth-thrush/"),"فطريات الفم","قد تسبب بقعًا بيضاء مع احمرار أو ألم داخل الفم وتغيرًا في الطعم.",["زيادة نمو Candida","المضادات الحيوية","بخاخات الربو","أطقم الأسنان أو عوامل أخرى"],"صعوبة أو ألم عند البلع أو ضعف المناعة يحتاج تقييمًا طبيًا.","استشر الصيدلي أو الطبيب إذا لم تتحسن خلال أسبوع أو لم تكن متأكدًا من السبب.","Oral thrush","May cause white patches with redness/soreness inside the mouth and taste changes.",["Candida overgrowth","Antibiotics","Asthma inhalers","Dentures or other factors"],"Difficulty or pain swallowing or immunocompromise needs medical review.","Ask a pharmacist or clinician if not improving within a week or if the cause is uncertain."),
    "urinary_incontinence": topic("🚻",["سلس بول","تسرب البول","ينزل بول لما اكح","بول بدون قصد","urinary incontinence","urine leakage"],src("Urinary incontinence","https://www.nhs.uk/conditions/urinary-incontinence/"),"تسرب البول دون قصد","السلس مشكلة شائعة وله عدة أنماط؛ قد يحدث مع الكحة والضحك أو مع إلحاح مفاجئ للتبول.",["ضعف قاع الحوض","فرط نشاط المثانة","احتباس أو أسباب أخرى"],"فقد مفاجئ للتحكم مع ضعف بالساقين أو خدر بمنطقة العجان يحتاج تقييمًا عاجلًا.","سجل أوقات التسرب والمحرضات وعدد مرات التبول وراجع مختصًا لتحديد النوع والعلاج.","Urinary incontinence","Incontinence is common and has several patterns; leakage may occur with coughing/laughing or after a sudden urge.",["Pelvic-floor weakness","Overactive bladder","Retention or other causes"],"Sudden loss of bladder control with leg weakness or saddle numbness needs urgent assessment.","Keep a bladder diary and seek clinical review to identify the type and treatment options."),
    "perimenopause": topic("🌡️",["هبات ساخنة","هبات حرارة","تعرق ليلي مع الدورة","اعراض سن اليأس","أعراض سن اليأس","perimenopause","hot flushes menopause"],src("Menopause and perimenopause symptoms","https://www.nhs.uk/conditions/menopause-and-perimenopause/symptoms/"),"أعراض ما قبل/حول انقطاع الدورة","قد تشمل تغير الدورة، هبات ساخنة، تعرقًا ليليًا، واضطرابات النوم أو المزاج، مع وجود أسباب أخرى ممكنة.",["تغير الهرمونات في مرحلة الانتقال نحو انقطاع الدورة"],"نزيف شديد جدًا، نزيف بعد انقطاع الدورة، ألم شديد أو إغماء يحتاج تقييمًا طبيًا.","تتبعي الدورة والهبات والنوم وناقشي الأعراض مع مختص إذا أثرت على الحياة أو كان النزف غير معتاد.","Perimenopause symptoms","Can include cycle changes, hot flushes, night sweats, sleep or mood changes, while other causes are also possible.",["Hormone changes during the transition toward menopause"],"Very heavy bleeding, bleeding after menopause, severe pain, or fainting needs medical assessment.","Track cycles, flushes and sleep; seek review if symptoms affect daily life or bleeding is unusual."),
    "hair_loss": topic("💇",["تساقط الشعر","شعري يطيح","فراغات بالشعر","hair loss","hair shedding"],src("Hair loss","https://www.nhs.uk/conditions/hair-loss/"),"تساقط الشعر","تساقط الشعر له أسباب كثيرة، وبعضه مؤقت وبعضه وراثي أو مرتبط بحالة صحية أو علاج.",["عوامل وراثية","مرض أو ضغط جسدي","نقص غذائي أو تغير هرموني","أدوية أو علاجات"],"تساقط مفاجئ جدًا، بقع صلع ملتهبة، ألم/ندبات بفروة الرأس أو أعراض عامة مستمرة تحتاج تقييمًا.","راجع طبيبًا إذا كان التساقط مفاجئًا أو مقلقًا أو ترافق مع أعراض أخرى.","Hair loss","Hair loss has many causes; some are temporary, while others are inherited or related to health conditions or treatments.",["Inherited patterns","Illness or physical stress","Nutritional/hormonal factors","Medicines or treatments"],"Very sudden loss, inflamed bald patches, scalp pain/scarring, or persistent systemic symptoms needs assessment.","See a clinician if hair loss is sudden, concerning, or accompanied by other symptoms."),
    "leg_cramps": topic("🦵",["تشنج الساق","شد الرجل","شد بالساق بالليل","leg cramps","calf cramp"],src("Leg cramps","https://www.nhs.uk/conditions/leg-cramps/"),"تشنجات الساق","ألم مفاجئ بسبب تقلص العضلة، وغالبًا يستمر ثواني أو دقائق وقد يحدث ليلًا.",["إجهاد العضلات","بعض الأدوية أو الحالات","أحيانًا دون سبب واضح"],"تورم وألم بساق واحدة مع ضيق تنفس أو ألم صدر يحتاج رعاية عاجلة.","التمدد اللطيف قد يساعد؛ راجع الطبيب إذا كانت التشنجات متكررة جدًا أو تعطل النوم.","Leg cramps","Sudden pain from a tightened muscle, often lasting seconds or minutes and sometimes occurring at night.",["Muscle strain","Some medicines or conditions","Sometimes no clear cause"],"One-sided painful swelling with breathlessness or chest pain needs urgent care.","Gentle stretching may help; seek review if cramps are frequent or disrupt sleep."),
    "varicose_veins": topic("🦵",["دوالي","دوالي الساق","عروق بارزة","عروق متعرجة","varicose veins","bulging leg veins"],src("Varicose veins","https://www.nhs.uk/conditions/varicose-veins/"),"دوالي الساقين","أوردة متوسعة وملتوية تحت الجلد، وغالبًا تظهر بالساق وقد تسبب وجعًا أو ثقلًا أو حكة أو تورمًا.",["ضعف صمامات الأوردة وتجمع الدم","الحمل والعمر والوقوف الطويل وعوامل أخرى"],"نزف من الدوالي أو قرحة لا تلتئم أو تورم مؤلم مفاجئ بساق واحدة يحتاج تقييمًا سريعًا.","الحركة ورفع الساق قد يساعدان، وراجع مختصًا إذا كانت تسبب ألمًا أو تورمًا أو تزداد.","Varicose veins","Enlarged twisted veins under the skin, usually in the legs, that can cause aching/heaviness, itching or swelling.",["Weak vein valves and blood pooling","Pregnancy, age, prolonged standing and other factors"],"Bleeding veins, a non-healing ulcer, or sudden painful one-sided swelling needs prompt assessment.","Activity and leg elevation may help; seek review if they cause pain/swelling or worsen."),
    "raynauds": topic("🧤",["رينو","اصابعي تصير بيضاء بالبرد","أصابعي تصير بيضاء بالبرد","اصابعي تزرق","أصابعي تزرق","raynauds","fingers turn white in cold"],src("Raynaud's","https://www.nhs.uk/conditions/raynauds/"),"نمط رينو","قد تتحول أصابع اليدين أو القدمين إلى لون شاحب أو أزرق مع البرد/التوتر وتصبح باردة أو مخدرة.",["تشنج مؤقت بالأوعية الصغيرة","قد يكون أوليًا أو مرتبطًا بحالات أخرى"],"قرح أو اسوداد بالأصابع أو ألم شديد لا يزول يحتاج تقييمًا عاجلًا.","حافظ على الدفء وراجع مختصًا إذا بدأت الأعراض حديثًا أو كانت شديدة أو بجهة واحدة.","Raynaud's pattern","Fingers or toes may turn pale/blue with cold or stress and feel cold or numb.",["Temporary small-vessel spasm","Can be primary or linked to another condition"],"Ulcers, blackening, or severe persistent pain needs urgent assessment.","Keep warm and seek review if symptoms are new, severe, or one-sided."),
}
