"""Search topics added in V251: allergy, sciatica, panic attack, low blood pressure, blurred vision,
depression.  Sources were fetched and matched to each topic on 2026-10-07 (NHS, MedlinePlus, Mayo Clinic,
Cleveland Clinic); causes / red flags / self-care follow those pages, with no diagnoses and no doses.

CLINICAL REVIEW: a licensed clinician must sign off before broad promotion (MEDICAL_REVIEW_NEEDED.md).
"""

_VERIFIED = "2026-10-07"


def _src(*rows):
    return [{"name": n, "title": n, "organization": o, "source_name": o, "url": u, "last_verified": _VERIFIED} for n, o, u in rows]


_CAUSES = {"ar": "أسباب محتملة", "en": "Possible causes"}

EXTRA_SEARCH_KB_V251 = {
    "allergy": {
        "emoji": "🤧", "category": "symptom",
        "aliases": ["حساسية", "الحساسية", "عندي حساسية", "حساسية موسمية", "حساسية الغبار", "حساسية الانف", "allergy", "allergies", "allergic reaction", "i have allergies"],
        "sources": _src(("Allergies — NHS", "NHS", "https://www.nhs.uk/conditions/allergies/"),
                        ("Allergy — MedlinePlus", "MedlinePlus", "https://medlineplus.gov/allergy.html")),
        "causes_label": _CAUSES,
        "ar": {"title": "الحساسية",
               "what": "الحساسية استجابة مبالغ فيها من الجهاز المناعي لمادة غالبًا لا تضر غيرك، وقد تظهر كعطاس وحكة وسيلان أنف ودموع أو طفح جلدي، وقد تكون شديدة أحيانًا.",
               "causes": ["حبوب اللقاح (حمى القش)", "عث الغبار", "أطعمة مثل الفول السوداني والحليب والبيض", "وبر الحيوانات", "لدغات الحشرات", "بعض الأدوية"],
               "self_care": "تجنب المحفز المعروف قدر الإمكان، واسأل الصيدلي أو الطبيب عن مضادات الهيستامين أو بخاخات الأنف المناسبة لك، وإن وُصف لك حقن أدرينالين فاحملها دائمًا.",
               "worry": "اتصل بالإسعاف 997 فورًا عند تورم الحلق أو اللسان أو الوجه، أو صعوبة شديدة في التنفس، أو دوخة شديدة أو فقدان وعي بعد التعرض لمحفز؛ قد تكون صدمة تحسسية.",
               "doctor": "راجع طبيبًا عند الاشتباه بإصابتك أو إصابة طفلك بحساسية لترتيب الفحوص المناسبة، أو إذا كانت الأعراض متكررة أو تؤثر على نومك أو عملك.",
               "follow_up": "ما الذي تعرضت له قبل ظهور الأعراض (طعام، غبار، دواء، حيوان)؟ وهل سبق أن حدث لك تورم في الوجه أو صعوبة في التنفس؟"},
        "en": {"title": "Allergy",
               "what": "An allergy is an over-reaction of the immune system to something that is usually harmless. It can cause sneezing, itching, a runny nose, watery eyes or a rash, and sometimes a severe reaction.",
               "causes": ["Pollen (hay fever)", "House dust mites", "Foods such as peanuts, milk and eggs", "Pet dander", "Insect stings", "Some medicines"],
               "self_care": "Avoid the known trigger where you can, ask a pharmacist or doctor which antihistamine or nasal spray suits you, and always carry a prescribed adrenaline auto-injector.",
               "worry": "Call 997 straight away for swelling of the throat, tongue or face, severe difficulty breathing, severe dizziness or fainting after exposure to a trigger; this can be anaphylaxis.",
               "doctor": "See a doctor if you or your child may have an allergy so it can be tested for, or if symptoms keep coming back or affect sleep or work.",
               "follow_up": "What were you exposed to before the symptoms (food, dust, medicine, animal)? Have you ever had facial swelling or trouble breathing?"},
    },
    "sciatica": {
        "emoji": "🦵", "category": "symptom",
        "aliases": ["عرق النسا", "عرق النساء", "الم يمتد من الظهر للرجل", "وجع ينزل من الظهر للرجل", "الم الظهر ينزل الى الرجل", "sciatica", "sciatic nerve pain", "pain down the leg from the back", "back pain radiating to leg"],
        "sources": _src(("Sciatica — NHS", "NHS", "https://www.nhs.uk/conditions/sciatica/"),
                        ("Sciatica — MedlinePlus", "MedlinePlus", "https://medlineplus.gov/sciatica.html")),
        "causes_label": _CAUSES,
        "ar": {"title": "عرق النسا",
               "what": "عرق النسا ألم ينتشر على امتداد العصب الوركي من أسفل الظهر عبر الورك والأرداف إلى الساق، وقد يصاحبه تنميل أو وخز أو ضعف في الساق.",
               "causes": ["انزلاق غضروفي (السبب الأشيع)", "تضيّق القناة الشوكية", "انزلاق إحدى فقرات العمود الفقري", "إصابة في الظهر"],
               "self_care": "ابقَ نشيطًا وامشِ وقم بحركات خفيفة، وجرّب كمادات دافئة أو باردة، وتجنب الجلوس أو الاستلقاء الطويل. يتحسن غالبًا خلال أسابيع إلى بضعة أشهر.",
               "worry": "اطلب رعاية طارئة فورًا إذا ظهر تنميل أو ضعف في الساقين معًا أو يزداد سوءًا، أو تنميل حول الأعضاء التناسلية أو الشرج، أو صعوبة في التبول أو التحكم بالإخراج.",
               "doctor": "راجع طبيبًا إذا لم يتحسن الألم بعد أسابيع من العناية المنزلية، أو ازداد سوءًا، أو أعاق نشاطك اليومي.",
               "follow_up": "هل يمتد الألم تحت الركبة؟ وهل لديك تنميل أو ضعف في الساق أو تغيّر في التبول؟"},
        "en": {"title": "Sciatica",
               "what": "Sciatica is pain along the sciatic nerve, running from the lower back through the hip and buttock down the leg. It can come with tingling, pins and needles or weakness in the leg.",
               "causes": ["A slipped (herniated) disc, the most common cause", "Narrowing of the spinal canal", "A vertebra slipping out of place", "A back injury"],
               "self_care": "Stay active with gentle movement and walking, try a warm or cold pack, and avoid long periods sitting or lying down. It usually improves within weeks to a few months.",
               "worry": "Get emergency care now for numbness or weakness in both legs or getting worse, numbness around the genitals or anus, or trouble passing urine or controlling your bowels.",
               "doctor": "See a doctor if the pain has not improved after several weeks of home care, is getting worse, or limits your daily activities.",
               "follow_up": "Does the pain go below the knee? Do you have numbness, leg weakness or any change in urination?"},
    },
    "panic_attack": {
        "emoji": "😨", "category": "symptom",
        "aliases": ["نوبة هلع", "نوبات هلع", "نوبة فزع", "نوبة ذعر", "هلع", "احس اني بموت من الخوف", "panic attack", "panic attacks", "panic disorder", "sudden intense fear"],
        "sources": _src(("Panic attacks and panic disorder — Mayo Clinic", "Mayo Clinic", "https://www.mayoclinic.org/diseases-conditions/panic-attacks/symptoms-causes/syc-20376021"),
                        ("Panic disorder — NHS", "NHS", "https://www.nhs.uk/mental-health/conditions/panic-disorder/")),
        "causes_label": _CAUSES,
        "ar": {"title": "نوبة الهلع",
               "what": "نوبة الهلع موجة مفاجئة من خوف شديد قد تصاحبها خفقان وضيق نفس وتعرق ورجفة ودوخة وإحساس بالاختناق، وتبلغ ذروتها غالبًا خلال دقائق ثم تهدأ.",
               "causes": ["ضغوط أو أحداث صادمة", "استعداد عائلي أو وراثي", "الإفراط في الكافيين أو التدخين", "اضطراب هلع يحتاج تقييمًا"],
               "self_care": "تنفّس ببطء وعمق، وذكّر نفسك أن النوبة ستمر وليست خطرة، وقلّل الكافيين والتدخين، ومارس الرياضة وتمارين الاسترخاء بانتظام.",
               "worry": "إذا كانت هذه أول مرة، أو كان الألم في الصدر شديدًا أو ضغطًا يمتد للذراع أو الفك، أو ضيق النفس شديدًا ولا يهدأ، فاطلب الطوارئ 997؛ فقد يشبه أعراض مشكلة قلبية أو تنفسية. وعند أفكار لإيذاء النفس اتصل 937 أو 920033360.",
               "doctor": "راجع طبيبًا إذا تكررت النوبات أو صرت تخاف حدوثها وتتجنب أماكن، لتأكيد التشخيص واستبعاد أسباب أخرى؛ والعلاج المبكر يساعد.",
               "follow_up": "كم مرة حدثت النوبات، وهل بدأت فجأة وهدأت خلال دقائق؟ وهل هذه أول مرة؟"},
        "en": {"title": "Panic attack",
               "what": "A panic attack is a sudden surge of intense fear that can bring a racing heart, breathlessness, sweating, trembling, dizziness and a feeling of choking. It usually peaks within minutes and then eases.",
               "causes": ["Stress or traumatic events", "Family history", "Heavy caffeine use or smoking", "Panic disorder that needs assessment"],
               "self_care": "Breathe slowly and deeply, remind yourself the attack will pass and is not dangerous, cut back on caffeine and smoking, and use regular exercise and relaxation.",
               "worry": "If this is your first time, or chest pain is severe or spreads to the arm or jaw, or breathlessness is severe and does not ease, call 997; it can look like a heart or breathing emergency. For thoughts of self-harm call 937 or 920033360.",
               "doctor": "See a doctor if attacks keep happening or you start avoiding places for fear of them, to confirm the cause and rule out other conditions; early treatment helps.",
               "follow_up": "How often do the attacks happen, and do they start suddenly and ease within minutes? Is this the first time?"},
    },
    "low_blood_pressure": {
        "emoji": "🩺", "category": "symptom",
        "aliases": ["ضغط منخفض", "انخفاض الضغط", "هبوط الضغط", "ضغطي واطي", "ضغط واطي", "ضغطي نازل", "low blood pressure", "hypotension", "low bp", "blood pressure is low"],
        "sources": _src(("Low blood pressure (hypotension) — Mayo Clinic", "Mayo Clinic", "https://www.mayoclinic.org/diseases-conditions/low-blood-pressure/symptoms-causes/syc-20355465"),
                        ("Low blood pressure — NHS", "NHS", "https://www.nhs.uk/conditions/low-blood-pressure-hypotension/"),
                        ("Low Blood Pressure — MedlinePlus", "MedlinePlus", "https://medlineplus.gov/lowbloodpressure.html")),
        "causes_label": _CAUSES,
        "ar": {"title": "انخفاض ضغط الدم",
               "what": "انخفاض ضغط الدم قراءة أقل من المعتاد قد لا تسبب أعراضًا، وقد تسبب دوخة أو شعورًا بالإغماء أو ضبابية أو غثيانًا أو تعبًا خاصة عند الوقوف السريع.",
               "causes": ["الجفاف", "بعض الأدوية ومنها أدوية الضغط", "الحمل", "حالات القلب أو الهرمونات كالسكري", "فقد الدم أو العدوى الشديدة", "الوقوف بسرعة من الجلوس أو الاستلقاء"],
               "self_care": "انهض ببطء، واشرب سوائل كافية، وتناول وجبات صغيرة متكررة، وقلّل الكحول، وتجنب الوقوف الطويل.",
               "worry": "اطلب الطوارئ 997 عند الإغماء، أو الارتباك، أو برودة الجلد مع تعرق، أو تنفس سريع، أو نبض ضعيف، أو بعد نزيف أو إصابة؛ فقد تكون علامات صدمة.",
               "doctor": "راجع طبيبًا إذا تكررت الدوخة أو الإغماء أو صاحبت القراءات المنخفضة أعراض، أو بدأت دواءً جديدًا قبل ذلك. القراءة المنخفضة دون أعراض لا تحتاج غالبًا إلى علاج.",
               "follow_up": "ما قراءة الضغط إن قسته، وهل تشعر بدوخة عند الوقوف؟ وهل تتناول دواءً للضغط أو أنت حامل؟"},
        "en": {"title": "Low blood pressure",
               "what": "Low blood pressure is a reading lower than usual. It may cause no symptoms, or dizziness, feeling faint, blurred vision, nausea or tiredness, especially when standing up quickly.",
               "causes": ["Dehydration", "Some medicines, including blood-pressure medicines", "Pregnancy", "Heart or hormone conditions such as diabetes", "Blood loss or severe infection", "Standing up too quickly"],
               "self_care": "Get up slowly, drink enough fluids, eat small frequent meals, limit alcohol and avoid standing for long periods.",
               "worry": "Call 997 for fainting, confusion, cold clammy skin, fast breathing or a weak pulse, or after bleeding or an injury; these can be signs of shock.",
               "doctor": "See a doctor if dizziness or fainting keeps happening, symptoms come with low readings, or it started after a new medicine. Low readings without symptoms usually need no treatment.",
               "follow_up": "What was the reading if you measured it, and do you feel dizzy on standing? Do you take blood-pressure medicine or are you pregnant?"},
    },
    "blurred_vision": {
        "emoji": "👁️", "category": "symptom",
        "aliases": ["زغللة", "زغلله", "زغللة في العين", "عيني مزغللة", "نظري مشوش", "رؤية ضبابية", "ضبابية في النظر", "تشوش الرؤية", "نظري ضعيف فجأة", "blurry vision", "blurred vision", "vision is blurry", "cloudy vision"],
        "sources": _src(("Blurred vision — Cleveland Clinic", "Cleveland Clinic", "https://my.clevelandclinic.org/health/symptoms/24262-blurred-vision"),
                        ("Vision problems — MedlinePlus Medical Encyclopedia", "MedlinePlus", "https://medlineplus.gov/ency/article/003029.htm")),
        "causes_label": _CAUSES,
        "ar": {"title": "زغللة أو تشوش الرؤية",
               "what": "تشوش الرؤية فقدان لحدة النظر وعدم القدرة على رؤية التفاصيل الدقيقة، وقد يصيب عينًا واحدة أو العينين، وقد يكون مؤقتًا أو مستمرًا.",
               "causes": ["أخطاء الانكسار (قصر النظر أو طوله أو الاستجماتيزم)", "جفاف العين", "إعتام عدسة العين (الماء الأبيض)", "الجلوكوما أو اعتلال الشبكية السكري", "آثار جانبية لبعض الأدوية"],
               "self_care": "افحص نظرك دوريًا وحدّث النظارة أو العدسات، واستخدم دموعًا اصطناعية لجفاف العين بعد استشارة الصيدلي، وخفف الجلوس الطويل أمام الشاشات مع راحات متكررة.",
               "worry": "اطلب الطوارئ فورًا عند تشوش أو فقدان مفاجئ للرؤية، أو ظهور ومضات وستار أسود، أو ألم شديد في العين، أو إصابة في العين، أو ترافق التشوش مع ضعف في الوجه أو الذراع أو صعوبة في الكلام أو صداع شديد مفاجئ؛ فقد يكون سكتة أو مشكلة في الشبكية.",
               "doctor": "أي تغيّر في الرؤية يستحق فحصًا عند طبيب عيون، خاصة إن كان جديدًا أو تدريجيًا يتفاقم أو لديك سكري أو ضغط.",
               "follow_up": "هل بدأ التشوش فجأة أم تدريجيًا؟ وهل يصيب عينًا واحدة أم العينين؟ وهل لديك سكري أو صداع أو ألم في العين؟"},
        "en": {"title": "Blurred vision",
               "what": "Blurred vision is a loss of sharpness and difficulty seeing fine detail. It can affect one eye or both and may be temporary or ongoing.",
               "causes": ["Refractive errors (short-sightedness, long-sightedness, astigmatism)", "Dry eyes", "Cataracts", "Glaucoma or diabetic retinopathy", "Side effects of some medicines"],
               "self_care": "Have regular eye tests and update glasses or lenses, use artificial tears for dry eyes after asking a pharmacist, and take regular breaks from screens.",
               "worry": "Get emergency care now for sudden blurring or loss of vision, flashes or a dark curtain, severe eye pain, an eye injury, or blurring together with facial or arm weakness, speech trouble or a sudden severe headache; it can be a stroke or a retinal problem.",
               "doctor": "Any change in vision deserves an eye examination, especially if it is new, gradually getting worse, or you have diabetes or high blood pressure.",
               "follow_up": "Did it start suddenly or gradually, in one eye or both? Do you have diabetes, headache or eye pain?"},
    },
    "depression": {
        "emoji": "💙", "category": "symptom",
        "aliases": ["اكتئاب", "الاكتئاب", "احس بحزن", "حزين طول الوقت", "مزاجي سيء", "ما عندي رغبة بشي", "فقدان الاهتمام", "نفسيتي تعبانة", "depression", "depressed", "feeling low", "low mood", "feeling down", "sad all the time"],
        "sources": _src(("Depression in adults — NHS", "NHS", "https://www.nhs.uk/mental-health/conditions/depression-in-adults/overview/"),
                        ("Depression — Mayo Clinic", "Mayo Clinic", "https://www.mayoclinic.org/diseases-conditions/depression/symptoms-causes/syc-20356007"),
                        ("Depression — MedlinePlus", "MedlinePlus", "https://medlineplus.gov/depression.html")),
        "causes_label": _CAUSES,
        "ar": {"title": "الاكتئاب وانخفاض المزاج",
               "what": "الاكتئاب أكثر من حزن عابر: مزاج منخفض مستمر أو فقدان الاهتمام والمتعة لأسبوعين أو أكثر، وقد يصاحبه اضطراب النوم والشهية وتعب وصعوبة تركيز وشعور بالذنب أو انعدام القيمة.",
               "causes": ["أحداث حياتية كفقد عزيز أو العمل", "استعداد عائلي", "تغيرات هرمونية وكيميائية في الدماغ", "ضغوط مزمنة أو صدمات", "أمراض مزمنة كالسكري وأمراض القلب"],
               "self_care": "حافظ على نشاط بدني منتظم وروتين نوم ثابت، وابقَ على تواصل مع من تثق بهم، وقلّل الكحول وتجنب التدخين، ولا توقف دواءً موصوفًا دون استشارة الطبيب.",
               "worry": "إذا خطرت لك أفكار بإيذاء نفسك أو أن الحياة لا تستحق العيش فلا تبقَ وحدك: تواصل الآن مع شخص تثق به واتصل بالصحة 937 أو مركز الاستشارات النفسية 920033360، وإن كنت في خطر مباشر فاتصل بالإسعاف 997.",
               "doctor": "راجع طبيبًا أو مختصًا نفسيًا إذا استمر المزاج المنخفض أو فقدان الاهتمام نحو أسبوعين أو أكثر أو أثّر على حياتك اليومية؛ فالمساعدة المبكرة تحسّن التعافي.",
               "follow_up": "منذ متى تشعر بهذا، وهل يؤثر على نومك وعملك؟ وهل راودتك أفكار لإيذاء نفسك؟"},
        "en": {"title": "Depression and low mood",
               "what": "Depression is more than passing sadness: a persistent low mood or loss of interest and pleasure for two weeks or more, which may come with changes in sleep and appetite, tiredness, trouble concentrating and feelings of guilt or worthlessness.",
               "causes": ["Life events such as bereavement or job loss", "Family history", "Hormonal and brain-chemistry changes", "Long-term stress or trauma", "Long-term illness such as diabetes or heart disease"],
               "self_care": "Keep up regular physical activity and a steady sleep routine, stay in touch with people you trust, cut down alcohol and avoid smoking, and do not stop a prescribed medicine without advice.",
               "worry": "If you have thoughts of harming yourself or that life is not worth living, do not stay alone: contact someone you trust now and call 937 or the mental-health line 920033360; if in immediate danger call 997.",
               "doctor": "See a doctor or mental-health professional if low mood or loss of interest lasts about two weeks or more or affects daily life; early help improves recovery.",
               "follow_up": "How long have you felt this way, and is it affecting your sleep or work? Have you had thoughts of harming yourself?"},
    },
}

# Extra everyday wordings (dialect / spelling variants) for topics that already exist.
ALIAS_PATCHES = {
    "headache": ["وجع راس", "وجع الراس", "الم الراس", "ألم الرأس", "راسي يؤلمني", "راسي يوجعني", "صداع شديد", "head hurts", "my head is pounding"],
    "shortness_of_breath": ["نهجان", "اهج", "نفسي قصير", "نفسي ضيق", "ما احصل نفس", "breathlessness", "out of breath", "trouble breathing"],
    "dizziness": ["دوخة", "دايخ", "دايخه", "الدنيا تدور", "light headed", "lightheaded", "feeling faint"],
    "knee_pain_common": ["وجع الركبة", "الم الركبة", "ألم الركبة", "ركبتي توجعني", "ركبتي تعورني", "knee pain", "my knee hurts", "sore knee"],
    "eye_redness": ["عيني حمراء", "عيوني حمر", "احمرار عيني", "عيني محمرة", "red eye", "red eyes", "bloodshot eyes"],
    "insomnia": ["قلة النوم", "ما اقدر انام", "ما اقدر أنام", "صعوبة النوم", "ارق", "sleeplessness", "cant sleep", "can't sleep", "trouble sleeping"],
    "tingling": ["تنميل اليدين", "خدر اليد", "خدر في اليدين", "تنميل الاصابع", "numbness in hands", "numb hands", "numb fingers", "pins and needles"],
    "urinary_symptoms": ["حرقان البول", "حرقة عند التبول", "الم عند التبول", "الم اثناء التبول", "pain when urinating", "painful urination", "burning urination", "burning when i pee", "burning when peeing"],
    "diabetes": ["سكر", "السكر", "ارتفاع السكر", "سكر الدم", "اعراض السكر", "sugar disease", "high sugar", "blood sugar"],
    "hypertension": ["ضغط مرتفع", "ضغط عالي", "ضغطي عالي", "ارتفاع الضغط", "high bp", "high blood pressure"],
    "reflux": ["حموضة", "حموضه", "حرقان المعدة", "حرقان في الصدر بعد الاكل", "heartburn", "acid reflux", "acid indigestion"],
    "common_cold": ["رشح", "رشح وعطاس", "زكام", "نزلة برد", "عطاس وسيلان", "runny nose and sneezing"],
    "nausea": ["غثيان", "نفسي مغثية", "نفسي تغثني", "احس بغثيان", "feel sick", "queasy", "nausea"],
    "fatigue": ["ارهاق", "ارهاق مستمر", "تعب مستمر", "تعبان دايم", "خمول", "always tired", "constant tiredness", "no energy"],
}
