"""Additional source-grounded symptom patterns, checked 2026-09-17.
Weights are heuristic ranking inputs, not calibrated disease probabilities.
This module adds data only; emergency rules and ranking logic remain separate.
"""

EXTRA_SYMPTOMS = [('heel-sole-pain',
  'ألم أسفل الكعب أو قوس القدم',
  'Pain under the heel or foot arch',
  'pain',
  ['كعبي يوجعني', 'وجع كعب القدم', 'الم باطن الكعب'],
  ['heel pain', 'pain under my heel', 'foot arch pain']),
 ('first-step-heel-pain',
  'ألم الكعب عند أول خطوات بعد الراحة',
  'Heel pain on first steps after rest',
  'pain',
  ['كعبي يوجعني اول ما اقوم', 'الم الكعب اول الصباح'],
  ['heel hurts on first steps', 'heel pain after resting']),
 ('outer-elbow-pain',
  'ألم الجهة الخارجية من المرفق',
  'Pain on the outside of the elbow',
  'pain',
  ['الم خارج الكوع', 'كوعي يوجعني من بره'],
  ['outer elbow pain', 'outside of elbow hurts']),
 ('elbow-pain-gripping',
  'ألم المرفق عند الإمساك بالأشياء',
  'Elbow pain when gripping objects',
  'pain',
  ['كوعي يوجعني لما امسك شي', 'الم الكوع عند حمل الاشياء'],
  ['elbow hurts when gripping', 'elbow pain lifting objects']),
 ('jaw-pain', 'ألم الفك', 'Jaw pain', 'pain', ['فكي يوجعني', 'وجع الفك'], ['my jaw hurts', 'aching jaw']),
 ('jaw-pain-chewing',
  'ألم الفك عند المضغ',
  'Jaw pain when chewing',
  'pain',
  ['فكي يوجعني لما امضغ', 'الم الفك مع الاكل'],
  ['jaw hurts when chewing', 'painful chewing in jaw']),
 ('jaw-clicking',
  'طقطقة الفك عند تحريكه',
  'Jaw clicking on movement',
  'pain',
  ['فكي يطقطق', 'صوت طقطقه بالفك'],
  ['clicking jaw', 'jaw pops']),
 ('finger-locking',
  'إصبع يعلق في وضع الانثناء',
  'Finger catches in a bent position',
  'pain',
  ['اصبعي يعلق', 'اصبعي يقفل لما اثنيه'],
  ['finger gets stuck bent', 'finger locking']),
 ('finger-stiffness-pain',
  'ألم أو تيبس الإصبع',
  'Finger pain or stiffness',
  'pain',
  ['اصبعي متيبس', 'الم الاصبع'],
  ['stiff finger', 'finger pain']),
 ('urge-move-legs',
  'رغبة ملحة في تحريك الساقين',
  'Strong urge to move the legs',
  'neurological',
  ['احس لازم احرك رجولي', 'رغبة بتحريك الساقين'],
  ['urge to move legs', 'need to keep moving my legs']),
 ('leg-discomfort-at-rest',
  'انزعاج بالساقين يزداد أثناء الراحة ليلًا',
  'Leg discomfort worse at rest at night',
  'neurological',
  ['رجولي تضايقني بالليل وانا مرتاح', 'انزعاج الساقين وقت النوم'],
  ['legs uncomfortable at rest at night', 'leg discomfort at bedtime']),
 ('loud-snoring',
  'شخير مرتفع',
  'Loud snoring',
  'respiratory',
  ['اشخر بصوت عالي', 'شخير قوي'],
  ['snoring loudly', 'heavy snoring']),
 ('sleep-breathing-pauses',
  'توقف وعودة التنفس أثناء النوم',
  'Breathing pauses and restarts during sleep',
  'respiratory',
  ['تنفسي يوقف وانا نايم ويرجع', 'توقف التنفس اثناء النوم'],
  ['breathing pauses during sleep', 'stop and start breathing in sleep']),
 ('daytime-sleepiness',
  'نعاس زائد أثناء النهار',
  'Excessive daytime sleepiness',
  'general',
  ['انعس كثير بالنهار', 'نعاس بالنهار'],
  ['sleepy during the day', 'daytime drowsiness']),
 ('eyelash-crusts',
  'قشور حول جذور الرموش',
  'Crusts around eyelash roots',
  'general',
  ['قشور على رموشي', 'جفوني تلصق الصباح'],
  ['crusty eyelashes', 'eyelids stuck in the morning']),
 ('itchy-eyelids',
  'حكة أو تهيج الجفون',
  'Itchy or irritated eyelids',
  'general',
  ['جفوني تحكني', 'حكة الجفون'],
  ['itchy eyelids', 'irritated eyelids']),
 ('mouth-ulcers',
  'قرح داخل الفم',
  'Ulcers inside the mouth',
  'general',
  ['قرحه داخل فمي', 'تقرحات الفم', 'قرحة اللسان'],
  ['mouth ulcers', 'canker sores', 'ulcer inside mouth']),
 ('bleeding-gums',
  'نزف اللثة عند تنظيف الأسنان',
  'Gums bleed when brushing',
  'general',
  ['لثتي تنزف لما افرش', 'نزيف اللثة'],
  ['bleeding gums', 'gums bleed when brushing']),
 ('swollen-gums',
  'تورم أو احمرار اللثة',
  'Swollen or red gums',
  'general',
  ['لثتي وارمه', 'احمرار اللثة'],
  ['swollen gums', 'red sore gums']),
 ('scalp-flakes',
  'قشور في فروة الرأس',
  'Flakes on the scalp',
  'skin',
  ['قشرة الشعر', 'فروة راسي فيها قشور'],
  ['scalp flakes', 'dandruff flakes']),
 ('itchy-scalp',
  'حكة فروة الرأس',
  'Itchy scalp',
  'skin',
  ['فروة راسي تحكني', 'حكة الراس'],
  ['itchy scalp', 'itching scalp']),
 ('golden-skin-crusts',
  'قروح جلدية بقشور ذهبية',
  'Skin sores with golden crusts',
  'skin',
  ['قشور عسلية على الجلد', 'قروح عليها قشر اصفر'],
  ['honey coloured crusts', 'golden crusted sores']),
 ('itch-between-toes',
  'حكة بين أصابع القدم',
  'Itching between toes',
  'skin',
  ['بين اصابع رجلي يحكني', 'حكه بين اصابع القدم'],
  ['itching between toes', 'itchy toe webs']),
 ('peeling-between-toes',
  'تقشر أو تشقق بين أصابع القدم',
  'Peeling or cracking between toes',
  'skin',
  ['تقشر بين اصابع رجلي', 'تشققات بين اصابع القدم'],
  ['peeling between toes', 'cracked skin between toes'])]

EXTRA_DISEASES = [{'slug': 'plantar-fasciitis',
  'name_ar': 'التهاب اللفافة الأخمصية',
  'name_en': 'Plantar fasciitis',
  'category': 'pain',
  'severity': 'mild',
  'symptoms': {'heel-sole-pain': 1.0, 'first-step-heel-pain': 1.0},
  'description_ar': 'قد يسبب ألمًا بأسفل الكعب يزداد عند أول خطوات بعد الراحة. هذا احتمال توعوي يحتاج '
                    'تقييمًا للتأكيد.',
  'description_en': 'May cause pain under the heel, worse on first steps after rest. This is an educational '
                    'possibility requiring assessment.',
  'risk_ar': 'إجهاد أنسجة باطن القدم؛ قد يرتبط بزيادة المشي أو أحذية قليلة الدعم.',
  'risk_en': 'Strain of the sole tissues, sometimes after increased walking or poorly supportive shoes.',
  'causes_ar': 'إجهاد أنسجة باطن القدم؛ قد يرتبط بزيادة المشي أو أحذية قليلة الدعم.',
  'causes_en': 'Strain of the sole tissues, sometimes after increased walking or poorly supportive shoes.',
  'next_ar': 'خفف النشاط المؤلم واستخدم حذاء داعمًا؛ راجع مختصًا إذا لم يتحسن خلال أسبوعين.',
  'next_en': 'Reduce painful activity and use supportive footwear; seek review if not improving within two '
             'weeks.',
  'red_ar': 'اطلب تقييمًا مبكرًا للألم الشديد أو فقد الإحساس، خصوصًا مع السكري.',
  'red_en': 'Seek prompt review for severe pain or loss of sensation, especially with diabetes.',
  'sources': [('nhs',
               'التهاب اللفافة الأخمصية — NHS',
               'Plantar fasciitis — NHS',
               'https://www.nhs.uk/conditions/plantar-fasciitis/')]},
 {'slug': 'tennis-elbow',
  'name_ar': 'مرفق التنس',
  'name_en': 'Tennis elbow',
  'category': 'pain',
  'severity': 'mild',
  'symptoms': {'outer-elbow-pain': 1.0, 'elbow-pain-gripping': 0.9},
  'description_ar': 'قد يسبب ألمًا خارج المرفق يزداد مع القبض أو الرفع. هذا احتمال توعوي يحتاج تقييمًا '
                    'للتأكيد.',
  'description_en': 'May cause outer elbow pain aggravated by gripping or lifting. This is an educational '
                    'possibility requiring assessment.',
  'risk_ar': 'إجهاد الأوتار مع تكرار حركة الرسغ والساعد.',
  'risk_en': 'Tendon strain associated with repetitive wrist and forearm movements.',
  'causes_ar': 'إجهاد الأوتار مع تكرار حركة الرسغ والساعد.',
  'causes_en': 'Tendon strain associated with repetitive wrist and forearm movements.',
  'next_ar': 'قلل النشاط المحفز وراجع مختصًا إذا استمر الألم بعد أسبوعين من العناية.',
  'next_en': 'Reduce triggering activities; seek review if pain persists after two weeks of self-care.',
  'red_ar': 'الألم المستمر أو الذي يعطل حركة الذراع يحتاج فحصًا.',
  'red_en': 'Persistent pain or difficulty using the arm needs assessment.',
  'sources': [('nhs',
               'مرفق التنس — NHS',
               'Tennis elbow — NHS',
               'https://www.nhs.uk/conditions/tennis-elbow/')]},
 {'slug': 'temporomandibular-disorder',
  'name_ar': 'اضطراب المفصل الفكي الصدغي',
  'name_en': 'Temporomandibular disorder',
  'category': 'pain',
  'severity': 'moderate',
  'symptoms': {'jaw-pain': 1.0, 'jaw-pain-chewing': 0.9, 'jaw-clicking': 0.8, 'ear-pain': 0.3},
  'description_ar': 'قد يسبب ألم الفك وطقطقته أو صعوبة حركته. هذا احتمال توعوي يحتاج تقييمًا للتأكيد.',
  'description_en': 'May cause jaw pain, clicking, or difficulty moving the jaw. This is an educational '
                    'possibility requiring assessment.',
  'risk_ar': 'قد يرتبط بصرير الأسنان أو إصابة أو إجهاد المفصل.',
  'risk_en': 'May be associated with teeth grinding, injury, or joint strain.',
  'causes_ar': 'قد يرتبط بصرير الأسنان أو إصابة أو إجهاد المفصل.',
  'causes_en': 'May be associated with teeth grinding, injury, or joint strain.',
  'next_ar': 'تجنب العلكة والطعام القاسي واطلب تقييمًا طبيًا أو سنيًا.',
  'next_en': 'Avoid gum and hard foods and arrange medical or dental assessment.',
  'red_ar': 'اطلب مراجعة عاجلة عند انغلاق الفك أو تعذر الأكل والشرب أو تغير الرؤية.',
  'red_en': 'Seek urgent assessment for jaw locking, inability to eat or drink, or vision changes.',
  'sources': [('nhs',
               'اضطراب المفصل الفكي الصدغي — NHS',
               'Temporomandibular disorder — NHS',
               'https://www.nhs.uk/conditions/temporomandibular-disorder-tmd/')]},
 {'slug': 'trigger-finger',
  'name_ar': 'الإصبع الزنادي',
  'name_en': 'Trigger finger',
  'category': 'pain',
  'severity': 'mild',
  'symptoms': {'finger-locking': 1.0, 'finger-stiffness-pain': 0.8},
  'description_ar': 'قد يعلق الإصبع مثنيًا مع ألم أو تيبس. هذا احتمال توعوي يحتاج تقييمًا للتأكيد.',
  'description_en': 'A finger may catch while bent, with pain or stiffness. This is an educational '
                    'possibility requiring assessment.',
  'risk_ar': 'تثخن الوتر قد يعيق انزلاقه؛ يزداد حدوثه مع السكري والتهاب المفاصل الروماتويدي.',
  'risk_en': 'A thickened tendon may not glide freely; diabetes and rheumatoid arthritis increase risk.',
  'causes_ar': 'تثخن الوتر قد يعيق انزلاقه؛ يزداد حدوثه مع السكري والتهاب المفاصل الروماتويدي.',
  'causes_en': 'A thickened tendon may not glide freely; diabetes and rheumatoid arthritis increase risk.',
  'next_ar': 'قلل الأنشطة التي تزيد الأعراض وراجع مختصًا إذا استمرت.',
  'next_en': 'Reduce activities that worsen symptoms and seek review if they persist.',
  'red_ar': 'تعطل استخدام اليد أو استمرار انغلاق الإصبع يحتاج تقييمًا.',
  'red_en': 'Difficulty using the hand or persistent locking needs assessment.',
  'sources': [('nhs',
               'الإصبع الزنادي — NHS',
               'Trigger finger — NHS',
               'https://www.nhs.uk/conditions/trigger-finger/')]},
 {'slug': 'restless-legs-syndrome',
  'name_ar': 'متلازمة تململ الساقين',
  'name_en': 'Restless legs syndrome',
  'category': 'neurological',
  'severity': 'mild',
  'symptoms': {'urge-move-legs': 1.0, 'leg-discomfort-at-rest': 1.0, 'insomnia': 0.25},
  'description_ar': 'رغبة ملحة لتحريك الساقين مع انزعاج يزداد غالبًا أثناء الراحة ليلًا. هذا احتمال توعوي '
                    'يحتاج تقييمًا للتأكيد.',
  'description_en': 'An urge to move the legs with discomfort, often worse at rest at night. This is an '
                    'educational possibility requiring assessment.',
  'risk_ar': 'قد يرتبط بالوراثة أو نقص الحديد أو الحمل أو بعض الأدوية.',
  'risk_en': 'May be linked to family history, low iron, pregnancy, or some medicines.',
  'causes_ar': 'قد يرتبط بالوراثة أو نقص الحديد أو الحمل أو بعض الأدوية.',
  'causes_en': 'May be linked to family history, low iron, pregnancy, or some medicines.',
  'next_ar': 'جرّب حركة لطيفة ونومًا منتظمًا؛ راجع مختصًا عند تأثر النوم، ولا تبدأ الحديد دون تقييم.',
  'next_en': 'Try gentle movement and regular sleep; seek review if sleep is affected, and do not self-start '
             'iron.',
  'red_ar': 'استمرار الأعراض رغم العناية أو تأثيرها على حياتك يحتاج مراجعة.',
  'red_en': 'Persistent symptoms despite self-care or effects on daily life need review.',
  'sources': [('nhs',
               'متلازمة تململ الساقين — NHS',
               'Restless legs syndrome — NHS',
               'https://www.nhs.uk/conditions/restless-legs-syndrome/')]},
 {'slug': 'obstructive-sleep-apnoea',
  'name_ar': 'انقطاع النفس الانسدادي أثناء النوم',
  'name_en': 'Obstructive sleep apnoea',
  'category': 'respiratory',
  'severity': 'moderate',
  'symptoms': {'loud-snoring': 0.8, 'sleep-breathing-pauses': 1.0, 'daytime-sleepiness': 0.85},
  'description_ar': 'قد يتكرر توقف وعودة التنفس أثناء النوم مع شخير ونعاس نهاري. هذا احتمال توعوي يحتاج '
                    'تقييمًا للتأكيد.',
  'description_en': 'Breathing may repeatedly pause and restart during sleep, with snoring and daytime '
                    'sleepiness. This is an educational possibility requiring assessment.',
  'risk_ar': 'تضيق مجرى التنفس أثناء النوم؛ يحتاج تقييمًا وقد يتطلب فحص نوم.',
  'risk_en': 'Airway narrowing during sleep; assessment may include a sleep study.',
  'causes_ar': 'تضيق مجرى التنفس أثناء النوم؛ يحتاج تقييمًا وقد يتطلب فحص نوم.',
  'causes_en': 'Airway narrowing during sleep; assessment may include a sleep study.',
  'next_ar': 'احجز تقييمًا طبيًا، وتجنب القيادة مع النعاس والمنومات دون وصفة.',
  'next_en': 'Arrange medical assessment; avoid driving while sleepy and non-prescribed sleeping pills.',
  'red_ar': 'لا تؤخر التقييم إذا لوحظ توقف التنفس أثناء النوم أو نعاس شديد.',
  'red_en': 'Do not delay assessment for witnessed breathing pauses or marked sleepiness.',
  'sources': [('nhs',
               'انقطاع النفس الانسدادي أثناء النوم — NHS',
               'Obstructive sleep apnoea — NHS',
               'https://www.nhs.uk/conditions/sleep-apnoea/')]},
 {'slug': 'blepharitis',
  'name_ar': 'التهاب حواف الجفون',
  'name_en': 'Blepharitis',
  'category': 'general',
  'severity': 'mild',
  'symptoms': {'eyelash-crusts': 1.0, 'itchy-eyelids': 0.9},
  'description_ar': 'قد يسبب حكة بالجفون وقشورًا حول جذور الرموش. هذا احتمال توعوي يحتاج تقييمًا للتأكيد.',
  'description_en': 'May cause itchy eyelids and crusts around eyelash roots. This is an educational '
                    'possibility requiring assessment.',
  'risk_ar': 'قد يرتبط ببكتيريا الجلد أو اضطراب غدد الجفون أو التهاب الجلد.',
  'risk_en': 'May involve skin bacteria, eyelid oil glands, or skin inflammation.',
  'causes_ar': 'قد يرتبط ببكتيريا الجلد أو اضطراب غدد الجفون أو التهاب الجلد.',
  'causes_en': 'May involve skin bacteria, eyelid oil glands, or skin inflammation.',
  'next_ar': 'نظف حواف الجفون بلطف واستشر الصيدلي؛ تجنب العدسات أثناء الأعراض.',
  'next_en': 'Clean eyelid edges gently and ask a pharmacist; avoid contact lenses while symptomatic.',
  'red_ar': 'ألم العين أو تغير الرؤية أو احمرار شديد يحتاج تقييمًا عاجلًا.',
  'red_en': 'Eye pain, vision changes, or very red eyes need urgent assessment.',
  'sources': [('nhs',
               'التهاب حواف الجفون — NHS',
               'Blepharitis — NHS',
               'https://www.nhs.uk/conditions/blepharitis/')]},
 {'slug': 'mouth-ulcer-pattern',
  'name_ar': 'قرح الفم — أسباب متعددة',
  'name_en': 'Mouth ulcers — several possible causes',
  'category': 'general',
  'severity': 'mild',
  'symptoms': {'mouth-ulcers': 1.0},
  'description_ar': 'قرح داخل الفم قد تنجم عن تهيج موضعي أو أسباب أخرى. هذا احتمال توعوي يحتاج تقييمًا '
                    'للتأكيد.',
  'description_en': 'Ulcers inside the mouth may follow local irritation or other causes. This is an '
                    'educational possibility requiring assessment.',
  'risk_ar': 'عض الخد أو احتكاك الأسنان أو التوتر من العوامل الممكنة.',
  'risk_en': 'Cheek biting, dental irritation, or stress may contribute.',
  'causes_ar': 'عض الخد أو احتكاك الأسنان أو التوتر من العوامل الممكنة.',
  'causes_en': 'Cheek biting, dental irritation, or stress may contribute.',
  'next_ar': 'تجنب المهيجات واستخدم فرشاة ناعمة؛ راجع طبيبًا أو طبيب أسنان إذا استمرت ثلاثة أسابيع.',
  'next_en': 'Avoid irritants and use a soft toothbrush; seek medical or dental review if lasting three '
             'weeks.',
  'red_ar': 'القرحة النازفة أو المتزايدة ألمًا واحمرارًا تحتاج مراجعة.',
  'red_en': 'Bleeding or increasingly painful and red ulcers need review.',
  'sources': [('nhs',
               'قرح الفم — أسباب متعددة — NHS',
               'Mouth ulcers — several possible causes — NHS',
               'https://www.nhs.uk/conditions/mouth-ulcers/')]},
 {'slug': 'gum-disease',
  'name_ar': 'مرض اللثة',
  'name_en': 'Gum disease',
  'category': 'general',
  'severity': 'moderate',
  'symptoms': {'bleeding-gums': 1.0, 'swollen-gums': 0.9},
  'description_ar': 'قد تظهر اللثة حمراء ومتورمة وتنزف عند تنظيف الأسنان. هذا احتمال توعوي يحتاج تقييمًا '
                    'للتأكيد.',
  'description_en': 'Gums may become red, swollen, and bleed during brushing. This is an educational '
                    'possibility requiring assessment.',
  'risk_ar': 'تراكم اللويحة على الأسنان يهيج اللثة.',
  'risk_en': 'Dental plaque build-up irritates the gums.',
  'causes_ar': 'تراكم اللويحة على الأسنان يهيج اللثة.',
  'causes_en': 'Dental plaque build-up irritates the gums.',
  'next_ar': 'احجز فحص أسنان واستمر بتنظيف لطيف للأسنان وما بينها.',
  'next_en': 'Arrange a dental examination and continue gentle tooth and interdental cleaning.',
  'red_ar': 'تورم شديد أو أسنان متخلخلة أو كتلة بالفم تحتاج موعد أسنان عاجلًا.',
  'red_en': 'Severe swelling, loose teeth, or a mouth lump needs urgent dental assessment.',
  'sources': [('nhs', 'مرض اللثة — NHS', 'Gum disease — NHS', 'https://www.nhs.uk/conditions/gum-disease/')]},
 {'slug': 'dandruff-pattern',
  'name_ar': 'قشرة فروة الرأس',
  'name_en': 'Dandruff',
  'category': 'skin',
  'severity': 'mild',
  'symptoms': {'scalp-flakes': 1.0, 'itchy-scalp': 0.7},
  'description_ar': 'قشور بفروة الرأس قد ترافقها حكة؛ بعض الحالات تشبه أمراض جلدية أخرى. هذا احتمال توعوي '
                    'يحتاج تقييمًا للتأكيد.',
  'description_en': 'Scalp flakes may come with itching; other skin conditions can look similar. This is an '
                    'educational possibility requiring assessment.',
  'risk_ar': 'قد يرتبط بخمائر الجلد أو أمراض جلدية، وليس بالضرورة بسوء النظافة.',
  'risk_en': 'May involve skin yeast or skin conditions, not necessarily poor hygiene.',
  'causes_ar': 'قد يرتبط بخمائر الجلد أو أمراض جلدية، وليس بالضرورة بسوء النظافة.',
  'causes_en': 'May involve skin yeast or skin conditions, not necessarily poor hygiene.',
  'next_ar': 'اسأل الصيدلي عن شامبو مناسب؛ راجع مختصًا إذا لم يتحسن خلال أربعة أسابيع.',
  'next_en': 'Ask a pharmacist about suitable shampoo; seek review if not improving within four weeks.',
  'red_ar': 'احمرار أو تورم الفروة أو حكة شديدة يحتاج تقييمًا.',
  'red_en': 'A red or swollen scalp or severe itching needs assessment.',
  'sources': [('nhs', 'قشرة فروة الرأس — NHS', 'Dandruff — NHS', 'https://www.nhs.uk/conditions/dandruff/')]},
 {'slug': 'impetigo',
  'name_ar': 'القوباء',
  'name_en': 'Impetigo',
  'category': 'skin',
  'severity': 'moderate',
  'symptoms': {'golden-skin-crusts': 1.0, 'skin-rash': 0.35},
  'description_ar': 'عدوى جلدية قد تظهر كقروح تتقشر بلون ذهبي؛ يلزم تمييزها عن طفوح أخرى. هذا احتمال توعوي '
                    'يحتاج تقييمًا للتأكيد.',
  'description_en': 'A skin infection may form golden-crusted sores; it must be distinguished from other '
                    'rashes. This is an educational possibility requiring assessment.',
  'risk_ar': 'عدوى تنتقل بالتلامس وقد تبدأ في جلد متضرر.',
  'risk_en': 'A contact-spread infection that can start in damaged skin.',
  'causes_ar': 'عدوى تنتقل بالتلامس وقد تبدأ في جلد متضرر.',
  'causes_en': 'A contact-spread infection that can start in damaged skin.',
  'next_ar': 'اطلب تقييمًا للعلاج، واغسل اليدين ولا تشارك المناشف.',
  'next_en': 'Seek treatment advice, wash hands, and do not share towels.',
  'red_ar': 'الرضع وضعف المناعة أو تدهور الأعراض يحتاجون تقييمًا طبيًا مبكرًا.',
  'red_en': 'Infants, immunocompromised people, or worsening symptoms need prompt medical assessment.',
  'sources': [('nhs', 'القوباء — NHS', 'Impetigo — NHS', 'https://www.nhs.uk/conditions/impetigo/')]},
 {'slug': 'athletes-foot',
  'name_ar': 'سعفة القدم',
  'name_en': 'Athlete’s foot',
  'category': 'skin',
  'severity': 'mild',
  'symptoms': {'itch-between-toes': 1.0, 'peeling-between-toes': 1.0},
  'description_ar': 'عدوى فطرية قد تسبب حكة وتقشرًا أو تشققًا بين أصابع القدم. هذا احتمال توعوي يحتاج '
                    'تقييمًا للتأكيد.',
  'description_en': 'A fungal infection may cause itching, peeling, or cracking between toes. This is an '
                    'educational possibility requiring assessment.',
  'risk_ar': 'الفطريات والرطوبة والقدم المتعرقة عوامل مرتبطة.',
  'risk_en': 'Fungi, moisture, and sweaty feet are associated factors.',
  'causes_ar': 'الفطريات والرطوبة والقدم المتعرقة عوامل مرتبطة.',
  'causes_en': 'Fungi, moisture, and sweaty feet are associated factors.',
  'next_ar': 'جفف بين الأصابع ولا تشارك المناشف واستشر الصيدلي عن علاج مناسب.',
  'next_en': 'Dry between toes, avoid sharing towels, and ask a pharmacist about suitable treatment.',
  'red_ar': 'قدم حارة أو حمراء أو مؤلمة، أو وجود سكري أو ضعف مناعة، يحتاج تقييمًا طبيًا.',
  'red_en': 'A hot, red, painful foot, diabetes, or reduced immunity needs medical assessment.',
  'sources': [('nhs',
               'سعفة القدم — NHS',
               'Athlete’s foot — NHS',
               'https://www.nhs.uk/conditions/athletes-foot/')]}]

# V53: high-priority safety-linked patterns. These rows improve the user-facing
# analysis coverage for symptoms that were previously represented only as red
# flags. Emergency triage still takes precedence in analysis_core; these
# conditions are educational possibilities, not diagnoses.
EXTRA_DISEASES += [
    {
        'slug': 'stroke-warning-pattern',
        'name_ar': 'نمط تحذيري قد يتوافق مع سكتة دماغية أو نوبة نقص تروية',
        'name_en': 'Stroke or TIA warning pattern',
        'category': 'neurological',
        'severity': 'high',
        'symptoms': {
            'one-sided-weakness': 1.0, 'one-sided-numbness': .9,
            'speech-difficulty': .95, 'face-drooping': .95,
            'sudden-vision-loss': .8, 'severe-headache': .55,
            'dizziness': .35,
        },
        'description_ar': 'ضعف أو خدر مفاجئ في جهة واحدة أو اضطراب الكلام أو تدلي الوجه قد يكون نمطًا طارئًا يحتاج تقييمًا فوريًا.',
        'description_en': 'Sudden one-sided weakness or numbness, speech difficulty, or facial droop can be an emergency warning pattern requiring immediate assessment.',
        'risk_ar': 'قد ترتبط هذه العلامات باضطراب حاد في تدفق الدم إلى الدماغ.',
        'risk_en': 'These signs can be associated with an acute disruption of blood flow to the brain.',
        'causes_ar': 'أسباب عصبية وعائية حادة محتملة؛ لا يمكن تأكيد السبب دون تقييم طبي عاجل.',
        'causes_en': 'Possible acute neurovascular causes; the cause cannot be confirmed without urgent medical assessment.',
        'next_ar': 'اطلب رعاية طبية طارئة فورًا ولا تنتظر زوال الأعراض من تلقاء نفسها.',
        'next_en': 'Seek emergency medical care immediately and do not wait for symptoms to resolve on their own.',
        'red_ar': 'أي ضعف مفاجئ بجهة واحدة أو اضطراب كلام أو تدلي وجه أو فقد مفاجئ للرؤية يعد علامة خطر.',
        'red_en': 'Any sudden one-sided weakness, speech difficulty, facial droop, or sudden vision loss is a red flag.',
        'sources': [('ninds', 'السكتة الدماغية — NINDS', 'Stroke — NINDS', 'https://www.ninds.nih.gov/health-information/disorders/stroke')],
    },
    {
        'slug': 'anaphylaxis-warning-pattern',
        'name_ar': 'نمط تحذيري للحساسية المفرطة',
        'name_en': 'Anaphylaxis warning pattern',
        'category': 'respiratory',
        'severity': 'high',
        'symptoms': {
            'throat-swelling': 1.0, 'tongue-swelling': 1.0,
            'shortness-of-breath': .95, 'wheezing': .8,
            'dizziness': .55, 'loss-of-consciousness': .45,
            'skin-rash': .4,
        },
        'description_ar': 'تورم الحلق أو اللسان مع صعوبة التنفس قد يدل على تفاعل تحسسي شديد سريع التطور.',
        'description_en': 'Throat or tongue swelling with breathing difficulty can indicate a rapidly developing severe allergic reaction.',
        'risk_ar': 'قد يحدث بعد طعام أو دواء أو لسعة أو مسبب حساسية آخر.',
        'risk_en': 'It can occur after food, medicine, insect stings, or another allergen exposure.',
        'causes_ar': 'استجابة تحسسية جهازية شديدة محتملة.',
        'causes_en': 'A possible severe systemic allergic response.',
        'next_ar': 'اطلب الطوارئ فورًا عند تورم الحلق أو اللسان أو صعوبة التنفس.',
        'next_en': 'Seek emergency help immediately for throat or tongue swelling or breathing difficulty.',
        'red_ar': 'تورم الفم أو اللسان أو الحلق، صعوبة التنفس، الإغماء أو التدهور السريع علامات طارئة.',
        'red_en': 'Mouth, tongue, or throat swelling, breathing difficulty, fainting, or rapid deterioration are emergency signs.',
        'sources': [('nhs', 'الحساسية المفرطة — NHS', 'Anaphylaxis — NHS', 'https://www.nhs.uk/conditions/anaphylaxis/')],
    },
    {
        'slug': 'meningitis-warning-pattern',
        'name_ar': 'نمط تحذيري قد يتوافق مع التهاب السحايا',
        'name_en': 'Meningitis warning pattern',
        'category': 'neurological',
        'severity': 'high',
        'symptoms': {
            'stiff-neck': 1.0, 'fever': .85, 'severe-headache': .75,
            'headache': .55, 'non-blanching-rash': .9,
            'vomiting': .45, 'light-sensitivity': .45, 'seizure': .35,
        },
        'description_ar': 'الحمى مع تيبس الرقبة أو صداع شديد أو طفح لا يختفي بالضغط قد تكون علامات مرض خطير يحتاج تقييمًا عاجلًا.',
        'description_en': 'Fever with a stiff neck, severe headache, or a non-blanching rash can be signs of a serious illness needing urgent assessment.',
        'risk_ar': 'قد يرتبط بعدوى تصيب الأغشية المحيطة بالدماغ والحبل الشوكي.',
        'risk_en': 'It can be associated with infection of the membranes around the brain and spinal cord.',
        'causes_ar': 'أسباب فيروسية أو بكتيرية وغيرها ممكنة، ولا يمكن تمييزها آمنًا دون تقييم طبي.',
        'causes_en': 'Viral, bacterial, and other causes are possible and cannot be safely distinguished without medical assessment.',
        'next_ar': 'اطلب تقييمًا طبيًا عاجلًا عند هذا النمط من الأعراض.',
        'next_en': 'Seek urgent medical assessment for this symptom pattern.',
        'red_ar': 'طفح لا يختفي بالضغط، تشنج، تدهور الوعي، تيبس شديد بالرقبة أو صداع شديد متزايد علامات طارئة.',
        'red_en': 'A non-blanching rash, seizure, reduced consciousness, marked neck stiffness, or worsening severe headache are emergency signs.',
        'sources': [('nhs', 'التهاب السحايا — NHS', 'Meningitis — NHS', 'https://www.nhs.uk/conditions/meningitis/')],
    },
    {
        'slug': 'seizure-episode-pattern',
        'name_ar': 'نوبة تشنجية — تحتاج تقييمًا للسبب',
        'name_en': 'Seizure episode — cause needs assessment',
        'category': 'neurological',
        'severity': 'high',
        'symptoms': {'seizure': 1.0, 'loss-of-consciousness': .55, 'headache': .25, 'confusion': .45},
        'description_ar': 'النوبة التشنجية عرض يحتاج تقييمًا طبيًا لتحديد السبب، خصوصًا إذا كانت الأولى أو استمرت أو تكررت.',
        'description_en': 'A seizure needs medical assessment to identify the cause, especially if it is a first episode, prolonged, or recurrent.',
        'risk_ar': 'الأسباب متعددة وتشمل حالات عصبية أو أيضية أو دوائية وغيرها.',
        'risk_en': 'Causes are varied and can include neurological, metabolic, medication-related, and other conditions.',
        'causes_ar': 'لا يمكن تحديد السبب من الأعراض وحدها.',
        'causes_en': 'The cause cannot be established from symptoms alone.',
        'next_ar': 'اطلب تقييمًا طبيًا عاجلًا للنوبة الأولى أو الطويلة أو المتكررة أو إذا لم يعد الشخص لوعيه الطبيعي.',
        'next_en': 'Seek urgent medical assessment for a first, prolonged, or repeated seizure, or if normal consciousness does not return.',
        'red_ar': 'استمرار النوبة، تكرارها دون تعافٍ، إصابة خطرة أو صعوبة تنفس تستدعي الطوارئ.',
        'red_en': 'A prolonged seizure, repeated seizures without recovery, serious injury, or breathing difficulty requires emergency care.',
        'sources': [('ninds', 'الصرع والنوبات — NINDS', 'Epilepsy and seizures — NINDS', 'https://www.ninds.nih.gov/health-information/disorders/epilepsy-and-seizures')],
    },
    {
        'slug': 'syncope-fainting-pattern',
        'name_ar': 'إغماء أو فقدان وعي عابر — يحتاج تقييمًا للسبب',
        'name_en': 'Fainting or transient loss of consciousness',
        'category': 'cardiovascular',
        'severity': 'moderate',
        'symptoms': {'loss-of-consciousness': 1.0, 'dizziness': .75, 'sweating': .45, 'palpitations': .3, 'general-weakness': .25},
        'description_ar': 'الإغماء له أسباب عديدة، من البسيطة إلى المهمة، ويحتاج تقييمًا خصوصًا إذا تكرر أو صاحبه ألم صدر أو خفقان.',
        'description_en': 'Fainting has many possible causes, from benign to important, and needs assessment especially if recurrent or associated with chest pain or palpitations.',
        'risk_ar': 'قد يرتبط بانخفاض ضغط الدم أو الجفاف أو أسباب قلبية أو عصبية وغيرها.',
        'risk_en': 'It can be related to low blood pressure, dehydration, cardiac, neurological, or other causes.',
        'causes_ar': 'الأسباب متعددة ولا يمكن تحديدها بدقة دون سياق وفحص.',
        'causes_en': 'Causes are varied and cannot be determined accurately without context and examination.',
        'next_ar': 'اطلب تقييمًا إذا تكرر الإغماء أو حدث أثناء الجهد أو ترافق مع ألم صدر أو خفقان أو إصابة.',
        'next_en': 'Seek assessment if fainting recurs, happens during exertion, or occurs with chest pain, palpitations, or injury.',
        'red_ar': 'الإغماء مع ألم صدر أو ضيق تنفس أو ضعف جهة واحدة أو عدم استعادة الوعي الطبيعي يستدعي الطوارئ.',
        'red_en': 'Fainting with chest pain, breathing difficulty, one-sided weakness, or failure to regain normal consciousness requires emergency care.',
        'sources': [('nhs', 'الإغماء — NHS', 'Fainting — NHS', 'https://www.nhs.uk/conditions/fainting/')],
    },
]
