"""V62 common-topic expansion for SymptoSense.

Adds high-frequency everyday symptom presentations to the symptom engine using
reviewed NHS/ACOG references. Educational and non-diagnostic.
"""

EXTRA_SOURCES_V4 = [
    (
        "acog", "ACOG", "American College of Obstetricians and Gynecologists",
        "https://www.acog.org/", "clinical_guideline_body", 24,
        "هيئة مهنية متخصصة في صحة النساء والتوليد تنشر إرشادات ومعلومات تثقيفية مبنية على الدليل.",
        "A professional obstetrics and gynecology body publishing evidence-based guidance and patient education.",
    ),
]

EXTRA_SYMPTOMS_V4 = [
    ("knee-pain", "ألم الركبة", "Knee pain", "pain", ["ركبتي توجع", "وجع الركبه", "الم بالركبة", "وجع الركبة"], ["knee pain", "knee ache"]),
    ("shoulder-pain", "ألم الكتف", "Shoulder pain", "pain", ["كتفي يوجع", "وجع الكتف", "الم بالكتف"], ["shoulder pain", "shoulder ache"]),
    ("heavy-periods", "دورة شهرية غزيرة", "Heavy periods", "general", ["دورة غزيرة", "دوره غزيره", "غزارة الدورة", "الدورة غزيرة"], ["heavy periods", "heavy menstrual bleeding"]),
    ("sore-throat", "ألم الحلق", "Sore throat", "general", ["حلقي يوجع", "وجع الحلق", "الم بالحلق", "حلقي يؤلمني"], ["sore throat", "throat pain"]),
    ("premenstrual-pattern", "أعراض قبل الدورة", "Premenstrual symptoms", "general", ["اعراض قبل الدورة", "أعراض قبل الدورة", "قبل الدورة اتعب", "تعب قبل الدورة", "pms"], ["premenstrual symptoms", "pms symptoms"]),
    ("indigestion", "عسر الهضم", "Indigestion", "digestive", ["عسر هضم", "سوء هضم", "ثقل بعد الاكل", "تخمه بعد الاكل"], ["indigestion", "dyspepsia"]),
    ("lower-back-pain", "ألم أسفل الظهر", "Lower back pain", "pain", ["الم اسفل الظهر", "وجع اسفل ظهري", "ظهري من تحت يوجع"], ["lower back pain", "low back ache"]),
    ("pain-after-activity", "ألم يزداد بعد الحركة أو النشاط", "Pain worse after activity", "pain", ["الالم يزيد بعد الحركة", "يوجعني بعد المشي", "بعد النشاط يزيد الالم"], ["pain worse after activity", "pain after walking"]),
    ("eyelid-lump", "كتلة أو حبة مؤلمة في الجفن", "Painful eyelid lump", "eye", ["حبة في الجفن", "دمل في العين", "حبة بطرف العين"], ["eyelid lump", "stye lump", "painful eyelid bump"]),
    ("ring-shaped-rash", "طفح دائري أو حلقي", "Ring-shaped rash", "skin", ["طفح دائري", "حلقة حمراء بالجلد", "بقعة دائرية تحك"], ["ring shaped rash", "circular itchy rash"]),
    ("lip-blisters", "فقاعات أو بثور مؤلمة حول الشفاه", "Painful blisters around lips", "skin", ["حبة حرارة على الشفايف", "فقاعات بالشفايف", "قرحة برد بالشفه"], ["cold sore", "lip blisters", "fever blister"]),
    ("ingrown-nail", "ظفر نامٍ داخل الجلد", "Ingrown nail", "skin", ["ظفر داخل اللحم", "الظفر داخل الجلد", "اصبع القدم حول الظفر يوجع"], ["ingrown toenail", "nail growing into skin"]),
    ("nail-discoloration", "تغير لون الظفر أو سماكته", "Nail discoloration or thickening", "skin", ["ظفري اصفر", "الظفر سميك", "لون الظفر تغير"], ["yellow nail", "thick nail", "nail discoloration"]),
    ("rough-skin-lump", "نتوء جلدي خشن صغير", "Small rough skin lump", "skin", ["ثؤلول", "حبة خشنة باليد", "نتوء جلدي خشن"], ["wart", "verruca", "rough skin lump"]),
    ("breast-tenderness", "ألم أو حساسية في الثدي", "Breast tenderness", "pain", ["الم الثدي", "ثديي يوجع قبل الدورة", "حساسية بالثدي"], ["breast pain", "breast tenderness"]),
    ("mood-swings", "تقلبات مزاجية", "Mood swings", "general", ["مزاجي يتغير قبل الدورة", "تقلب مزاج", "عصبية قبل الدورة"], ["mood swings", "irritable before period"]),
    ("vaginal-discharge", "إفرازات مهبلية متغيرة", "Changed vaginal discharge", "general", ["افرازات مهبلية", "افرازات غريبة", "تغير الافرازات"], ["vaginal discharge", "changed vaginal discharge"]),
    ("vaginal-itching", "حكة أو تهيج مهبلي", "Vaginal itching or irritation", "general", ["حكة بالمهبل", "حكة بالمنطقة الحساسة", "تهيج مهبلي"], ["vaginal itching", "vaginal irritation"]),
    ("vaginal-odor", "رائحة مهبلية غير معتادة", "Unusual vaginal odor", "general", ["ريحة افرازات قوية", "رائحة مهبلية", "ريحة سمكية"], ["vaginal odor", "fishy vaginal smell"]),
    ("anal-pain", "ألم حول فتحة الشرج", "Anal pain", "pain", ["الم فتحة الشرج", "الم وقت التبرز", "حرقان بعد التبرز"], ["anal pain", "pain when passing stool"]),
    ("bright-red-rectal-blood", "دم أحمر فاتح مع التبرز", "Bright red rectal blood", "general", ["دم احمر على المناديل", "دم بعد التبرز", "دم احمر فاتح بالبراز"], ["bright red blood after stool", "blood on toilet paper"]),
    ("burping", "تجشؤ متكرر", "Frequent burping", "digestive", ["تجشؤ", "اتجشأ كثير", "تكريع كثير"], ["burping", "belching"]),
    ("nosebleed", "نزيف من الأنف", "Nosebleed", "general", ["رعاف", "انفي ينزف", "دم من الانف"], ["nosebleed", "epistaxis", "nose bleeding"]),
    ("painful-swallowing", "ألم عند البلع", "Pain when swallowing", "pain", ["البلع يوجع", "الم لما ابلع", "حلقي يوجع وقت البلع"], ["painful swallowing", "pain when swallowing"]),
    ("scratchy-throat", "حلق جاف أو مخدوش", "Scratchy throat", "general", ["حلقي ناشف", "حكة بالحلق", "حلقي مخدوش"], ["scratchy throat", "dry throat"]),
]

EXTRA_DISEASES_V4 = [
    {
        "slug":"mechanical-low-back-pain", "name_ar":"ألم أسفل الظهر الميكانيكي", "name_en":"Mechanical low back pain", "category":"musculoskeletal", "severity":"mild",
        "symptoms":{"lower-back-pain":0.95,"back-pain":0.85,"pain-after-activity":0.55},
        "description_ar":"ألم أسفل الظهر شائع وقد يرتبط بإجهاد العضلات أو الحركة والوضعيات. وجود العرض لا يحدد السبب وحده.",
        "description_en":"Low back pain is common and may relate to muscle strain, movement, or posture. The symptom alone does not identify the cause.",
        "risk_ar":"يحتاج تقييمًا عاجلًا إذا ترافق مع ضعف شديد بالساقين أو فقد التحكم بالبول/البراز أو خدر بمنطقة العجان.",
        "risk_en":"Urgent assessment is needed with severe leg weakness, loss of bladder/bowel control, or saddle numbness.",
        "causes_ar":"شد عضلي أو إجهاد أو وضعيات وحركة متكررة، مع أسباب أخرى أقل شيوعًا.", "causes_en":"Muscle strain, overuse, posture, or other less common causes.",
        "red_ar":"ألم بعد إصابة كبيرة، ضعف عصبي جديد، أو مشاكل التحكم بالبول/البراز تحتاج رعاية عاجلة.", "red_en":"Major trauma, new neurological weakness, or bladder/bowel control problems need urgent care.",
        "next_ar":"حافظ على حركة لطيفة وتجنب الحمل المجهد، وراجع مختصًا إذا استمر الألم أو كان شديدًا.", "next_en":"Keep gently active, avoid aggravating strain, and seek review if pain persists or is severe.",
        "sources":[("nhs","ألم الظهر — NHS","Back pain — NHS","https://www.nhs.uk/conditions/back-pain/")],
    },
    {
        "slug":"common-knee-pain-pattern", "name_ar":"نمط ألم الركبة الشائع", "name_en":"Common knee pain pattern", "category":"musculoskeletal", "severity":"mild",
        "symptoms":{"knee-pain":0.95,"pain-after-activity":0.55,"joint-pain":0.35},
        "description_ar":"ألم الركبة قد ينتج عن إجهاد أو إصابة بسيطة أو أسباب مفصلية متعددة، ويحتاج السياق والفحص لتحديد السبب.",
        "description_en":"Knee pain can follow overuse, minor injury, or several joint-related causes; context and assessment are needed to identify the cause.",
        "risk_ar":"عدم القدرة على تحميل الوزن، تورم شديد، تغير شكل الركبة، أو حرارة واحمرار مع حمى يحتاج تقييمًا عاجلًا.", "risk_en":"Inability to bear weight, major swelling/deformity, or a hot red knee with fever needs urgent assessment.",
        "causes_ar":"إجهاد، إصابة، التهاب أو مشكلات مفصلية مختلفة.", "causes_en":"Overuse, injury, inflammation, or other joint problems.",
        "red_ar":"ركبة حارة ومتورمة مع حرارة عامة أو إصابة قوية تحتاج تقييمًا عاجلًا.", "red_en":"A hot swollen knee with fever or major injury needs urgent assessment.",
        "next_ar":"خفف النشاط المهيج وراقب التحسن؛ راجع مختصًا إذا لم يتحسن الألم خلال أسابيع أو كان شديدًا.", "next_en":"Reduce aggravating activity and monitor; seek review if pain is severe or does not improve over a few weeks.",
        "sources":[("nhs","ألم الركبة — NHS","Knee pain — NHS","https://www.nhs.uk/symptoms/knee-pain/")],
    },
    {
        "slug":"common-shoulder-pain-pattern", "name_ar":"نمط ألم الكتف الشائع", "name_en":"Common shoulder pain pattern", "category":"musculoskeletal", "severity":"mild",
        "symptoms":{"shoulder-pain":0.95,"pain-after-activity":0.55,"joint-pain":0.35},
        "description_ar":"ألم الكتف شائع وقد يرتبط بإجهاد الأوتار أو الجراب أو تيبس المفصل أو إصابة بسيطة.",
        "description_en":"Shoulder pain is common and may relate to tendon/bursa irritation, stiffness, or minor injury.",
        "risk_ar":"ألم مفاجئ شديد مع عدم القدرة على تحريك الذراع أو تغير شكل الكتف يحتاج تقييمًا عاجلًا.", "risk_en":"Sudden severe pain with inability to move the arm or shoulder deformity needs urgent assessment.",
        "causes_ar":"إجهاد متكرر، التهاب الأوتار/الجراب، تيبس أو إصابة.", "causes_en":"Overuse, tendon/bursa irritation, stiffness, or injury.",
        "red_ar":"ألم شديد بعد إصابة أو ضعف مفاجئ بالذراع يستدعي تقييمًا عاجلًا.", "red_en":"Severe pain after injury or sudden arm weakness needs urgent assessment.",
        "next_ar":"استمر بحركة لطيفة وتجنب ما يزيد الألم، وراجع مختصًا إذا لم يبدأ التحسن خلال نحو أسبوعين.", "next_en":"Keep the shoulder gently moving, avoid aggravating activity, and seek review if improvement does not begin within about two weeks.",
        "sources":[("nhs","ألم الكتف — NHS","Shoulder pain — NHS","https://www.nhs.uk/symptoms/shoulder-pain/")],
    },
    {
        "slug":"stye", "name_ar":"شعيرة أو دمل الجفن", "name_en":"Stye", "category":"eye", "severity":"mild",
        "symptoms":{"eyelid-lump":0.95,"eye-pain":0.45,"eye-redness":0.35},
        "description_ar":"الشعيرة كتلة صغيرة مؤلمة على الجفن غالبًا بسبب التهاب بصيلة رمش أو غدة بالجفن.", "description_en":"A stye is a small painful eyelid lump, often from infection of an eyelash follicle or eyelid gland.",
        "risk_ar":"إذا أثرت في الرؤية أو انتشر التورم والاحمرار حول العين يلزم تقييم سريع.", "risk_en":"Vision change or spreading redness/swelling around the eye needs prompt assessment.",
        "causes_ar":"عدوى موضعية في بصيلة رمش أو غدة بالجفن.", "causes_en":"Localized infection of an eyelash follicle or eyelid gland.",
        "red_ar":"تغير الرؤية أو تورم شديد ممتد حول العين يحتاج تقييمًا عاجلًا.", "red_en":"Vision change or severe spreading swelling needs urgent assessment.",
        "next_ar":"كمادات دافئة ونظافة اليدين، ولا تحاول عصرها. راجع مختصًا إذا لم تتحسن أو كانت شديدة.", "next_en":"Use warm compresses and hand hygiene; do not squeeze it. Seek review if severe or not improving.",
        "sources":[("nhs","الشعيرة — NHS","Stye — NHS","https://www.nhs.uk/conditions/stye/")],
    },
    {
        "slug":"ringworm", "name_ar":"السعفة (فطريات جلدية حلقية)", "name_en":"Ringworm", "category":"skin", "severity":"mild",
        "symptoms":{"ring-shaped-rash":0.95,"itching":0.65,"dry-skin":0.3},
        "description_ar":"السعفة عدوى فطرية شائعة قد تسبب طفحًا دائريًا متقشرًا أو حاكًا، وليست بسبب ديدان.", "description_en":"Ringworm is a common fungal infection that can cause a circular, scaly, itchy rash; it is not caused by worms.",
        "risk_ar":"انتشار واسع أو إصابة فروة الرأس أو ضعف المناعة يحتاج تقييمًا طبيًا.", "risk_en":"Widespread disease, scalp involvement, or immunocompromise needs medical review.",
        "causes_ar":"فطريات جلدية تنتقل بالتماس المباشر أو الأسطح الملوثة.", "causes_en":"Dermatophyte fungi spread through direct contact or contaminated surfaces.",
        "red_ar":"علامات عدوى ثانوية شديدة مثل ألم متزايد أو قيح أو حمى تحتاج تقييمًا.", "red_en":"Signs of significant secondary infection such as worsening pain, pus, or fever need assessment.",
        "next_ar":"استشر الصيدلي/الطبيب للعلاج المناسب، خاصة لفروة الرأس أو إذا لم يتحسن الطفح.", "next_en":"Ask a pharmacist/clinician about treatment, especially for scalp involvement or persistent rash.",
        "sources":[("nhs","السعفة — NHS","Ringworm — NHS","https://www.nhs.uk/conditions/ringworm/")],
    },
    {
        "slug":"cold-sore", "name_ar":"قرحة البرد حول الشفاه", "name_en":"Cold sore", "category":"skin", "severity":"mild",
        "symptoms":{"lip-blisters":0.95,"burning-sensation":0.45,"itching":0.35},
        "description_ar":"قرحة البرد غالبًا تبدأ بوخز أو حكة ثم تظهر فقاعات مؤلمة حول الشفاه أو الوجه.", "description_en":"Cold sores often begin with tingling/itching followed by painful blisters around the lips or face.",
        "risk_ar":"إصابة قرب العين أو ضعف المناعة أو قرح كبيرة جدًا تحتاج تقييمًا طبيًا.", "risk_en":"Eye-area involvement, immunocompromise, or very large sores needs medical assessment.",
        "causes_ar":"فيروس الهربس البسيط الذي قد ينشط من وقت لآخر.", "causes_en":"Herpes simplex virus reactivation.",
        "red_ar":"ألم أو احمرار بالعين مع قرح الوجه يحتاج تقييمًا عاجلًا.", "red_en":"Eye pain/redness with facial sores needs urgent assessment.",
        "next_ar":"تجنب لمس القرحة ومشاركة الأدوات الشخصية، وراجع مختصًا إذا كانت شديدة أو متكررة أو قرب العين.", "next_en":"Avoid touching the sore or sharing personal items; seek review if severe, recurrent, or near the eye.",
        "sources":[("nhs","قرح البرد — NHS","Cold sores — NHS","https://www.nhs.uk/conditions/cold-sores/")],
    },
    {
        "slug":"ingrown-toenail", "name_ar":"ظفر القدم النامي للداخل", "name_en":"Ingrown toenail", "category":"skin", "severity":"mild",
        "symptoms":{"ingrown-nail":0.95,"big-toe-pain":0.55,"swelling":0.35},
        "description_ar":"الظفر النامي للداخل يحدث عندما تدخل حافة الظفر في الجلد وقد يسبب ألمًا واحمرارًا وتورمًا.", "description_en":"An ingrown toenail occurs when the nail edge grows into the skin, causing pain, redness, and swelling.",
        "risk_ar":"قيح أو احمرار منتشر أو حمى، خصوصًا مع السكري، يحتاج تقييمًا طبيًا.", "risk_en":"Pus, spreading redness, or fever, especially with diabetes, needs medical review.",
        "causes_ar":"قص الظفر بشكل غير مناسب أو أحذية ضيقة أو شكل الظفر.", "causes_en":"Improper nail trimming, tight footwear, or nail shape.",
        "red_ar":"انتشار التهاب بالقدم أو حرارة عامة يحتاج تقييمًا سريعًا.", "red_en":"Spreading foot infection or systemic fever needs prompt assessment.",
        "next_ar":"حافظ على القدم نظيفة وجافة وتجنب قص الزوايا بعمق؛ راجع مختصًا إذا استمر الألم أو ظهر التهاب.", "next_en":"Keep the foot clean/dry and avoid digging into nail corners; seek review for persistent pain or infection.",
        "sources":[("nhs","الظفر النامي للداخل — NHS","Ingrown toenail — NHS","https://www.nhs.uk/conditions/ingrown-toenail/")],
    },
    {
        "slug":"fungal-nail-infection", "name_ar":"فطريات الأظافر", "name_en":"Fungal nail infection", "category":"skin", "severity":"mild",
        "symptoms":{"nail-discoloration":0.95,"itch-between-toes":0.25},
        "description_ar":"فطريات الأظافر قد تجعل الظفر سميكًا أو متغير اللون أو هشًا، وتكثر مع الرطوبة أو فطريات القدم.", "description_en":"Fungal nail infection can make nails thick, discolored, or brittle and is more common with damp feet or athlete's foot.",
        "risk_ar":"ألم شديد أو التهاب حول الظفر أو وجود سكري يحتاج تقييمًا مبكرًا.", "risk_en":"Severe pain, surrounding infection, or diabetes warrants early assessment.",
        "causes_ar":"عدوى فطرية في الظفر، وقد تمتد من فطريات القدم.", "causes_en":"Fungal nail infection, sometimes spreading from athlete's foot.",
        "red_ar":"احمرار منتشر أو قيح أو حمى تحتاج تقييمًا طبيًا.", "red_en":"Spreading redness, pus, or fever needs medical assessment.",
        "next_ar":"حافظ على القدم جافة ونظيفة واستشر الصيدلي أو الطبيب إذا لم تتحسن أو كان الظفر شديد التأثر.", "next_en":"Keep feet clean/dry and seek pharmacist/medical advice if persistent or extensive.",
        "sources":[("nhs","فطريات الأظافر — NHS","Fungal nail infection — NHS","https://www.nhs.uk/conditions/fungal-nail-infection/")],
    },
    {
        "slug":"warts-verrucas", "name_ar":"الثآليل الجلدية", "name_en":"Warts and verrucas", "category":"skin", "severity":"mild",
        "symptoms":{"rough-skin-lump":0.95,"itching":0.2},
        "description_ar":"الثآليل نتوءات جلدية صغيرة وخشنة غالبًا، وقد تظهر في اليدين أو القدمين وتختفي أحيانًا تلقائيًا مع الوقت.", "description_en":"Warts are small rough skin lumps, often on hands or feet, and may resolve on their own over time.",
        "risk_ar":"نزف الثؤلول أو تغير شكله أو وجوده على الوجه/الأعضاء التناسلية يحتاج تقييمًا.", "risk_en":"Bleeding, change in appearance, or facial/genital lesions need medical review.",
        "causes_ar":"فيروسات من عائلة HPV تنتقل عبر الجلد أو الأسطح الملوثة.", "causes_en":"HPV viruses transmitted through skin contact or contaminated surfaces.",
        "red_ar":"تغير سريع أو نزف غير معتاد في كتلة جلدية يحتاج فحصًا.", "red_en":"Rapid change or unusual bleeding from a skin lump needs assessment.",
        "next_ar":"تجنب العبث بها واستشر الصيدلي/الطبيب إذا كانت مؤلمة أو متكررة أو تغيرت.", "next_en":"Avoid picking and seek pharmacist/medical advice if painful, recurrent, or changing.",
        "sources":[("nhs","الثآليل — NHS","Warts and verrucas — NHS","https://www.nhs.uk/conditions/warts-and-verrucas/")],
    },
    {
        "slug":"premenstrual-syndrome-pattern", "name_ar":"أعراض ما قبل الدورة (PMS)", "name_en":"Premenstrual syndrome pattern", "category":"womens_health", "severity":"mild",
        "symptoms":{"premenstrual-pattern":1.0,"mood-swings":0.15,"breast-tenderness":0.15,"bloating":0.12,"headache":0.1,"fatigue":0.1,"menstrual-cramps":0.1},
        "description_ar":"PMS هو نمط أعراض جسدية ومزاجية يتكرر قبل الدورة ويخف بعد بدايتها، وقد يختلف من شهر لآخر.", "description_en":"PMS is a recurring pattern of physical and mood symptoms before a period that eases after menstruation begins.",
        "risk_ar":"تدهور مزاج شديد أو أفكار إيذاء النفس تحتاج مساعدة عاجلة.", "risk_en":"Severe mood deterioration or self-harm thoughts require urgent help.",
        "causes_ar":"تغيرات هرمونية مرتبطة بالدورة مع اختلاف الاستجابة بين الأشخاص.", "causes_en":"Cycle-related hormonal changes with individual variation.",
        "red_ar":"أفكار إيذاء النفس أو أعراض شديدة جدًا تستدعي مساعدة فورية.", "red_en":"Self-harm thoughts or very severe symptoms require immediate help.",
        "next_ar":"تتبعي الأعراض مع موعد الدورة لعدة دورات وراجعي مختصًا إذا أثرت على حياتك اليومية.", "next_en":"Track symptoms against cycle timing and seek review if they interfere with daily life.",
        "sources":[("acog","متلازمة ما قبل الدورة — ACOG","Premenstrual syndrome — ACOG","https://www.acog.org/womens-health/faqs/premenstrual-syndrome")],
    },
    {
        "slug":"heavy-menstrual-bleeding-pattern", "name_ar":"غزارة الدورة الشهرية", "name_en":"Heavy menstrual bleeding pattern", "category":"womens_health", "severity":"moderate",
        "symptoms":{"heavy-periods":0.98,"fatigue":0.4,"dizziness":0.3,"shortness-of-breath":0.25,"menstrual-cramps":0.35},
        "description_ar":"غزارة الدورة قد تعني نزفًا أكثر أو أطول من المعتاد وقد تؤثر في النشاط اليومي أو تسبب فقر الدم.", "description_en":"Heavy menstrual bleeding means more or longer bleeding than usual and can affect daily life or contribute to anemia.",
        "risk_ar":"نزيف شديد جدًا مع دوخة أو إغماء أو ضيق نفس يحتاج تقييمًا عاجلًا.", "risk_en":"Very heavy bleeding with dizziness, fainting, or shortness of breath needs urgent assessment.",
        "causes_ar":"قد تكون دون سبب واضح أو ترتبط باضطرابات هرمونية أو رحمية أو نزفية أو أدوية.", "causes_en":"Possible causes include hormonal, uterine, bleeding-related, medication-related, or no clear cause.",
        "red_ar":"نزف غزير سريع أو إغماء أو ضعف شديد يحتاج رعاية عاجلة.", "red_en":"Rapid heavy bleeding, fainting, or marked weakness needs urgent care.",
        "next_ar":"راجعي مختصًا إذا كانت الدورة تؤثر على حياتك أو استمرت أكثر من المعتاد أو ترافقت مع تعب واضح.", "next_en":"Seek review if bleeding affects daily life, lasts longer than usual, or causes significant fatigue.",
        "sources":[("acog","غزارة نزف الدورة — ACOG","Heavy menstrual bleeding — ACOG","https://www.acog.org/womens-health/faqs/heavy-menstrual-bleeding")],
    },
    {
        "slug":"irregular-periods-pattern", "name_ar":"عدم انتظام الدورة", "name_en":"Irregular periods pattern", "category":"womens_health", "severity":"mild",
        "symptoms":{"irregular-periods":0.98,"fatigue":0.2,"weight-gain":0.12,"weight-loss":0.12},
        "description_ar":"تغير الفاصل بين الدورات أو تغير النمط المعتاد قد يحدث لأسباب طبيعية أو هرمونية أو مرتبطة بالوزن أو التوتر أو أدوية.", "description_en":"Changes in cycle timing can have normal, hormonal, weight-related, stress-related, or medication-related causes.",
        "risk_ar":"نزيف شديد أو ألم حوض حاد أو احتمال حمل مع ألم شديد يحتاج تقييمًا عاجلًا.", "risk_en":"Heavy bleeding, severe pelvic pain, or possible pregnancy with severe pain needs urgent assessment.",
        "causes_ar":"البلوغ، الاقتراب من سن اليأس، الحمل، التوتر، تغير الوزن، التمارين الشديدة، وسائل منع الحمل أو حالات هرمونية.", "causes_en":"Puberty, perimenopause, pregnancy, stress, weight change, intense exercise, contraception, or hormonal conditions.",
        "red_ar":"نزف شديد أو ألم حوض شديد أو إغماء يحتاج رعاية عاجلة.", "red_en":"Heavy bleeding, severe pelvic pain, or fainting needs urgent care.",
        "next_ar":"تتبعي مواعيد الدورة وراجعي مختصًا إذا تغير نمطك المعتاد أو طال الانقطاع أو ظهرت أعراض أخرى.", "next_en":"Track cycle dates and seek review if your usual pattern changes, periods stop for a prolonged time, or other symptoms appear.",
        "sources":[("nhs","عدم انتظام الدورة — NHS","Irregular periods — NHS","https://www.nhs.uk/symptoms/irregular-periods/")],
    },
    {
        "slug":"vaginal-thrush-pattern", "name_ar":"نمط فطريات المهبل", "name_en":"Vaginal thrush pattern", "category":"womens_health", "severity":"mild",
        "symptoms":{"vaginal-itching":0.9,"vaginal-discharge":0.75,"painful-urination":0.35},
        "description_ar":"الفطريات المهبلية قد تسبب حكة وتهيجًا مع إفرازات بيضاء سميكة غالبًا دون رائحة قوية، لكن الأعراض قد تشبه أسبابًا أخرى.", "description_en":"Vaginal thrush can cause itching/irritation with thick white discharge, often without strong odor, but similar symptoms can have other causes.",
        "risk_ar":"أعراض أول مرة أو أثناء الحمل أو تكرارها كثيرًا أو ألم حوض/حمى يحتاج تقييمًا طبيًا.", "risk_en":"First-time symptoms, pregnancy, frequent recurrence, pelvic pain, or fever need medical review.",
        "causes_ar":"زيادة نمو فطر Candida بعد تغير توازن البيئة الطبيعية.", "causes_en":"Candida overgrowth after a change in the normal local balance.",
        "red_ar":"حمى أو ألم حوض شديد أو أعراض عامة شديدة ليست نموذجية وتحتاج تقييمًا.", "red_en":"Fever, severe pelvic pain, or significant systemic symptoms are not typical and need assessment.",
        "next_ar":"راجعي مختصًا إذا كانت أول مرة أو لم تكوني متأكدة من السبب، وتجنبي التشخيص الذاتي عند وجود رائحة قوية أو ألم حوض.", "next_en":"Seek review if this is the first episode or the cause is uncertain, especially with strong odor or pelvic pain.",
        "sources":[("nhs","الفطريات — NHS","Thrush — NHS","https://www.nhs.uk/conditions/thrush-in-men-and-women/"),("acog","التهاب المهبل — ACOG","Vaginitis — ACOG","https://www.acog.org/womens-health/faqs/vaginitis")],
    },
    {
        "slug":"bacterial-vaginosis-pattern", "name_ar":"نمط اختلال البكتيريا المهبلية (BV)", "name_en":"Bacterial vaginosis pattern", "category":"womens_health", "severity":"mild",
        "symptoms":{"vaginal-discharge":0.85,"vaginal-odor":0.95},
        "description_ar":"BV سبب شائع لتغير الإفرازات ورائحتها، وغالبًا تكون الإفرازات رقيقة مع رائحة قوية. التشخيص يحتاج تقييمًا لأن الأسباب تتشابه.", "description_en":"BV is a common cause of changed discharge and odor, often thin discharge with a strong smell. Assessment is needed because causes overlap.",
        "risk_ar":"الحمل أو ألم الحوض أو حرارة أو نزيف غير معتاد يستدعي تقييمًا طبيًا.", "risk_en":"Pregnancy, pelvic pain, fever, or unusual bleeding warrants medical assessment.",
        "causes_ar":"اختلال توازن البكتيريا الطبيعية في المهبل.", "causes_en":"An imbalance in normal vaginal bacteria.",
        "red_ar":"ألم حوض شديد أو حمى أو نزيف غير معتاد يحتاج تقييمًا عاجلًا.", "red_en":"Severe pelvic pain, fever, or unusual bleeding needs prompt assessment.",
        "next_ar":"راجعي مختصًا للتأكد من السبب، خصوصًا في الحمل أو إذا كانت الأعراض جديدة.", "next_en":"Seek clinical assessment to confirm the cause, especially in pregnancy or with new symptoms.",
        "sources":[("nhs","اختلال البكتيريا المهبلية — NHS","Bacterial vaginosis — NHS","https://www.nhs.uk/conditions/bacterial-vaginosis/"),("acog","التهاب المهبل — ACOG","Vaginitis — ACOG","https://www.acog.org/womens-health/faqs/vaginitis")],
    },
    {
        "slug":"anal-fissure", "name_ar":"شق شرجي", "name_en":"Anal fissure", "category":"digestive", "severity":"mild",
        "symptoms":{"anal-pain":0.95,"bright-red-rectal-blood":0.75,"constipation":0.35,"straining-stool":0.4},
        "description_ar":"الشق الشرجي تمزق صغير قد يسبب ألمًا حادًا أثناء التبرز وحرقانًا بعده مع دم أحمر فاتح.", "description_en":"An anal fissure is a small tear that can cause sharp pain during bowel movements, burning afterward, and bright red blood.",
        "risk_ar":"نزيف غزير أو براز أسود أو دوخة/إغماء يحتاج تقييمًا عاجلًا.", "risk_en":"Heavy bleeding, black stool, dizziness, or fainting needs urgent assessment.",
        "causes_ar":"إمساك أو براز صلب أو إجهاد أثناء التبرز، مع أسباب أخرى أقل شيوعًا.", "causes_en":"Constipation, hard stool, or straining, with other less common causes.",
        "red_ar":"نزيف كبير أو ألم شديد مستمر أو علامات عدوى تحتاج تقييمًا.", "red_en":"Large bleeding, persistent severe pain, or infection signs need assessment.",
        "next_ar":"حافظ على ليونة البراز بالسوائل والألياف، وراجع مختصًا إذا لم يتحسن أو تكرر النزيف.", "next_en":"Keep stools soft with fluids/fiber and seek review if it does not improve or bleeding recurs.",
        "sources":[("nhs","الشق الشرجي — NHS","Anal fissure — NHS","https://www.nhs.uk/conditions/anal-fissure/")],
    },
    {
        "slug":"functional-dyspepsia-pattern", "name_ar":"عسر الهضم", "name_en":"Indigestion pattern", "category":"digestive", "severity":"mild",
        "symptoms":{"indigestion":1.0,"heartburn":0.15,"bloating":0.12,"nausea":0.1,"burping":0.15,"early-satiety":0.1,"upper-abdominal-burning":0.12},
        "description_ar":"عسر الهضم قد يظهر كحرقة أو امتلاء وانتفاخ وغثيان وتجشؤ، خصوصًا بعد الطعام أو الشراب.", "description_en":"Indigestion can cause heartburn, fullness, bloating, nausea, and burping, often after eating or drinking.",
        "risk_ar":"ألم صدر شديد أو قيء دموي أو براز أسود أو فقد وزن غير مبرر يحتاج تقييمًا عاجلًا/مبكرًا.", "risk_en":"Severe chest pain, vomiting blood, black stool, or unexplained weight loss needs urgent/early assessment.",
        "causes_ar":"ارتجاع حمضي أو وجبات كبيرة أو بعض الأطعمة/المشروبات أو أدوية، مع أسباب أخرى.", "causes_en":"Acid reflux, large meals, certain foods/drinks, medicines, or other causes.",
        "red_ar":"قيء دموي أو براز أسود أو ألم شديد مفاجئ يحتاج رعاية عاجلة.", "red_en":"Vomiting blood, black stool, or sudden severe pain needs urgent care.",
        "next_ar":"راقب ارتباط الأعراض بالطعام وراجع مختصًا إذا كانت متكررة أو مستمرة أو تزداد.", "next_en":"Track relation to meals and seek review if symptoms are recurrent, persistent, or worsening.",
        "sources":[("nhs","عسر الهضم — NHS","Indigestion — NHS","https://www.nhs.uk/conditions/indigestion/")],
    },
    {
        "slug":"dry-mouth-pattern", "name_ar":"جفاف الفم", "name_en":"Dry mouth pattern", "category":"general", "severity":"mild",
        "symptoms":{"dry-mouth":0.98,"increased-thirst":0.35},
        "description_ar":"جفاف الفم شائع وقد يرتبط بالجفاف أو بعض الأدوية أو التنفس من الفم أو القلق، وأحيانًا حالات صحية أخرى.", "description_en":"Dry mouth is common and may relate to dehydration, medicines, mouth breathing, anxiety, or other health conditions.",
        "risk_ar":"صعوبة بلع شديدة أو جفاف شديد مع قلة بول أو دوخة واضحة يحتاج تقييمًا.", "risk_en":"Severe swallowing difficulty or marked dehydration with reduced urination/dizziness needs assessment.",
        "causes_ar":"الجفاف، أدوية، التنفس من الفم ليلًا، القلق، وأسباب أخرى.", "causes_en":"Dehydration, medicines, mouth breathing at night, anxiety, and other causes.",
        "red_ar":"جفاف شديد مع علامات جفاف عام يحتاج تقييمًا طبيًا.", "red_en":"Severe dry mouth with systemic dehydration signs needs medical assessment.",
        "next_ar":"اشرب سوائل بانتظام وراجع الأدوية مع مختص، واطلب تقييمًا إذا استمر الجفاف أو ترافق مع عطش وتبول متكرر.", "next_en":"Sip fluids regularly, review medicines with a professional, and seek assessment if persistent or accompanied by excessive thirst/urination.",
        "sources":[("nhs","جفاف الفم — NHS","Dry mouth — NHS","https://www.nhs.uk/symptoms/dry-mouth/")],
    },
    {
        "slug":"nosebleed-pattern", "name_ar":"الرعاف (نزيف الأنف)", "name_en":"Nosebleed pattern", "category":"general", "severity":"mild",
        "symptoms":{"nosebleed":0.98,"dizziness":0.15},
        "description_ar":"الرعاف شائع وغالبًا بسيط، وقد يحدث مع جفاف الأنف أو العبث به أو إصابة خفيفة أو أسباب أخرى.", "description_en":"Nosebleeds are common and often minor, occurring with nasal dryness, picking, minor injury, or other causes.",
        "risk_ar":"نزيف يستمر أكثر من 10–15 دقيقة رغم الضغط، أو نزيف غزير، أو بعد إصابة رأس، أو مع ضعف/دوخة يحتاج رعاية عاجلة.", "risk_en":"Bleeding lasting over 10–15 minutes despite pressure, heavy bleeding, head injury, weakness, or dizziness needs urgent care.",
        "causes_ar":"جفاف وتهيج الأنف أو إصابة بسيطة أو أدوية/اضطرابات نزف في بعض الحالات.", "causes_en":"Nasal dryness/irritation, minor injury, or sometimes medicines/bleeding disorders.",
        "red_ar":"نزيف غزير أو مستمر مع دوخة أو بعد ضربة للرأس يحتاج تقييمًا عاجلًا.", "red_en":"Heavy/persistent bleeding with dizziness or after head injury needs urgent assessment.",
        "next_ar":"اجلس للأمام واضغط على الجزء اللين من الأنف باستمرار، واطلب مساعدة إذا لم يتوقف أو تكرر كثيرًا.", "next_en":"Sit forward and apply continuous pressure to the soft part of the nose; seek help if it does not stop or recurs often.",
        "sources":[("nhs","الرعاف — NHS","Nosebleed — NHS","https://www.nhs.uk/conditions/nosebleed/")],
    },
    {
        "slug":"breast-pain-pattern", "name_ar":"ألم الثدي", "name_en":"Breast pain pattern", "category":"womens_health", "severity":"mild",
        "symptoms":{"breast-tenderness":0.95,"mood-swings":0.15},
        "description_ar":"ألم الثدي شائع وغالبًا يرتبط بتغيرات الدورة، لكنه قد يرتبط أيضًا بإصابة أو دواء أو حالات أخرى.", "description_en":"Breast pain is common and often linked to menstrual changes, but can also relate to injury, medicines, or other conditions.",
        "risk_ar":"كتلة صلبة ثابتة، تغير شكل الثدي، إفراز دموي من الحلمة، أو احمرار وسخونة مع حرارة يحتاج تقييمًا سريعًا.", "risk_en":"A fixed hard lump, breast-shape change, bloody nipple discharge, or red hot breast with fever needs prompt assessment.",
        "causes_ar":"تغيرات الدورة، إصابات الرقبة/الكتف/الصدر، أدوية، حمل أو التهاب في بعض الحالات.", "causes_en":"Cycle changes, neck/shoulder/chest strain, medicines, pregnancy, or inflammation in some cases.",
        "red_ar":"كتلة جديدة ثابتة أو تغير الجلد/الحلمة أو حرارة مع احمرار شديد يحتاج تقييمًا سريعًا.", "red_en":"A new fixed lump, skin/nipple change, or fever with marked redness needs prompt assessment.",
        "next_ar":"راقبي ارتباط الألم بالدورة وراجعي مختصًا إذا لم يتحسن أو ظهرت أي علامة جديدة في الثدي.", "next_en":"Track relation to the cycle and seek review if pain does not improve or any new breast change appears.",
        "sources":[("nhs","ألم الثدي — NHS","Breast pain — NHS","https://www.nhs.uk/symptoms/breast-pain/")],
    },
    {
        "slug":"simple-sore-throat-pattern", "name_ar":"التهاب أو ألم الحلق الشائع", "name_en":"Common sore throat pattern", "category":"respiratory", "severity":"mild",
        "symptoms":{"sore-throat":0.95,"painful-swallowing":0.65,"scratchy-throat":0.6,"cough":0.25,"fever":0.3,"swollen-lymph-nodes":0.25},
        "description_ar":"ألم الحلق شائع وغالبًا يرتبط بعدوى فيروسية أو تهيج، وقد يصاحبه ألم عند البلع أو جفاف أو سعال بسيط.", "description_en":"Sore throat is common and often related to viral infection or irritation, with painful swallowing, scratchiness, or mild cough.",
        "risk_ar":"صعوبة التنفس أو عدم القدرة على البلع أو سيلان اللعاب أو تدهور سريع يحتاج طوارئ.", "risk_en":"Breathing difficulty, inability to swallow, drooling, or rapid deterioration needs emergency care.",
        "causes_ar":"نزلات البرد والإنفلونزا والتهاب اللوز أو الحنجرة والتدخين/التهيج، وأحيانًا عدوى بكتيرية.", "causes_en":"Colds/flu, tonsillitis/laryngitis, smoke/irritation, and sometimes bacterial infection.",
        "red_ar":"ضيق تنفس أو عدم القدرة على البلع أو أعراض شديدة تتفاقم بسرعة تستدعي طوارئ.", "red_en":"Breathing difficulty, inability to swallow, or rapidly worsening severe symptoms require emergency care.",
        "next_ar":"السوائل والراحة قد تساعد، وراجع مختصًا إذا لم يتحسن خلال نحو أسبوع أو كان متكررًا/شديدًا.", "next_en":"Fluids and rest may help; seek review if not improving within about a week or if recurrent/severe.",
        "sources":[("nhs","ألم الحلق — NHS","Sore throat — NHS","https://www.nhs.uk/symptoms/sore-throat/")],
    },
]

EXISTING_DISEASE_SOURCE_ENRICHMENT_V4 = {}
EXISTING_DISEASE_SYMPTOM_ENRICHMENT_V4 = {}
EXTRA_RED_RULES_V4 = []
EXTRA_RED_RULE_DETAILS_V4 = {}
