"""V73 everyday-symptom expansion for SymptoSense.

Adds common, recognizable symptom presentations backed by direct NHS patient-
information references.  The entries are educational/non-diagnostic; red-flag
triage remains an independent safety layer.
"""

EXTRA_SOURCES_V5 = []

EXTRA_SYMPTOMS_V5 = [
    ("ear-blocked", "انسداد أو امتلاء الأذن", "Blocked or full ear", "ear", ["اذني مسدودة", "أذني مسدودة", "اذني مقفلة", "أذني مقفلة", "احس اذني ممتلئة", "أحس أذني ممتلئة"], ["blocked ear", "full ear", "ear feels blocked"]),
    ("hearing-loss", "ضعف أو نقص السمع", "Reduced hearing", "ear", ["سمعي خف", "السمع ضعيف", "ما اسمع كويس", "ما أسمع كويس", "نقص السمع"], ["reduced hearing", "hearing loss", "can't hear well"]),
    ("eye-floaters", "نقاط أو خيوط عائمة في النظر", "Eye floaters", "eye", ["نقاط سوداء بعيني", "اشوف ذباب", "أشوف ذباب", "خيوط تتحرك بالنظر", "ذبابات العين"], ["eye floaters", "floaters", "spots moving in vision"]),
    ("eye-flashes", "ومضات ضوئية في النظر", "Flashes in vision", "eye", ["ومضات بالعين", "فلاشات بالنظر", "اشوف وميض", "أشوف وميض", "ضوء يلمع بعيني"], ["flashes in vision", "flashing lights in eye", "eye flashes"]),
    ("hiccups", "حازوقة أو فواق", "Hiccups", "general", ["حازوقة", "شهقة متكررة", "فواق", "الحازوقة ما توقف", "الحازوقه"], ["hiccups", "hiccup", "persistent hiccups"]),
    ("bad-breath", "رائحة فم غير مستحبة", "Bad breath", "mouth", ["ريحة فمي", "رائحة فمي", "نفس ريحته", "ريحة الفم", "رائحة الفم كريهة"], ["bad breath", "halitosis", "breath smells"]),
    ("white-mouth-patches", "بقع بيضاء داخل الفم", "White patches in the mouth", "mouth", ["بقع بيضاء بالفم", "فطريات الفم", "فطريات بالفم", "لساني ابيض وما يروح", "لساني أبيض وما يروح", "طبقة بيضاء بالفم"], ["white patches in mouth", "white coating in mouth", "mouth white patches"]),
    ("mouth-pain", "ألم أو حرقة داخل الفم", "Mouth pain or soreness", "mouth", ["فمي يوجع", "حرقة بالفم", "الم داخل الفم", "ألم داخل الفم"], ["sore mouth", "mouth pain"]),
    ("altered-taste", "تغير أو طعم غير مستحب في الفم", "Altered or unpleasant taste", "mouth", ["طعم غريب بالفم", "طعم مو حلو", "طعمي متغير", "طعم سيء بالفم"], ["altered taste", "unpleasant taste", "bad taste in mouth"]),
    ("urine-leakage", "تسرب البول دون قصد", "Unintentional urine leakage", "urinary", ["يتسرب البول", "بول ينزل بدون قصد", "ينزل بول لما اكح", "ينزل بول لما أضحك", "سلس بول"], ["urine leakage", "leaking urine", "urinary incontinence"]),
    ("urinary-urgency", "إلحاح مفاجئ للتبول", "Sudden urinary urgency", "urinary", ["فجأة لازم اروح الحمام", "فجأة لازم أروح الحمام", "الحاجة للبول فجأة", "الحاح التبول", "إلحاح التبول"], ["urinary urgency", "sudden urge to pee", "urgent need to urinate"]),
    ("hot-flushes", "هبات ساخنة", "Hot flushes", "general", ["هبات ساخنة", "هبات حرارة", "حرارة مفاجئة بالجسم", "تجيني حرارة فجأة"], ["hot flushes", "hot flashes", "sudden heat waves"]),
    ("leg-cramps", "تشنجات أو شد مؤلم في الساق", "Leg cramps", "pain", ["تشنج الساق", "شد بالساق", "عضلة الساق تقفل", "كرامب بالساق", "تشنج الرجل"], ["leg cramps", "calf cramps", "muscle cramp in leg"]),
    ("visible-varicose-veins", "أوردة بارزة ومتعرجة بالساق", "Visible varicose veins", "vascular", ["عروق بارزة برجلي", "عروق متعرجة بالساق", "دوالي الساق", "عروق زرقاء بارزة"], ["varicose veins", "bulging leg veins", "twisted veins in leg"]),
    ("leg-heaviness", "ثقل أو وجع في الساقين", "Leg heaviness or aching", "vascular", ["رجولي ثقيلة", "ثقل بالساق", "وجع وثقل بالرجل", "الساق ثقيلة بعد الوقوف"], ["heavy legs", "leg heaviness", "aching legs after standing"]),
    ("cold-fingers", "برودة أصابع اليدين أو القدمين", "Cold fingers or toes", "vascular", ["اصابعي باردة", "أصابعي باردة", "يدي تبرد بسرعة", "اصابع رجلي باردة"], ["cold fingers", "cold toes", "fingers get cold"]),
    ("finger-color-change", "تغير لون الأصابع مع البرد", "Finger color change with cold", "vascular", ["اصابعي تصير بيضاء", "أصابعي تصير بيضاء", "اصابعي تزرق", "أصابعي تزرق", "لون اصابعي يتغير مع البرد"], ["fingers turn white", "fingers turn blue", "finger colour changes in cold"]),
]

EXTRA_DISEASES_V5 = [
    {
        "slug":"earwax-build-up", "name_ar":"تراكم شمع الأذن", "name_en":"Earwax build-up", "category":"ear", "severity":"mild",
        "symptoms":{"ear-blocked":0.95,"hearing-loss":0.82,"tinnitus":0.45},
        "description_ar":"تراكم شمع الأذن قد يسبب إحساسًا بانسداد الأذن أو نقص السمع، وأحيانًا طنينًا أو دوخة. لا يمكن تأكيد السبب من الأعراض وحدها.",
        "description_en":"Earwax build-up can cause a blocked-ear feeling or reduced hearing, and sometimes tinnitus or dizziness. Symptoms alone cannot confirm the cause.",
        "risk_ar":"ألم شديد، إفرازات أو نزف، دوخة شديدة، أو فقد سمع مفاجئ يحتاج تقييمًا طبيًا سريعًا.",
        "risk_en":"Severe pain, discharge/bleeding, severe vertigo, or sudden hearing loss needs prompt assessment.",
        "causes_ar":"زيادة أو انحشار شمع الأذن، وقد يزيد مع استخدام أعواد الأذن أو بعض السماعات.", "causes_en":"Excess or impacted earwax; cotton buds and some hearing devices can contribute.",
        "red_ar":"فقدان السمع المفاجئ أو تدهور سريع يحتاج تقييمًا عاجلًا.", "red_en":"Sudden hearing loss or rapid worsening needs urgent assessment.",
        "next_ar":"تجنب إدخال أعواد أو أدوات داخل الأذن واستشر الصيدلي أو الطبيب إذا استمر الانسداد أو ضعف السمع.", "next_en":"Do not insert cotton buds or tools into the ear; seek pharmacist/medical advice if blockage or hearing reduction persists.",
        "sources":[("nhs","تراكم شمع الأذن — NHS","Earwax build-up — NHS","https://www.nhs.uk/conditions/earwax-build-up/")],
    },
    {
        "slug":"eye-floaters-flashes", "name_ar":"عوامات أو ومضات في مجال النظر", "name_en":"Floaters or flashes in vision", "category":"eye", "severity":"moderate",
        "symptoms":{"eye-floaters":0.92,"eye-flashes":0.86},
        "description_ar":"العوامات والومضات قد تكون شائعة وغير خطرة أحيانًا، لكن ظهورها لأول مرة أو زيادتها المفاجئة يحتاج تقييمًا للعين لاستبعاد مشكلة في الشبكية.",
        "description_en":"Floaters and flashes can sometimes be harmless, but first-time or sudden increases need eye assessment to rule out retinal problems.",
        "risk_ar":"ظهور مفاجئ لكثير من العوامات أو الومضات، ستارة أو ظل في الرؤية، تشوش أو ألم بالعين يحتاج تقييمًا عاجلًا.",
        "risk_en":"A sudden shower of floaters/flashes, a curtain or shadow, blurred vision, or eye pain needs urgent assessment.",
        "causes_ar":"تغيرات داخل الجسم الزجاجي بالعين، مع أسباب أخرى قد تشمل تمزقًا أو انفصالًا بالشبكية.", "causes_en":"Changes in the eye's vitreous; other causes can include retinal tear or detachment.",
        "red_ar":"ستارة أو ظل، تدهور الرؤية، ألم العين، أو زيادة مفاجئة واضحة تستدعي رعاية عاجلة.", "red_en":"A curtain/shadow, reduced vision, eye pain, or a sudden marked increase needs urgent care.",
        "next_ar":"إذا كانت جديدة أو زادت فجأة فاطلب تقييمًا عاجلًا للعين؛ أما الأعراض القديمة المستقرة فناقشها في فحص عيون روتيني.", "next_en":"Seek urgent eye assessment if new or suddenly worse; long-standing stable symptoms can be discussed at a routine eye examination.",
        "sources":[("nhs","العوامات والومضات في العين — NHS","Floaters and flashes in the eyes — NHS","https://www.nhs.uk/symptoms/floaters-and-flashes-in-the-eyes/")],
    },
    {
        "slug":"persistent-hiccups", "name_ar":"الحازوقة (الفواق)", "name_en":"Hiccups", "category":"general", "severity":"mild",
        "symptoms":{"hiccups":1.0},
        "description_ar":"الحازوقة شائعة وغالبًا تزول خلال دقائق، لكنها تحتاج مراجعة إذا استمرت طويلًا أو تكررت بشكل يؤثر على الحياة.",
        "description_en":"Hiccups are common and usually stop within minutes, but persistent or frequently recurring hiccups may need review.",
        "risk_ar":"إذا استمرت أكثر من 48 ساعة أو كانت شديدة ومتكررة وتؤثر على الأكل أو النوم فاطلب تقييمًا طبيًا.",
        "risk_en":"Seek medical review if hiccups last more than 48 hours or recur severely enough to affect eating or sleep.",
        "causes_ar":"قد تبدأ بعد الأكل أو الشرب أو تغيرات مفاجئة، وكثيرًا لا يوجد سبب واضح.", "causes_en":"They may follow eating, drinking, or sudden changes, and often have no clear cause.",
        "red_ar":"استمرارها أكثر من 48 ساعة أو وجود أعراض عصبية أو تنفسية جديدة يحتاج تقييمًا.", "red_en":"Persistence beyond 48 hours or new neurological/respiratory symptoms needs assessment.",
        "next_ar":"راقب المدة وتجنب المحفزات التي لاحظتها، وراجع الطبيب إذا تجاوزت 48 ساعة أو عادت كثيرًا.", "next_en":"Track duration and triggers; see a clinician if they last over 48 hours or keep returning.",
        "sources":[("nhs","الحازوقة — NHS","Hiccups — NHS","https://www.nhs.uk/symptoms/hiccups/")],
    },
    {
        "slug":"halitosis", "name_ar":"رائحة الفم غير المستحبة", "name_en":"Bad breath (halitosis)", "category":"mouth", "severity":"mild",
        "symptoms":{"bad-breath":1.0,"dry-mouth":0.42},
        "description_ar":"رائحة الفم شائعة وغالبًا ترتبط بالفم والأسنان أو جفاف الفم، وقد ترتبط أحيانًا باللوز أو الارتجاع.",
        "description_en":"Bad breath is common and is often related to dental/oral causes or dry mouth, and sometimes tonsil or reflux problems.",
        "risk_ar":"ألم أسنان شديد، تورم بالوجه، صعوبة بلع أو تنفس، أو حمى مع تورم يحتاج تقييمًا سريعًا.",
        "risk_en":"Severe tooth pain, facial swelling, difficulty swallowing/breathing, or fever with swelling needs prompt assessment.",
        "causes_ar":"مشكلات اللثة أو الأسنان، جفاف الفم، بعض الأطعمة أو التدخين، والتهاب اللوز أو الارتجاع أحيانًا.", "causes_en":"Dental/gum problems, dry mouth, some foods or smoking, and sometimes tonsillitis or reflux.",
        "red_ar":"تورم سريع بالوجه أو صعوبة التنفس/البلع تستدعي رعاية عاجلة.", "red_en":"Rapid facial swelling or breathing/swallowing difficulty needs urgent care.",
        "next_ar":"حافظ على تنظيف الأسنان واللسان وخيط الأسنان، وراجع طبيب الأسنان إذا استمرت الرائحة لأسابيع أو معها ألم/نزف لثة.", "next_en":"Maintain tooth/tongue cleaning and flossing; see a dentist if it persists for weeks or comes with gum pain/bleeding.",
        "sources":[("nhs","رائحة الفم — NHS","Bad breath — NHS","https://www.nhs.uk/symptoms/bad-breath/")],
    },
    {
        "slug":"oral-thrush", "name_ar":"فطريات الفم", "name_en":"Oral thrush", "category":"mouth", "severity":"mild",
        "symptoms":{"white-mouth-patches":0.98,"mouth-pain":0.58,"altered-taste":0.35},
        "description_ar":"فطريات الفم قد تظهر كبقع بيضاء داخل الفم مع احمرار أو ألم أو تغير في الطعم، لكن توجد أسباب أخرى للبقع البيضاء.",
        "description_en":"Oral thrush can cause white mouth patches with redness, soreness, or taste changes, but white patches can have other causes.",
        "risk_ar":"صعوبة أو ألم شديد عند البلع، ضعف مناعة، أو استمرار الأعراض رغم العلاج يحتاج تقييمًا طبيًا.",
        "risk_en":"Difficulty or marked pain swallowing, immunocompromise, or symptoms that persist despite treatment need medical review.",
        "causes_ar":"زيادة نمو فطر Candida، وقد يرتبط بالمضادات الحيوية أو بخاخات الربو أو أطقم الأسنان أو عوامل أخرى.", "causes_en":"Candida overgrowth; antibiotics, asthma inhalers, dentures, and other factors can contribute.",
        "red_ar":"صعوبة البلع أو انتشار الأعراض مع ضعف المناعة يستدعي تقييمًا طبيًا.", "red_en":"Swallowing difficulty or spreading symptoms with immunocompromise needs medical assessment.",
        "next_ar":"استشر الصيدلي أو الطبيب للتأكد من السبب والعلاج المناسب، خصوصًا إذا لم تتحسن خلال أسبوع.", "next_en":"Ask a pharmacist or clinician to confirm the cause and treatment, especially if not improving within a week.",
        "sources":[("nhs","فطريات الفم — NHS","Oral thrush — NHS","https://www.nhs.uk/conditions/oral-thrush-mouth-thrush/")],
    },
    {
        "slug":"urinary-incontinence-pattern", "name_ar":"نمط تسرب البول", "name_en":"Urinary incontinence pattern", "category":"urinary", "severity":"mild",
        "symptoms":{"urine-leakage":0.98,"urinary-urgency":0.66,"frequent-urination":0.35},
        "description_ar":"تسرب البول دون قصد شائع وله أنماط مختلفة، مثل التسرب مع الكحة/الضحك أو بعد إلحاح مفاجئ للتبول.",
        "description_en":"Unintentional urine leakage is common and has different patterns, such as leakage with coughing/laughing or after a sudden intense urge.",
        "risk_ar":"ضعف جديد بالساقين، خدر بمنطقة العجان، أو فقد مفاجئ للتحكم بالبول مع أعراض عصبية يحتاج تقييمًا عاجلًا.",
        "risk_en":"New leg weakness, saddle numbness, or sudden loss of bladder control with neurological symptoms needs urgent assessment.",
        "causes_ar":"ضعف عضلات قاع الحوض، فرط نشاط المثانة، احتباس أو أسباب أخرى تعتمد على النمط والسياق.", "causes_en":"Pelvic-floor weakness, overactive bladder, retention, or other causes depending on pattern and context.",
        "red_ar":"تغير مفاجئ مع ضعف أو خدر عصبي، حرارة وألم شديد، أو احتباس بول يحتاج تقييمًا سريعًا.", "red_en":"Sudden change with neurological weakness/numbness, fever with severe pain, or urinary retention needs prompt assessment.",
        "next_ar":"دوّن متى يحدث التسرب وما يحفزه وعدد مرات التبول، وراجع مختصًا لتحديد النوع وخيارات العلاج.", "next_en":"Track when leakage occurs, triggers, and urination frequency, then seek clinical review to identify the type and options.",
        "sources":[("nhs","سلس البول — NHS","Urinary incontinence — NHS","https://www.nhs.uk/conditions/urinary-incontinence/")],
    },
    {
        "slug":"perimenopause-symptom-pattern", "name_ar":"نمط أعراض ما قبل/حول انقطاع الدورة", "name_en":"Perimenopause symptom pattern", "category":"general", "severity":"mild",
        "symptoms":{"hot-flushes":0.92,"night-sweats":0.76,"irregular-periods":0.62,"insomnia":0.38,"mood-swings":0.34},
        "description_ar":"قد تتغير الدورة ويظهر معها هبات ساخنة أو تعرق ليلي أو تغيرات النوم والمزاج خلال مرحلة ما قبل انقطاع الدورة، لكن هذه الأعراض لها أسباب أخرى أيضًا.",
        "description_en":"Cycle changes with hot flushes, night sweats, sleep or mood changes can occur during perimenopause, but these symptoms also have other causes.",
        "risk_ar":"نزيف شديد جدًا، نزيف بعد انقطاع الدورة، ألم حاد، إغماء أو تدهور شديد يحتاج تقييمًا طبيًا سريعًا.",
        "risk_en":"Very heavy bleeding, bleeding after menopause, severe pain, fainting, or marked deterioration needs prompt assessment.",
        "causes_ar":"تغير مستويات الهرمونات مع الانتقال نحو انقطاع الدورة، مع وجود أسباب أخرى ممكنة للأعراض نفسها.", "causes_en":"Hormone changes during the transition toward menopause, while the same symptoms can have other causes.",
        "red_ar":"نزيف غير معتاد شديد أو بعد انقطاع الدورة يحتاج تقييمًا طبيًا.", "red_en":"Very unusual bleeding or bleeding after menopause needs medical assessment.",
        "next_ar":"تتبعي الدورة والهبات والنوم، وناقشي الأعراض مع مختص إذا أثرت على حياتك أو كان نمط النزف غير معتاد.", "next_en":"Track cycles, flushes, and sleep; discuss symptoms with a clinician if they affect daily life or bleeding is unusual.",
        "sources":[("nhs","أعراض سن اليأس وما قبله — NHS","Menopause and perimenopause symptoms — NHS","https://www.nhs.uk/conditions/menopause-and-perimenopause/symptoms/")],
    },
    {
        "slug":"common-leg-cramps", "name_ar":"تشنجات الساق الشائعة", "name_en":"Common leg cramps", "category":"musculoskeletal", "severity":"mild",
        "symptoms":{"leg-cramps":1.0},
        "description_ar":"تشنج الساق ألم مفاجئ بسبب تقلص العضلة، وغالبًا يكون قصيرًا وقد يحدث ليلًا. تكراره الشديد يحتاج تقييمًا للأسباب المحتملة.",
        "description_en":"A leg cramp is sudden pain from a muscle tightening, often brief and sometimes occurring at night. Frequent severe cramps may need review.",
        "risk_ar":"تورم ساق واحدة أو احمرار وسخونة، ضيق نفس، ضعف شديد، أو تشنجات طويلة ومتكررة تحتاج تقييمًا طبيًا.",
        "risk_en":"One-sided swelling/redness/warmth, breathlessness, marked weakness, or prolonged frequent cramps needs medical assessment.",
        "causes_ar":"إجهاد العضلات، بعض الأدوية أو الحالات، وقد لا يوجد سبب واضح.", "causes_en":"Muscle strain, some medicines or conditions, and sometimes no clear cause.",
        "red_ar":"تورم مؤلم بساق واحدة مع ضيق نفس أو ألم صدر يستدعي رعاية عاجلة.", "red_en":"Painful one-sided leg swelling with breathlessness or chest pain needs urgent care.",
        "next_ar":"التمدد اللطيف قد يساعد أثناء التشنج، وراجع مختصًا إذا كانت التشنجات متكررة جدًا أو تعطل النوم.", "next_en":"Gentle stretching may help during a cramp; seek review if cramps are frequent or disrupt sleep.",
        "sources":[("nhs","تشنجات الساق — NHS","Leg cramps — NHS","https://www.nhs.uk/conditions/leg-cramps/")],
    },
    {
        "slug":"varicose-veins", "name_ar":"دوالي الساقين", "name_en":"Varicose veins", "category":"vascular", "severity":"mild",
        "symptoms":{"visible-varicose-veins":0.98,"leg-heaviness":0.68,"leg-swelling":0.42,"itching":0.25},
        "description_ar":"الدوالي أوردة متوسعة وملتوية تحت الجلد، وغالبًا تكون بالساقين وقد تسبب ثقلًا أو وجعًا أو حكة أو تورمًا.",
        "description_en":"Varicose veins are enlarged twisted veins under the skin, usually in the legs, and may cause aching/heaviness, itching, or swelling.",
        "risk_ar":"نزف من الدوالي، قرحة لا تلتئم، أو تورم وألم مفاجئ بساق واحدة يحتاج تقييمًا طبيًا سريعًا.",
        "risk_en":"Bleeding varicose veins, a non-healing ulcer, or sudden one-sided painful swelling needs prompt assessment.",
        "causes_ar":"ضعف صمامات الأوردة مع تجمع الدم، وتزيد مع العمر والحمل والوقوف الطويل وعوامل أخرى.", "causes_en":"Weak vein valves causing blood pooling; risk increases with age, pregnancy, prolonged standing and other factors.",
        "red_ar":"نزف من الوريد أو تورم ساق مفاجئ ومؤلم مع ضيق تنفس يحتاج رعاية عاجلة.", "red_en":"Vein bleeding or sudden painful leg swelling with breathlessness needs urgent care.",
        "next_ar":"الحركة ورفع الساق قد يساعدان الأعراض؛ راجع مختصًا إذا كان هناك ألم أو حكة أو تورم أو تدهور.", "next_en":"Activity and leg elevation can help symptoms; seek review for pain, itching, swelling, or worsening.",
        "sources":[("nhs","الدوالي — NHS","Varicose veins — NHS","https://www.nhs.uk/conditions/varicose-veins/")],
    },
    {
        "slug":"common-hair-loss-pattern", "name_ar":"نمط تساقط الشعر الشائع", "name_en":"Common hair-loss pattern", "category":"skin", "severity":"mild",
        "symptoms":{"hair-loss":1.0},
        "description_ar":"تساقط الشعر شائع وله أسباب متعددة؛ بعض الأنماط مؤقتة بعد مرض أو ضغط جسدي، وبعضها وراثي أو مرتبط بنقص أو تغير هرموني أو علاج.",
        "description_en":"Hair loss is common and has many causes; some patterns are temporary after illness or physical stress, while others are inherited or linked to deficiencies, hormonal changes, or treatments.",
        "risk_ar":"تساقط سريع جدًا، مناطق مؤلمة أو ملتهبة/متندبة بفروة الرأس، أو أعراض عامة مستمرة تحتاج تقييمًا طبيًا.",
        "risk_en":"Very rapid loss, painful/inflamed or scarred scalp areas, or persistent systemic symptoms need medical assessment.",
        "causes_ar":"عوامل وراثية، مرض أو ضغط جسدي، نقص الحديد أو تغيرات هرمونية، وبعض الأدوية أو العلاجات.", "causes_en":"Inherited patterns, illness or physical stress, iron deficiency or hormonal change, and some medicines/treatments.",
        "red_ar":"التساقط المفاجئ الشديد أو التهاب/ندبات فروة الرأس يحتاج تقييمًا.", "red_en":"Very sudden severe loss or scalp inflammation/scarring needs assessment.",
        "next_ar":"راقب نمط ومدة التساقط وراجع مختصًا إذا كان مفاجئًا أو مقلقًا أو مستمرًا؛ تحديد السبب يسبق اختيار العلاج.", "next_en":"Track the pattern and duration and seek review if sudden, concerning, or persistent; identifying the cause should come before choosing treatment.",
        "sources":[("nhs","تساقط الشعر — NHS","Hair loss — NHS","https://www.nhs.uk/conditions/hair-loss/")],
    },
    {
        "slug":"raynauds-pattern", "name_ar":"نمط رينو مع البرد", "name_en":"Raynaud's pattern", "category":"vascular", "severity":"mild",
        "symptoms":{"cold-fingers":0.82,"finger-color-change":0.98,"numbness":0.34},
        "description_ar":"في رينو قد تتغير ألوان أصابع اليدين أو القدمين مع البرد أو التوتر وتصبح باردة أو مخدرة، لكن تغير اللون قد تكون له أسباب أخرى.",
        "description_en":"With Raynaud's, fingers or toes may change colour with cold or stress and feel cold or numb, though colour change can have other causes.",
        "risk_ar":"ألم شديد مستمر، قرح أو سواد بالأصابع، أو أعراض جديدة بجهة واحدة تحتاج تقييمًا طبيًا.",
        "risk_en":"Persistent severe pain, ulcers/blackening of digits, or new one-sided symptoms need medical assessment.",
        "causes_ar":"تشنج مؤقت في الأوعية الصغيرة استجابة للبرد أو التوتر، وقد يكون أوليًا أو مرتبطًا بحالات أخرى.", "causes_en":"Temporary spasm of small blood vessels in response to cold/stress; it can be primary or secondary to other conditions.",
        "red_ar":"تقرحات أو اسوداد الأصابع أو ألم شديد لا يزول يحتاج رعاية عاجلة.", "red_en":"Ulcers, blackening of digits, or severe persistent pain needs urgent assessment.",
        "next_ar":"حافظ على الدفء وتجنب التغير المفاجئ بالحرارة، وراجع مختصًا إذا بدأت الأعراض حديثًا أو كانت شديدة.", "next_en":"Keep warm and avoid abrupt temperature changes; seek review if symptoms are new, severe, or worsening.",
        "sources":[("nhs","مرض رينو — NHS","Raynaud's — NHS","https://www.nhs.uk/conditions/raynauds/")],
    },
]

# V73 adds coverage only.  It deliberately does not add new emergency rules;
# safety/triage stays conservative and independently reviewed.
EXISTING_DISEASE_SOURCE_ENRICHMENT_V5 = {}
EXISTING_DISEASE_SYMPTOM_ENRICHMENT_V5 = {}
EXTRA_RED_RULES_V5 = []
EXTRA_RED_RULE_DETAILS_V5 = {}
