"""Routes for group "admin", moved out of webapp.py (behaviour unchanged).

Dependencies from webapp.py are injected by register(); decorators like login_required are applied there in the
original order. Generated by tools/extract_routes.py.
"""
from routes import _inject
from dashboard import DASHBOARD_HTML
from datetime import datetime
from datetime import timedelta
from datetime import timezone
from flask import Response
from flask import g
from flask import jsonify
from flask import redirect
from flask import render_template_string
from flask import request
from flask import send_file
from flask import session
from flask import url_for
import admin_2fa
import admin_complete
import admin_operational
import admin_security
import advanced_features
import best_effort
import clinical_review
import content_gaps
import content_priority
import csv
import db
import decision_log
import health_library
import hmac
import html as html_lib
import io
import json
import judge_challenge
import logging
import medical_knowledge
import medical_source_pipeline
import medical_taxonomy
import medication_email
import ops_quality
import os
import performance_benchmark
import platform_v2
import privacy_features
import production_readiness
import production_verification
import release_candidate
import research_study
import research_validation
import safety_engine
import secrets
import time
import v50_wow
import v51_innovation
import zipfile

DEPS = ("L", "STATIC_ASSET_VERSION", "_admin_allowed", "_admin_analytics_filters", "_admin_auth_debug", "_admin_csrf_token", "_admin_page_gate", "_admin_session_valid", "_auth_csrf_token", "_auth_csrf_valid", "_auth_email_provider_state", "_auth_form_expired_message", "_complete_admin_2fa_login", "_configured_web_secret", "_lang", "_mk_error", "_page", "_pending_admin_2fa_user", "_rate_limited_response", "_request_allowed", "_send_auth_email", "_sentry_enabled", "_ss_user", "_ss_user_id", "admin_api_required", )

_SPECS = {}
_WRAPPERS = {
    "admin_quality_snapshot": ('admin_api_required("analytics")', ),
    "admin_quality_center": (),
    "admin_judge_challenge": (),
    "api_admin_judge_challenge_run": ('admin_api_required("analytics")', ),
    "admin_clinical_review": (),
    "admin_competition_dashboard": (),
    "admin_innovation_lab": (),
    "innovation_lab_probe": ('admin_api_required("analytics")', ),
    "innovation_lab_evidence": ('admin_api_required("analytics")', ),
    "admin_2fa_setup": (),
    "admin_2fa_verify": (),
    "api_admin_2fa_status": ('admin_api_required("settings")', ),
    "admin_2fa_manage": (),
    "api_admin_auth_email_status": ('admin_api_required("access")', ),
    "api_admin_auth_email_test": ('admin_api_required("access")', ),
    "api_admin_auth_email_confirm": ('admin_api_required("access")', ),
    "admin_login": (),
    "admin_verify": (),
    "admin_claim": (),
    "admin": (),
    "admin_lab_trials_export_xlsx": (),
    "admin_blood_trials_export_xlsx": (),
    "admin_lab_trials_page": (),
    "admin_section": (),
    "api_admin_data_pulse": ('admin_api_required("analytics")', ),
    "api_admin_quality_dashboard": ('admin_api_required("analytics")', ),
    "api_admin_content_gaps": ('admin_api_required("analytics")', ),
    "api_admin_system_health": ('admin_api_required("medical")', ),
    "api_admin_performance_benchmark": ('admin_api_required("medical")', ),
    "api_admin_production_readiness": ('admin_api_required("medical")', ),
    "api_admin_error_monitoring_status": ('admin_api_required("access")', ),
    "api_admin_error_monitoring_test": ('admin_api_required("access")', ),
    "api_admin_research_study": ('admin_api_required("analytics")', ),
    "api_admin_research_study_freeze": ('admin_api_required("analytics")', ),
    "api_admin_research_validation_export": ('admin_api_required("analytics")', ),
    "api_admin_research_validation": ('admin_api_required("analytics")', ),
    "api_admin_research_validation_item": ('admin_api_required("analytics")', ),
    "api_admin_audit": ('admin_api_required("access")', ),
    "api_admin_users": ('admin_api_required("super")', ),
    "api_admin_user_role": ('admin_api_required("access")', ),
    "api_admin_v2_analytics": ('admin_api_required("analytics")', ),
    "api_admin_complete_analytics": ('admin_api_required("analytics")', ),
    "api_admin_content": ('admin_api_required("medical")', ),
    "api_admin_content_item": ('admin_api_required("medical")', ),
    "api_admin_user_status": ('admin_api_required("super")', ),
    "api_admin_security_activity": ('admin_api_required("super")', ),
    "api_admin_security_audit": ('admin_api_required("super")', ),
    "api_admin_analytics_export_preview": ('admin_api_required("analytics")', ),
    "api_admin_analytics_export_xlsx": ('admin_api_required("analytics")', ),
    "api_admin_dropoff": ('admin_api_required("analytics")', ),
    "api_admin_live_activity": ('admin_api_required("analytics")', ),
    "api_admin_ui_audit": ('admin_api_required("access")', ),
    "api_admin_analysis_results": ('admin_api_required("access")', ),
    "api_admin_lab_trials": ('admin_api_required("access")', ),
    "api_admin_export_lab_trials_xlsx": ('admin_api_required("access")', ),
    "api_admin_blood_trials": ('admin_api_required("access")', ),
    "api_admin_export_blood_trials_xlsx": ('admin_api_required("access")', ),
    "api_admin_clear_lab_trials": ('admin_api_required("access")', ),
    "api_admin_reset_test_data": ('admin_api_required("access")', ),
    "api_admin_export_xlsx": ('admin_api_required("access")', ),
    "api_admin_export_pilot_xlsx": ('admin_api_required("access")', ),
    "api_admin_audit_export": ('admin_api_required("access")', ),
    "api_admin_ai_performance": ('admin_api_required("analytics")', ),
    "api_admin_explainable_ai": ('admin_api_required("analytics")', ),
    "api_admin_profile": ('admin_api_required("access")', ),
    "api_admin_profile_password": ('admin_api_required("access")', ),
    "api_admin_logout_all_sessions": ('admin_api_required("access")', ),
    "api_admin_knowledge_graph": ('admin_api_required("medical")', ),
    "api_admin_anomalies": ('admin_api_required("analytics")', ),
    "api_admin_automatic_insights": ('admin_api_required("analytics")', ),
    "api_admin_privacy_analytics": ('admin_api_required("access")', ),
    "api_admin_ask_data": ('admin_api_required("analytics")', ),
    "api_admin_funnel_by_mode": ('admin_api_required("analytics")', ),
    "api_admin_medical_source_review_list": ('admin_api_required("medical")', ),
    "api_admin_medical_source_review_fetch": ('admin_api_required("medical")', ),
    "api_admin_icd11_candidates": ('admin_api_required("medical")', ),
    "api_admin_icd11_approve": ('admin_api_required("medical")', ),
    "api_admin_content_priority_gsc": ('admin_api_required("analytics")', ),
    "api_admin_content_priority_trends": ('admin_api_required("analytics")', ),
    "api_admin_medication_email_status": ('admin_api_required("access")', ),
}


def route(rule, **opts):
    def deco(fn):
        _SPECS.setdefault(fn.__name__, {"fn": fn, "rules": []})["rules"].append((rule, opts))
        return fn
    return deco


@route("/api/admin/quality", methods=["GET"])
def admin_quality_snapshot():
    response = jsonify({"ok": True, **ops_quality.quality_snapshot()})
    response.headers["Cache-Control"] = "private, no-store"
    return response


@route("/admin/quality-center")
def admin_quality_center():
    denied = _admin_page_gate("/admin/quality-center")
    if denied: return denied
    ar = _lang() != "en"
    body = ('<main class="container" style="max-width:980px;padding:24px 16px 60px"><div class="ss-stack">'
            '<section class="ss-card"><h1 style="margin:0 0 6px">%s</h1><p class="ss-muted" id="qcNote"></p></section>'
            '<section class="ss-card" id="qcRoot" aria-live="polite">%s</section></div></main>'
            '<script src="/static/js/quality-center.js" defer></script>') % (
        "مركز الجودة" if ar else "Quality centre", "جارٍ التحميل…" if ar else "Loading…")
    return _page("مركز الجودة" if ar else "Quality centre", body)


@route("/admin/judge-challenge")
def admin_judge_challenge():
    denied = _admin_page_gate("/admin/judge-challenge")
    if denied: return denied
    csrf = _admin_csrf_token()
    def challenge_page(title, body, **kwargs):
        return _page(title, '<meta name="admin-csrf" content="%s">%s' % (html_lib.escape(csrf, quote=True), body), **kwargs)
    return judge_challenge.render_page(page=challenge_page, lang=_lang())


@route("/api/admin/judge-challenge/run", methods=["POST"])
def api_admin_judge_challenge_run():
    data = request.get_json(silent=True) or {}
    case_id = str(data.get("case_id") or "").strip()
    lang = "en" if str(data.get("lang") or _lang()).lower() == "en" else "ar"
    try: result = judge_challenge.run_case(case_id, lang)
    except ValueError: return _mk_error("invalid_case", 400)
    return jsonify({"ok": True, "result": result})


@route("/admin/clinical-review")
def admin_clinical_review():
    denied = _admin_page_gate("/admin/clinical-review")
    if denied is not None:
        return denied
    if not _admin_allowed("medical"):
        return _page("Admin", '<div class="card" style="max-width:560px;margin:40px auto;text-align:center"><h2>🔒 403</h2><a class="btn" href="/admin">Admin</a></div>'), 403
    return clinical_review.render_page(page=_page, lang=_lang(), csrf=_admin_csrf_token(), decision_summary=decision_log.summary())


@route("/admin/competition-dashboard")
def admin_competition_dashboard():
    denied = _admin_page_gate("/admin/competition-dashboard")
    if denied is not None:
        return denied
    return v50_wow.render_competition_dashboard(page=_page, lang=_lang())


@route("/admin/innovation-lab")
def admin_innovation_lab():
    denied = _admin_page_gate("/admin/innovation-lab")
    if denied is not None:
        return denied
    admin_csrf = _admin_csrf_token()
    def _admin_lab_page(title, body, **kwargs):
        return _page(title, '<meta name="admin-csrf" content="%s">%s' % (html_lib.escape(admin_csrf, quote=True), body), **kwargs)
    return v51_innovation.render_innovation_lab(page=_admin_lab_page, lang=_lang())


@route("/api/admin/innovation-lab/probe", methods=["POST"])
def innovation_lab_probe():
    if not _request_allowed("innovation_probe", 40, 60):
        return jsonify({"ok": False, "error": "rate_limited"}), 429
    data = request.get_json(silent=True) or {}
    if not isinstance(data, dict):
        return jsonify({"ok": False, "error": "invalid_json"}), 400
    text = data.get("text")
    if not isinstance(text, str) or not text.strip():
        return jsonify({"ok": False, "error": "empty_text"}), 400
    if len(text) > 180:
        return jsonify({"ok": False, "error": "text_too_long"}), 413
    result = v51_innovation.probe_phrase(text, str(data.get("lang") or _lang()))
    return jsonify(result), (200 if result.get("ok") else 400)


@route("/api/admin/innovation-lab/evidence", methods=["GET"])
def innovation_lab_evidence():
    response = jsonify(v51_innovation.evidence_snapshot())
    response.headers["Cache-Control"] = "private, no-store"
    return response


@route("/admin/2fa/setup", methods=["GET", "POST"])
def admin_2fa_setup():
    user = _pending_admin_2fa_user()
    if not user:
        return redirect(url_for("login", next="/admin"))
    lang = _lang(); ar = lang == "ar"
    if not admin_2fa.available():
        msg = ("تعذر إعداد التحقق بخطوتين لأن WEB_SECRET غير مضبوط بشكل ثابت أو مكتبة التشفير غير متاحة. اضبط WEB_SECRET ثم أعد النشر." if ar else
               "Two-factor setup is unavailable because WEB_SECRET is not configured as a stable secret or the encryption dependency is unavailable. Configure WEB_SECRET and redeploy.")
        return _page("Admin 2FA", '<div class="card" style="max-width:680px;margin:40px auto"><h2>🔐 Admin 2FA</h2><p class="muted">%s</p><a class="btn" href="/login?next=/admin">%s</a></div>' % (msg, "العودة لتسجيل الدخول" if ar else "Back to sign in")), 503
    st = admin_2fa.status(int(user["id"]))
    if st.get("enabled"):
        return redirect(url_for("admin_2fa_verify"))
    error = None
    recovery_codes = None
    if request.method == "POST":
        if not _auth_csrf_valid():
            error = _auth_form_expired_message(lang)
        elif not _request_allowed("admin_2fa_setup", 8, 600, str(user["id"])):
            error = "محاولات كثيرة. انتظر قليلًا ثم حاول مرة أخرى." if ar else "Too many attempts. Please wait and try again."
        else:
            try:
                recovery_codes = admin_2fa.confirm_setup(int(user["id"]), request.form.get("code") or "")
                _complete_admin_2fa_login(int(user["id"]), "totp_setup")
                best_effort.call(platform_v2.audit, int(user['id']), 'enabled_2fa', 'admin_security', 'self', None, {'status': 'success'})
            except ValueError:
                error = "الرمز غير صحيح. انتظر الرمز الجديد في تطبيق Authenticator وحاول مرة أخرى." if ar else "The code is incorrect. Wait for a fresh Authenticator code and try again."
    if recovery_codes:
        codes = "".join('<code style="display:block;padding:7px 10px;border:1px solid #DCE8F0;border-radius:8px;margin:5px 0;direction:ltr;text-align:center">%s</code>' % c for c in recovery_codes)
        body = '''<div class="card" style="max-width:680px;margin:40px auto"><h2>✅ %s</h2><p class="muted">%s</p><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin:18px 0">%s</div><div class="privacy-banner">%s</div><a class="btn" style="margin-top:16px" href="/admin">%s</a></div>''' % (
            "تم تفعيل التحقق بخطوتين" if ar else "Two-factor authentication enabled",
            "احفظ رموز الاسترداد في مكان آمن. كل رمز يعمل مرة واحدة فقط، ولن نعرضها لك مرة أخرى." if ar else "Save these recovery codes somewhere safe. Each code works once and they will not be shown again.",
            codes,
            "لا تحفظ هذه الرموز داخل الموقع أو في لقطة شاشة عامة." if ar else "Do not store these codes in the site or in a public screenshot.",
            "الدخول إلى لوحة الأدمن" if ar else "Continue to Admin",
        )
        return _page("Admin 2FA", body)
    secret = admin_2fa.begin_setup(int(user["id"]))
    uri = admin_2fa.provisioning_uri(secret, user.get("email") or "admin@symptosense")
    qr = admin_2fa.qr_data_uri(uri)
    img = ('<img src="%s" alt="Authenticator QR" style="width:220px;height:220px;max-width:100%%;border:1px solid #DCE8F0;border-radius:14px;padding:8px;background:#fff">' % qr) if qr else ""
    body = '''
    <div class="card" style="max-width:720px;margin:34px auto">
      <h2>🔐 %s</h2><p class="muted">%s</p>
      <div style="display:grid;grid-template-columns:minmax(0,240px) 1fr;gap:24px;align-items:center;margin:20px 0">%s<div><ol style="line-height:2"><li>%s</li><li>%s</li><li>%s</li></ol><div class="privacy-banner"><b>%s</b><div style="direction:ltr;word-break:break-all;margin-top:8px;font-family:monospace">%s</div></div></div></div>
      <form method="post"><input type="hidden" name="csrf_token" value="%s"><label style="font-weight:800">%s</label><input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required placeholder="123456" style="width:100%%;margin:8px 0 12px"><div class="auth-error %s">%s</div><button class="btn" type="submit">%s</button></form>
    </div>
    ''' % (
        "إعداد التحقق بخطوتين للأدمن" if ar else "Set up Admin two-factor authentication",
        "هذه الخطوة إلزامية لحماية لوحة الإدارة وبيانات البحث." if ar else "This step is required to protect the Admin dashboard and research data.",
        img,
        "افتح تطبيق Google Authenticator أو Microsoft Authenticator أو 1Password." if ar else "Open Google Authenticator, Microsoft Authenticator, or 1Password.",
        "امسح رمز QR. إذا تعذر المسح استخدم المفتاح اليدوي أدناه." if ar else "Scan the QR code. If scanning fails, use the manual key below.",
        "اكتب الرمز المكوّن من 6 أرقام للتأكيد." if ar else "Enter the 6-digit code to confirm setup.",
        "المفتاح اليدوي:" if ar else "Manual setup key:", secret,
        _auth_csrf_token(),
        "رمز Authenticator" if ar else "Authenticator code",
        "show" if error else "", error or "",
        "تفعيل 2FA" if ar else "Enable 2FA",
    )
    return _page("Admin 2FA", body)


@route("/admin/2fa", methods=["GET", "POST"])
def admin_2fa_verify():
    user = _pending_admin_2fa_user()
    if not user:
        return redirect(url_for("login", next="/admin"))
    lang = _lang(); ar = lang == "ar"
    st = admin_2fa.status(int(user["id"]))
    if not st.get("enabled"):
        return redirect(url_for("admin_2fa_setup"))
    error = None
    if request.method == "POST":
        if not _auth_csrf_valid():
            error = _auth_form_expired_message(lang)
        elif not _request_allowed("admin_2fa_verify", 8, 600, str(user["id"])):
            session.clear()
            return redirect(url_for("login", next="/admin"))
        else:
            attempts = int(session.get("admin_2fa_attempts", 0) or 0) + 1
            session["admin_2fa_attempts"] = attempts
            if attempts > 8:
                session.clear()
                return redirect(url_for("login", next="/admin"))
            ok, method = admin_2fa.verify(int(user["id"]), request.form.get("code") or "")
            if ok:
                _complete_admin_2fa_login(int(user["id"]), method or "totp")
                return redirect(url_for("admin"))
            error = "الرمز غير صحيح. يمكنك استخدام رمز Authenticator أو أحد رموز الاسترداد." if ar else "Invalid code. Use the current Authenticator code or one of your recovery codes."
    body = '''<div class="card" style="max-width:560px;margin:40px auto;text-align:center"><div style="font-size:42px">🔐</div><h2>%s</h2><p class="muted">%s</p><form method="post" style="text-align:%s"><input type="hidden" name="csrf_token" value="%s"><label style="display:block;font-weight:800;margin-bottom:8px">%s</label><input name="code" autocomplete="one-time-code" required maxlength="12" style="width:100%%;text-align:center;direction:ltr;font-size:22px;letter-spacing:3px" placeholder="123456"><div class="auth-error %s" style="margin-top:10px">%s</div><button class="btn" style="width:100%%;justify-content:center;margin-top:12px" type="submit">%s</button></form><p class="muted" style="margin-top:14px">%s</p></div>''' % (
        "تحقق إضافي للأدمن" if ar else "Admin verification",
        "أدخل الرمز الحالي من تطبيق Authenticator." if ar else "Enter the current code from your Authenticator app.",
        "right" if ar else "left", _auth_csrf_token(),
        "رمز التحقق" if ar else "Verification code", "show" if error else "", error or "",
        "تحقق وادخل" if ar else "Verify and continue",
        "يمكن أيضًا استخدام رمز استرداد لمرة واحدة إذا فقدت الوصول إلى التطبيق." if ar else "A one-time recovery code can also be used if you lose access to the app.",
    )
    return _page("Admin 2FA", body)


@route("/api/admin/2fa/status")
def api_admin_2fa_status():
    return jsonify({"ok": True, "two_factor": admin_2fa.status(int(_ss_user_id()))})


@route("/admin/2fa/manage")
def admin_2fa_manage():
    if not _admin_session_valid():
        return redirect(url_for("login", next="/admin/2fa/manage"))
    st = admin_2fa.status(int(_ss_user_id())); ar = _lang() == "ar"
    label = ("التحقق بخطوتين مفعّل" if ar else "Two-factor authentication is enabled") if st.get("enabled") else ("التحقق بخطوتين غير مفعّل" if ar else "Two-factor authentication is not enabled")
    body = '''<div class="card" style="max-width:650px;margin:40px auto"><h2>🔐 %s</h2><div class="privacy-banner"><b>%s</b><br>%s</div><p class="muted" style="margin-top:14px">%s: <b>%s</b></p><a class="btn ghost" href="/admin#settings">%s</a></div>''' % (
        "أمان حساب الأدمن" if ar else "Admin account security", label,
        "سيُطلب رمز Authenticator بعد كلمة المرور في كل جلسة جديدة." if ar else "A current Authenticator code is required after the password for each new Admin session.",
        "رموز الاسترداد المتبقية" if ar else "Recovery codes remaining", st.get("recovery_codes_remaining", 0),
        "العودة إلى الإعدادات" if ar else "Back to settings",
    )
    return _page("Admin 2FA", body)


@route("/api/admin/auth-email-status", methods=["GET"])
def api_admin_auth_email_status():
    """Non-sensitive production diagnostics for verification/reset email delivery."""
    state=_auth_email_provider_state()
    return jsonify({
        "ok": True,
        "provider": state.get("provider") or "none",
        "configured": bool(state.get("configured")),
        "missing": state.get("missing") or [],
        "invalid": state.get("invalid") or [],
        "sender_address_valid": bool(state.get("sender_address_valid")),
        "sender_domain": state.get("sender_domain") or None,
        "uses_resend_test_domain": bool(state.get("uses_resend_test_domain")),
        "production_recipient_delivery_ready": bool(state.get("production_recipient_delivery_ready")),
        "site_url": state.get("site_url"),
        "site_url_source": state.get("site_url_source"),
        "web_secret_configured": bool(os.environ.get("WEB_SECRET", "").strip()),
        "secure_session_cookie": bool(app.config.get("SESSION_COOKIE_SECURE")),
    })


@route("/api/admin/auth-email-test", methods=["POST"])
def api_admin_auth_email_test():
    """Send one generic test message to the currently authenticated Admin."""
    if not _request_allowed("admin_email_test", 3, 600, str(_ss_user_id() or "")):
        return _rate_limited_response()
    user=_ss_user() or {}
    email=(user.get("email") or "").strip().lower()
    if not email:
        return jsonify({"ok":False,"error":"admin_email_unavailable"}),400
    ar=_lang()=="ar"
    subject="اختبار بريد SymptoSense" if ar else "SymptoSense email test"
    html=(
        '<div dir="rtl" style="font-family:Arial,sans-serif"><h2>نجح اتصال البريد</h2><p>هذه رسالة اختبار لإعداد Email Verification وPassword Reset في SymptoSense.</p></div>'
        if ar else
        '<div style="font-family:Arial,sans-serif"><h2>Email delivery is connected</h2><p>This is a test of the SymptoSense Email Verification and Password Reset delivery configuration.</p></div>'
    )
    ok,reason=_send_auth_email(email,subject,html,"auth_test")
    best_effort.call(production_verification.record, 'email_delivery', 'sent' if ok else 'failed', {'provider': _auth_email_provider_state().get('provider') or 'unknown', 'app_version': release_candidate.APP_VERSION, 'reason': reason or 'accepted'})
    best_effort.call(platform_v2.audit, int(user.get('id')), 'test_auth_email', 'authentication', 'delivery', None, {'status': 'success' if ok else 'failed', 'reason': reason or 'accepted'})
    return jsonify({"ok":bool(ok),"error":None if ok else reason,"confirmation_required":bool(ok)}), (200 if ok else 502)


@route("/api/admin/auth-email-confirm", methods=["POST"])
def api_admin_auth_email_confirm():
    """Admin confirms the generic launch-test message actually reached the inbox."""
    state = production_verification.get("email_delivery") or {}
    if state.get("status") not in {"sent", "verified"}:
        return jsonify({"ok":False,"error":"send_email_test_first"}),400
    details = dict(state.get("details") or {})
    details.update({"app_version":release_candidate.APP_VERSION,"confirmed_by_admin":True})
    result = production_verification.record("email_delivery","verified",details)
    best_effort.call(platform_v2.audit, int(_ss_user_id()), 'confirmed_auth_email_delivery', 'authentication', 'delivery', None, {'status': 'verified'})
    return jsonify({"ok":True,"verification":result})


@route("/admin/login")
def admin_login():
    """Backward-compatible route; Admin uses the normal authenticated account."""
    return redirect(url_for("login", next="/admin"))


@route("/admin/verify")
def admin_verify():
    return redirect(url_for("admin"))


@route("/admin/claim", methods=["GET", "POST"])
def admin_claim():
    """Legacy route retained only so old links do not break.

    Admin assignment no longer uses a claim token. It is synchronized from the
    already-authenticated existing owner account.
    """
    if not _ss_user_id():
        return redirect(url_for("login", next="/admin"))
    if _admin_session_valid():
        return redirect(url_for("admin"))
    msg = "هذه الصفحة لم تعد مطلوبة. صلاحية Admin مرتبطة بحساب مالكة المشروع المصادق عليه فقط." if _lang() == "ar" else "This page is no longer required. Admin access is tied only to the authenticated project-owner account."
    return _page("Admin", '<div class="card" style="max-width:620px;margin:40px auto;text-align:center"><h2>🔒 Admin</h2><p class="muted">%s</p><a class="btn" href="/home">Home</a></div>' % msg), 403


@route("/admin")
def admin():
    if not _ss_user_id():
        _admin_auth_debug("admin_route", None, granted=False, redirect_target="/login?next=/admin")
        return redirect(url_for("login", next="/admin"))
    current_user = _ss_user()
    if not _admin_session_valid():
        if getattr(g, "admin_2fa_required", False):
            session.clear()
            return redirect(url_for("login", next="/admin"))
        if getattr(g, "admin_session_expired", False):
            return redirect(url_for("login", next="/admin"))
        _admin_auth_debug("admin_route", current_user, granted=False, redirect_target="403")
        t = L["en" if _lang() == "en" else "ar"]
        msg = "هذه الصفحة متاحة لحساب Admin فقط." if _lang() == "ar" else "This page is available to the Admin account only."
        return _page("Admin", '<div class="card" style="max-width:560px;margin:40px auto;text-align:center;"><h2>🔒 Admin</h2><p class="muted">%s</p><a class="btn" href="/home">%s</a></div>' % (msg, t.get("nav_home", "Home"))), 403
    _admin_auth_debug("admin_route", current_user, granted=True, redirect_target="/admin")
    return render_template_string(
        DASHBOARD_HTML,
        admin_user=_ss_user(),
        csrf_token=_admin_csrf_token(),
        lang="en" if _lang() == "en" else "ar",
        launch_reset_enabled=(os.environ.get("ALLOW_LAUNCH_RESET", "0").strip().lower() in {"1","true","yes","on"}),
        asset_version=STATIC_ASSET_VERSION,
    )


@route("/admin/analysis-trials/export.xlsx", methods=["GET"])
@route("/admin/lab-trials/export.xlsx", methods=["GET"])
def admin_lab_trials_export_xlsx():
    """Download a validated XLSX using Flask's native file response."""
    if not _ss_user_id():
        return redirect(url_for("login", next="/admin/analysis-trials"))
    current_user=_ss_user()
    if not _admin_session_valid() or not current_user or current_user.get("role")!="admin":
        return redirect(url_for("login", next="/admin/analysis-trials"))

    try:
        db.init_db()
        buf=db.admin_export_symptom_trials_xlsx()
        payload=buf.getvalue()

        if len(payload)<2000 or not payload.startswith(b"PK"):
            raise RuntimeError("xlsx_payload_invalid")
        with zipfile.ZipFile(io.BytesIO(payload),"r") as archive:
            if archive.testzip():
                raise RuntimeError("xlsx_zip_corrupt")
            required={"[Content_Types].xml","xl/workbook.xml","xl/worksheets/sheet1.xml"}
            if not required.issubset(set(archive.namelist())):
                raise RuntimeError("xlsx_required_parts_missing")

        stamp=datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        filename=f"SymptoSense_Symptom_Trials_{stamp}.xlsx"
        buf.seek(0)
        response=send_file(
            buf,
            mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            as_attachment=True,
            download_name=filename,
            conditional=False,
            etag=False,
            max_age=0,
        )
        response.headers["Cache-Control"]="no-store, max-age=0"
        response.headers["Pragma"]="no-cache"
        response.headers["X-Content-Type-Options"]="nosniff"
        response.headers["X-Download-Options"]="noopen"
        return response
    except Exception as exc:
        request_id=getattr(g,"request_id","")
        app.logger.exception(
            "Admin symptom-trial Excel download failed request_id=%s error_type=%s",
            request_id,type(exc).__name__,
        )
        ar=_lang()=="ar"
        body="""
        <div class="card" style="max-width:760px;margin:30px auto">
          <h1>⚠️ __TITLE__</h1>
          <p>__TEXT__</p>
          <p class="muted">Request ID: __RID__</p>
          <div class="data-actions"><a class="btn" href="/admin/analysis-trials">__BACK__</a></div>
        </div>
        """
        body=(body.replace("__TITLE__","تعذر إنشاء ملف Excel" if ar else "Excel export failed")
                  .replace("__TEXT__","لم يتم تنزيل ملف غير صالح. ارجع لبيانات التجارب وحاول مرة أخرى." if ar else "An invalid file was not downloaded. Return to Trial Data and try again.")
                  .replace("__RID__",html_lib.escape(str(request_id),quote=True))
                  .replace("__BACK__","العودة إلى بيانات التجارب" if ar else "Back to Trial Data"))
        return _page("Excel Export Error",body),500


@route("/admin/blood-trials/export.xlsx", methods=["GET"])
def admin_blood_trials_export_xlsx():
    """Download the consented blood-analysis collection Excel file."""
    if not _ss_user_id():
        return redirect(url_for("login", next="/admin/analysis-trials"))
    current_user = _ss_user()
    if not _admin_session_valid() or not current_user or current_user.get("role") != "admin":
        return redirect(url_for("login", next="/admin/analysis-trials"))

    try:
        db.init_db()
        buf = db.admin_export_blood_collection_xlsx()
        payload = buf.getvalue()
        if len(payload) < 2000 or not payload.startswith(b"PK"):
            raise RuntimeError("xlsx_payload_invalid")
        with zipfile.ZipFile(io.BytesIO(payload), "r") as archive:
            if archive.testzip():
                raise RuntimeError("xlsx_zip_corrupt")
            required = {"[Content_Types].xml", "xl/workbook.xml", "xl/worksheets/sheet1.xml"}
            if not required.issubset(set(archive.namelist())):
                raise RuntimeError("xlsx_required_parts_missing")

        stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        filename = f"SymptoSense_Blood_Analysis_Trials_{stamp}.xlsx"
        buf.seek(0)
        response = send_file(
            buf,
            mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            as_attachment=True,
            download_name=filename,
            conditional=False,
            etag=False,
            max_age=0,
        )
        response.headers["Cache-Control"] = "no-store, max-age=0"
        response.headers["Pragma"] = "no-cache"
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Download-Options"] = "noopen"
        return response
    except Exception as exc:
        request_id = getattr(g, "request_id", "")
        app.logger.exception(
            "Admin blood-trial Excel download failed request_id=%s error_type=%s",
            request_id, type(exc).__name__,
        )
        ar = _lang() == "ar"
        body = """
        <div class="card" style="max-width:760px;margin:30px auto">
          <h1>⚠️ __TITLE__</h1>
          <p>__TEXT__</p>
          <p class="muted">Request ID: __RID__</p>
          <div class="data-actions"><a class="btn" href="/admin/analysis-trials">__BACK__</a></div>
        </div>
        """
        body = (body.replace("__TITLE__", "تعذر إنشاء ملف تحليل الدم" if ar else "Blood-analysis Excel export failed")
                    .replace("__TEXT__", "لم يتم تنزيل ملف غير صالح. ارجع لبيانات التجارب وحاول مرة أخرى." if ar else "An invalid file was not downloaded. Return to Trial Data and try again.")
                    .replace("__RID__", html_lib.escape(str(request_id)))
                    .replace("__BACK__", "العودة إلى ملفات Excel" if ar else "Back to Excel files"))
        return _page("Blood Analysis Excel Export Error", body), 500


@route("/admin/analysis-trials", methods=["GET", "POST"])
@route("/admin/lab-trials", methods=["GET", "POST"])
def admin_lab_trials_page():
    """Admin tools for saved symptom-analysis trials."""
    if not _ss_user_id():
        return redirect(url_for("login", next="/admin/analysis-trials"))
    current_user = _ss_user()
    if not _admin_session_valid() or not current_user or current_user.get("role") != "admin":
        return redirect(url_for("login", next="/admin/analysis-trials"))

    message = ""
    error = ""
    if request.method == "POST":
        supplied = str(request.form.get("csrf_token") or "")
        expected = str(session.get("admin_csrf") or "")
        if not expected or not supplied or not secrets.compare_digest(supplied, expected):
            error = "تعذر التحقق من الطلب. أعد تحميل الصفحة وحاول مرة أخرى." if _lang() == "ar" else "Request verification failed. Reload and try again."
        else:
            password = str(request.form.get("current_password") or "")
            phrase = str(request.form.get("confirmation") or "").strip().upper()
            if phrase != "DELETE TRIALS":
                error = "اكتب DELETE TRIALS كما هي للتأكيد." if _lang() == "ar" else "Type DELETE TRIALS exactly to confirm."
            elif not db.verify_ss_user_password(_ss_user_id(), password):
                error = "كلمة مرور Admin غير صحيحة." if _lang() == "ar" else "Incorrect Admin password."
            else:
                result = db.admin_clear_symptom_trials()
                message = (
                    f"تم حذف {int(result.get('deleted_analyses') or 0)} تجربة تحليل أعراض محفوظة. لم يتم حذف أي حساب مستخدم."
                    if _lang() == "ar"
                    else f"Deleted {int(result.get('deleted_analyses') or 0)} saved symptom-analysis trials. No user accounts were deleted."
                )
                best_effort.call(platform_v2.audit, int(_ss_user_id()), 'clear_symptom_trials', 'admin_data', 'records', None, {'deleted_analyses': int(result.get('deleted_analyses') or 0), 'affected_testers': int(result.get('affected_testers') or 0), 'accounts_deleted': False, 'blood_tests_deleted': False})

    try:
        summary = db.admin_symptom_trial_summary()
    except (db.DB_ERRORS + (ValueError, TypeError)):
        summary = {"saved_analyses": 0, "distinct_testers": 0}
    try:
        blood_summary = db.admin_blood_collection_summary()
    except (db.DB_ERRORS + (ValueError, TypeError)):
        blood_summary = {"saved_tests": 0, "distinct_testers": 0}

    ar = _lang() == "ar"
    try:
        symptom_preview_rows = db.admin_symptom_trial_rows()[:12]
    except (db.DB_ERRORS + (ValueError, TypeError)):
        symptom_preview_rows = []
    if symptom_preview_rows:
        preview_body = "".join(
            "<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>" % (
                html_lib.escape(str(item.get("age") or "—")),
                html_lib.escape(str(item.get("gender") or "—")),
                html_lib.escape(str(item.get("symptoms") or "—")),
                html_lib.escape(str(item.get("duration") or "—")),
            )
            for item in symptom_preview_rows
        )
    else:
        preview_body = '<tr><td colspan="4" class="muted">%s</td></tr>' % (
            "لا توجد تحليلات أعراض محفوظة بعد." if ar else "No saved symptom analyses yet."
        )
    preview_html = """
      <div class="card" style="margin-top:16px;overflow:auto">
        <div style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap">
          <div><h2 style="margin:0">__PREVIEW_TITLE__</h2><p class="muted" style="margin:6px 0 0">__PREVIEW_DESC__</p></div>
          <span class="muted">__PREVIEW_COUNT__</span>
        </div>
        <div style="overflow:auto;margin-top:12px">
          <table class="ss-symptom-preview" style="width:100%;border-collapse:collapse;min-width:620px">
            <thead><tr><th>__AGE__</th><th>__GENDER__</th><th>__SYMPTOMS__</th><th>__DURATION__</th></tr></thead>
            <tbody>__PREVIEW_ROWS__</tbody>
          </table>
        </div>
      </div>
    """
    preview_html=(preview_html
        .replace("__PREVIEW_TITLE__","معاينة بيانات تحليل الأعراض" if ar else "Symptom-analysis data preview")
        .replace("__PREVIEW_DESC__","هذه نفس الحقول التي ستدخل ملف Excel. تأكد أن عمود الأعراض ممتلئ قبل التنزيل." if ar else "These are the same fields written to Excel. Confirm the Symptoms column is populated before downloading.")
        .replace("__PREVIEW_COUNT__",(("%d صف ظاهر" if ar else "%d rows shown") % len(symptom_preview_rows)))
        .replace("__AGE__","العمر" if ar else "Age")
        .replace("__GENDER__","الجنس" if ar else "Gender")
        .replace("__SYMPTOMS__","الأعراض" if ar else "Symptoms")
        .replace("__DURATION__","المدة" if ar else "Duration")
        .replace("__PREVIEW_ROWS__",preview_body))
    html = """
    <div class="card" style="max-width:900px;margin:28px auto">
      <div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap">
        <div><h1 style="margin:0">📊 __TITLE__</h1><p class="muted" style="margin-top:6px">__DESC__</p></div>
        <a class="btn ghost" href="/admin">← __BACK__</a>
      </div>
      __MESSAGE__
      <div class="grid" style="grid-template-columns:repeat(2,minmax(0,1fr));margin-top:18px">
        <div class="card"><small class="muted">__SAVED_LABEL__</small><h2>__SAVED__</h2></div>
        <div class="card"><small class="muted">__TESTERS_LABEL__</small><h2>__TESTERS__</h2></div>
      </div>
      <div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:16px" class="ss-admin-excel-files">
        <div class="card" style="margin:0;background:#f8fbfd;border:1px solid #dceafa">
          <div style="display:flex;align-items:center;gap:10px;margin-bottom:8px"><span style="font-size:24px">🩺</span><div><b>__SYM_FILE_TITLE__</b><div class="muted" style="font-size:12px">__SYM_FILE_COUNT__</div></div></div>
          <p class="muted" style="margin:0 0 14px">__EXCEL_FIELDS__</p>
          <a class="btn" style="width:100%;justify-content:center" href="/admin/analysis-trials/export.xlsx" download>📥 __SYM_EXPORT__</a>
        </div>
        <div class="card" style="margin:0;background:#f8fbfd;border:1px solid #dceafa">
          <div style="display:flex;align-items:center;gap:10px;margin-bottom:8px"><span style="font-size:24px">🩸</span><div><b>__BLOOD_FILE_TITLE__</b><div class="muted" style="font-size:12px">__BLOOD_FILE_COUNT__</div></div></div>
          <p class="muted" style="margin:0 0 14px">__BLOOD_FIELDS__</p>
          <a class="btn" style="width:100%;justify-content:center" href="/admin/blood-trials/export.xlsx" download>📥 __BLOOD_EXPORT__</a>
        </div>
      </div>
      __SYMPTOM_PREVIEW__
      <style>.ss-symptom-preview th,.ss-symptom-preview td{padding:9px 10px;border-bottom:1px solid #e5eef4;text-align:start}.ss-symptom-preview th{background:#f2f8fc;color:#234b69}@media(max-width:700px){.ss-admin-excel-files{grid-template-columns:1fr!important}}</style>
      <p class="muted" style="margin-top:12px">__GUEST_NOTE__</p>
      <hr style="border:0;border-top:1px solid #dceafa;margin:28px 0">
      <div id="delete">
        <h2>🧹 __DELETE_TITLE__</h2><p class="muted">__DELETE_DESC__</p>
        <form method="post" action="/admin/analysis-trials" style="display:grid;gap:12px;max-width:560px;margin-top:16px">
          <input type="hidden" name="csrf_token" value="__CSRF__">
          <label>__PASSWORD_LABEL__<input class="inp" type="password" name="current_password" autocomplete="current-password" required></label>
          <label>__CONFIRM_LABEL__<input class="inp" type="text" name="confirmation" placeholder="DELETE TRIALS" required></label>
          <button class="btn danger" type="submit">🧹 __DELETE_BUTTON__</button>
        </form>
      </div>
    </div>
    """
    msg_html = ""
    if message:
        msg_html = '<div class="card" style="margin-top:16px;background:#ecfdf5;color:#166534;border-color:#bbf7d0"><b>%s</b></div>' % html_lib.escape(message)
    elif error:
        msg_html = '<div class="card" style="margin-top:16px;background:#fef2f2;color:#991b1b;border-color:#fecaca"><b>%s</b></div>' % html_lib.escape(error)

    replacements = {
        "__TITLE__": "ملفات Excel للتجارب" if ar else "Trial Excel Files",
        "__DESC__": "ملف مستقل لتحليل الأعراض وملف مستقل لتحليل الدم، بدون أسماء أو بريد إلكتروني." if ar else "Separate Excel files for symptom analysis and blood analysis, without names or email addresses.",
        "__BACK__": "العودة للأدمن" if ar else "Back to Admin",
        "__MESSAGE__": msg_html,
        "__SAVED_LABEL__": "تحليلات أعراض محفوظة" if ar else "Saved symptom analyses",
        "__SAVED__": str(int(summary.get("saved_analyses") or 0)),
        "__TESTERS_LABEL__": "حسابات جرّبت تحليل الأعراض" if ar else "Accounts that tried symptom analysis",
        "__TESTERS__": str(int(summary.get("distinct_testers") or 0)),
        "__EXCEL_FIELDS_TITLE__": "ملفات Excel" if ar else "Excel files",
        "__EXCEL_FIELDS__": "العمر • الجنس • الأعراض • المدة فقط" if ar else "Age • Gender • Symptoms • Duration only",
        "__SYM_FILE_TITLE__": "ملف تحليل الأعراض" if ar else "Symptom Analysis File",
        "__SYM_FILE_COUNT__": (f"{int(summary.get('saved_analyses') or 0)} تحليل محفوظ" if ar else f"{int(summary.get('saved_analyses') or 0)} saved analyses"),
        "__SYM_EXPORT__": "تحميل ملف تحليل الأعراض" if ar else "Download Symptom Analysis File",
        "__BLOOD_FILE_TITLE__": "ملف تحليل الدم" if ar else "Blood Analysis File",
        "__BLOOD_FILE_COUNT__": (f"{int(blood_summary.get('saved_tests') or 0)} تحليل محفوظ" if ar else f"{int(blood_summary.get('saved_tests') or 0)} saved analyses"),
        "__BLOOD_FIELDS__": "العمر • الجنس • القيم المنخفضة / الناقصة فقط" if ar else "Age • Gender • Low / deficient values only",
        "__BLOOD_EXPORT__": "تحميل ملف تحليل الدم" if ar else "Download Blood Analysis File",
        "__EXPORT__": "تنزيل Excel" if ar else "Download Excel",
        "__SYMPTOM_PREVIEW__": preview_html,
        "__GUEST_NOTE__": "تحليل الأعراض يُجمع عند تسجيل الدخول حسب إعدادات الخصوصية. تحليل الدم لا يُحفظ في ملف التجارب إلا بعد تسجيل الدخول والموافقة الصريحة على حفظ بيانات تحليل الدم." if ar else "Symptom analysis is collected while signed in according to privacy settings. Blood analysis is included in the trial file only after sign-in and explicit blood-data consent.",
        "__DELETE_TITLE__": "حذف تجارب تحليل الأعراض السابقة" if ar else "Delete Previous Symptom Trials",
        "__DELETE_DESC__": "يحذف تحليلات الأعراض ونتائجها المرتبطة فقط. لا يحذف الحسابات أو CBC أو الأدوية أو قاعدة المعرفة." if ar else "Deletes symptom-analysis trials and linked results only. Accounts, CBC data, medications, and the knowledge base are preserved.",
        "__PASSWORD_LABEL__": "كلمة مرور Admin الحالية" if ar else "Current Admin password",
        "__CONFIRM_LABEL__": "للتأكيد اكتب DELETE TRIALS" if ar else "Type DELETE TRIALS to confirm",
        "__DELETE_BUTTON__": "حذف تجارب تحليل الأعراض" if ar else "Delete Symptom Analysis Trials",
        "__CSRF__": html_lib.escape(_admin_csrf_token(), quote=True),
    }
    for key, value in replacements.items():
        html = html.replace(key, value)
    return _page("Trial Excel Files", html)


@route("/admin/<section>")
def admin_section(section):
    allowed={"knowledge-graph","anomalies","audit-log","ask-data","insights","ai-performance","explainable-ai","data-export","privacy-analytics","health-analytics","medications","heatmap","settings","dropoff","live-activity","content-gaps"}
    if section not in allowed:
        return redirect(url_for("admin"))
    if not _ss_user_id():
        return redirect(url_for("login", next=request.path))
    if not _admin_session_valid():
        if getattr(g, "admin_session_expired", False):
            return redirect(url_for("login", next=request.path))
        return _page("Admin", '<div class="card" style="max-width:560px;margin:40px auto;text-align:center"><h2>🔒 403</h2><p class="muted">Admin access only.</p><a class="btn" href="/home">Home</a></div>'), 403
    if section == "settings":
        return redirect(url_for("admin", view="adminsettings") + "#labTrialCleanupCard")
    return redirect(url_for("admin") + "#" + section)


@route("/api/admin/data-pulse", methods=["GET"])
def api_admin_data_pulse():
    """Aggregate, privacy-safe platform and knowledge counts for Admin only."""
    db.init_db()
    platform_v2.init_schema()
    medical_knowledge.init_schema()
    conn = db._conn()
    cur = conn.cursor()
    try:
        def count(sql, params=()):
            cur.execute(sql, params)
            row = cur.fetchone()
            return int((row or [0])[0] or 0)

        def table_exists(table):
            if db.USE_POSTGRES:
                cur.execute("SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=%s LIMIT 1", (table,))
                return cur.fetchone() is not None
            cur.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name=? LIMIT 1", (table,))
            return cur.fetchone() is not None

        def table_count(table, where=""):
            if not table_exists(table):
                return 0
            sql = "SELECT COUNT(*) FROM " + table + ((" WHERE " + where) if where else "")
            return count(sql)

        registered_users = count("SELECT COUNT(*) FROM ss_users WHERE COALESCE(role,'user') <> 'admin'")
        admin_accounts = count("SELECT COUNT(*) FROM ss_users WHERE COALESCE(role,'user') = 'admin'")
        unique_visitors = count("SELECT COUNT(DISTINCT user_hash) FROM visits") if table_exists("visits") else 0
        symptom_analyses = table_count("records")
        blood_tests = table_count("blood_tests")
        chat_messages = table_count("ss_chat_history")
        followups = table_count("symptom_followups")
        # ss_daily_checkins is the canonical table after migration. Never add
        # legacy + canonical counts because migrated rows may exist in both.
        daily_checkins = table_count("ss_daily_checkins") if table_exists("ss_daily_checkins") else table_count("daily_checkins")
        medication_plans = table_count("med_plans")
        medication_logs = table_count("med_logs")
        medication_reminders = table_count("med_reminders")
        feedback_rows = table_count("feedback")
        assistant_feedback = table_count("assistant_feedback")
        saved_comments = table_count("feedback", "comment IS NOT NULL AND TRIM(comment) <> ''")
        family_profiles = table_count("family_members")
        health_profiles = table_count("ss_health_profiles")
        visits = table_count("visits")
        usage_events = table_count("ss_usage_events")
        analysis_results = table_count("results")

        # This is deliberately a count of tracked application rows, not bytes on
        # disk and not a count of static medical-knowledge rows. The breakdown
        # makes the metric auditable and avoids presenting it as dataset size.
        user_generated_breakdown = {
            "symptom_analyses": symptom_analyses,
            "analysis_results": analysis_results,
            "blood_tests": blood_tests,
            "chat_messages": chat_messages,
            "followups": followups,
            "daily_checkins": daily_checkins,
            "medication_plans": medication_plans,
            "medication_logs": medication_logs,
            "medication_reminders": medication_reminders,
            "feedback": feedback_rows,
            "assistant_feedback": assistant_feedback,
            "family_profiles": family_profiles,
            "health_profiles": health_profiles,
            "visits": visits,
            "usage_events": usage_events,
        }
        stored_data_records = sum(user_generated_breakdown.values())
    finally:
        conn.close()

    knowledge = v51_innovation._knowledge_metrics()
    knowledge_total = int(knowledge.get("symptoms", 0)) + int(knowledge.get("diseases", 0)) + int(knowledge.get("links", 0)) + int(knowledge.get("red_rules", 0)) + int(knowledge.get("sources", 0)) + int(knowledge.get("combos", 0)) + int(knowledge.get("aliases_ar", 0)) + int(knowledge.get("aliases_en", 0))

    return jsonify({
        "ok": True,
        "people": {
            "registered_users": registered_users,
            "admin_accounts": admin_accounts,
            "unique_visitors": unique_visitors,
            "family_profiles": family_profiles,
        },
        "activity": {
            "symptom_analyses": symptom_analyses,
            "blood_tests": blood_tests,
            "chat_messages": chat_messages,
            "followups": followups,
            "daily_checkins": daily_checkins,
            "medication_plans": medication_plans,
            "medication_logs": medication_logs,
            "medication_reminders": medication_reminders,
            "feedback": feedback_rows,
            "assistant_feedback": assistant_feedback,
            "saved_comments": saved_comments,
        },
        "data": {
            "stored_data_records": stored_data_records,
            "metric_scope": "tracked_application_rows_not_storage_bytes",
            "breakdown": user_generated_breakdown,
            "knowledge_items": knowledge_total,
        },
        "knowledge": {
            "symptoms": int(knowledge.get("symptoms", 0)),
            "conditions": int(knowledge.get("diseases", 0)),
            "relationships": int(knowledge.get("links", 0)),
            "red_flag_rules": int(knowledge.get("red_rules", 0)),
            "verified_sources": int(knowledge.get("sources", 0)),
            "combos": int(knowledge.get("combos", 0)),
            "search_aliases": int(knowledge.get("aliases_ar", 0)) + int(knowledge.get("aliases_en", 0)),
        },
        "database_backend": "PostgreSQL" if db.USE_POSTGRES else "SQLite",
        "privacy_note": "Aggregate counts only; this endpoint does not return health text, emails, names, or message contents.",
    })


@route("/api/admin/quality-dashboard", methods=["GET"])
def api_admin_quality_dashboard():
    """Privacy-safe quality signals for symptom and laboratory analysis.

    Metrics are operational/verification indicators, not diagnostic accuracy.
    No symptom text, lab values, names, emails, or uploaded files are returned.
    """
    try:
        try:
            days = max(1, min(365, int(request.args.get("days") or 30)))
        except (TypeError, ValueError):
            days = 30
        db.init_db(); platform_v2.init_schema()
        since = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
        conn = db._conn(); cur = conn.cursor()
        try:
            def scalar(sql, params=()):
                cur.execute(sql, params)
                row = cur.fetchone()
                return int((row or [0])[0] or 0)

            symptom_success = scalar(
                f"SELECT COUNT(*) FROM ss_usage_events WHERE created_at>={db.PH} AND path='/api/analyze' AND event_type='analysis_complete'",
                (since,),
            )
            symptom_failed = scalar(
                f"SELECT COUNT(*) FROM ss_usage_events WHERE created_at>={db.PH} AND path='/api/analyze' AND event_type='error'",
                (since,),
            )
            safety_alerts = scalar(
                f"SELECT COUNT(*) FROM ss_usage_events WHERE created_at>={db.PH} AND service='symptom_analysis' AND event_type='safety_alert'",
                (since,),
            )
            blood_extract_success = scalar(
                f"SELECT COUNT(*) FROM ss_usage_events WHERE created_at>={db.PH} AND path='/api/blood' AND event_type='blood_extract_complete'",
                (since,),
            )
            blood_analysis_success = scalar(
                f"SELECT COUNT(*) FROM ss_usage_events WHERE created_at>={db.PH} AND path='/api/blood' AND event_type='blood_analysis_complete'",
                (since,),
            )
            blood_failed = scalar(
                f"SELECT COUNT(*) FROM ss_usage_events WHERE created_at>={db.PH} AND path='/api/blood' AND event_type='error'",
                (since,),
            )
            cur.execute(
                f"SELECT data FROM blood_tests WHERE timestamp>={db.PH} ORDER BY timestamp DESC",
                (since,),
            )
            blood_rows = cur.fetchall()
        finally:
            conn.close()

        saved_blood = 0
        confirmed_blood = 0
        files_with_meta = 0
        full_file_reads = 0
        pages_total = 0
        pages_read = 0
        total_indicators = 0
        sourced_indicators = 0
        needs_review_values = 0
        for row in blood_rows:
            raw = row[0] if row else None
            try:
                data = json.loads(raw) if isinstance(raw, str) else (raw or {})
            except (TypeError, ValueError, OverflowError):
                continue
            if not isinstance(data, dict):
                continue
            saved_blood += 1
            confirmed_blood += int(bool(data.get("confirmed_by_user")))
            meta = data.get("extraction_meta") if isinstance(data.get("extraction_meta"), dict) else {}
            if meta and bool(meta.get("server_verified")):
                # V153: completeness metrics only use metadata that was issued
                # by the server during the actual upload/extraction request.
                files_with_meta += 1
                try: pt = max(0, int(meta.get("pages_total") or 0))
                except (TypeError, ValueError): pt = 0
                try: pr = max(0, int(meta.get("pages_read") or 0))
                except (TypeError, ValueError): pr = 0
                pages_total += pt; pages_read += min(pr, pt) if pt else pr
                full_file_reads += int(bool(meta.get("complete_page_read")) and (not pt or pr >= pt))
            indicators = data.get("indicators") if isinstance(data.get("indicators"), list) else []
            for item in indicators:
                if not isinstance(item, dict):
                    continue
                total_indicators += 1
                src = item.get("source") if isinstance(item.get("source"), dict) else {}
                if src.get("url"):
                    sourced_indicators += 1
            verification = data.get("verification") if isinstance(data.get("verification"), dict) else {}
            counts = verification.get("counts") if isinstance(verification.get("counts"), dict) else {}
            needs_review_values += int(counts.get("needs_review") or 0) + int(counts.get("fallback_reference") or 0)

        safety_validation = safety_engine.validation_report()
        try:
            knowledge = medical_knowledge.statistics()
        except Exception:
            knowledge = {}

        symptom_total = symptom_success + symptom_failed
        blood_total = blood_analysis_success + blood_failed
        source_pct = round(sourced_indicators * 100.0 / total_indicators, 1) if total_indicators else 0.0
        full_read_pct = round(full_file_reads * 100.0 / files_with_meta, 1) if files_with_meta else 0.0
        return jsonify({
            "ok": True,
            "days": days,
            "symptoms": {
                "completed": symptom_success,
                "failed": symptom_failed,
                "success_rate": round(symptom_success * 100.0 / symptom_total, 1) if symptom_total else None,
                "safety_alerts": safety_alerts,
                "safety_validation": safety_validation,
                "knowledge_source_coverage_pct": knowledge.get("source_coverage_pct"),
                "symptom_support_coverage_pct": knowledge.get("symptom_support_coverage_pct"),
            },
            "blood": {
                "extractions_completed": blood_extract_success,
                "analyses_completed": blood_analysis_success,
                "failed_requests": blood_failed,
                "success_rate": round(blood_analysis_success * 100.0 / blood_total, 1) if blood_total else None,
                "saved_analyses": saved_blood,
                "confirmed_by_user": confirmed_blood,
                "files_with_completeness_metadata": files_with_meta,
                "full_file_reads": full_file_reads,
                "full_file_read_rate": full_read_pct if files_with_meta else None,
                "pages_read": pages_read,
                "pages_total": pages_total,
                "values_needing_review": needs_review_values,
                "source_linked_values": sourced_indicators,
                "total_values": total_indicators,
                "source_coverage_pct": source_pct if total_indicators else None,
            },
            "notes": {
                "accuracy_claim": "These are operational and verification metrics, not clinical diagnostic accuracy.",
                "telemetry_scope": "Request success/failure metrics include only sessions where optional analytics telemetry was permitted; saved blood-analysis aggregates are date-scoped, explicitly consented, and file-completeness counts use server-verified extraction metadata only.",
            },
        })
    except Exception as exc:
        return _mk_error(exc, 500)


@route("/api/admin/content-gaps", methods=["GET"])
def api_admin_content_gaps():
    """Actionable knowledge/search gaps without returning user identifiers."""
    try:
        try:
            days = max(1, min(365, int(request.args.get("days") or 30)))
            limit = max(5, min(100, int(request.args.get("limit") or 20)))
        except (TypeError, ValueError):
            days, limit = 30, 20
        return jsonify({
            "ok": True,
            "content_gaps": content_gaps.report(days=days, limit=limit),
            "external_priority_gaps": content_priority.content_gap_report(days=max(days, 90), limit=limit),
        })
    except Exception as exc:
        return _mk_error(exc, 500)


@route("/api/admin/system-health", methods=["GET"])
def api_admin_system_health():
    started = time.perf_counter()
    health = medical_knowledge.system_health()
    required = {"/admin", "/api/admin/v2/analytics", "/api/admin/system-health"}
    registered = {rule.rule for rule in app.url_map.iter_rules()}
    missing = sorted(required - registered)
    health["components"]["api"] = {
        "status": "online" if not missing else "offline",
        "response_ms": round((time.perf_counter() - started) * 1000, 1),
        "error": None if not missing else "Missing routes: " + ", ".join(missing),
    }
    if not _configured_web_secret and health["components"].get("authentication", {}).get("status") == "online":
        health["components"]["authentication"]["status"] = "degraded"
        health["components"]["authentication"]["error"] = "WEB_SECRET is not configured; sessions use an ephemeral process key"
    groq_configured = bool(os.environ.get("GROQ_API_KEY", "").strip())
    health["components"]["assistant_provider"] = {
        "status": "online" if groq_configured else "degraded",
        "configured": groq_configured,
        "fallback": "local_curated_health_fallback",
        "error": None if groq_configured else "GROQ_API_KEY is not configured; local fallback remains available",
    }
    return jsonify({"ok": True, "health": health})


@route("/api/admin/performance-benchmark", methods=["GET", "POST"])
def api_admin_performance_benchmark():
    """Return or run a bounded, Admin-only connection-pooling benchmark.

    GET is read-only and returns the most recent measured result. POST runs a
    short real benchmark against PostgreSQL and persists its aggregate metrics.
    No DSN, query parameters, health data, or user data are returned.
    """
    if request.method == "GET":
        return jsonify({
            "ok": True,
            "available": bool(db.USE_POSTGRES),
            "pooling_enabled": bool(db.USE_POSTGRES),
            "benchmark": performance_benchmark.latest_result(),
            "database_backend": "PostgreSQL" if db.USE_POSTGRES else "SQLite",
        })
    try:
        result = performance_benchmark.run_connection_pooling_benchmark(
            sequential_requests=25,
            concurrent_workers=6,
            requests_per_worker=3,
            benchmark_type="admin_quick",
            persist=True,
        )
        best_effort.call(platform_v2.audit, int(_ss_user_id()), 'ran', 'performance_benchmark', 'connection_pooling', None, {'sequential_requests': 25, 'concurrent_requests': 18, 'privacy': 'aggregate_technical_metrics_only'})
        return jsonify({"ok": True, "available": True, "pooling_enabled": True, "benchmark": result, "database_backend": "PostgreSQL"})
    except performance_benchmark.BenchmarkUnavailable:
        return jsonify({"ok": False, "error": "postgres_required"}), 409
    except performance_benchmark.BenchmarkBusy:
        return jsonify({"ok": False, "error": "benchmark_already_running"}), 409
    except Exception as exc:
        app.logger.warning("Performance benchmark failed; error_type=%s", type(exc).__name__)
        return jsonify({"ok": False, "error": "benchmark_failed"}), 500


@route("/api/admin/production-readiness", methods=["GET"])
def api_admin_production_readiness():
    try:
        rules = {rule.rule for rule in app.url_map.iter_rules()}
        return jsonify({"ok": True, "readiness": production_readiness.build(rules)})
    except Exception as exc:
        return _mk_error(exc)


@route("/api/admin/error-monitoring/status", methods=["GET"])
def api_admin_error_monitoring_status():
    state = production_verification.get("error_monitoring")
    return jsonify({
        "ok":True,
        "configured":bool(os.environ.get("SENTRY_DSN","").strip()),
        "enabled":bool(_sentry_enabled),
        "release":release_candidate.APP_VERSION,
        "environment":(os.environ.get("SENTRY_ENVIRONMENT") or os.environ.get("RAILWAY_ENVIRONMENT_NAME") or ("production" if os.environ.get("RAILWAY_ENVIRONMENT") else "development")),
        "last_test":state,
    })


@route("/api/admin/error-monitoring/test", methods=["POST"])
def api_admin_error_monitoring_test():
    """Emit a content-free Sentry test event. No request/user/health payload is attached."""
    if not _sentry_enabled:
        return jsonify({"ok":False,"error":"sentry_not_configured"}),400
    try:
        import sentry_sdk
        event_id = sentry_sdk.capture_message("symptosense_admin_monitoring_test", level="info")
        sentry_sdk.flush(timeout=2.0)
        eid = str(event_id or "")
        state = production_verification.record("error_monitoring","test_event_created",{"event_id":eid,"app_version":release_candidate.APP_VERSION})
        best_effort.call(platform_v2.audit, int(_ss_user_id()), 'tested_error_monitoring', 'system', 'sentry', None, {'event_id': eid[-12:] if eid else 'created'})
        return jsonify({"ok":True,"event_id":eid,"verification":state})
    except Exception as exc:
        app.logger.warning("Privacy-safe Sentry test failed: %s", type(exc).__name__)
        return jsonify({"ok":False,"error":"sentry_test_failed"}),502


@route("/api/admin/research-study", methods=["GET"])
def api_admin_research_study():
    return jsonify({"ok":True,"study":research_study.status(),"release":release_candidate.metadata()})


@route("/api/admin/research-study/freeze", methods=["POST"])
def api_admin_research_study_freeze():
    data=request.get_json(silent=True) or {}
    if str(data.get("confirmation") or "").strip().upper() != "FREEZE":
        return jsonify({"ok":False,"error":"freeze_confirmation_required"}),400
    study=research_study.freeze_current(_ss_user_id(), data.get("study_version"), data.get("note"))
    best_effort.call(platform_v2.audit, int(_ss_user_id()), 'froze_research_version', 'research', 'study_version', None, {'study_version': study.get('study_version'), 'app_version': study.get('app_version')})
    return jsonify({"ok":True,"study":study})


@route("/api/admin/research-validation/export", methods=["GET"])
def api_admin_research_validation_export():
    try:
        mode=(request.args.get("mode") or "results").strip().lower()
        blinded=mode in {"blinded","reviewer"}
        rows=research_validation.export_rows(blinded=blinded)
        buf=io.StringIO(newline="")
        if rows:
            writer=csv.DictWriter(buf,fieldnames=list(rows[0].keys()))
            writer.writeheader(); writer.writerows(rows)
        else:
            buf.write("case_code,case_summary,reference_risk\n")
        payload='\ufeff'+buf.getvalue()
        name='SymptoSense_Validation_Blinded_Reviewer.csv' if blinded else 'SymptoSense_Validation_Results.csv'
        return Response(payload,mimetype='text/csv; charset=utf-8',headers={'Content-Disposition':f'attachment; filename={name}'})
    except Exception as exc:
        return _mk_error(exc)


@route("/api/admin/research-validation", methods=["GET", "POST"])
def api_admin_research_validation():
    try:
        if request.method == "GET":
            return jsonify({"ok": True, "summary": research_validation.summary(), "cases": research_validation.list_cases(request.args.get("limit", 300))})
        item = research_validation.save_case(request.get_json(silent=True) or {})
        best_effort.call(platform_v2.audit, int(_ss_user_id()), 'created_research_validation_case', 'research_validation', str(item.get('id')), None, {'case_code': item.get('case_code'), 'reference_risk': item.get('reference_risk'), 'system_risk': item.get('system_risk')})
        return jsonify({"ok": True, "case": item}), 201
    except ValueError as exc:
        code=str(exc)
        if code in {"case_code_required","valid_reference_risk_required","verified_reference_requires_reviewer_and_source"}:
            return jsonify({"ok":False,"error":code}),400
        return _mk_error(exc)
    except Exception as exc:
        return _mk_error(exc)


@route("/api/admin/research-validation/<int:case_id>", methods=["PUT", "DELETE"])
def api_admin_research_validation_item(case_id):
    try:
        if request.method == "DELETE":
            ok = research_validation.delete_case(case_id)
            best_effort.call(platform_v2.audit, int(_ss_user_id()), 'deleted_research_validation_case', 'research_validation', str(case_id), None, {'deleted': bool(ok)})
            return jsonify({"ok": bool(ok)}) if ok else _mk_error("validation_case_not_found", 404)
        item = research_validation.save_case(request.get_json(silent=True) or {}, case_id)
        best_effort.call(platform_v2.audit, int(_ss_user_id()), 'updated_research_validation_case', 'research_validation', str(case_id), None, {'case_code': item.get('case_code'), 'reference_risk': item.get('reference_risk'), 'system_risk': item.get('system_risk')})
        return jsonify({"ok": True, "case": item})
    except ValueError as exc:
        code=str(exc)
        if code in {"case_code_required","valid_reference_risk_required","verified_reference_requires_reviewer_and_source","validation_case_not_found"}:
            return jsonify({"ok":False,"error":code}),400
        return _mk_error(exc)
    except Exception as exc:
        return _mk_error(exc)


@route("/api/admin/audit", methods=["GET"])
def api_admin_audit():
    try:
        limit = max(1, min(300, int(request.args.get("limit", 150))))
    except (TypeError, ValueError):
        limit = 150
    medical_rows = medical_knowledge.audit_log(limit)
    system_rows = platform_v2.audit_log(limit)
    privacy_rows = privacy_features.privacy_audit_events(limit)
    rows = [{**row, "source": "medical"} for row in medical_rows]
    for row in system_rows:
        rows.append({
            "id": row.get("id"), "admin_id": row.get("admin_id"),
            "action": row.get("action"), "entity_type": row.get("entity_type"), "entity_id": row.get("entity_id"),
            "previous_value": row.get("previous_value"), "new_value": row.get("new_value"), "timestamp": row.get("timestamp"), "source": "system",
        })
    rows.extend(privacy_rows)
    for row in rows:
        action = str(row.get("action") or "")
        row["result"] = "failed" if ("failed" in action or "denied" in action) else ("expired" if "timeout" in action else "success")
        row["admin_account"] = db.OWNER_ADMIN_EMAIL if (row.get("admin_id") or row.get("entity_id") == "owner") else ("User/Privacy" if row.get("source") == "privacy" else "System")
    rows.sort(key=lambda x: str(x.get("timestamp") or ""), reverse=True)
    return jsonify({"ok": True, "audit": rows[:limit]})


@route("/api/admin/users", methods=["GET"])
def api_admin_users():
    return jsonify({"ok": True, "users": platform_v2.list_users_admin()})


@route("/api/admin/users/<int:user_id>/role", methods=["PUT"])
def api_admin_user_role(user_id):
    return jsonify({"ok": False, "error": "role_management_disabled"}), 403


@route("/api/admin/v2/analytics", methods=["GET"])
def api_admin_v2_analytics():
    try:
        return jsonify({"ok": True, "analytics": platform_v2.analytics_summary(request.args.get("days", 30))})
    except Exception as exc:
        return _mk_error(exc)


@route("/api/admin/complete-analytics", methods=["GET"])
def api_admin_complete_analytics():
    try:
        return jsonify({"ok": True, "analytics": admin_complete.complete_analytics(request.args.get("days", 30))})
    except Exception as exc:
        return _mk_error(exc)


@route("/api/admin/content", methods=["GET", "POST"])
def api_admin_content():
    try:
        if request.method == "GET":
            return jsonify({"ok": True, "content": platform_v2.list_content(False, request.args.get("q", ""), request.args.get("type", ""))})
        return jsonify({"ok": True, "content": platform_v2.save_content(request.get_json(silent=True) or {}, int(_ss_user_id()))})
    except Exception as exc:
        return _mk_error(exc)


@route("/api/admin/content/<int:content_id>", methods=["GET", "PUT", "DELETE"])
def api_admin_content_item(content_id):
    try:
        if request.method == "GET":
            item = platform_v2.get_content(content_id)
            return jsonify({"ok": bool(item), "content": item}) if item else _mk_error("not_found", 404)
        if request.method == "DELETE":
            platform_v2.delete_content(content_id, int(_ss_user_id()))
            return jsonify({"ok": True})
        return jsonify({"ok": True, "content": platform_v2.save_content(request.get_json(silent=True) or {}, int(_ss_user_id()), content_id)})
    except Exception as exc:
        return _mk_error(exc)


@route("/api/admin/users/<int:user_id>/status", methods=["PUT"])
def api_admin_user_status(user_id):
    try:
        data = request.get_json(silent=True) or {}
        return jsonify({"ok": True, "user": platform_v2.set_user_status(user_id, data.get("status"), int(_ss_user_id()))})
    except Exception as exc:
        return _mk_error(exc)


@route("/api/admin/security/activity", methods=["GET"])
def api_admin_security_activity():
    return jsonify({"ok": True, "activity": platform_v2.login_activity(request.args.get("limit", 200))})


@route("/api/admin/security/audit", methods=["GET"])
def api_admin_security_audit():
    return jsonify({"ok": True, "audit": platform_v2.audit_log(request.args.get("limit", 200))})


@route("/api/admin/analytics-export/preview", methods=["GET"])
def api_admin_analytics_export_preview():
    try:
        filters=_admin_analytics_filters()
        return jsonify({"ok":True, **admin_operational.medication_analytics_preview(filters)})
    except Exception as exc: return _mk_error(exc)


@route("/api/admin/analytics-export/xlsx", methods=["GET"])
def api_admin_analytics_export_xlsx():
    filters=_admin_analytics_filters()
    try:
        supplied=request.headers.get("X-CSRF-Token",""); expected=session.get("admin_csrf","")
        if not expected or not secrets.compare_digest(supplied,expected):
            return jsonify({"ok":False,"error":"csrf_failed"}),403
        buf=admin_operational.export_medication_analytics_excel(filters)
        filter_types=[k for k in ("age_group","gender","medication","symptom","risk") if filters.get(k)]
        platform_v2.audit(int(_ss_user_id()),"exported","analytics","medication_analytics",None,{"period":filters.get("period"),"filter_types":filter_types,"privacy":"aggregated_anonymized"})
        stamp=datetime.now().strftime("%Y-%m-%d")
        return send_file(buf,mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",as_attachment=True,download_name=f"SymptoSense_Data_Analytics_{stamp}.xlsx")
    except Exception as exc:
        best_effort.call(platform_v2.audit, int(_ss_user_id()), 'export_failed', 'analytics', 'medication_analytics', None, {'error_type': type(exc).__name__})
        return _mk_error(exc)


@route("/api/admin/dropoff", methods=["GET"])
def api_admin_dropoff():
    try:
        period=(request.args.get("period") or "30d").lower()
        if period not in {"today","7d","30d","90d","custom"}: period="30d"
        device=(request.args.get("device") or "").lower()
        if device not in {"","mobile","desktop","tablet"}: device=""
        return jsonify({"ok":True,"dropoff":admin_operational.dropoff_analysis(period,request.args.get("start"),request.args.get("end"),device)})
    except Exception as exc: return _mk_error(exc)


@route("/api/admin/live-activity", methods=["GET"])
def api_admin_live_activity():
    try:
        cat=(request.args.get("category") or "all").lower()
        if cat not in {"all","analysis","assistant","reports","authentication","system"}: cat="all"
        win=(request.args.get("window") or "hour").lower()
        if win not in {"hour","today","7d"}: win="hour"
        return jsonify({"ok":True,"activity":admin_operational.live_activity(request.args.get("limit",80),cat,win)})
    except Exception as exc: return _mk_error(exc)


@route("/api/admin/ui-audit", methods=["POST"])
def api_admin_ui_audit():
    data=request.get_json(silent=True) or {}; action=str(data.get("action") or "")
    allowed={"opened_analytics","changed_analytics_filters","opened_live_activity","changed_dashboard_settings","opened_dropoff"}
    if action not in allowed: return jsonify({"ok":False,"error":"invalid_action"}),400
    platform_v2.audit(int(_ss_user_id()),action,"admin_dashboard",None,None,{"section":str(data.get("section") or "")[:40]})
    return jsonify({"ok":True})


@route("/api/admin/analysis-results", methods=["GET"])
def api_admin_analysis_results():
    """Pseudonymized, consent-eligible saved symptom-analysis results for research review."""
    try:
        data = admin_complete.admin_analysis_results(
            query=request.args.get("q", ""),
            risk=request.args.get("risk", ""),
            lang=request.args.get("lang", ""),
            page=request.args.get("page", 1),
            per_page=request.args.get("per_page", 50),
        )
        return jsonify({"ok": True, "results": data})
    except Exception as exc:
        return _mk_error(exc)


@route("/api/admin/analysis-trials", methods=["GET"])
@route("/api/admin/lab-trials", methods=["GET"])
def api_admin_lab_trials():
    """Privacy-safe count of saved symptom-analysis trials."""
    try:
        db.init_db()
        return jsonify({"ok": True, "summary": db.admin_symptom_trial_summary()})
    except Exception as exc:
        return _mk_error(exc, 500)


@route("/api/admin/analysis-trials/export-xlsx", methods=["GET"])
@route("/api/admin/lab-trials/export-xlsx", methods=["GET"])
def api_admin_export_lab_trials_xlsx():
    """Compatibility endpoint; use the browser-native symptom-trial download."""
    return redirect(url_for("admin_lab_trials_export_xlsx"), code=302)


@route("/api/admin/blood-trials", methods=["GET"])
def api_admin_blood_trials():
    """Privacy-safe count of saved blood analyses."""
    try:
        db.init_db()
        return jsonify({"ok": True, "summary": db.admin_blood_collection_summary()})
    except Exception as exc:
        return _mk_error(exc, 500)


@route("/api/admin/blood-trials/export-xlsx", methods=["GET"])
def api_admin_export_blood_trials_xlsx():
    return redirect(url_for("admin_blood_trials_export_xlsx"), code=302)


@route("/api/admin/analysis-trials/clear", methods=["POST"])
@route("/api/admin/lab-trials/clear", methods=["POST"])
def api_admin_clear_lab_trials():
    """Delete saved symptom-analysis trials without deleting accounts."""
    data = request.get_json(silent=True) or {}
    confirmation = str(data.get("confirmation") or "").strip().upper()
    current_password = str(data.get("current_password") or "")
    # DELETE LABS remains accepted only for old cached Admin pages.
    if confirmation not in {"DELETE TRIALS", "DELETE LABS"}:
        return jsonify({"ok": False, "error": "trial_delete_confirmation_required"}), 400
    if not db.verify_ss_user_password(_ss_user_id(), current_password):
        return jsonify({"ok": False, "error": "current_password_incorrect"}), 403
    try:
        result = db.admin_clear_symptom_trials()
        best_effort.call(platform_v2.audit, int(_ss_user_id()), 'clear_symptom_trials', 'admin_data', 'records', None, {'deleted_analyses': int(result.get('deleted_analyses') or 0), 'affected_testers': int(result.get('affected_testers') or 0), 'accounts_deleted': False, 'blood_tests_deleted': False})
        return jsonify({"ok": True, "cleared": result})
    except Exception as exc:
        app.logger.exception(
            "Admin symptom-trial cleanup failed; request_id=%s",
            getattr(g, "request_id", ""),
        )
        return _mk_error(exc, 500)


@route("/api/admin/reset-test-data", methods=["POST"])
def api_admin_reset_test_data():
    """Prepare SymptoSense for public launch by removing test/user data.

    Disabled by default after launch. It must be explicitly enabled with
    ALLOW_LAUNCH_RESET=1 in addition to Admin auth, CSRF and password confirmation.
    """
    if os.environ.get("ALLOW_LAUNCH_RESET", "0").strip().lower() not in {"1","true","yes","on"}:
        return jsonify({"ok": False, "error": "launch_reset_disabled"}), 403
    data = request.get_json(silent=True) or {}
    confirmation = str(data.get("confirmation") or "").strip().upper()
    current_password = str(data.get("current_password") or "")
    if confirmation != "RESET":
        return jsonify({"ok": False, "error": "reset_confirmation_required"}), 400
    if not db.verify_ss_user_password(_ss_user_id(), current_password):
        return jsonify({"ok": False, "error": "current_password_incorrect"}), 403
    try:
        summary = db.reset_public_launch_data(_ss_user_id())
        # The reset clears historical audit rows; record one fresh, non-sensitive
        # event proving that a deliberate launch reset occurred.
        best_effort.call(platform_v2.audit, int(_ss_user_id()), 'public_launch_reset', 'admin_data', 'all_test_data', None, {'removed_users': int(summary.get('removed_users') or 0), 'deleted_rows': int(summary.get('deleted_rows') or 0), 'preserved_admin': True, 'preserved_medical_knowledge': True})
        return jsonify({"ok": True, "reset": summary})
    except Exception as exc:
        app.logger.exception("Admin public-launch reset failed")
        return _mk_error(exc)


@route("/api/admin/export/xlsx", methods=["GET"])
def api_admin_export_xlsx():
    try:
        supplied=request.headers.get("X-CSRF-Token",""); expected=session.get("admin_csrf","")
        if not expected or not secrets.compare_digest(supplied,expected):
            return jsonify({"ok":False,"error":"csrf_failed"}),403
        buf = admin_complete.export_admin_workbook("official")
        platform_v2.audit(int(_ss_user_id()), "exported", "admin_data", "excel", None, {"format": "xlsx", "privacy": "pseudonymized_consent_eligible", "sheets": 4, "purpose": "scientific_research_export", "dataset_scope": "official_frozen"})
        stamp = datetime.now().strftime("%Y-%m-%d")
        return send_file(buf, mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", as_attachment=True, download_name=f"SymptoSense_Research_Export_{stamp}.xlsx")
    except Exception as exc:
        best_effort.call(platform_v2.audit, int(_ss_user_id()), 'export_failed', 'admin_data', 'excel', None, {'error_type': type(exc).__name__})
        return _mk_error(exc)


@route("/api/admin/export/pilot-xlsx", methods=["GET"])
def api_admin_export_pilot_xlsx():
    """Export eligible Pilot/non-frozen rows separately from official study data."""
    try:
        supplied=request.headers.get("X-CSRF-Token",""); expected=session.get("admin_csrf","")
        if not expected or not secrets.compare_digest(supplied,expected):
            return jsonify({"ok":False,"error":"csrf_failed"}),403
        buf = admin_complete.export_admin_workbook("pilot")
        platform_v2.audit(int(_ss_user_id()), "exported", "admin_data", "excel", None, {"format":"xlsx","privacy":"pseudonymized_consent_eligible","sheets":4,"purpose":"scientific_research_pilot_export"})
        stamp = datetime.now().strftime("%Y-%m-%d")
        return send_file(buf, mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", as_attachment=True, download_name=f"SymptoSense_Pilot_Data_{stamp}.xlsx")
    except Exception as exc:
        best_effort.call(platform_v2.audit, int(_ss_user_id()), 'export_failed', 'admin_data', 'pilot_excel', None, {'error_type': type(exc).__name__})
        return _mk_error(exc)


@route("/api/admin/audit/export", methods=["GET"])
def api_admin_audit_export():
    try:
        supplied=request.headers.get("X-CSRF-Token",""); expected=session.get("admin_csrf","")
        if not expected or not secrets.compare_digest(supplied,expected):
            return jsonify({"ok":False,"error":"csrf_failed"}),403
        buf = advanced_features.export_audit_excel()
        platform_v2.audit(int(_ss_user_id()), "exported", "audit_log", "excel", None, {"format": "xlsx"})
        stamp = datetime.now().strftime("%Y-%m-%d")
        return send_file(buf, mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", as_attachment=True, download_name=f"SymptoSense_Audit_{stamp}.xlsx")
    except Exception as exc:
        return _mk_error(exc)


@route("/api/admin/ai-performance", methods=["GET"])
def api_admin_ai_performance():
    try:
        performance=advanced_features.ai_performance(request.args.get("days",30))
        performance["model"]=admin_complete.model_card()
        return jsonify({"ok":True,"performance":performance})
    except Exception as exc: return _mk_error(exc)


@route("/api/admin/explainable-ai", methods=["GET"])
def api_admin_explainable_ai():
    try:
        return jsonify({"ok": True, "explainability": admin_complete.explainable_ai()})
    except Exception as exc:
        return _mk_error(exc)


@route("/api/admin/profile", methods=["GET"])
def api_admin_profile():
    user=_ss_user() or {}
    try: timeout=max(5,min(240,int(os.environ.get("ADMIN_SESSION_TIMEOUT_MINUTES","30"))))
    except (TypeError,ValueError): timeout=30
    uid=int(user.get("id") or _ss_user_id())
    try: two_factor=admin_2fa.status(uid)
    except Exception: logging.getLogger(__name__).warning("Handled exception in api_admin_profile; fallback applied (handler 15027)"); two_factor={"enabled":False}
    try: session_control=admin_security.status(uid)
    except Exception: logging.getLogger(__name__).warning("Handled exception in api_admin_profile; fallback applied (handler 15029)"); session_control={"session_epoch":None,"forced_logout_at":None}
    return jsonify({"ok":True,"profile":{
        "email":user.get("email"),"role":"Administrator","last_login":user.get("last_login"),
        "session_timeout_minutes":timeout,"change_password_available":True,
        "two_factor_available":bool(admin_2fa.available()),
        "two_factor_status":"enabled" if two_factor.get("enabled") else "setup_required",
        "session_epoch":session_control.get("session_epoch"),
        "last_forced_logout":session_control.get("forced_logout_at"),
        "logout_all_sessions_available":True,
    }})


@route("/api/admin/profile/password", methods=["POST"])
def api_admin_profile_password():
    data=request.get_json(silent=True) or {}
    current=str(data.get("current_password") or ""); new=str(data.get("new_password") or "")
    confirm=str(data.get("confirm_password") or "")
    if not hmac.compare_digest(new,confirm):
        return jsonify({"ok":False,"error":"password_mismatch"}),400
    ok,error=db.change_ss_user_password(int(_ss_user_id()),current,new)
    if not ok:
        best_effort.call(platform_v2.audit, int(_ss_user_id()), 'password_change_failed', 'admin_security', 'self', None, {'status': 'failed', 'reason': error})
        return jsonify({"ok":False,"error":error}),400
    user_id=int(_ss_user_id())
    admin_security.rotate_epoch(user_id)
    platform_v2.audit(user_id,"password_changed","admin_security","self",None,{"status":"success","all_admin_sessions_revoked":True})
    # A password change is a security boundary: every old Admin session,
    # including this browser, must authenticate again and complete 2FA.
    session.clear()
    return jsonify({"ok":True,"message":"password_changed_reauth_required","login_url":"/login?next=/admin"})


@route("/api/admin/sessions/logout-all", methods=["POST"])
def api_admin_logout_all_sessions():
    if not _request_allowed("admin_logout_all", 5, 600, str(_ss_user_id() or "")):
        return _rate_limited_response()
    data=request.get_json(silent=True) or {}
    password=str(data.get("current_password") or "")
    uid=int(_ss_user_id())
    if not password or not db.verify_ss_user_password(uid,password):
        best_effort.call(platform_v2.audit, uid, 'logout_all_sessions_failed', 'admin_security', 'self', None, {'status': 'failed'})
        return jsonify({"ok":False,"error":"current_password_incorrect"}),403
    new_epoch=admin_security.rotate_epoch(uid)
    best_effort.call(platform_v2.audit, uid, 'logout_all_sessions', 'admin_security', 'self', None, {'status': 'success', 'session_epoch': new_epoch})
    session.clear()
    return jsonify({"ok":True,"login_url":"/login?next=/admin"})


@route("/api/admin/knowledge-graph", methods=["GET"])
def api_admin_knowledge_graph():
    try: return jsonify({"ok": True, "graph": advanced_features.knowledge_graph_data()})
    except Exception as exc: return _mk_error(exc)


@route("/api/admin/anomalies", methods=["GET"])
def api_admin_anomalies():
    try: return jsonify({"ok": True, "anomalies": advanced_features.anomaly_detection()})
    except Exception as exc: return _mk_error(exc)


@route("/api/admin/automatic-insights", methods=["GET"])
def api_admin_automatic_insights():
    try: return jsonify({"ok": True, "insights": advanced_features.automatic_insights()})
    except Exception as exc: return _mk_error(exc)


@route("/api/admin/privacy-analytics", methods=["GET"])
def api_admin_privacy_analytics():
    try:
        return jsonify({"ok": True, "analytics": privacy_features.anonymous_health_analytics()})
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/admin/ask-data", methods=["POST"])
def api_admin_ask_data():
    try:
        data=request.get_json(silent=True) or {}
        answer=advanced_features.ask_your_data(data.get("question", ""), "en" if data.get("lang")=="en" else "ar")
        if answer.get("ok"):
            platform_v2.audit(int(_ss_user_id()), "queried", "ask_your_data", "aggregate", None, {"result_type": answer.get("type")})
        return jsonify(answer), (200 if answer.get("ok") else 400)
    except Exception as exc: return _mk_error(exc)


@route("/api/admin/funnel-by-mode", methods=["GET"])
def api_admin_funnel_by_mode():
    try:
        days = int(request.args.get("days", 30))
    except (TypeError, ValueError):
        days = 30
    return jsonify({"ok": True, "funnel": admin_operational.mode_completion(days)})


@route("/api/admin/medical-source-review", methods=["GET"])
def api_admin_medical_source_review_list():
    try:
        limit = max(1, min(200, int(request.args.get("limit") or 100)))
        return jsonify({
            "ok": True,
            "items": medical_source_pipeline.pending(limit),
            "source_gaps": health_library.source_quality_audit()[:500],
            "icd11_coverage": medical_taxonomy.coverage_report(),
            "external_priority_gaps": content_priority.content_gap_report(limit=100),
        })
    except Exception as exc:
        return _mk_error(exc, 500)


@route("/api/admin/medical-source-review/fetch", methods=["POST"])
def api_admin_medical_source_review_fetch():
    try:
        data = request.get_json(silent=True) or {}
        term = str(data.get("term") or "").strip()[:240]
        if not term:
            return jsonify({"ok": False, "error": "missing_term"}), 400
        lang = "en" if data.get("lang") == "en" else "ar"
        result = medical_source_pipeline.queue_research_bundle(
            term, lang, data.get("nhs_section"), data.get("nhs_slug")
        )
        return jsonify({"ok": True, **result})
    except ValueError:
        return jsonify({"ok": False, "error": "invalid_request"}), 400
    except Exception as exc:
        return _mk_error(exc, 500)


@route("/api/admin/icd11/candidates", methods=["POST"])
def api_admin_icd11_candidates():
    try:
        data=request.get_json(silent=True) or {}
        kind=str(data.get("kind") or "").strip()
        entity_id=int(data.get("entity_id") or 0)
        if kind not in {"disease","symptom"} or entity_id<=0:
            return jsonify({"ok":False,"error":"invalid_entity"}),400
        items=medical_taxonomy.queue_entity_candidates(kind,entity_id,limit=int(data.get("limit") or 5))
        return jsonify({"ok":True,"items":items})
    except (ValueError,TypeError):
        return jsonify({"ok":False,"error":"invalid_request"}),400
    except Exception as exc:
        return _mk_error(exc,500)


@route("/api/admin/icd11/approve", methods=["POST"])
def api_admin_icd11_approve():
    try:
        data=request.get_json(silent=True) or {}
        mapping_id=int(data.get("mapping_id") or 0)
        if mapping_id<=0:
            return jsonify({"ok":False,"error":"invalid_mapping"}),400
        reviewer=str(_ss_user_id() or "admin")
        return jsonify({"ok":True,"mapping":medical_taxonomy.approve_mapping(mapping_id,reviewer)})
    except (ValueError,TypeError):
        return jsonify({"ok":False,"error":"invalid_request"}),400
    except Exception as exc:
        return _mk_error(exc,500)


@route("/api/admin/content-priority/search-console-sync", methods=["POST"])
def api_admin_content_priority_gsc():
    try:
        data=request.get_json(silent=True) or {}
        return jsonify({"ok":True,**content_priority.fetch_search_console(days=int(data.get("days") or 28),country=str(data.get("country") or "sau"))})
    except (ValueError,TypeError):
        return jsonify({"ok":False,"error":"invalid_request"}),400
    except Exception as exc:
        return _mk_error(exc,500)


@route("/api/admin/content-priority/trends-import", methods=["POST"])
def api_admin_content_priority_trends():
    try:
        data=request.get_json(silent=True) or {}
        csv_text=str(data.get("csv") or "")
        if not csv_text.strip():
            return jsonify({"ok":False,"error":"missing_csv"}),400
        return jsonify({"ok":True,**content_priority.import_google_trends_csv(csv_text,country=str(data.get("country") or "SA"))})
    except Exception as exc:
        return _mk_error(exc,500)


@route("/api/admin/medication-email/status", methods=["GET"])
def api_admin_medication_email_status():
    try:
        return jsonify({"ok": True, **medication_email.delivery_summary(100)})
    except Exception as exc:
        return _mk_error(exc)


def register_routes(app, namespace):
    """Inject webapp dependencies, apply the original decorators, and add the URL rules (same endpoint names)."""
    missing = [n for n in DEPS if n not in namespace]
    if missing:
        raise RuntimeError("routes.admin: missing dependencies %s" % missing)
    g = globals()
    for n in DEPS:
        g[n] = _inject.dependency(namespace, n)
    g["app"] = app
    for name, spec in _SPECS.items():
        view = spec["fn"]
        for w in reversed(_WRAPPERS.get(name, ())):
            view = _inject.resolve_wrapper(w, g)(view)
        for rule, opts in spec["rules"]:
            kw = dict(opts)
            endpoint = kw.pop("endpoint", name)
            app.add_url_rule(rule, endpoint=endpoint, view_func=view, **kw)
