"""Routes for group "assistant", moved out of webapp.py (behaviour unchanged).

Dependencies from webapp.py are injected by register(); decorators like login_required are applied there in the
original order. Generated by tools/extract_routes.py.
"""
from routes import _inject
from demo_analysis import demo_analysis_result
from flask import g
from flask import jsonify
from flask import request
from flask import send_file
from search_support import _health_search_query_shell
from search_support import _health_search_result_relevant
import admin_operational
import advanced_features
import analysis_core
import best_effort
import calculators as calcmod
import clinical_signoff
import clinical_text
import content_gaps
import db
import decision_log
import external_drug_lookup
import feature_flags
import health_search
import io
import json
import logging
import medical_knowledge
import medication_warnings
import ops_metrics
import os
import platform_v2
import privacy_features
import re
import safety_engine
import search_engine_v2
import search_fidelity
import search_lab_cards
import symptom_context
import symptom_guidance

DEPS = ("_analysis_input_error", "_analytics_consent_ok", "_analytics_session_id", "_assistant_compact_response", "_assistant_contextual_health_answer", "_assistant_extended_symptom_reply", "_assistant_general_local_fallback", "_assistant_local_health_answer", "_assistant_local_mental_answer", "_assistant_services", "_augment_analysis_sources", "_bounded_env_int", "_consent_required_json", "_consent_state", "_data_user_id", "_ensure_analysis_match_sources", "_groq_chat_completion_with_retry", "_health_search_medication_context", "_health_search_question_answer", "_health_search_relation_result", "_lang", "_local_request_allowed", "_local_symptom_hits", "_mk_error", "_normalize_health_query_text", "_pdf_report", "_plain_topic_curated_result", "_rate_limited_response", "_request_allowed", "_request_rate_identity", "_research_consent_ok", "_sanitize_analysis_notes_for_safety", "_search_contextual_structured_result", "_service_consent_ok", "_ss_user_id", "_voice_parse", "api_login_required", )

_SPECS = {}
_WRAPPERS = {
    "api_symptoms_extract": (),
    "api_diseases": (),
    "api_disease_detail": (),
    "api_disease_sources": (),
    "api_symptoms": (),
    "api_symptom_detail": (),
    "api_symptom_sources": (),
    "api_voice_parse": (),
    "api_voice": (),
    "api_analyze_differential_question": (),
    "api_analyze_data_quality": (),
    "api_analyze_safety_check": (),
    "api_analyze": (),
    "api_export_pdf": ('api_login_required', ),
    "api_export_current_pdf": (),
    "api_assistant": (),
    "api_assistant_feedback": (),
    "api_search_suggestions": (),
    "api_search": (),
    "api_calc": (),
    "api_drug": (),
}


def route(rule, **opts):
    def deco(fn):
        _SPECS.setdefault(fn.__name__, {"fn": fn, "rules": []})["rules"].append((rule, opts))
        return fn
    return deco


@route("/api/symptoms/extract", methods=["POST"])
def api_symptoms_extract():
    data=request.get_json(silent=True) or {}
    lang="en" if data.get("lang")=="en" else "ar"
    text=data.get("text", "")
    try:
        result=advanced_features.smart_extract_symptoms(text, lang) or {}
    except Exception:
        logging.getLogger(__name__).warning("Handled exception in api_symptoms_extract; fallback applied (handler 14079)")
        result={}
    found=list(result.get("found") or [])
    seen=set()
    for item in found:
        key=str(item.get("slug") or item.get("name_ar") or item.get("name_en") or "").strip().lower()
        if key: seen.add(key)
    for item in _local_symptom_hits(text):
        key=item["slug"].lower()
        if key not in seen:
            found.append(item); seen.add(key)
    result["found"]=found[:24]
    # Natural-language context is extracted deterministically from the user's own
    # wording. It is used only to avoid repetitive questions and to summarize
    # timing/triggers; it never creates a diagnosis.
    result["context"] = symptom_context.extract_context(text, found=found[:24], lang=lang)
    # Keep unknown free-text symptoms instead of forcing a wrong match.  The
    # client then routes them through a body-system/context clarifier.
    result["lexicon_version"]="symptom-universal-context-v4"
    return jsonify({"ok": True, **result})


@route("/api/diseases", methods=["GET"])
def api_diseases():
    try:
        rows = medical_knowledge.list_entities(
            "diseases", False, request.args.get("q", ""),
            request.args.get("category"), request.args.get("severity"),
        )
        return jsonify({"ok": True, "diseases": rows})
    except Exception as exc:
        return _mk_error(exc)


@route("/api/diseases/<int:entity_id>", methods=["GET"])
def api_disease_detail(entity_id):
    item = medical_knowledge.get_entity("disease", entity_id, public=True)
    return jsonify({"ok": bool(item), "disease": item}) if item else _mk_error("not_found", 404)


@route("/api/diseases/<int:entity_id>/sources", methods=["GET"])
def api_disease_sources(entity_id):
    item = medical_knowledge.get_entity("disease", entity_id, public=True)
    return jsonify({"ok": bool(item), "sources": (item or {}).get("sources", [])}) if item else _mk_error("not_found", 404)


@route("/api/symptoms", methods=["GET"])
def api_symptoms():
    try:
        rows = medical_knowledge.list_entities(
            "symptoms", False, request.args.get("q", ""), request.args.get("category")
        )
        return jsonify({"ok": True, "symptoms": rows})
    except Exception as exc:
        return _mk_error(exc)


@route("/api/symptoms/<int:entity_id>", methods=["GET"])
def api_symptom_detail(entity_id):
    item = medical_knowledge.get_entity("symptom", entity_id, public=True)
    return jsonify({"ok": bool(item), "symptom": item}) if item else _mk_error("not_found", 404)


@route("/api/symptoms/<int:entity_id>/sources", methods=["GET"])
def api_symptom_sources(entity_id):
    item = medical_knowledge.get_entity("symptom", entity_id, public=True)
    return jsonify({"ok": bool(item), "sources": (item or {}).get("sources", [])}) if item else _mk_error("not_found", 404)


@route("/api/voice/parse", methods=["POST"])
def api_voice_parse():
    if not _service_consent_ok():
        return jsonify({"ok":False,"error":"consent_required","consent_url":"/consent?next=/chat"}),403
    data=request.get_json(silent=True) or {}; text=str(data.get("text") or "").strip()[:1200]
    lang="en" if data.get("lang")=="en" else "ar"
    if not text:
        return jsonify({"ok":False,"error":"empty_transcript"}),400
    return jsonify({"ok":True,"text":text,"parsed":_voice_parse(text,lang),"audio_stored":False})


@route("/api/voice", methods=["POST"])
def api_voice():
    """Transcribe a short, user-initiated voice answer when browser speech recognition is unavailable.

    The audio is handled in memory for this request and is not stored by SymptoSense.
    External transcription is used only when the user has already granted service consent.
    """
    if not _service_consent_ok():
        return jsonify({"ok":False,"error":"consent_required","consent_required":True,"consent_url":"/consent?next=/chat","audio_stored":False}),403
    try:
        voice_max = max(2, min(60, int(os.environ.get("VOICE_RATE_LIMIT_MAX", "12") or 12)))
        voice_window = max(60, int(os.environ.get("VOICE_RATE_LIMIT_WINDOW_SECONDS", "300") or 300))
    except (TypeError, ValueError):
        voice_max, voice_window = 12, 300
    if not _request_allowed("voice_stt", voice_max, voice_window):
        return _rate_limited_response()
    f = request.files.get("audio")
    if not f:
        return jsonify({"ok":False,"error":"missing_audio","audio_stored":False}),400
    voice_upload_limit = _bounded_env_int("VOICE_UPLOAD_MAX_BYTES", 8 * 1024 * 1024, 1024 * 1024, 12 * 1024 * 1024)
    raw = f.read(voice_upload_limit + 1)
    if not raw:
        return jsonify({"ok":False,"error":"empty_audio","audio_stored":False}),400
    if len(raw) > voice_upload_limit:
        return jsonify({"ok":False,"error":"audio_too_large","audio_stored":False}),413
    lang = "en" if request.form.get("lang") == "en" else "ar"
    filename = (f.filename or "symptosense-voice.webm").strip() or "symptosense-voice.webm"
    filename = re.sub(r"[^A-Za-z0-9._-]+", "-", filename)[-120:]
    try:
        client = analysis_core._groq_client()
        audio_file = io.BytesIO(raw)
        audio_file.name = filename
        tr = client.audio.transcriptions.create(
            file=audio_file,
            model=os.environ.get("VOICE_STT_MODEL", "whisper-large-v3-turbo"),
            language="en" if lang == "en" else "ar",
            response_format="json",
            temperature=0.0,
        )
        text = str(getattr(tr, "text", "") or (tr.get("text") if isinstance(tr, dict) else "")).strip()[:1200]
        if not text:
            return jsonify({"ok":False,"error":"empty_transcript","audio_stored":False}),422
        return jsonify({"ok":True,"text":text,"parsed":_voice_parse(text,lang),"audio_stored":False})
    except Exception as e:
        request_id = getattr(g, "request_id", "")
        app.logger.warning("Voice transcription unavailable; request_id=%s error_type=%s", request_id, type(e).__name__)
        return jsonify({
            "ok":False,
            "error":"تعذر تحويل الصوت إلى نص حاليًا. حاول مرة أخرى أو استخدم الكتابة." if lang=="ar" else "Unable to transcribe audio right now. Try again or use typing.",
            "request_id":request_id,
            "audio_stored":False,
        }),503


@route("/api/analyze/differential-question", methods=["POST"])
def api_analyze_differential_question():
    try:
        if not _service_consent_ok():
            return _consent_required_json("/chat")
        data = request.get_json(silent=True) or {}
        invalid_field = _analysis_input_error(data)
        if invalid_field:
            return jsonify({"ok": False, "error": "Invalid input.", "error_code": "invalid_input", "field": invalid_field}), 400
        lang = "en" if data.get("lang") == "en" else "ar"
        symptoms = data.get("symptoms") or []
        if isinstance(symptoms, str):
            symptoms = [symptoms]
        asked = data.get("asked") or []
        negatives = data.get("negatives") or []
        gender = str(data.get("gender") or "").strip().lower()
        result = medical_knowledge.differential_question(
            [str(x).strip() for x in symptoms if str(x).strip()][:30],
            asked=[str(x) for x in asked][:20],
            negatives=[str(x) for x in negatives][:20],
            gender=gender,
            lang=lang,
        )
        result["ok"] = True
        return jsonify(result)
    except Exception as exc:
        return _mk_error(exc, 500)


@route("/api/analyze/data-quality", methods=["POST"])
def api_analyze_data_quality():
    try:
        if not _service_consent_ok():
            return _consent_required_json("/chat")
        data=request.get_json(silent=True) or {}
        invalid_field = _analysis_input_error(data)
        if invalid_field:
            return jsonify({"ok": False, "error": "Invalid input.", "error_code": "invalid_input", "field": invalid_field}), 400
        lang="en" if data.get("lang")=="en" else "ar"
        symptoms=data.get("symptoms") or []
        if isinstance(symptoms,str): symptoms=[symptoms]
        patient={
            "age":data.get("age"),"gender":data.get("gender"),"symptoms":[str(x).strip() for x in symptoms if str(x).strip()][:20],
            "duration":data.get("duration"),"severity":data.get("severity"),"conditions":str(data.get("conditions") or "")[:1000],
            "medications":str(data.get("medications") or "")[:1000],"allergies":str(data.get("allergies") or "")[:1000],
            "notes":str(data.get("notes") or "")[:2000],"location":str(data.get("location") or "")[:200],
            "history_answered":bool(data.get("history_answered")),
        }
        return jsonify({"ok":True,"data_quality":analysis_core.assess_data_quality(patient,lang)})
    except Exception as exc:
        return _mk_error(exc, 500)


@route("/api/analyze/safety-check", methods=["POST"])
def api_analyze_safety_check():
    """Fast deterministic red-flag check before adaptive follow-up questions.

    This endpoint never diagnoses. It exists only to bypass normal questioning
    when a narrow, high-concern safety rule matches the user's current input.
    """
    try:
        if not _service_consent_ok():
            return _consent_required_json("/chat")
        data = request.get_json(silent=True) or {}
        invalid_field = _analysis_input_error(data)
        if invalid_field:
            return jsonify({"ok": False, "error": "Invalid input.", "error_code": "invalid_input", "field": invalid_field}), 400
        lang = "en" if data.get("lang") == "en" else "ar"
        symptoms = data.get("symptoms") or []
        if isinstance(symptoms, str):
            symptoms = [symptoms]
        patient = {
            "symptoms": [str(x).strip() for x in symptoms if str(x).strip()][:30],
            "notes": _sanitize_analysis_notes_for_safety(data.get("notes")),
            "age": data.get("age"),
            "severity": data.get("severity"),
            "duration": data.get("duration"),
        }
        safety = safety_engine.evaluate(patient, lang=lang)
        payload = {"ok": True, "emergency": bool(safety.get("emergency")), "safety_engine": safety}
        if safety.get("emergency"):
            decision_log.record("emergency", safety.get("rule_ids"), lang, "safety_check")
        if safety.get("emergency"):
            payload["result"] = safety_engine.emergency_result(safety, lang=lang)
        return jsonify(payload)
    except Exception as exc:
        return _mk_error(exc, 500)


@route("/api/analyze", methods=["POST"])
def api_analyze():
    try:
        # Parse the request before touching PostgreSQL.  The ready-made demo is
        # intentionally self-contained and must never wait on DB schema warmup,
        # consent tables, or account persistence just to render an illustrative
        # walkthrough.  Normal assessments still enforce consent below.
        data = request.get_json(silent=True) or {}
        demo_mode = data.get("demo_mode") is True
        lang_pre = "en" if data.get("lang") == "en" else _lang()
        analyze_max = _bounded_env_int("ANALYZE_RATE_LIMIT_MAX", 20, 5, 120)
        analyze_window_seconds = _bounded_env_int("ANALYZE_RATE_LIMIT_WINDOW_SECONDS", 300, 60, 86400)
        if demo_mode:
            allowed = _local_request_allowed(
                "analyze_demo", _request_rate_identity("demo"),
                max(analyze_max, 30), analyze_window_seconds,
            )
        else:
            allowed = _request_allowed("analyze", analyze_max, analyze_window_seconds)
        if not allowed:
            msg = "عدد كبير جدًا من الطلبات خلال فترة قصيرة؛ يرجى المحاولة بعد قليل." if lang_pre == "ar" else "Too many requests in a short period; please try again shortly."
            return jsonify({"ok": False, "error": msg, "error_code": "rate_limited"}), 429
        if demo_mode:
            # Demo sessions never read/write account consent or health records.
            consent = {"service_usage": True, "analytics_research": False, "research_participation": False, "needs_review": False}
            g.symptosense_demo = True
        else:
            consent = _consent_state()
            if not consent.get("service_usage") or consent.get("needs_review"):
                lang0 = _lang()
                return jsonify({"ok": False, "error": "يلزم اختيار تفضيلات الخصوصية قبل تحليل الأعراض." if lang0 == "ar" else "Please choose your privacy preferences before symptom analysis.", "consent_required": True, "consent_url": "/consent?next=/chat"}), 403
        if demo_mode:
            # Demo walkthroughs are deliberately detached from account health
            # records even when the browser has prior CBC/reanalysis state.
            data["blood_id"] = None
            data["previous_record_id"] = None
            data["use_saved"] = False
        invalid_field = _analysis_input_error(data)
        if invalid_field:
            return jsonify({"ok": False, "error": "يرجى التحقق من البيانات المدخلة." if _lang() == "ar" else "Please check the supplied input.", "error_code": "invalid_input", "field": invalid_field}), 400
        for field in ("age", "severity", "member_id", "blood_id", "previous_record_id"):
            if data.get(field) not in (None, ""):
                if field == "age":
                    data[field] = clinical_text.parse_age_years(data[field])
                else:
                    number = float(data[field])
                    data[field] = int(number) if number.is_integer() else number
        lang = "en" if data.get("lang") == "en" else "ar"
        symptoms = data.get("symptoms") or []
        if isinstance(symptoms, str):
            symptoms = [symptoms]
        symptoms = [str(s).strip()[:300] for s in symptoms if str(s).strip()][:20]
        if not symptoms:
            msg = "يرجى اختيار عرض واحد على الأقل قبل بدء التحليل." if lang == "ar" else "Please select at least one symptom before starting the assessment."
            return jsonify({"ok": False, "error": msg}), 400
        if demo_mode:
            return jsonify(demo_analysis_result(lang))
        try:
            member_id = int(data.get("member_id") or 0)
        except (TypeError, ValueError):
            member_id = 0
        raw_severity = data.get("severity")
        try:
            severity = max(1, min(5, int(raw_severity))) if raw_severity not in (None, "") else None
        except (TypeError, ValueError):
            severity = None
        use_saved = False if demo_mode else data.get("use_saved", False)
        if demo_mode:
            member_id = 0
        member = None
        if member_id:
            # Family records are account-scoped. Never continue with a supplied
            # member_id that is absent from the current account: doing so could
            # create an orphan/misattributed health record.
            if not _ss_user_id():
                return jsonify({"ok": False, "error": "login_required", "error_code": "login_required"}), 401
            try:
                member = db.get_member(_data_user_id(), int(member_id))
            except Exception:
                logging.getLogger(__name__).debug("Handled exception in api_analyze; family lookup failed")
                member = None
            if not member:
                return jsonify({"ok": False, "error": "family_member_not_found", "error_code": "invalid_member"}), 404
        patient = {
            "user_id": None if demo_mode else (("account-%s" % _ss_user_id()) if _ss_user_id() else None),
            "age": data.get("age"),
            "gender": data.get("gender"),
            "symptoms": symptoms,
            "duration": data.get("duration"),
            "severity": severity,
            "conditions": data.get("conditions", ""),
            "medications": data.get("medications", ""),
            "allergies": data.get("allergies", ""),
            "notes": _sanitize_analysis_notes_for_safety(data.get("notes")),
            "location": str(data.get("location") or "")[:200],
            "history_answered": bool(data.get("history_answered")),
            "onset": str(data.get("onset") or "")[:80],
            "course": str(data.get("course") or "")[:80],
            "pattern_worse": str(data.get("pattern_worse") or "")[:160],
            "pattern_relief": str(data.get("pattern_relief") or "")[:160],
            "redflag_yes": [str(x)[:40] for x in (data.get("redflag_yes") or [])][:12] if isinstance(data.get("redflag_yes"), list) else [],
            "raw_description": str(data.get("raw_description") or "")[:1200],
            "negative_symptoms": [str(x).strip() for x in (data.get("negative_symptoms") or data.get("negatives") or []) if str(x).strip()][:20],
            # Free-text coverage analytics are strictly opt-in. Demo runs never
            # write coverage phrases, even if this browser previously consented.
            "analytics_consent": bool(consent.get("analytics_research")) and not bool(consent.get("needs_review")) and not demo_mode,
            "member_id": member_id,
        }
        if member:
            patient["member_name"] = member.get("name", "")
        blood_id = data.get("blood_id")
        if blood_id:
            try:
                bt = db.get_blood_test(_data_user_id(), blood_id)
                if bt and bt.get("data"):
                    patient["blood_id"] = int(blood_id)
                    patient["blood"] = bt["data"]
            except Exception:
                logging.getLogger(__name__).warning("Handled exception in api_analyze; fallback applied (handler 15772)")
                pass
        # Smart context: use saved health profile if requested and permitted.
        # Reuse the same privacy row later when deciding whether to save chat
        # history so the Analyze request does not open another DB connection.
        analysis_privacy = None
        if use_saved and not member:
            uid = _ss_user_id()
            if uid:
                analysis_privacy = db.load_privacy_settings(uid)
                if analysis_privacy.get("use_in_analysis", True):
                    hp = db.load_health_profile(uid)
                    if hp:
                        if patient["age"] in (None, "") and hp.get("dob"):
                            patient["age"] = clinical_text.parse_age_years(hp.get("dob"))
                        if not patient["gender"] and hp.get("gender"):
                            patient["gender"] = hp["gender"]
                        if not patient["conditions"] and hp.get("health_conditions"):
                            patient["conditions"] = hp["health_conditions"]
                        if not patient["medications"] and hp.get("medications"):
                            patient["medications"] = hp["medications"]
                        if not patient["allergies"] and hp.get("allergies"):
                            patient["allergies"] = hp["allergies"]
        # Fallback to legacy profile if still missing
        if not patient["conditions"] or not patient["medications"] or patient["age"] in (None, ""):
            try:
                if member:
                    if patient["age"] in (None, ""):
                        patient["age"] = member.get("age") or None
                    if not patient["gender"]:
                        patient["gender"] = member.get("gender") or None
                    if not patient["conditions"]:
                        patient["conditions"] = member.get("conditions") or ""
                    if not patient["medications"]:
                        patient["medications"] = member.get("medications") or ""
                    if not patient["allergies"]:
                        patient["allergies"] = member.get("allergies") or ""
                elif _ss_user_id() and use_saved and analysis_privacy and analysis_privacy.get("use_in_analysis", False):
                    # Persistent legacy profile data is account-only. Guests,
                    # including sessions from older releases, never read it.
                    p = db.load_profile(_data_user_id())
                    if p:
                        if patient["age"] in (None, ""):
                            patient["age"] = p.get("age") or None
                        if not patient["gender"]:
                            patient["gender"] = p.get("gender") or None
                        if not patient["conditions"]:
                            patient["conditions"] = p.get("conditions") or ""
                        if not patient["medications"]:
                            patient["medications"] = p.get("medications") or ""
                        if not patient["allergies"]:
                            patient["allergies"] = p.get("allergies") or ""
            except Exception:
                logging.getLogger(__name__).warning("Handled exception in api_analyze; fallback applied (handler 15829)")
                pass
        # V151: deterministic Safety Engine runs before disease matching or any
        # explanatory AI layer. If a strict red-flag rule matches, stop the
        # normal assessment and return urgent guidance immediately.
        pre_safety = safety_engine.evaluate(patient, lang=lang)
        if pre_safety.get("emergency"):
            result = safety_engine.emergency_result(pre_safety, lang=lang)
            # V212: authenticated emergency assessments must be persisted too.
            # Previously the deterministic safety short-circuit returned before
            # analysis_core.run_analysis(), so those symptom trials could be absent
            # from health history/Admin Excel even though the user completed an
            # assessment. Guests remain ephemeral exactly as before.
            emergency_record_id = None
            user_key = patient.get("user_id")
            if user_key and str(user_key).startswith("account-"):
                try:
                    emergency_persisted = dict(result)
                    emergency_persisted["symptoms"] = list(patient.get("symptoms") or [])
                    emergency_persisted["input_snapshot"] = {
                        "age": patient.get("age"),
                        "gender": patient.get("gender"),
                        "symptoms": list(patient.get("symptoms") or []),
                        "duration": patient.get("duration") or "",
                        "severity": patient.get("severity"),
                        "conditions": patient.get("conditions") or "",
                        "medications": patient.get("medications") or "",
                        "allergies": patient.get("allergies") or "",
                        "notes": patient.get("notes") or "",
                    }
                    emergency_record_id = db.save_analysis_record_with_result(
                        user_key, lang, patient.get("age"), patient.get("gender"),
                        patient.get("symptoms") or [], patient.get("duration"),
                        patient.get("severity"), "high", emergency_persisted,
                        patient.get("conditions", ""), patient.get("medications", ""),
                        patient.get("member_id", 0),
                    )
                except Exception:
                    logging.getLogger(__name__).exception("Emergency symptom analysis could not be persisted")
            result["record_id"] = emergency_record_id
            result["record_saved"] = bool(emergency_record_id)
        else:
            result = analysis_core.run_analysis(patient, lang=lang)
        result = _augment_analysis_sources(result, patient.get("symptoms") or [])
        result = _ensure_analysis_match_sources(result)
        result["symptom_pattern_summary"] = symptom_context.pattern_summary(patient, lang=lang)
        result["symptom_timeline"] = {
            "duration": patient.get("duration") or "",
            "onset": patient.get("onset") or "",
            "course": patient.get("course") or "",
            "worse": patient.get("pattern_worse") or "",
            "relief": patient.get("pattern_relief") or "",
        }
        result["demo_mode"] = bool(demo_mode)
        if result.get("record_id"):
            try:
                privacy_features.set_record_consent_eligibility(int(result["record_id"]), _analytics_consent_ok(), _research_consent_ok())
            except Exception:
                logging.getLogger(__name__).debug("Handled exception in api_analyze; fallback applied (handler 15836)")
                pass
        previous_record_id = data.get("previous_record_id")
        if previous_record_id and result.get("record_id"):
            try:
                advanced_features.link_reanalysis(_data_user_id(), int(previous_record_id), int(result.get("record_id")))
            except Exception:
                logging.getLogger(__name__).debug("Handled exception in api_analyze; fallback applied (handler 15842)")
                pass
        # Save chat history if user is logged in and privacy allows
        uid = _ss_user_id()
        if uid and not demo_mode:
            privacy = analysis_privacy if analysis_privacy is not None else db.load_privacy_settings(uid)
            if privacy.get("save_chat_history", True):
                try:
                    symptoms_text = ", ".join(patient.get("symptoms", []))
                    db.save_chat_message(uid, "user", symptoms_text)
                    if result.get("possible_conditions"):
                        db.save_chat_message(uid, "assistant", str(result.get("possible_conditions", ""))[:500])
                except Exception:
                    logging.getLogger(__name__).warning("Handled exception in api_analyze; fallback applied (handler 15854)")
                    pass
        try:
            flags = analysis_core.detect_red_flags(patient["symptoms"], patient["notes"], lang, age=patient.get("age"), severity=patient.get("severity"), duration=patient.get("duration"), redflag_yes=patient.get("redflag_yes"))
            if flags:
                result["emergency"] = True
                if member and member.get("name"):
                    pfx = ("لدى " + member["name"] + ": ") if lang == "ar" else ("For " + member["name"] + ": ")
                    flags = [pfx + f for f in flags]
                result["emergency_flags"] = flags
                if member and member.get("name"):
                    result["emergency_person"] = member["name"]
                if _analytics_consent_ok():
                    platform_v2.record_usage("safety_alert", "/api/analyze", lang, request.headers.get("User-Agent", ""), 200, service="symptom_analysis")
        except Exception:
            logging.getLogger(__name__).error("Post-analysis red-flag re-check failed", exc_info=True)
            ops_metrics.event_error("post_analysis_redflag_recheck")
        try:
            if demo_mode:
                raise RuntimeError("demo results are never logged")
            _lvl = "emergency" if (pre_safety.get("emergency") or result.get("emergency")) else str(result.get("urgency") or "low")
            _rules = list(pre_safety.get("rule_ids") or []) or [
                (r.get("slug") if isinstance(r, dict) else "") for r in (result.get("risk_reasons") or [])]
            decision_log.record(_lvl, _rules, lang, "analyze")
        except Exception:
            pass
        return jsonify(result)
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/analyze/export/<int:record_id>")
def api_export_pdf(record_id):
    db.init_db()
    result = db.load_result(_data_user_id(), record_id)
    if not result:
        return jsonify({
            "ok": False,
            "error": "تعذر العثور على النتيجة المحفوظة؛ سيحاول الموقع إنشاء التقرير من النتيجة الحالية." if _lang() == "ar" else "The saved result was not found; the site will try to build the report from the current result.",
            "error_code": "result_not_found",
        }), 404
    lang = "en" if result.get("lang") == "en" else "ar"
    try:
        buf = _pdf_report(result, lang)
    except Exception as exc:
        return _mk_error(exc, 500)
    try:
        if _analytics_consent_ok():
            platform_v2.record_usage("report_generated", "/api/analyze/export", lang, request.headers.get("User-Agent", ""), 200, None)
            admin_operational.record_journey(_analytics_session_id(), "report", request.headers.get("User-Agent", ""))
    except Exception:
        logging.getLogger(__name__).warning("Handled exception in api_export_pdf; fallback applied (handler 16182)")
        pass
    fname = "symptosense-report-%s.pdf" % record_id
    response = send_file(
        buf, mimetype="application/pdf",
        as_attachment=True, download_name=fname,
    )
    response.headers["Cache-Control"] = "no-store, private"
    return response


@route("/api/analyze/export-current", methods=["POST"])
def api_export_current_pdf():
    """Create a non-persistent PDF for guests or an unavailable saved record."""
    if not _service_consent_ok():
        return _consent_required_json("/chat")
    try:
        data = request.get_json(silent=True) or {}
        raw = data.get("result") or {}
        if not isinstance(raw, dict) or not raw:
            return jsonify({"ok": False, "error": "لا توجد نتيجة حالية لإنشاء التقرير." if _lang() == "ar" else "There is no current result to export."}), 400
        allowed = {
            "lang", "age", "gender", "symptoms", "duration", "severity", "urgency", "risk_level", "risk_label",
            "data_quality", "knowledge_matches", "possible_conditions", "recommendations", "danger_signs",
            "when_to_seek_care", "home_care", "questions_for_doctor", "medical_sources",
        }
        export_result = {key: raw.get(key) for key in allowed if key in raw}
        # Bound nested client data before sending it to the PDF renderer.
        packed = json.dumps(export_result, ensure_ascii=False)
        if len(packed.encode("utf-8")) > 350_000:
            return jsonify({"ok": False, "error": "حجم بيانات التقرير أكبر من المسموح." if _lang() == "ar" else "The report data is too large."}), 413
        export_result = json.loads(packed)
        lang = "en" if data.get("lang") == "en" or export_result.get("lang") == "en" else "ar"
        buf = _pdf_report(export_result, lang)
        response = send_file(buf, mimetype="application/pdf", as_attachment=True, download_name="symptosense-report-current.pdf")
        response.headers["Cache-Control"] = "no-store, private"
        return response
    except Exception as exc:
        return _mk_error(exc, 500)


@route("/api/assistant", methods=["POST"])
def api_assistant():
    if not _request_allowed("assistant",
        _bounded_env_int("ASSISTANT_RATE_LIMIT_MAX", 40, 5, 300),
        _bounded_env_int("ASSISTANT_RATE_LIMIT_WINDOW_SECONDS", 300, 60, 86400),
    ):
        return _rate_limited_response()
    lang = "ar"
    services = []
    mode = ""
    last_text = ""
    if not _service_consent_ok():
        return _consent_required_json("/assistant")
    try:
        data = request.get_json(silent=True)
        if not isinstance(data, dict):
            return jsonify({"ok": False, "error": "invalid_json_object"}), 400
        lang = "en" if data.get("lang") == "en" else "ar"
        mode = str(data.get("mode") or "").strip()
        if mode not in {"", "mh"}:
            return jsonify({"ok": False, "error": "invalid_mode"}), 400
        raw_messages = data.get("messages") or []
        if not isinstance(raw_messages, list) or len(raw_messages) > 20:
            return jsonify({"ok": False, "error": "invalid_messages"}), 400
        messages = []
        total_chars = 0
        for item in raw_messages:
            if not isinstance(item, dict) or item.get("role") not in {"user", "assistant"}:
                return jsonify({"ok": False, "error": "invalid_messages"}), 400
            content = item.get("content")
            if content is None or content == "":
                continue
            if not isinstance(content, str) or len(content) > 2000:
                return jsonify({"ok": False, "error": "invalid_messages"}), 400
            total_chars += len(content)
            if total_chars > 12000:
                return jsonify({"ok": False, "error": "messages_too_large"}), 413
            messages.append({"role": item.get("role"), "content": content})
        last_text = messages[-1]["content"][:600] if messages else ""
        # Mental-wellbeing safety is deterministic and runs before the language
        # model. This protects the most sensitive flow even if the provider is
        # unavailable, slow, or returns an unsafe/irrelevant answer.
        if mode == "mh":
            import mental_support as _mental_support
            mh_followup = _mental_support.is_affirmative_crisis_followup(messages)
            mh_level = "direct" if mh_followup else _mental_support.safety_level(last_text)
            if mh_level != "none":
                if mh_followup:
                    answer = _mental_support.crisis_message(lang)
                else:
                    answer = _mental_support.supportive_answer(last_text, lang)
                if mh_level in {"direct", "other_harm"}:
                    mh_flags = ["mental_health_crisis"]
                elif mh_level == "passive":
                    mh_flags = ["mental_health_safety_check"]
                else:
                    mh_flags = ["medical_emergency"]
                emergency_label = "Emergency numbers" if lang == "en" else "أرقام الطوارئ"
                return jsonify({
                    "ok": True,
                    "answer": answer,
                    "emergency_flags": mh_flags,
                    "services": [{"label": emergency_label, "url": "/emergency"}],
                    "medical_sources": [],
                    "mental_safety_level": mh_level,
                })
        flags = analysis_core.detect_red_flags([], last_text, lang)
        services = [] if mode == "mh" else _assistant_services(last_text, lang)
        if flags:
            if lang == "en":
                answer = ("I'm concerned about what you described — it can be an emergency sign ("
                          + ", ".join(flags) + "). Please call emergency services right away (997 in Saudi Arabia) or go to the nearest ER. Do not wait for a reply here.")
            else:
                answer = ("أقلقني ما وصفته — قد يكون علامة طارئة (" + "، ".join(flags) +
                          "). يرجى الاتصال بالإسعاف فورًا 997 أو التوجه لأقرب طوارئ. لا تنتظر الرد هنا.")
            return jsonify({"ok": True, "answer": answer, "emergency_flags": flags, "services": services})
        curated = None if mode == "mh" else health_search.curated_result(last_text, lang)
        if curated is not None:
            return jsonify({"ok": True, "answer": curated["direct_answer"], "emergency_flags": [],
                            "services": services, "medical_sources": curated["sources"]})
        contextual_answer = None if mode == "mh" else _assistant_contextual_health_answer(last_text, lang)
        if contextual_answer:
            return jsonify({"ok": True, "answer": _assistant_compact_response(contextual_answer, lang, mode),
                            "emergency_flags": [], "services": services, "medical_sources": []})
        extended = None if mode == "mh" else _assistant_extended_symptom_reply(last_text, lang)
        if extended and extended["sources"]:
            return jsonify({"ok": True, "answer": extended["answer"], "emergency_flags": [],
                            "services": services, "medical_sources": extended["sources"]})
        kb_bundle = None
        assistant_sources = []
        if mode != "mh" and last_text:
            try:
                kb_bundle = medical_knowledge.knowledge_bundle([last_text], severity=1, notes=last_text, lang=lang)
                assistant_sources = kb_bundle.get("sources", [])[:5]
            except Exception:
                logging.getLogger(__name__).warning("Handled exception in api_assistant; fallback applied (handler 16786)")
                kb_bundle = None
        hist = []
        for m in messages[-10:]:
            role = "user" if m.get("role") == "user" else "assistant"
            hist.append({"role": role, "content": str(m.get("content") or "")[:600]})
        if mode == "mh":
            if lang == "en":
                sys = (
                    "You are the mental-wellbeing talk space inside SymptoSense. Sound like a warm, grounded friend in a text conversation: natural, human-sounding, brief, and specific to what the user actually said. Do not use a fixed counseling template and do not sound clinical unless safety requires it. "
                    "Match the user's level of formality, use light everyday language, and vary your openings so replies do not feel scripted. One to four short sentences is usually enough. Ask no more than one question at a time. "
                    "If the user says they only want to vent or be heard, mostly listen: reflect what they said naturally and do not jump into exercises, advice, reframing, or a plan unless they ask. If they want help thinking, help untangle one piece at a time. "
                    "Before replying, infer the user's immediate need from the conversation: listening/venting, calming, sorting thoughts, a small action plan, sleep support, social anxiety, study/work overwhelm, intrusive unwanted thoughts, relationship boundaries, grief, anger, loneliness, or self-criticism. Respond to that need rather than giving generic wellness advice. Offer at most one exercise or one concrete next step per reply unless the user explicitly asks for a plan. For plans, use 2-4 tiny, realistic steps and start with the easiest one. For unwanted intrusive thoughts, do not treat the thought as intent unless the user expresses intent, plan, or inability to stay safe; avoid reassurance loops and help them label the thought and return attention to the present. "
                    "Do not diagnose, label a disorder, shame, over-reassure, or pretend to be a human or a real friend. Do not volunteer that you are AI in ordinary replies; if the user asks who/what you are, answer honestly that you are a digital support assistant in SymptoSense, then continue naturally. "
                    "Useful micro-steps, only when they fit or are requested, include gentle 4-in/6-out breathing without breath-holding, "
                    "5-4-3-2-1 grounding, making one task smaller, writing one racing thought down, reducing stimulation before sleep, or reaching out to one trusted person. "
                    "If low mood, anxiety, sleep difficulty, or distress is persistent or clearly impairing daily life, gently suggest professional support. "
                    "If the user expresses passive death wishes or says people would be better without them, ask directly whether they are thinking about harming themselves or ending their life now. "
                    "If they express self-harm/suicide intent, a plan, or inability to stay safe, stop ordinary coaching: tell them not to stay alone, move away from means of harm, stay with a trusted person, "
                    "and call Saudi ambulance 997 or the unified emergency number 911 now; Ministry of Health 937 is available 24/7 for health consultation. "
                    "If panic-like distress includes severe chest pain, severe breathing difficulty, fainting, sudden weakness, or another strong new physical symptom, do not assume it is anxiety; advise emergency evaluation."
                )
            else:
                sys = (
                    "أنت مساحة فضفضة ودعم داخل SymptoSense. أسلوبك قريب من صديق هادئ في محادثة واتساب: سعودي طبيعي، دافئ، مختصر، ويرد على الكلام نفسه بدل الردود العامة أو الرسمية. لا تستخدم قالبًا ثابتًا ولا تجعل كل رد يبدو كجلسة علاج. "
                    "طابق أسلوب المستخدم بدرجة خفيفة، ونوّع بداية الرد حتى ما يبان محفوظًا. غالبًا تكفي جملة إلى أربع جمل قصيرة، واسأل سؤالًا واحدًا فقط في كل مرة. "
                    "إذا قال المستخدم إنه يبي يفضفض أو يبي أحد يسمعه، اسمعه أكثر مما تنصحه: علّق على كلامه بشكل طبيعي ولا تقفز لتمارين أو حلول أو إعادة صياغة إيجابية إلا إذا طلب. وإذا قال إنه يبي يرتب أفكاره، خذ موضوعًا واحدًا في كل مرة ورتبه معه بهدوء. "
                    "قبل الرد، افهم احتياجه الأقرب من سياق المحادثة: فضفضة واستماع، تهدئة، ترتيب أفكار، خطة صغيرة قابلة للتنفيذ، نوم، قلق اجتماعي، ضغط دراسة/عمل، أفكار مزعجة متكررة، حدود في العلاقات، فقد، غضب، وحدة، أو جلد ذات. رد على الاحتياج نفسه بدل نصائح نفسية عامة. لا تعطِ أكثر من تمرين واحد أو خطوة عملية واحدة في الرد إلا إذا طلب خطة؛ عندها استخدم 2 إلى 4 خطوات صغيرة وابدأ بالأسهل. في الأفكار الدخيلة أو المزعجة لا تعتبر وجود الفكرة نية للتصرف ما لم يذكر نية أو خطة أو عدم قدرته على البقاء آمنًا؛ تجنب دوامة الطمأنة وركز على تسمية الفكرة والعودة للحاضر. "
                    "لا تشخّص اضطرابًا نفسيًا، ولا تضع ملصقات، ولا تحكم أو تبالغ في الطمأنة، ولا تدّعي أنك إنسان أو صديق حقيقي. لا تذكر من نفسك أنك AI في الردود العادية؛ إذا سألك المستخدم من أنت أو هل أنت إنسان، قل بصراحة إنك مساعد دعم رقمي داخل SymptoSense ثم كمل الكلام بشكل طبيعي. من الأدوات المناسبة فقط عند الحاجة أو الطلب: تنفس 4 ثوان شهيق/6 زفير بدون حبس النفس، "
                    "تمرين 5-4-3-2-1، تصغير مهمة واحدة، كتابة فكرة متكررة، تقليل التنبيه قبل النوم، أو التواصل مع شخص موثوق. "
                    "إذا كان الحزن أو القلق أو الأرق أو الضيق مستمرًا أو يؤثر بوضوح على الحياة اليومية، اقترح مراجعة مختص بلطف. "
                    "إذا قال المستخدم إنه يتمنى ألا يصحو أو أن الآخرين أفضل بدونه، اسأله مباشرة هل يفكر الآن في إيذاء نفسه أو إنهاء حياته. "
                    "إذا عبّر عن نية إيذاء النفس أو الانتحار أو خطة أو عدم القدرة على البقاء آمنًا، أوقف الإرشاد العادي وركز على السلامة: لا يبقى وحده، يبتعد عن وسائل الأذى، يبقى مع شخص يثق به، "
                    "ويتصل بالإسعاف 997 أو بالطوارئ الموحدة 911 الآن؛ ووزارة الصحة 937 متاحة على مدار الساعة للاستشارة الصحية. "
                    "إذا وُصفت أعراض تشبه الهلع لكن معها ألم صدر شديد أو صعوبة شديدة في التنفس أو إغماء أو ضعف مفاجئ أو عرض جسدي جديد وقوي، لا تفترض أنها قلق ووجّه للطوارئ."
                )
        elif lang == "en":
            sys = (
                "You are SymptoSense's in-site assistant. Answer the user's exact question directly and concisely in warm English. Preserve the full meaning of multi-word phrases: modifiers such as 'during my period', 'after food', 'while pregnant', body location, timing, and duration are part of the question and must not be dropped. Never answer only one keyword when the user supplied a more specific phrase. For a simple question, use 2-4 short sentences and at most 80 words. Do not repeat the question, add a long introduction, or list unrelated causes. Expand only when the user asks for more detail. "
                "You help navigate the site: /chat symptom analysis, /blood CBC upload, /meds medication info & reminders, "
                "/family Family Health Hub with per-person records, /search smart health search, /calculators health calculators (BMI, fluids, calories, blood sugar), "
                "/emergency emergency numbers & nearest hospitals, "
                "/checkin daily tracking. If the user describes severe symptoms (chest pain, breathing trouble, bleeding, confusion, fainting), "
                "urge them to call local emergency services immediately (997 for ambulance in Saudi Arabia). Always add that this is awareness information, not a final diagnosis."
            )
        else:
            sys = (
                "أنت المساعد الداخلي لموقع SymptoSense. أجب على سؤال المستخدم نفسه مباشرة وباختصار وبالعربية بأسلوب سعودي ودود. حافظ على معنى العبارة كاملة: الكلمات التي تحدد السياق مثل «مع الدورة»، «بعد الأكل»، «أثناء الحمل»، مكان العرض، توقيته ومدته جزء أساسي من السؤال ولا يجوز تجاهلها. إذا كتب المستخدم عبارة مركبة مثل «غثيان الدورة» فلا تجب عن «الغثيان» وحده. للسؤال البسيط استخدم 2 إلى 4 جمل قصيرة وبحد أقصى 80 كلمة. لا تكرر السؤال، ولا تبدأ بمقدمة طويلة، ولا تسرد أسبابًا كثيرة غير مطلوبة. توسع فقط إذا طلب المستخدم تفاصيل أكثر. "
                "تساعد في التوجيه داخل الموقع: /chat تحليل الأعراض، /blood رفع فحص الدم، /meds معلومات وتذكير الأدوية، "
                "/family مركز صحة العائلة بسجلات منفصلة لكل فرد، /search البحث الصحي الذكي، /calculators الحاسبات الصحية (BMI والسوائل والسعرات والسكر)، /emergency أرقام الطوارئ وأقرب مستشفى، /checkin المتابعة اليومية. "
                "إذا وصف المستخدم أعراضاً خطرة (ألم صدر، صعوبة تنفس، نزيف، تشوش، إغماء) حثه على الاتصال بالإسعاف 997 فورًا. "
                "وذكّر دائماً أن هذه معلومات توعوية وليست تشخيصًا نهائيًا."
            )
        sys += (" Never invent diseases, symptoms, medicines, doses, percentages, sources, or links. "
                "If reliable information is unavailable, say so clearly. Do not present a definitive diagnosis."
                if lang == "en" else
                " لا تخترع أمراضًا أو أعراضًا أو أدوية أو جرعات أو نسبًا أو مصادر أو روابط. إذا لم تتوفر معلومة موثوقة فاذكر ذلك بوضوح، ولا تقدم تشخيصًا قطعيًا.")
        if kb_bundle and kb_bundle.get("matches"):
            grounded = []
            for match in kb_bundle["matches"][:3]:
                grounded.append({
                    "condition": match.get("name_en") if lang == "en" else match.get("name_ar"),
                    "match_level": match.get("match_level"),
                    "matched_symptoms": [s.get("name_en") if lang == "en" else s.get("name_ar") for s in match.get("matched_symptoms", [])],
                })
            sys += (" Use only this retrieved knowledge-base context for condition explanations: " if lang == "en" else
                    " استخدم فقط سياق قاعدة المعرفة المسترجع التالي عند شرح الحالات: ") + json.dumps(grounded, ensure_ascii=False)
        if mode != "mh" and data.get("use_my_data") is True and _ss_user_id():
            try:
                import assistant_context
                sys += assistant_context.system_addendum(assistant_context.build(_data_user_id(), lang), lang)
            except Exception as exc:  # personal context is optional; the assistant must still answer
                app.logger.warning("assistant context unavailable; error_type=%s", type(exc).__name__)
        msgs = [{"role": "system", "content": sys}] + hist
        try:
            r = _groq_chat_completion_with_retry(
                msgs, temperature=0.5, max_completion_tokens=240, timeout=6,
            )
            answer = r.choices[0].message.content.strip()
            if not answer:
                raise ValueError("empty_assistant_reply")
            # Defensive mode guard: a mental-wellbeing request must not surface
            # a generic physical-health fallback. This also covers providers
            # that return a canned refusal/fallback as a successful response.
            if mode == "mh":
                _mh_wrong = (
                    "لا أستطيع الرد", "لا استطيع الرد", "تحليل الأعراض", "تحليل الأعراض",
                    "راجع الطبيب عند الحاجة", "can't reply right now", "cannot reply right now",
                    "symptom analysis page", "symptom check",
                )
                if (not answer) or any(x in answer.lower() for x in _mh_wrong):
                    answer = _assistant_local_mental_answer(last_text, lang) or answer
        except Exception:
            # Do not drop simple health questions into a generic "offline"
            # message. Use the curated local health-search knowledge as a safe
            # fallback so terms such as "دوخة" remain useful even when the
            # external AI provider is temporarily unavailable.
            logging.getLogger(__name__).warning("Handled exception in api_assistant; fallback applied (handler 16870)")
            local_answer = (
                _assistant_local_mental_answer(last_text, lang)
                if mode == "mh"
                else _assistant_local_health_answer(last_text, lang)
            )
            if local_answer:
                answer = local_answer
                # Local fallbacks intentionally do not attach broad medical
                # source chips that may not match the exact user message.
                assistant_sources = []
            else:
                answer = ("أنا معك هنا 🤍 اكتب ما يشغلك بكلمات بسيطة، وسأحاول مساعدتك بخطوة هادئة وآمنة."
                          if (lang == "ar" and mode == "mh") else
                          "I'm here with you 🤍 Share what is on your mind in simple words, and I'll try to support you with a calm, safe next step."
                          if mode == "mh" else
                          (_assistant_general_local_fallback(last_text, lang) or "تعذر الوصول إلى المساعد الكامل الآن. اكتب تفاصيل أكثر عن سؤالك الصحي.")
                          if lang == "ar" else
                          (_assistant_general_local_fallback(last_text, lang) or "The full assistant is temporarily unavailable. Add more detail to your health question."))
        answer = _assistant_compact_response(answer, lang, mode)
        return jsonify({"ok": True, "answer": answer, "emergency_flags": [], "services": services,
                        "medical_sources": assistant_sources})
    except Exception as e:
        app.logger.warning("Assistant request failed; using safe local fallback; error_type=%s", type(e).__name__)
        answer = (_assistant_local_mental_answer(last_text, lang) if mode == "mh" else _assistant_local_health_answer(last_text, lang))
        if not answer:
            answer = ("أنا معك هنا 🤍 اكتب ما يشغلك بكلمات بسيطة، وسأحاول مساعدتك بخطوة هادئة وآمنة."
                      if (lang == "ar" and mode == "mh") else
                      "I'm here with you 🤍 Share what is on your mind in simple words, and I'll try to support you with a calm, safe next step."
                      if mode == "mh" else
                      (_assistant_general_local_fallback(last_text, lang) or "تعذر الوصول إلى المساعد الكامل الآن. اكتب تفاصيل أكثر عن سؤالك الصحي.")
                      if lang == "ar" else
                      (_assistant_general_local_fallback(last_text, lang) or "The full assistant is temporarily unavailable. Add more detail to your health question."))
        answer = _assistant_compact_response(answer, lang, mode)
        return jsonify({"ok": True, "answer": answer, "emergency_flags": [], "services": services, "medical_sources": [], "fallback": True})


@route("/api/assistant/feedback", methods=["POST"])
def api_assistant_feedback():
    if not _analytics_consent_ok():
        return jsonify({"ok":True,"recorded":False,"reason":"analytics_consent_disabled"})
    try:
        data = request.get_json(silent=True)
        if not isinstance(data, dict):
            return jsonify({"ok": False, "error": "invalid_json_object"}), 400
        rating = int(data.get("rating") or 0)
        if rating not in (0, 1, 2):
            return jsonify({"ok": False, "error": "rating must be 0, 1 or 2"}), 400
        allowed_reasons = {"unclear", "too_long", "not_answered", "need_more", "not_relevant", "other"}
        reason = str(data.get("reason") or "").strip() or None
        if reason is not None and reason not in allowed_reasons:
            return jsonify({"ok": False, "error": "invalid_reason"}), 400
        db.init_db()
        # Store only aggregate feedback metadata, never chat/reply free text.
        db.save_assistant_feedback(_data_user_id(), None, rating, reason)
        return jsonify({"ok": True})
    except (TypeError, ValueError):
        return jsonify({"ok": False, "error": "rating must be 0, 1 or 2"}), 400
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/search/suggestions")
def api_search_suggestions():
    """Low-latency type-ahead suggestions from the curated knowledge base."""
    lang = "en" if request.args.get("lang") == "en" else "ar"
    q = str(request.args.get("q") or "").strip()[:120]
    if len(q) < 2:
        return jsonify({"ok": True, "suggestions": []})
    try:
        items = search_engine_v2.suggestions(q, lang, 7)
        norm = _normalize_health_query_text(q)
        special = []
        if lang == "ar" and (("غث" in norm) or ("لوع" in norm)):
            special.append({"label":"غثيان مع الحر", "kind":"symptom", "slug":"heat-nausea-context", "score":1.0})
            special.append({"label":"الغثيان مع الدورة الشهرية", "kind":"symptom", "slug":"period-nausea-context", "score":0.99})
        elif lang == "en" and any(x in q.lower() for x in ("nausea", "nauseous", "queasy")):
            special.append({"label":"Nausea in hot weather", "kind":"symptom", "slug":"heat-nausea-context", "score":1.0})
            special.append({"label":"Nausea around your period", "kind":"symptom", "slug":"period-nausea-context", "score":0.99})
        seen=set()
        merged=[]
        for item in special + list(items or []):
            label=str((item or {}).get("label") or "").strip().casefold()
            if not label or label in seen:
                continue
            seen.add(label); merged.append(item)
            if len(merged) >= 7:
                break
        return jsonify({"ok": True, "suggestions": merged})
    except Exception as e:
        app.logger.warning("Search suggestions failed; error_type=%s", type(e).__name__)
        return jsonify({"ok": True, "suggestions": []})


@route("/api/search")
def api_search():
    try:
        lang = "en" if request.args.get("lang") == "en" else "ar"
        q = (request.args.get("q") or "").strip()
        if not q:
            return jsonify({"ok": True, "result": None, "suggestions": health_search.suggestion_terms(lang), "search_v2": {"coverage":"empty","results":[]}})

        # V51 Search Engine V3 ranks only curated KB entities, recovers multiple
        # symptoms from one sentence, and adds typo/dialect/combo tolerance. The existing query-first medical answer
        # pipeline remains authoritative for explanatory copy.
        v2_search = search_engine_v2.search(q, lang, 8) if feature_flags.SEARCH_ENGINE_V2 else {"coverage":"disabled","results":[]}

        # Query-first pipeline for ALL health topics:
        # 1) exact contextual handlers when available,
        # 2) curated glossary/KB only when it is genuinely related,
        # 3) neutral shell so the full question can still be answered.
        # Context-sensitive phrases must be resolved before the generic curated
        # glossary. Otherwise a query such as "غثيان الحر" can be reduced to
        # generic nausea and lose the heat modifier before the direct handler
        # gets a chance to run.
        # A query that is exactly a curated topic name/alias ("Constipation", "الإمساك") has no
        # modifier to preserve, so the curated card must win over the generic contextual answer.
        result = _plain_topic_curated_result(q, lang)
        if result is None and not search_fidelity.exact_library_hit(v2_search, q):
            result = _search_contextual_structured_result(q, lang)
        if result is None:
            result = health_search.curated_result(q, lang)
        if result is None:
            # V252: any blood analyte (AST, CRP, sodium, "low magnesium"...) gets a sourced card
            # from the blood-test tables instead of a fuzzy/unrelated glossary hit.
            try:
                result = search_lab_cards.lookup(q, lang)
            except Exception:
                logging.getLogger(__name__).debug("Handled exception in lab search card; fallback applied (handler V252)")
                result = None
        if result is None:
            # A medicine mentioned in a multi-part query must never be discarded
            # by the fuzzy glossary matcher. Re-run the relationship resolver
            # explicitly before accepting a standalone topic card.
            med_context = _health_search_medication_context(q, lang)
            if med_context:
                result = _health_search_relation_result(q, lang)
        if result is None:
            candidate = health_search.search_health(q, lang)
            result = candidate if _health_search_result_relevant(q, candidate, lang) else None
        if result is None:
            ops_metrics.incr("search_content_gap")  # count only; the query text is never stored
            result = _health_search_query_shell(q, lang)

        def _entity_sources(entity):
            sources = []
            for source in (entity or {}).get("sources", []):
                url = source.get("reference_url") or source.get("official_url")
                if not url:
                    continue
                sources.append({
                    "name": source.get("source_name"),
                    "organization": source.get("organization"),
                    "url": url,
                })
            return sources

        def _enrich_search_topic(topic):
            """Enrich one symptom card with trusted library context.

            The curated search text remains authoritative. The medical library
            only fills missing fields and adds source-grounded context such as
            related conditions and follow-up questions. Nothing here is a
            diagnostic probability or a causal claim.
            """
            if not topic or topic.get("category") != "symptom":
                return topic
            probe = topic.get("title") or ""
            normalized = medical_knowledge.normalize_symptoms([probe], lang)
            canonical = normalized.get("canonical") or []
            if not canonical:
                return topic
            symptom = canonical[0]
            entity = medical_knowledge.get_entity("symptom", symptom["symptom_id"], public=True)
            if not entity:
                return topic
            sources = _entity_sources(entity)
            if sources and not topic.get("sources"):
                topic["sources"] = sources
            if not topic.get("worry"):
                topic["worry"] = entity.get("red_flags_en") if lang == "en" else entity.get("red_flags_ar")
            if not topic.get("what"):
                topic["what"] = entity.get("description_en") if lang == "en" else entity.get("description_ar")

            # Add a few related KB conditions as context only. They are not
            # ranked as diagnoses and are shown with an explicit UI disclaimer.
            related = []
            for rel in sorted((entity.get("diseases") or []), key=lambda x: float(x.get("weight") or 0), reverse=True):
                did = rel.get("disease_id")
                if not did:
                    continue
                try:
                    if not medical_knowledge.public_source_ready("disease", int(did)):
                        continue
                except Exception:
                    continue
                label = rel.get("name_en") if lang == "en" else rel.get("name_ar")
                if label:
                    related.append({"label": label, "slug": rel.get("slug")})
                if len(related) >= 3:
                    break
            if related:
                topic["related_conditions"] = related

            # Reuse reviewed/generic symptom-guidance questions when available.
            try:
                guidance = symptom_guidance.get(int(symptom["symptom_id"])) or {}
            except (TypeError, ValueError, OverflowError):
                guidance = {}
            questions = guidance.get("followup_questions_en" if lang == "en" else "followup_questions_ar") or []
            if questions:
                topic["clarifying_questions"] = [str(x).strip() for x in questions if str(x).strip()][:3]
            care = guidance.get("when_to_seek_care_en" if lang == "en" else "when_to_seek_care_ar")
            if care and not topic.get("doctor"):
                topic["doctor"] = care
            return topic

        # V75: make the health search cover the full active symptom library, not
        # only the smaller hand-authored search glossary. Search Engine V3
        # already recognizes several symptoms in one sentence; turn those hits
        # into source-grounded cards from Medical Knowledge so combinations such
        # as "headache + nausea + light sensitivity" stay visible together.
        symptom_rows = medical_knowledge.list_entities("symptoms", include_inactive=False, search="") or []
        symptom_by_slug = {str(row.get("slug") or ""): row for row in symptom_rows if row.get("slug")}

        def _library_topic_from_hit(hit):
            slug = str((hit or {}).get("slug") or "")
            row = symptom_by_slug.get(slug)
            if not row:
                return None
            entity = medical_knowledge.get_entity("symptom", row.get("id"), public=True)
            if not entity:
                return None
            title = entity.get("name_en") if lang == "en" else entity.get("name_ar")
            what = entity.get("description_en") if lang == "en" else entity.get("description_ar")
            worry = entity.get("red_flags_en") if lang == "en" else entity.get("red_flags_ar")
            topic = {
                "key": slug, "emoji": "🩺", "category": "symptom",
                "title": title or (hit or {}).get("label") or slug,
                "what": what or "", "causes": [],
                "causes_label": "💡 Common causes" if lang == "en" else "💡 الأسباب المحتملة",
                "worry": worry or "",
                "doctor": (
                    "Seek medical review if this symptom persists, worsens, or appears with a warning sign."
                    if lang == "en" else
                    "اطلب مراجعة طبية إذا استمر هذا العرض أو ازداد أو ظهر معه أي علامة خطر."
                ),
                "sources": _entity_sources(entity),
            }
            return _enrich_search_topic(topic)

        def _split_info_list(value):
            if isinstance(value, (list, tuple)):
                return [str(x).strip() for x in value if str(x).strip()][:6]
            text = str(value or "").strip()
            if not text:
                return []
            parts = re.split(r"(?:\r?\n|[•▪]|\s+[؛;]\s+)", text)
            cleaned = [re.sub(r"^[\-–—•▪\s]+", "", x).strip() for x in parts]
            return [x for x in cleaned if x][:6]

        disease_rows = medical_knowledge.list_entities("diseases", include_inactive=False, search="") or []
        disease_by_slug = {str(row.get("slug") or ""): row for row in disease_rows if row.get("slug")}

        def _library_disease_topic_from_hit(hit):
            if str((hit or {}).get("kind") or "") != "disease":
                return None
            if float((hit or {}).get("score") or 0) < 0.72:
                return None
            slug = str((hit or {}).get("slug") or "")
            row = disease_by_slug.get(slug)
            if not row:
                return None
            try:
                if not medical_knowledge.public_source_ready("disease", int(row.get("id"))):
                    return None
            except Exception:
                return None
            entity = medical_knowledge.get_entity("disease", row.get("id"), public=True)
            if not entity:
                return None
            suffix = "_en" if lang == "en" else "_ar"
            related_symptoms = []
            for rel in (entity.get("symptoms") or [])[:5]:
                label = rel.get("name_en") if lang == "en" else rel.get("name_ar")
                if label:
                    related_symptoms.append(label)
            return {
                "key": slug, "emoji": "📋", "category": "disease",
                "title": entity.get("name" + suffix) or (hit or {}).get("label") or slug,
                "what": entity.get("description" + suffix) or "",
                "causes": _split_info_list(entity.get("common_causes" + suffix)),
                "causes_label": "💡 Common causes" if lang == "en" else "💡 الأسباب الشائعة",
                "risk_factors": _split_info_list(entity.get("risk_factors" + suffix)),
                "related_symptoms": related_symptoms,
                "worry": entity.get("red_flags" + suffix) or "",
                "doctor": entity.get("recommended_next_step" + suffix) or "",
                "next_step": entity.get("recommended_next_step" + suffix) or "",
                "sources": _entity_sources(entity),
            }

        # Prefer an exact/high-confidence specific library concept over a more
        # generic glossary match (for example "السكري من النوع الثاني" should
        # not collapse to generic diabetes, and "الصداع النصفي" should not
        # collapse to generic headache). Contextual relationship handlers still
        # win because their modifiers are clinically important to the question.
        ranked_hits_all = list(v2_search.get("results") or [])
        best_hit = max(ranked_hits_all, key=lambda x: float((x or {}).get("score") or 0), default=None)
        if (result and best_hit and float(best_hit.get("score") or 0) >= 0.96
                and not result.get("contextual") and not result.get("relation_query")
                and not result.get("curated_answer")):
            specific = _library_disease_topic_from_hit(best_hit)
            if specific is None:
                try:
                    specific_candidate = health_search.search_health(str(best_hit.get("label") or ""), lang)
                except Exception:
                    specific_candidate = None
                if specific_candidate and specific_candidate.get("key") != "compound":
                    specific = _enrich_search_topic(dict(specific_candidate))
            if specific is not None:
                specific["original_query"] = q
                specific["query_first"] = True
                specific["query_only"] = False
                result = specific

        # V76 fix: a fuzzy alias match not in the user's own text (e.g. "صداع"
        # also matches "اسوأ صداع") wrongly triggered "combined" below, wiping sources.
        def _hit_actually_in_query(hit, _q="".join(str(q or "").split())):
            matched = "".join(str((hit or {}).get("matched_text") or "").split())
            return bool(matched) and matched in _q
        recognized_hits = [h for h in (v2_search.get("recognized_symptoms") or []) if _hit_actually_in_query(h)][:8]
        library_topics = []
        library_seen = set()
        for hit in recognized_hits:
            topic = _library_topic_from_hit(hit)
            key = str((topic or {}).get("key") or "")
            if topic and key and key not in library_seen:
                library_seen.add(key)
                library_topics.append(topic)

        # If the free-text shell is all we have, use the strongest ranked KB
        # candidate only when confidence is high. This makes full-library
        # diseases, tests, medicines and typo-recovered topics searchable while
        # preserving the user's original words and the Did-you-mean cue.
        if result and result.get("query_only"):
            ranked_hits = list(v2_search.get("results") or [])
            top_hit = max(ranked_hits, key=lambda x: float((x or {}).get("score") or 0), default=None)
            recovered = _library_disease_topic_from_hit(top_hit) if top_hit else None
            if recovered is None and top_hit and float(top_hit.get("score") or 0) >= 0.72:
                try:
                    recovered_candidate = health_search.search_health(str(top_hit.get("label") or ""), lang)
                except Exception:
                    recovered_candidate = None
                if recovered_candidate and recovered_candidate.get("key") != "compound":
                    recovered = _enrich_search_topic(dict(recovered_candidate))
            if recovered is not None:
                recovered["original_query"] = q
                recovered["query_first"] = True
                recovered["query_only"] = False
                result = recovered

        # V252: a 2-3 word query must be fully covered by the card shown (see search_fidelity.rescue).
        try:
            result = search_fidelity.rescue(q, lang, result, health_search, _library_topic_from_hit,
                                            _library_disease_topic_from_hit, _enrich_search_topic)
        except Exception:
            logging.getLogger(__name__).debug("Handled exception in fidelity rescue; fallback applied (handler V252)")

        if result:
            if result.get("matched_topics"):
                result["matched_topics"] = [_enrich_search_topic(dict(t)) for t in result["matched_topics"]]
            else:
                result = _enrich_search_topic(result)

            # Merge every recognized symptom from the active library, up to a
            # compact UI limit. This is descriptive retrieval only: no diagnosis
            # score or causal claim is created by combining the cards.
            if library_topics:
                existing = list(result.get("matched_topics") or [])
                existing_keys = {str(x.get("key") or "") for x in existing if isinstance(x, dict)}
                for topic in library_topics:
                    if str(topic.get("key") or "") not in existing_keys:
                        existing.append(topic)
                        existing_keys.add(str(topic.get("key") or ""))
                    if len(existing) >= 3:
                        break
                # One library symptom is also useful when the hand-authored
                # glossary only produced a neutral shell.
                if len(existing) >= 2 or result.get("query_only"):
                    result["matched_topics"] = existing[:3]
                    result["query_only"] = False
                    result["sources"] = []
                if len(library_topics) >= 2:
                    result["category"] = "combined"
                    names = [str(x.get("title") or "") for x in library_topics[:3] if x.get("title")]
                    result["combined_summary"] = (
                        "تم التعرف على %d أعراض في نفس البحث: %s. نعرضها معًا لفهم السياق، دون افتراض أن لها سببًا واحدًا أو أنها تشخيص."
                        % (len(names), "، ".join(names))
                        if lang != "en" else
                        "%d symptoms were recognized in the same search: %s. They are shown together for context without assuming one shared cause or making a diagnosis."
                        % (len(names), ", ".join(names))
                    )

            if result.get("matched_topics"):
                # Sources stay attached to the concept they support. Do not merge
                # them into one compound list that could look like a source for a
                # causal relationship between the symptoms.
                result["sources"] = []
        else:
            # Fallback to the editable Medical Knowledge Base when the curated
            # health-search glossary does not recognize the query at all.
            normalized = medical_knowledge.normalize_symptoms([q], lang)
            canonical = normalized.get("canonical") or []
            if canonical:
                symptom = canonical[0]
                entity = medical_knowledge.get_entity("symptom", symptom["symptom_id"], public=True)
                if entity:
                    result = {
                        "key": entity.get("slug"), "emoji": "🩺", "category": "symptom",
                        "title": entity.get("name_en") if lang == "en" else entity.get("name_ar"),
                        "what": entity.get("description_en") if lang == "en" else entity.get("description_ar"),
                        "causes": [],
                        "causes_label": "💡 Common causes" if lang == "en" else "💡 الأسباب المحتملة",
                        "worry": entity.get("red_flags_en") if lang == "en" else entity.get("red_flags_ar"),
                        "doctor": (
                            "Seek medical review if symptoms persist, worsen, or a red flag appears."
                            if lang == "en" else
                            "اطلب مراجعة طبية إذا استمرت الأعراض أو ساءت أو ظهرت علامة خطر."
                        ),
                        "sources": _entity_sources(entity),
                        "recognized_topics": [entity.get("name_en") if lang == "en" else entity.get("name_ar")],
                        "original_query": q,
                    }

        if result:
            clinical_signoff.annotate(result, lang)
            result["original_query"] = q
            result["recognized_symptoms_v3"] = v2_search.get("recognized_symptoms", [])
            result["pattern_insights_v3"] = v2_search.get("pattern_insights", [])
            result["search_intent_v4"] = v2_search.get("query_intent") or "explain"
            result["search_contexts_v4"] = v2_search.get("contexts") or []
            result["did_you_mean_v4"] = v2_search.get("did_you_mean")
            genuinely_combined_count = len([h for h in result["recognized_symptoms_v3"] if _hit_actually_in_query(h)])
            if genuinely_combined_count >= 2 and result.get("category") in {None, "term", "symptom"}:
                result["category"] = "combined"
            direct_answer = _health_search_question_answer(q, lang, result)
            if direct_answer:
                result["direct_answer"] = direct_answer
            else:
                # Defensive guarantee: never send a non-empty search back with
                # an empty answer card. Preserve the query rather than guessing.
                result["direct_answer"] = (("بحثك هو: «" + q + "». لم تتوفر معلومات موثوقة كافية للإجابة بدقة الآن، لذلك لم أعرض نتيجة غير مرتبطة. جرّب إضافة تفاصيل أكثر أو استخدم المساعد الذكي.") if lang != "en" else
                                           ("Your search is: “" + q + "”. There is not enough reliable information to answer accurately right now, so no unrelated result was substituted. Add more detail or use the AI assistant."))

            # The user's words are always the primary intent. Curated cards are
            # supporting information only, never the title/meaning of the search.
            result["query_first"] = True

            # Content-gap telemetry is optional and privacy-aware. It is recorded
            # only after analytics consent, only for searches that fell through to
            # the neutral query shell, and never with a user/session identifier.
            if result.get("query_only") and _analytics_consent_ok():
                best_effort.call(content_gaps.log_search_gap, q, lang)

        payload = jsonify({
            "ok": True,
            "result": result,
            "suggestions": health_search.suggestion_terms(lang),
            "search_version": "v5-comprehensive-library-search",
            "search_v2": v2_search,
        })
        payload.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0"
        payload.headers["Pragma"] = "no-cache"
        payload.headers["Expires"] = "0"
        payload.headers["X-SymptoSense-Search-Version"] = "v5-comprehensive-library-search"
        return payload
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/calc")
def api_calc():
    try:
        kind = (request.args.get("kind") or "").strip()
        if kind == "bmi":
            w = float(request.args.get("w", ""))
            h = float(request.args.get("h", ""))
            if w <= 0 or w > 500 or h <= 0 or h > 250:
                return jsonify({"ok": False, "error": "invalid bmi input"})
            return jsonify({"ok": True, "kind": "bmi", **calcmod.calc_bmi(w, h)})
        if kind == "fluids":
            age = float(request.args.get("age", ""))
            w = float(request.args.get("w", ""))
            act = request.args.get("act", "low")
            if w <= 0 or w > 500 or age <= 0 or age > 120 or act not in ("low", "medium", "high"):
                return jsonify({"ok": False, "error": "invalid fluids input"})
            return jsonify({"ok": True, "kind": "fluids", **calcmod.calc_fluids(int(age), w, act)})
        if kind == "dose":
            hh = int(float(request.args.get("h", "")))
            mm = int(float(request.args.get("m", "")))
            iv = int(float(request.args.get("iv", "")))
            if iv not in calcmod.DOSE_INTERVALS:
                return jsonify({"ok": False, "error": "invalid interval"})
            return jsonify({"ok": True, "kind": "dose", **calcmod.calc_doses(hh, mm, iv)})
        if kind == "cal":
            age = float(request.args.get("age", ""))
            g = request.args.get("g", "male")
            h = float(request.args.get("h", ""))
            w = float(request.args.get("w", ""))
            act = request.args.get("act", "low")
            if age <= 0 or age > 120 or w <= 0 or w > 500 or h <= 0 or h > 250:
                return jsonify({"ok": False, "error": "invalid calories input"})
            return jsonify({"ok": True, "kind": "cal", **calcmod.calc_calories(int(age), g, h, w, act)})
        if kind == "sugar":
            val = float(request.args.get("val", ""))
            unit = request.args.get("unit", "mg")
            mtype = request.args.get("type", "fasting")
            age_raw = request.args.get("age", "").strip()
            age = int(float(age_raw)) if age_raw else None
            if mtype not in calcmod.SUGAR_TYPES:
                return jsonify({"ok": False, "error": "invalid measurement type"})
            if val <= 0 or (mtype == "a1c" and val > 25):
                return jsonify({"ok": False, "error": "invalid reading"})
            res = calcmod.calc_sugar(val, unit, mtype, age=age)
            return jsonify({"ok": True, "kind": "sugar", "type": mtype, **res})
        return jsonify({"ok": False, "error": "unknown kind"})
    except (ValueError, TypeError):
        return jsonify({"ok": False, "error": "مدخلات غير صالحة." if _lang()=="ar" else "Invalid input.", "error_code": "invalid_input"}), 400
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/drug")
def api_drug():
    name = (request.args.get("name") or "").strip()
    if not name or len(name) > 120:
        return jsonify({"ok": False, "error_code": "invalid_drug_query"}), 400

    # Local reviewed records remain the fast source of truth. External network
    # lookup is attempted only after a local miss.
    d = medication_warnings.lookup_drug(name)
    source_kind = "local"
    if not d:
        d = external_drug_lookup.lookup_external_drug(name)
        source_kind = "external"
    if not d:
        return jsonify({"ok": True, "result": None, "source_kind": "none"})

    lang = "en" if _lang() == "en" else "ar"
    if source_kind == "external":
        d = external_drug_lookup.localize_external_result(d, lang)
    return jsonify({
        "ok": True, "result": True,
        "source_kind": source_kind,
        "external": bool(d.get("external")),
        "cache_hit": bool(d.get("cache_hit")),
        "name": d["name_en"] if lang == "en" else d["name_ar"],
        "generic_name": d.get("generic_name") or "",
        "uses": d["uses_en"] if lang == "en" else d["uses_ar"],
        "warning": d["warning_en"] if lang == "en" else d["warning_ar"],
        "interactions": d["interact_en"] if lang == "en" else d["interact_ar"],
        "notice": (d.get("notice_en") if lang == "en" else d.get("notice_ar")) or "",
        "last_updated": d.get("updated_at") or d.get("fetched_at"),
        "sources": d.get("sources") or [],
        "source_policy": d.get("source_policy") or {},
        "arabic_summary_status": d.get("arabic_summary_status") or "",
    })


def register_routes(app, namespace):
    """Inject webapp dependencies, apply the original decorators, and add the URL rules (same endpoint names)."""
    missing = [n for n in DEPS if n not in namespace]
    if missing:
        raise RuntimeError("routes.assistant: missing dependencies %s" % missing)
    g = globals()
    for n in DEPS:
        g[n] = _inject.dependency(namespace, n)
    g["app"] = app
    for name, spec in _SPECS.items():
        view = spec["fn"]
        for w in reversed(_WRAPPERS.get(name, ())):
            view = _inject.resolve_wrapper(w, g)(view)
        for rule, opts in spec["rules"]:
            kw = dict(opts)
            endpoint = kw.pop("endpoint", name)
            app.add_url_rule(rule, endpoint=endpoint, view_func=view, **kw)
