"""Routes for group "auth", moved out of webapp.py (behaviour unchanged).

Dependencies from webapp.py are injected by register(); decorators like login_required are applied there in the
original order. Generated by tools/extract_routes.py.
"""
from routes import _inject
from datetime import datetime
from datetime import timezone
from flask import jsonify
from flask import redirect
from flask import request
from flask import session
from flask import url_for
import admin_2fa
import admin_security
import best_effort
import db
import logging
import platform_v2

DEPS = ("L", "_admin_auth_core_ready", "_admin_auth_debug", "_analytics_consent_ok", "_auth_csrf_token", "_auth_csrf_valid", "_auth_email_provider_state", "_auth_form_expired_message", "_auth_login_error", "_begin_admin_2fa_challenge", "_bounded_env_int", "_client_ip", "_issue_verification_email", "_lang", "_localized_url", "_login_pair_allowed", "_page", "_rate_limited_response", "_record_login_telemetry_async", "_request_allowed", "_safe_next_url", "_send_password_reset_email", "_ss_user", "_transactional_auth_url", )

_SPECS = {}
_WRAPPERS = {
    "login": (),
    "register": (),
    "verify_email_pending": (),
    "verify_email_token": (),
    "forgot_password": (),
    "reset_password": (),
    "logout": (),
    "api_register": (),
    "api_login": (),
    "api_resend_verification": (),
}


def route(rule, **opts):
    def deco(fn):
        _SPECS.setdefault(fn.__name__, {"fn": fn, "rules": []})["rules"].append((rule, opts))
        return fn
    return deco


@route("/login", methods=["GET", "POST"])
def login():
    # Authentication depends only on the core account DB. Optional analytics
    # schemas are deliberately not initialized on the user-facing login path.
    db.init_db()
    lang=_lang(); t=L["en" if lang=="en" else "ar"]
    error=None; error_code=None
    next_param=_safe_next_url("/profile")
    if next_param.startswith("/family"):
        reason="يلزم تسجيل الدخول لحفظ ملفات العائلة ومتابعتها بأمان من أي جهاز." if lang=="ar" else "Sign in to securely save and access family profiles on any device."
    elif next_param.startswith("/meds"):
        reason="يلزم تسجيل الدخول لحفظ تذكيرات الأدوية وربطها بحسابك." if lang=="ar" else "Sign in to save medication reminders to your account."
    else:
        reason="بعد تسجيل الدخول يمكنك الوصول إلى ملفك ونتائجك المحفوظة." if lang=="ar" else "After signing in, you can access your profile and saved results."
    if request.method=="POST" and not _auth_csrf_valid():
        error=_auth_form_expired_message(lang); error_code="csrf_failed"
    elif request.method=="POST":
        email=(request.form.get("email") or "").strip().lower(); password=request.form.get("password") or ""
        network_origin=_client_ip()
        rate_blocked=(not _login_pair_allowed(email, network_origin, "login") or not _request_allowed(
            "login_ip",
            _bounded_env_int("AUTH_RATE_LIMIT_MAX", 30, 5, 300),
            _bounded_env_int("AUTH_RATE_LIMIT_WINDOW_SECONDS", 900, 60, 86400),
        ))
        result=({"ok":False,"error":"rate_limited"} if rate_blocked
                else db.authenticate_ss_user_status(email,password))
        user_id=result.get("user_id") if result.get("ok") else None
        if result.get("error")=="verification_required" and result.get("user_id"):
            session.clear(); session["pending_verification_user_id"]=int(result["user_id"]); session.permanent=True
            sent, send_error = _issue_verification_email(int(result["user_id"]), lang)
            session["verification_send_state"]="sent" if sent else (send_error or "verification_required")
            return redirect(url_for("verify_email_pending"))
        if user_id:
            db.promote_existing_owner_admin(user_id)
        login_user=db.get_ss_user(user_id) if user_id else None
        if not rate_blocked:
            _record_login_telemetry_async(
                email, network_origin, user_id, bool(user_id),
                bool(login_user and login_user.get("role")=="admin"),
                request.headers.get("User-Agent", ""),
            )
        if user_id:
            is_admin=bool(login_user and login_user.get("role")=="admin")
            if is_admin and not _admin_auth_core_ready(2.0):
                session.clear()
                error_code="admin_security_initializing"
                error=("جاري تجهيز أمان حساب الأدمن. انتظر لحظات ثم حاول تسجيل الدخول مرة أخرى."
                       if lang=="ar" else
                       "Admin security is still initializing. Please wait a moment and sign in again.")
                _admin_auth_debug("login_admin_core_not_ready",login_user,granted=False,redirect_target=None)
            elif is_admin and admin_2fa.required():
                _begin_admin_2fa_challenge(int(user_id))
                st=admin_2fa.status(int(user_id))
                redirect_target=url_for("admin_2fa_verify") if st.get("enabled") else url_for("admin_2fa_setup")
                best_effort.call(platform_v2.audit, int(user_id), 'login_password_verified', 'admin_session', 'self', None, {'status': '2fa_pending', 'setup_required': not bool(st.get('enabled'))})
                _admin_auth_debug("login_password_success_2fa_pending",login_user,granted=False,redirect_target=redirect_target)
                return redirect(redirect_target)
            elif user_id:
                session.clear(); session["ss_user_id"]=int(user_id); session.permanent=True
                session["login_toast"]="admin" if is_admin else "user"
                if is_admin:
                    session["admin_last_seen"]=int(datetime.now(timezone.utc).timestamp())
                    session["admin_2fa_verified"]=not admin_2fa.required()
                    session["admin_session_epoch"]=admin_security.current_epoch(int(user_id))
                    best_effort.call(platform_v2.audit, int(user_id), 'login', 'admin_session', 'self', None, {'status': 'success', '2fa_required': False})
                redirect_target="/admin" if is_admin else next_param
                _admin_auth_debug("login_success",login_user,granted=is_admin,redirect_target=redirect_target)
                return redirect(redirect_target)
        if not error:
            error_code=result.get("error") or "incorrect_credentials"
            _admin_auth_debug("login_failed",None,granted=False,redirect_target=None)
            if db.is_owner_admin_email(email):
                best_effort.call(platform_v2.audit, None, 'login_failed', 'admin_session', 'owner', None, {'status': 'failed'})
            error=(("محاولات تسجيل دخول كثيرة. انتظر 15 دقيقة ثم حاول مرة أخرى."
                    if lang=="ar" else "Too many sign-in attempts. Wait 15 minutes and try again.")
                   if error_code=="rate_limited" else _auth_login_error(lang,error_code))
    create_action=""
    body="""
    <div class="auth-wrap"><div class="auth-card">
      <div class="auth-icon">🩺</div><div style="font-weight:900;color:#123B70;font-size:20px;direction:ltr;margin-bottom:5px">SymptoSense 🩺</div>
      <h1>__H__</h1><p class="auth-sub">__SUB__</p><div class="auth-reason">🔐 __REASON__</div>
      <div class="auth-error __ERR_CLASS__">__ERR__</div>__CREATE_ACTION__
      <form method="POST" action="/login?next=__NEXT__">
        <input type="hidden" name="csrf_token" value="__CSRF__">
        <div class="auth-field"><label>__EMAIL__</label><input type="email" name="email" required maxlength="254" placeholder="name@example.com" autocomplete="email"></div>
        <div class="auth-field"><label>__PASS__</label><input type="password" name="password" required maxlength="256" placeholder="••••••••" autocomplete="current-password"></div>
        <button type="submit" class="auth-btn">__BTN__</button>
      </form>
      <p class="auth-link" style="margin-top:12px"><a href="/forgot-password">__FORGOT__</a></p>
      <p class="auth-link">__NOACCT__ <a href="/register?next=__NEXT__">__REG__</a></p>
      <div style="display:flex;align-items:center;gap:10px;margin:16px 0;color:#94A3B8"><span style="height:1px;background:#DCE8F0;flex:1"></span><span>__OR__</span><span style="height:1px;background:#DCE8F0;flex:1"></span></div>
      <a class="btn auth-guest-btn" href="/home">__GUEST__</a>
    </div></div>
    """
    from html import escape
    vals={"__H__":"مرحبًا بعودتك" if lang=="ar" else "Welcome back","__SUB__":"سجّل الدخول للوصول إلى معلوماتك ونتائجك المحفوظة." if lang=="ar" else "Sign in to access your saved information and results.","__REASON__":reason,"__EMAIL__":t["login_email"],"__PASS__":t["login_pass"],"__BTN__":t["login_btn"],"__FORGOT__":"نسيت كلمة المرور؟" if lang=="ar" else "Forgot password?","__NOACCT__":t["login_noaccount"],"__REG__":t["login_register"],"__OR__":"أو" if lang=="ar" else "or","__GUEST__":"المتابعة كزائر" if lang=="ar" else "Continue as guest","__NEXT__":escape(next_param),"__CSRF__":_auth_csrf_token(),"__ERR_CLASS__":"show" if error else "","__ERR__":error or "","__CREATE__":"إنشاء حساب" if lang=="ar" else "Create Account"}
    create_action=create_action.replace("__NEXT__",escape(next_param)).replace("__CREATE__",vals["__CREATE__"])
    vals["__CREATE_ACTION__"]=create_action
    for k,v in vals.items(): body=body.replace(k,v)
    return _page(t["title_login"],body)


@route("/register", methods=["GET", "POST"])
def register():
    db.init_db(); platform_v2.init_schema()
    lang=_lang(); t=L["en" if lang=="en" else "ar"]; error=None
    next_param=_safe_next_url("/profile")
    if request.method=="POST" and not _auth_csrf_valid():
        error=_auth_form_expired_message(lang)
    elif request.method=="POST" and not _request_allowed("register", 5, 900):
        error="طلبات إنشاء حساب كثيرة. انتظر 15 دقيقة ثم حاول مرة أخرى." if lang=="ar" else "Too many registration attempts. Wait 15 minutes and try again."
    elif request.method=="POST":
        name=(request.form.get("name") or "").strip(); email=(request.form.get("email") or "").strip().lower()
        password=request.form.get("password") or ""; confirm=request.form.get("confirm") or ""; accepted=request.form.get("accept_terms")=="on"
        if not accepted: error="يجب الموافقة على سياسة الخصوصية وشروط الاستخدام." if lang=="ar" else "You must accept the privacy policy and terms of use."
        elif password!=confirm: error=t["register_pass_mismatch"]
        elif len(password)<8: error="استخدم 8 أحرف على الأقل لكلمة المرور." if lang=="ar" else "Use at least 8 characters for your password."
        else:
            user_id,err=db.create_ss_user(email,name,password)
            if user_id:
                session.clear(); session["pending_verification_user_id"]=int(user_id); session["post_verify_next"]=next_param; session.permanent=True
                sent,send_error=_issue_verification_email(int(user_id),lang)
                if _analytics_consent_ok():
                    best_effort.call(platform_v2.record_usage, 'new_account', '/register', lang, request.headers.get('User-Agent', ''), 201, None)
                session["verification_send_state"]="sent" if sent else (send_error or "failed")
                return redirect(url_for("verify_email_pending"))
            mapping={"email_exists":"تعذر إكمال إنشاء الحساب بهذه البيانات. جرّب تسجيل الدخول أو استخدم بريدًا آخر." if lang=="ar" else "Unable to complete registration with these details. Try signing in or use another email.","owner_account_must_exist":"حساب مالك المشروع يجب أن يكون موجودًا مسبقًا ولا يمكن إنشاؤه من صفحة التسجيل." if lang=="ar" else "The project owner account must already exist and cannot be created from this page.","password_too_short":"استخدم 8 أحرف على الأقل لكلمة المرور." if lang=="ar" else "Use at least 8 characters for your password.","password_too_long":"كلمة المرور طويلة جدًا. استخدم 256 حرفًا أو أقل." if lang=="ar" else "The password is too long. Use 256 characters or fewer.","invalid_email":"أدخل بريدًا إلكترونيًا صالحًا." if lang=="ar" else "Enter a valid email address.","invalid_name":"أدخل اسمًا صالحًا." if lang=="ar" else "Enter a valid name."}
            error=mapping.get(err,t["register_error"])
    body="""
    <div class="auth-wrap"><div class="auth-card"><div class="auth-icon">🩺</div><div style="font-weight:900;color:#123B70;font-size:20px;direction:ltr;margin-bottom:5px">SymptoSense 🩺</div>
      <h1>__H__</h1><p class="auth-sub">__SUB__</p><div class="auth-error __ERR_CLASS__">__ERR__</div>
      <form method="POST" action="/register?next=__NEXT__">
        <input type="hidden" name="csrf_token" value="__CSRF__">
        <div class="auth-field"><label>__NAME__</label><input type="text" name="name" required minlength="2" maxlength="100" autocomplete="name"></div>
        <div class="auth-field"><label>__EMAIL__</label><input type="email" name="email" required maxlength="254" placeholder="name@example.com" autocomplete="email"></div>
        <div class="auth-field"><label>__PASS__</label><input type="password" name="password" required minlength="8" maxlength="256" autocomplete="new-password"></div>
        <div class="auth-field"><label>__CONFIRM__</label><input type="password" name="confirm" required minlength="8" maxlength="256" autocomplete="new-password"></div>
        <label class="auth-consent"><input type="checkbox" name="accept_terms" required><span class="auth-consent-text">__ACCEPT__</span></label>
        <button type="submit" class="auth-btn">__BTN__</button>
      </form><p class="auth-link">__HASACCT__ <a href="/login?next=__NEXT__">__LOGIN__</a></p>
    </div></div>
    """
    from html import escape
    privacy_url=escape(_localized_url("/privacy",lang)); terms_url=escape(_localized_url("/terms",lang))
    accept=(f'أوافق على <a class="auth-legal-link" href="{privacy_url}" target="_blank" rel="noopener noreferrer">سياسة الخصوصية</a> و<a class="auth-legal-link" href="{terms_url}" target="_blank" rel="noopener noreferrer">شروط الاستخدام</a>' if lang=="ar" else f'I agree to the <a class="auth-legal-link" href="{privacy_url}" target="_blank" rel="noopener noreferrer">Privacy Policy</a> and <a class="auth-legal-link" href="{terms_url}" target="_blank" rel="noopener noreferrer">Terms of Use</a>')
    vals={"__H__":t["register_h"],"__SUB__":"أنشئ حسابك، ثم تحقّق من بريدك الإلكتروني قبل تسجيل الدخول." if lang=="ar" else "Create your account, then verify your email before signing in.","__NAME__":t["register_name"],"__EMAIL__":t["register_email"],"__PASS__":t["register_pass"],"__CONFIRM__":t["register_confirm"],"__BTN__":t["register_btn"],"__HASACCT__":t["register_hasaccount"],"__LOGIN__":t["register_login"],"__ACCEPT__":accept,"__NEXT__":escape(next_param),"__CSRF__":_auth_csrf_token(),"__ERR_CLASS__":"show" if error else "","__ERR__":error or ""}
    for k,v in vals.items(): body=body.replace(k,v)
    return _page(t["title_register"],body)


@route("/verify-email", methods=["GET", "POST"])
def verify_email_pending():
    db.init_db(); platform_v2.init_schema(); ar=_lang()=="ar"
    uid=session.get("pending_verification_user_id"); notice=""; error=""
    user=db.get_ss_user(uid) if uid else None
    if user and user.get("email_verified"):
        session.pop("pending_verification_user_id",None)
        return redirect("/login")
    if request.method=="POST" and not _auth_csrf_valid():
        error=_auth_form_expired_message(_lang())
    elif request.method=="POST":
        action=request.form.get("action") or "resend"
        if not user:
            error="ابدأ من تسجيل الدخول أو إنشاء حساب." if ar else "Start from sign in or create an account."
        elif action=="verify_code":
            verified_uid, code_status = platform_v2.consume_email_verification_code(int(uid), request.form.get("verification_code") or "")
            if verified_uid:
                pending_next=session.pop("post_verify_next",None) or "/profile"
                session.pop("pending_verification_user_id",None)
                session["ss_user_id"]=int(verified_uid); session.permanent=True
                verified_user=db.get_ss_user(int(verified_uid))
                is_admin=bool(verified_user and verified_user.get("role")=="admin")
                session["login_toast"]="admin" if is_admin else "user"
                return redirect("/admin" if is_admin else (pending_next if isinstance(pending_next,str) and pending_next.startswith("/") and not pending_next.startswith("//") and not pending_next.startswith("/admin") else "/profile"))
            messages={
                "expired": "انتهت صلاحية الرمز. اطلب رمزًا جديدًا." if ar else "The code expired. Request a new code.",
                "used": "تم استخدام هذا الرمز. اطلب رمزًا جديدًا." if ar else "This code was already used. Request a new code.",
                "too_many_attempts": "محاولات كثيرة. اطلب رمزًا جديدًا." if ar else "Too many attempts. Request a new code.",
            }
            error=messages.get(code_status,"رمز التحقق غير صحيح." if ar else "The verification code is incorrect.")
        elif action=="change_email":
            new_email=(request.form.get("new_email") or "").strip().lower()
            current_password=request.form.get("current_password") or ""
            ok,err=db.update_unverified_email(int(uid),new_email,current_password)
            if ok:
                try: platform_v2.invalidate_email_verifications(int(uid))
                except Exception as exc: app.logger.debug("Non-critical operation skipped: %s", type(exc).__name__)
                user=db.get_ss_user(uid)
                sent,reason=_issue_verification_email(int(uid),_lang())
                notice=("تم تحديث البريد وإرسال رابط تحقق جديد." if ar else "Email updated and a new verification link was sent.") if sent else ("تم تحديث البريد، لكن تعذر إرسال الرسالة. تحقق من إعداد مزود البريد." if ar else "Email updated, but the message could not be sent. Check the email provider configuration.")
            else:
                if err in {"invalid_email","email_exists"}:
                    error="تعذر استخدام هذا البريد. تحقق من الصيغة أو استخدم بريدًا آخر." if ar else "Unable to use this email. Check the format or use another address."
                elif err=="incorrect_password":
                    error="كلمة المرور الحالية غير صحيحة." if ar else "The current password is incorrect."
                else:
                    error="تعذر تغيير البريد." if ar else "Unable to change the email."
        else:
            sent,reason=_issue_verification_email(int(uid),_lang())
            if sent: notice="أرسلنا رمز تحقق جديدًا إلى بريدك الإلكتروني." if ar else "We sent a new verification code to your email."
            elif reason in {"cooldown","rate_limited"}: error="يرجى الانتظار قبل طلب رسالة تحقق أخرى." if ar else "Please wait before requesting another verification email."
            elif reason=="email_not_configured": error="خدمة البريد غير مضبوطة بعد. أضف إعدادات Brevo أو SMTP أو Resend في Railway." if ar else "Email delivery is not configured. Add Brevo, SMTP, or Resend settings in Railway."
            elif reason=="email_invalid_api_key": error="مفتاح Resend غير صالح. حدّث RESEND_API_KEY في Railway." if ar else "The Resend API key is invalid. Update RESEND_API_KEY in Railway."
            elif reason=="email_test_domain_restricted": error="إعداد Resend الحالي مخصص للاختبار فقط. لإرسال الرسائل لكل المستخدمين يجب توثيق Domain في Resend واستخدامه في RESEND_FROM." if ar else "The current Resend sender is test-only. Verify a domain in Resend and use it in RESEND_FROM to email all users."
            elif reason=="email_sender_domain_unverified": error="الدومين المستخدم في RESEND_FROM غير موثق في Resend." if ar else "The domain used by RESEND_FROM is not verified in Resend."
            elif reason=="email_sender_placeholder": error="قيمة RESEND_FROM ما زالت مثالًا تجريبيًا. استبدلها بعنوان من دومين موثق في Resend." if ar else "RESEND_FROM is still a placeholder. Replace it with an address on a verified Resend domain."
            elif reason=="email_api_key_placeholder": error="قيمة RESEND_API_KEY ما زالت مثالًا وليست مفتاح Resend فعليًا." if ar else "RESEND_API_KEY is still a placeholder, not a real Resend API key."
            elif reason=="email_sender_invalid": error="صيغة RESEND_FROM غير صحيحة. استخدم: SymptoSense <noreply@your-domain.com>." if ar else "RESEND_FROM is invalid. Use: SymptoSense <noreply@your-domain.com>."
            elif reason=="email_smtp_not_configured": error="إعداد Gmail غير مكتمل. تأكد من إضافة جميع متغيرات SMTP في Railway." if ar else "Gmail configuration is incomplete. Add all SMTP variables in Railway."
            elif reason=="email_smtp_auth_failed": error="رفض Gmail تسجيل الدخول. تأكد من البريد وكلمة مرور التطبيق App Password، وليس كلمة مرور Gmail العادية." if ar else "Gmail rejected the sign-in. Check the email and App Password; do not use the normal Gmail password."
            elif reason=="email_smtp_connection_failed": error="تعذر الاتصال بخادم Gmail. تحقق من إعدادات SMTP ثم حاول مجددًا." if ar else "Could not connect to Gmail. Check the SMTP settings and try again."
            elif reason=="email_smtp_sender_invalid": error="صيغة SMTP_FROM غير صحيحة. استخدم: SymptoSense <your-email@gmail.com>." if ar else "SMTP_FROM is invalid. Use: SymptoSense <your-email@gmail.com>."
            elif reason=="email_smtp_port_invalid": error="قيمة SMTP_PORT غير صحيحة. استخدم 587 مع TLS." if ar else "SMTP_PORT is invalid. Use 587 with TLS."
            elif reason=="email_brevo_not_configured": error="إعداد Brevo غير مكتمل. أضف متغيرات BREVO الثلاثة في Railway." if ar else "Brevo is incomplete. Add all three BREVO variables in Railway."
            elif reason in {"email_brevo_auth_failed","email_brevo_key_placeholder"}: error="مفتاح Brevo غير صالح. أنشئ API Key جديدًا وحدّث BREVO_API_KEY في Railway." if ar else "The Brevo API key is invalid. Create a new key and update BREVO_API_KEY in Railway."
            elif reason=="email_brevo_sender_invalid": error="بريد المرسل في Brevo غير صالح أو غير موثق. تحقق من BREVO_FROM_EMAIL وحالة Verified." if ar else "The Brevo sender is invalid or unverified. Check BREVO_FROM_EMAIL and its Verified status."
            elif reason=="email_brevo_rate_limited": error="تم بلوغ حد الإرسال في Brevo. انتظر تجدد الحد اليومي ثم حاول مجددًا." if ar else "The Brevo sending limit was reached. Wait for the daily allowance to reset."
            elif reason in {"email_brevo_connection_failed","email_brevo_delivery_failed"}: error="تعذر إرسال الرسالة عبر Brevo الآن. تحقق من الإعدادات ثم حاول مجددًا." if ar else "Brevo could not send the email. Check the configuration and try again."
            else: error="تعذر إرسال رسالة التحقق الآن. تحقق من إعدادات البريد في Railway ثم حاول مرة أخرى." if ar else "Unable to send the verification email. Check the email configuration in Railway and try again."
    state=session.pop("verification_send_state",None)
    if state and not notice and not error:
        if state=="sent":
            notice="أرسلنا رمز التحقق إلى بريدك الإلكتروني." if ar else "We sent the verification code to your email."
        elif state in {"cooldown","rate_limited"}:
            notice="يرجى التحقق من بريدك أولًا. أُرسل رمز مؤخرًا؛ استخدمه أو انتظر قليلًا قبل طلب رمز جديد." if ar else "Please verify your email first. A code was sent recently; use it or wait before requesting a new one."
        elif state=="email_not_configured":
            error="خدمة البريد غير مضبوطة. أضف إعدادات Brevo أو SMTP أو Resend في Railway قبل محاولة الإرسال." if ar else "Email delivery is not configured. Add Brevo, SMTP, or Resend settings in Railway before resending."
        elif state=="email_invalid_api_key":
            error="مفتاح Resend غير صالح. حدّث RESEND_API_KEY في Railway." if ar else "The Resend API key is invalid. Update RESEND_API_KEY in Railway."
        elif state=="email_test_domain_restricted":
            error="مرسل Resend الحالي للاختبار فقط. وثّق Domain في Resend ثم حدّث RESEND_FROM." if ar else "The current Resend sender is test-only. Verify a domain in Resend and update RESEND_FROM."
        elif state=="email_sender_domain_unverified":
            error="الدومين الموجود في RESEND_FROM غير موثق في Resend." if ar else "The domain in RESEND_FROM is not verified in Resend."
        elif state=="email_sender_placeholder":
            error="قيمة RESEND_FROM ما زالت مثالًا تجريبيًا. استبدلها بعنوان من دومين موثق في Resend." if ar else "RESEND_FROM is still a placeholder. Replace it with an address on a verified Resend domain."
        elif state=="email_api_key_placeholder":
            error="قيمة RESEND_API_KEY ما زالت مثالًا وليست مفتاح Resend فعليًا." if ar else "RESEND_API_KEY is still a placeholder, not a real Resend API key."
        elif state=="email_sender_invalid":
            error="صيغة RESEND_FROM غير صحيحة." if ar else "RESEND_FROM is invalid."
        elif state=="email_smtp_not_configured":
            error="إعداد Gmail غير مكتمل. أضف جميع متغيرات SMTP في Railway." if ar else "Gmail configuration is incomplete. Add all SMTP variables in Railway."
        elif state=="email_smtp_auth_failed":
            error="رفض Gmail تسجيل الدخول. تحقّق من App Password والبريد المرسل." if ar else "Gmail rejected the sign-in. Check the App Password and sender email."
        elif state=="email_smtp_connection_failed":
            error="تعذر الاتصال بخادم Gmail. تحقق من إعدادات SMTP وحاول مجددًا." if ar else "Could not connect to Gmail. Check the SMTP settings and try again."
        elif state=="email_smtp_sender_invalid":
            error="صيغة SMTP_FROM غير صحيحة." if ar else "SMTP_FROM is invalid."
        elif state=="email_smtp_port_invalid":
            error="قيمة SMTP_PORT غير صحيحة؛ استخدم 587." if ar else "SMTP_PORT is invalid; use 587."
        elif state=="email_brevo_not_configured":
            error="إعداد Brevo غير مكتمل. أضف متغيرات BREVO الثلاثة في Railway." if ar else "Brevo is incomplete. Add all three BREVO variables in Railway."
        elif state in {"email_brevo_auth_failed","email_brevo_key_placeholder"}:
            error="مفتاح Brevo غير صالح. حدّث BREVO_API_KEY في Railway." if ar else "The Brevo API key is invalid. Update BREVO_API_KEY in Railway."
        elif state=="email_brevo_sender_invalid":
            error="بريد Brevo المرسل غير صالح أو غير موثق." if ar else "The Brevo sender is invalid or unverified."
        elif state=="email_brevo_rate_limited":
            error="تم بلوغ حد Brevo اليومي. حاول بعد تجدد الحد." if ar else "The Brevo daily sending limit was reached. Try again after it resets."
        elif state in {"email_brevo_connection_failed","email_brevo_delivery_failed"}:
            error="تعذر إرسال الرسالة عبر Brevo الآن. حاول مجددًا." if ar else "Brevo could not send the email. Try again."
        elif state=="verification_required":
            notice="يرجى التحقق من بريدك الإلكتروني أولًا. إذا لم تصل الرسالة، استخدم إعادة الإرسال." if ar else "Please verify your email first. If the message did not arrive, use resend."
        else:
            error="تعذر إرسال رسالة التحقق حاليًا. تحقق من إعدادات البريد في Railway ثم حاول مرة أخرى." if ar else "The verification email could not be sent. Check the email configuration in Railway and try again."
    masked=""
    if user and user.get("email"):
        e=str(user["email"]); parts=e.split("@",1); masked=(parts[0][:2]+"***@"+parts[1]) if len(parts)==2 else "***"
    body="""
    <div class="auth-wrap"><div class="auth-card"><div class="auth-icon">📧</div><h1>__TITLE__</h1><p class="auth-sub">__SUB__</p><p class="muted" style="direction:ltr">__MASKED__</p>
      __NOTICE____ERROR__
      <form method="post" style="margin-bottom:12px"><input type="hidden" name="csrf_token" value="__CSRF__"><input type="hidden" name="action" value="verify_code"><div class="auth-field"><label>__CODELABEL__</label><input type="text" name="verification_code" required inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" style="direction:ltr;text-align:center;font-size:25px;letter-spacing:7px" placeholder="000000"></div><button class="auth-btn" type="submit">__VERIFYBTN__</button></form>
      <form method="post"><input type="hidden" name="csrf_token" value="__CSRF__"><input type="hidden" name="action" value="resend"><button class="auth-btn" type="submit">__RESEND__</button></form>
      <details style="margin-top:14px;text-align:start"><summary style="cursor:pointer;font-weight:700">__CHANGE__</summary><form method="post" style="margin-top:10px"><input type="hidden" name="csrf_token" value="__CSRF__"><input type="hidden" name="action" value="change_email"><div class="auth-field"><label>__NEWEMAIL__</label><input type="email" name="new_email" required autocomplete="email"></div><div class="auth-field"><label>__PASSWORD__</label><input type="password" name="current_password" required autocomplete="current-password"></div><button class="btn ghost" type="submit">__SAVEEMAIL__</button></form></details>
      <p class="auth-link"><a href="/login">__BACK__</a></p>
    </div></div>
    """
    notice_html='<div class="ss-msg success" style="display:block">'+notice+'</div>' if notice else ""
    error_html='<div class="auth-error show">'+error+'</div>' if error else ""
    vals={"__TITLE__":"📧 تحقق من بريدك الإلكتروني" if ar else "📧 Verify Your Email","__SUB__":"أدخل رمز التحقق المكوّن من 6 أرقام الذي أرسلناه إلى بريدك." if ar else "Enter the six-digit verification code sent to your email.","__MASKED__":masked,"__NOTICE__":notice_html,"__ERROR__":error_html,"__CODELABEL__":"رمز التحقق" if ar else "Verification code","__VERIFYBTN__":"تأكيد الرمز" if ar else "Verify Code","__RESEND__":"إرسال رمز جديد" if ar else "Send New Code","__CHANGE__":"تغيير البريد الإلكتروني" if ar else "Change Email","__NEWEMAIL__":"البريد الإلكتروني الجديد" if ar else "New email","__PASSWORD__":"كلمة المرور الحالية" if ar else "Current password","__SAVEEMAIL__":"حفظ وإرسال رمز جديد" if ar else "Save & send new code","__BACK__":"العودة إلى تسجيل الدخول" if ar else "Back to Login","__CSRF__":_auth_csrf_token()}
    for k,v in vals.items(): body=body.replace(k,v)
    return _page("تحقق من البريد" if ar else "Verify Email",body)


@route("/verify-email/<token>")
def verify_email_token(token):
    ar=_lang()=="ar"; status=platform_v2.email_verification_status(token)
    # Auto-login is allowed only when the verification link is opened in the
    # same browser session that created the account. Possession of a valid
    # email token alone never creates a session on another browser/device.
    pending_uid=session.get("pending_verification_user_id")
    pending_next=session.get("post_verify_next") or "/profile"
    if status=="valid":
        uid,result=platform_v2.consume_email_verification(token)
        if uid:
            same_registration_session=bool(pending_uid and int(pending_uid)==int(uid))
            session.pop("pending_verification_user_id",None); session.pop("post_verify_next",None)
            if same_registration_session:
                session["ss_user_id"]=int(uid); session["login_toast"]="user"; session.permanent=True
                target=pending_next if isinstance(pending_next,str) and pending_next.startswith("/") and not pending_next.startswith("//") else "/profile"
                if target.startswith("/admin"):
                    target="/profile"
                return redirect(target)
            body='<div class="auth-wrap"><div class="auth-card"><div class="auth-icon">✅</div><h1>%s</h1><p class="auth-sub">%s</p><a class="auth-btn" href="/login">%s</a></div></div>' % (("تم التحقق من البريد الإلكتروني" if ar else "Email verified"),("يمكنك تسجيل الدخول الآن." if ar else "You can sign in now."),("تسجيل الدخول" if ar else "Back to Login"))
            return _page("تم التحقق" if ar else "Email Verified",body)
        status=result
    msg={"expired":"انتهت صلاحية رابط التحقق." if ar else "This verification link has expired.","used":"تم استخدام رابط التحقق بالفعل." if ar else "This verification link has already been used.","invalid":"رابط التحقق غير صالح." if ar else "This verification link is invalid."}.get(status,"تعذر التحقق من الرابط." if ar else "Unable to verify this link.")
    body='<div class="auth-wrap"><div class="auth-card"><div class="auth-icon">⚠️</div><h1>%s</h1><p class="auth-sub">%s</p><a class="auth-btn" href="/login">%s</a></div></div>' % (("تعذر التحقق" if ar else "Verification unavailable"),msg,("العودة إلى تسجيل الدخول" if ar else "Back to Login"))
    return _page("تحقق من البريد" if ar else "Verify Email",body),400


@route("/forgot-password", methods=["GET", "POST"])
def forgot_password():
    db.init_db(); platform_v2.init_schema(); ar=_lang()=="ar"; sent=False; form_error=""
    if request.method=="POST" and not _auth_csrf_valid():
        form_error=_auth_form_expired_message(_lang())
    elif request.method=="POST" and not _request_allowed("forgot_password", 5, 900):
        # Keep the same public response shape to avoid account-enumeration clues.
        sent=True
    elif request.method=="POST":
        email=(request.form.get("email") or "").strip().lower()
        provider_state=_auth_email_provider_state()
        provider_error=not provider_state.get("configured")
        if platform_v2.email_is_valid(email) and not provider_error:
            token,user_id,reason=platform_v2.create_password_reset(email)
            if token and user_id:
                reset_url=_transactional_auth_url("reset-password", token, _lang())
                ok,send_error=_send_password_reset_email(email,reset_url,_lang())
                if not ok:
                    try: platform_v2.discard_password_reset_token(token)
                    except Exception as exc: app.logger.debug("Non-critical operation skipped: %s", type(exc).__name__)
                    provider_error=True
        sent=True
    generic="إذا كان الحساب موجودًا لهذا البريد، فقد تم إرسال رابط إعادة تعيين كلمة المرور." if ar else "If an account exists for this email, a password reset link has been sent."
    # Keep the public response identical whether the account exists, the
    # request was throttled, or the provider had a transient failure. Details
    # remain in server logs/configuration diagnostics only.
    body="""<div class="auth-wrap"><div class="auth-card"><div class="auth-icon">🔑</div><h1>__TITLE__</h1><p class="auth-sub">__SUB__</p>__NOTICE____ERROR__<form method="post"><input type="hidden" name="csrf_token" value="__CSRF__"><div class="auth-field"><label>__EMAIL__</label><input type="email" name="email" required autocomplete="email" placeholder="name@example.com"></div><button class="auth-btn" type="submit">__BTN__</button></form><p class="auth-link"><a href="/login">__BACK__</a></p></div></div>"""
    notice=('<div class="ss-msg success" style="display:block">%s</div>' % generic) if sent else ""
    error_html=('<div class="auth-error show">%s</div>' % form_error) if form_error else ""
    vals={"__TITLE__":"نسيت كلمة المرور؟" if ar else "Forgot Password?","__SUB__":"أدخل بريدك لإرسال رابط إعادة تعيين مؤقت." if ar else "Enter your email to receive a temporary reset link.","__EMAIL__":"البريد الإلكتروني" if ar else "Email","__BTN__":"إرسال رابط الاستعادة" if ar else "Send Reset Link","__BACK__":"العودة إلى تسجيل الدخول" if ar else "Back to Login","__NOTICE__":notice,"__ERROR__":error_html,"__CSRF__":_auth_csrf_token()}
    for k,v in vals.items(): body=body.replace(k,v)
    return _page(vals["__TITLE__"],body)


@route("/reset-password/<token>", methods=["GET", "POST"])
def reset_password(token):
    ar=_lang()=="ar"; status=platform_v2.password_reset_status(token); error=""; success=False
    if status!="valid":
        msg={"expired":"انتهت صلاحية رابط إعادة التعيين." if ar else "This password reset link has expired.","used":"تم استخدام رابط إعادة التعيين بالفعل." if ar else "This password reset link has already been used.","invalid":"رابط إعادة التعيين غير صالح." if ar else "This password reset link is invalid."}.get(status,"الرابط غير متاح." if ar else "This link is unavailable.")
        body='<div class="auth-wrap"><div class="auth-card"><div class="auth-icon">⚠️</div><h1>%s</h1><p class="auth-sub">%s</p><a class="auth-btn" href="/forgot-password">%s</a></div></div>' % (("تعذر إعادة التعيين" if ar else "Reset unavailable"),msg,("طلب رابط جديد" if ar else "Request a new link"))
        return _page("استعادة كلمة المرور" if ar else "Reset Password",body),400
    if request.method=="POST" and not _auth_csrf_valid():
        error=_auth_form_expired_message(_lang())
    elif request.method=="POST":
        password=request.form.get("password") or ""; confirm=request.form.get("confirm") or ""
        if password!=confirm: error="كلمتا المرور غير متطابقتين." if ar else "Passwords do not match."
        else:
            try:
                reset_uid = platform_v2.password_reset_user_id(token)
                success=platform_v2.consume_password_reset(token,password)
                if success and reset_uid:
                    try:
                        reset_user = db.get_ss_user(int(reset_uid))
                        if reset_user and reset_user.get("role") == "admin":
                            admin_security.rotate_epoch(int(reset_uid))
                            platform_v2.audit(int(reset_uid), "password_reset", "admin_security", "self", None, {"all_admin_sessions_revoked": True})
                    except Exception:
                        logging.getLogger(__name__).debug("Handled exception in reset_password; fallback applied (handler 13472)")
                        pass
                if not success: error="الرابط غير صالح أو انتهت صلاحيته." if ar else "This link is invalid or has expired."
            except ValueError as exc:
                error=("كلمة المرور طويلة جدًا. استخدم 256 حرفًا أو أقل." if ar else "The password is too long. Use 256 characters or fewer.") if str(exc)=="password_too_long" else ("استخدم 8 أحرف على الأقل." if ar else "Use at least 8 characters.")
    if success:
        # Password-reset completion revokes the current browser session. The
        # user must authenticate again with the new password.
        session.clear()
        body='<div class="auth-wrap"><div class="auth-card"><div class="auth-icon">✅</div><h1>%s</h1><p class="auth-sub">%s</p><a class="auth-btn" href="/login">%s</a></div></div>' % (("تمت إعادة تعيين كلمة المرور بنجاح" if ar else "Password reset successfully"),("يمكنك تسجيل الدخول بكلمة المرور الجديدة." if ar else "You can now sign in with your new password."),("العودة إلى تسجيل الدخول" if ar else "Back to Login"))
    else:
        body="""<div class="auth-wrap"><div class="auth-card"><div class="auth-icon">🔐</div><h1>__TITLE__</h1><div class="auth-error __ERR_CLASS__">__ERROR__</div><form method="post"><input type="hidden" name="csrf_token" value="__CSRF__"><div class="auth-field"><label>__PASS__</label><input type="password" name="password" required minlength="8" maxlength="256" autocomplete="new-password"></div><div class="auth-field"><label>__CONFIRM__</label><input type="password" name="confirm" required minlength="8" maxlength="256" autocomplete="new-password"></div><button class="auth-btn" type="submit">__BTN__</button></form></div></div>"""
        vals={"__TITLE__":"إعادة تعيين كلمة المرور" if ar else "Reset Password","__PASS__":"كلمة المرور الجديدة" if ar else "New Password","__CONFIRM__":"تأكيد كلمة المرور الجديدة" if ar else "Confirm New Password","__BTN__":"إعادة تعيين كلمة المرور" if ar else "Reset Password","__CSRF__":_auth_csrf_token(),"__ERR_CLASS__":"show" if error else "","__ERROR__":error}
        for k,v in vals.items(): body=body.replace(k,v)
    return _page("استعادة كلمة المرور" if ar else "Reset Password",body)


@route("/logout")
def logout():
    try:
        u=_ss_user()
        if u and u.get("role")=="admin": platform_v2.audit(int(u.get("id")),"logout","admin_session","self",None,{"status":"success"})
    except Exception as exc: app.logger.debug("Non-critical operation skipped: %s", type(exc).__name__)
    session.clear(); return redirect("/home")


@route("/api/auth/register", methods=["POST"])
def api_register():
    db.init_db(); platform_v2.init_schema()
    if not _request_allowed("api_register", 5, 900):
        return _rate_limited_response()
    try:
        data=request.get_json(force=True)
        name=(data.get("name") or "").strip(); email=(data.get("email") or "").strip().lower()
        password=data.get("password") or ""; confirm=data.get("confirm",password) or ""
        if password!=confirm: return jsonify({"ok":False,"error":"password_mismatch"}),400
        if len(password)<8: return jsonify({"ok":False,"error":"password_too_short"}),400
        if "accept_terms" in data and data.get("accept_terms") is not True: return jsonify({"ok":False,"error":"terms_required"}),400
        user_id,err=db.create_ss_user(email,name,password)
        if not user_id:
            if err == "email_exists":
                # Avoid confirming whether an email is already registered. Keep
                # the public response generic; no session is created or changed.
                return jsonify({"ok":False,"error":"registration_unavailable"}),400
            status = 503 if err == "database_error" else 400
            return jsonify({"ok":False,"error":err}),status
        session.clear(); session["pending_verification_user_id"]=int(user_id); session.permanent=True
        sent,send_error=_issue_verification_email(int(user_id),_lang())
        return jsonify({"ok":True,"verification_required":True,"email_sent":bool(sent),"email_error":send_error if not sent else None,"redirect_url":"/verify-email"}),201
    except Exception as e:
        app.logger.warning("API register failed; error_type=%s",type(e).__name__)
        return jsonify({"ok":False,"error":"registration_failed"}),500


@route("/api/auth/login", methods=["POST"])
def api_login():
    db.init_db()
    try:
        data=request.get_json(force=True); email=(data.get("email") or "").strip().lower(); password=data.get("password") or ""
        network_origin=_client_ip()
        if (not _login_pair_allowed(email, network_origin, "api_login")
                or not _request_allowed(
                    "api_login_ip",
                    _bounded_env_int("AUTH_RATE_LIMIT_MAX", 30, 5, 300),
                    _bounded_env_int("AUTH_RATE_LIMIT_WINDOW_SECONDS", 900, 60, 86400),
                )):
            return _rate_limited_response()
        result=db.authenticate_ss_user_status(email,password); user_id=result.get("user_id") if result.get("ok") else None
        if result.get("error")=="verification_required" and result.get("user_id"):
            session.clear(); session["pending_verification_user_id"]=int(result["user_id"]); session.permanent=True
            return jsonify({"ok":False,"error":"verification_required","redirect_url":"/verify-email"}),403
        if user_id: db.promote_existing_owner_admin(user_id)
        login_user=db.get_ss_user(user_id) if user_id else None
        _record_login_telemetry_async(
            email, network_origin, user_id, bool(user_id),
            bool(login_user and login_user.get("role")=="admin"),
            request.headers.get("User-Agent", ""),
        )
        if user_id:
            is_admin=bool(login_user and login_user.get("role")=="admin")
            if is_admin and not _admin_auth_core_ready(2.0):
                session.clear()
                _admin_auth_debug("api_login_admin_core_not_ready",login_user,granted=False,redirect_target=None)
                return jsonify({
                    "ok":False,
                    "error":"admin_security_initializing",
                    "retryable":True,
                    "message":"جاري تجهيز أمان حساب الأدمن. حاول مرة أخرى بعد لحظات." if _lang()=="ar" else "Admin security is still initializing. Try again in a moment.",
                }),503
            if is_admin and admin_2fa.required():
                _begin_admin_2fa_challenge(int(user_id))
                st=admin_2fa.status(int(user_id))
                redirect_target=url_for("admin_2fa_verify") if st.get("enabled") else url_for("admin_2fa_setup")
                best_effort.call(platform_v2.audit, int(user_id), 'login_password_verified', 'admin_session', 'self', None, {'status': '2fa_pending', 'setup_required': not bool(st.get('enabled'))})
                return jsonify({"ok":True,"redirect_url":redirect_target,"role":"admin","is_admin":True,"two_factor_required":True,"two_factor_setup_required":not bool(st.get("enabled"))})
            session.clear(); session["ss_user_id"]=int(user_id); session.permanent=True
            session["login_toast"]="admin" if is_admin else "user"
            if is_admin:
                session["admin_last_seen"]=int(datetime.now(timezone.utc).timestamp())
                session["admin_2fa_verified"]=not admin_2fa.required()
                session["admin_session_epoch"]=admin_security.current_epoch(int(user_id))
                best_effort.call(platform_v2.audit, int(user_id), 'login', 'admin_session', 'self', None, {'status': 'success', '2fa_required': False})
            redirect_target="/admin" if is_admin else "/profile"
            _admin_auth_debug("api_login_success",login_user,granted=is_admin,redirect_target=redirect_target)
            return jsonify({"ok":True,"redirect_url":redirect_target,"role":login_user.get("role","user"),"is_admin":is_admin,"user":login_user})
        _admin_auth_debug("api_login_failed",None,granted=False,redirect_target=None)
        code=result.get("error") or "incorrect_credentials"
        # Do not expose account existence/status through the public login response.
        # Verification is handled above only after a correct password.
        if code in {"account_not_found", "account_unavailable"}:
            code = "incorrect_credentials"
        if db.is_owner_admin_email(email):
            best_effort.call(platform_v2.audit, None, 'login_failed', 'admin_session', 'owner', None, {'status': 'failed'})
        return jsonify({"ok":False,"error":code}),401
    except Exception as e:
        app.logger.warning("API login failed; error_type=%s",type(e).__name__)
        return jsonify({"ok":False,"error":"login_failed"}),500


@route("/api/auth/resend-verification", methods=["POST"])
def api_resend_verification():
    uid=session.get("pending_verification_user_id")
    if not uid: return jsonify({"ok":False,"error":"verification_session_required"}),401
    if not _request_allowed("verification_resend", 5, 900, str(uid)):
        return _rate_limited_response()
    sent,reason=_issue_verification_email(int(uid),_lang())
    if sent: return jsonify({"ok":True})
    if reason in {"cooldown","rate_limited"}: return jsonify({"ok":False,"error":"please_wait"}),429
    return jsonify({"ok":False,"error":reason or "email_send_failed"}),503


def register_routes(app, namespace):
    """Inject webapp dependencies, apply the original decorators, and add the URL rules (same endpoint names)."""
    missing = [n for n in DEPS if n not in namespace]
    if missing:
        raise RuntimeError("routes.auth: missing dependencies %s" % missing)
    g = globals()
    for n in DEPS:
        g[n] = _inject.dependency(namespace, n)
    g["app"] = app
    for name, spec in _SPECS.items():
        view = spec["fn"]
        for w in reversed(_WRAPPERS.get(name, ())):
            view = _inject.resolve_wrapper(w, g)(view)
        for rule, opts in spec["rules"]:
            kw = dict(opts)
            endpoint = kw.pop("endpoint", name)
            app.add_url_rule(rule, endpoint=endpoint, view_func=view, **kw)
