"""Routes for group "labs", moved out of webapp.py (behaviour unchanged).

Dependencies from webapp.py are injected by register(); decorators like login_required are applied there in the
original order. Generated by tools/extract_routes.py.
"""
from routes import _inject
from datetime import datetime
from datetime import timezone
from flask import g
from flask import jsonify
from flask import request
from flask import session
from flask import url_for
import analysis_core
import base64
import best_effort
import blood_test
import clinical_text
import db
import hashlib
import hmac
import json
import lab_intake
import medication_email
import os
import platform_v2
import re
import secrets
import time

DEPS = ("BLOOD_COLLECTION_CONSENT_VERSION", "_analytics_consent_ok", "_blood_saved_result_response", "_bounded_env_int", "_consent_required_json", "_data_user_id", "_detect_blood_upload_kind", "_downscale_jpeg", "_extract_blood_from_image", "_lang", "_medication_user_id", "_mk_error", "_rate_limited_response", "_request_allowed", "_safe_pdf_page_png", "_service_consent_ok", "_ss_user_id", "api_login_required", "blood_page", "login_required", )

_SPECS = {}
_WRAPPERS = {
    "blood": ('login_required', ),
    "api_blood_history": ('api_login_required', ),
    "api_blood": (),
}


def route(rule, **opts):
    def deco(fn):
        _SPECS.setdefault(fn.__name__, {"fn": fn, "rules": []})["rules"].append((rule, opts))
        return fn
    return deco


@route("/blood")
def blood():
    return blood_page()


@route("/api/blood/history", methods=["GET"])
def api_blood_history():
    try:
        db.init_db()
        member_id = request.args.get("member")
        try:
            member_filter = int(member_id) if member_id not in (None, "") else None
        except (TypeError, ValueError):
            return jsonify({"ok": False, "error": "invalid_member"}), 400
        if member_filter is not None and member_filter < 0:
            return jsonify({"ok": False, "error": "invalid_member"}), 400
        tests = db.get_blood_tests(_data_user_id(), limit=8, member_id=member_filter)
        out = []
        for bt in tests:
            data = bt["data"] or {}
            out.append({
                "id": bt["id"],
                "timestamp": bt.get("timestamp") or "",
                "level": data.get("level"),
                "summary": data.get("summary"),
                "indicators": data.get("indicators") or [],
            })
        return jsonify({"ok": True, "tests": out})
    except Exception as e:
        request_id=getattr(g,"request_id","")
        app.logger.error("Analysis failed; request_id=%s error_type=%s",request_id,type(e).__name__)
        return jsonify({"ok":False,"error":"تعذر تشغيل التحليل حاليًا. حاول مرة أخرى." if _lang()=="ar" else "Unable to run the assessment right now. Please try again.","request_id":request_id}),500


@route("/api/blood", methods=["POST"])
def api_blood():
    lang = "en" if _lang() == "en" else "ar"
    uid = _ss_user_id()
    if not uid:
        return jsonify({
            "ok": False, "error": "login_required",
            "message": "يلزم تسجيل الدخول أولًا لتجربة تحليل الدم." if lang == "ar" else "Please sign in first to try blood-test analysis.",
            "login_url": url_for("login", next="/blood"),
        }), 401
    user = db.get_ss_user(uid)
    if not user or user.get("status") != "active":
        session.clear()
        return jsonify({"ok": False, "error": "login_required", "login_url": url_for("login", next="/blood")}), 401
    if not _service_consent_ok():
        return _consent_required_json("/blood")

    supplied_collection_consent = str(request.form.get("blood_collection_consent") or "").strip() == "1"
    collection_consent_ok = False
    try:
        db.init_db()
        collection_consent_ok = db.has_blood_collection_consent(
            _data_user_id(), BLOOD_COLLECTION_CONSENT_VERSION
        )
        # Migrate a valid legacy in-session v1 consent into account-level
        # storage, and persist any newly supplied consent exactly once per
        # consent version.
        legacy_session_ok = bool(
            session.get("blood_collection_consent_v1")
            and BLOOD_COLLECTION_CONSENT_VERSION == "blood-v1"
            and session.get("blood_collection_consent_version") in {None, "blood-v1"}
        )
        session_version_ok = session.get("blood_collection_consent_version") == BLOOD_COLLECTION_CONSENT_VERSION
        if (supplied_collection_consent or legacy_session_ok or session_version_ok) and not collection_consent_ok:
            db.save_blood_collection_consent(_data_user_id(), BLOOD_COLLECTION_CONSENT_VERSION)
            collection_consent_ok = True
        if collection_consent_ok:
            session["blood_collection_consent_v1"] = True
            session["blood_collection_consent_version"] = BLOOD_COLLECTION_CONSENT_VERSION
            session.permanent = True
    except Exception:
        app.logger.warning("Blood collection consent persistence failed", exc_info=True)
        collection_consent_ok = bool(
            session.get("blood_collection_consent_v1")
            and (session.get("blood_collection_consent_version") in {None, BLOOD_COLLECTION_CONSENT_VERSION})
        )
    if not collection_consent_ok:
        return jsonify({
            "ok": False,
            "error": "blood_collection_consent_required",
            "message": ("يلزم الموافقة على استخدام بيانات تحليل الدم بصورة مجهولة قبل المتابعة." if lang == "ar" else "Consent to anonymized use of blood-test analysis data is required before continuing."),
        }), 403
    mode = str(request.form.get("mode") or "full").strip().lower()
    app.logger.info("BLOOD_API request mode=%s user_signed_in=%s", mode, bool(_ss_user_id()))
    if mode not in {"full", "extract", "analyze_confirmed"}:
        mode = "extract"
    # V199 invariant: every newly uploaded report goes through the server-issued
    # confirmation receipt. This prevents legacy/default clients from bypassing
    # the value-review screen or two-pass disagreement confirmation.
    if mode == "full":
        mode = "extract"

    try:
        blood_max = max(2, min(40, int(os.environ.get("BLOOD_RATE_LIMIT_MAX", "10") or 10)))
        blood_window = max(60, int(os.environ.get("BLOOD_RATE_LIMIT_WINDOW_SECONDS", "300") or 300))
    except (TypeError, ValueError):
        blood_max, blood_window = 10, 300
    # Confirmation should not consume a second expensive vision quota slot.
    # Upload/vision rate limiting is intentionally deferred until after the
    # exact-file duplicate check, so re-opening a saved file is cheap and does
    # not consume the AI extraction quota.
    if mode == "analyze_confirmed":
        if not _request_allowed("blood_confirm", 40, blood_window):
            return _rate_limited_response()

    gender = str(request.form.get("gender") or "").strip().lower()
    if gender not in {"m", "f"}:
        gender = ""
    age = clinical_text.parse_age_years(request.form.get("age") or None)
    clinical_context = blood_test.normalize_analysis_context({})
    raw_context = request.form.get("clinical_context") or ""
    if raw_context:
        try:
            parsed_context = json.loads(raw_context)
        except (TypeError, ValueError, OverflowError):
            parsed_context = {}
        clinical_context = blood_test.normalize_analysis_context(parsed_context)
    member_id = request.form.get("member_id") or 0
    try:
        member_id = int(member_id or 0)
    except (TypeError, ValueError):
        return jsonify({"ok": False, "error": "invalid_member"}), 400

    member = None
    if member_id:
        if not _ss_user_id():
            return jsonify({"ok": False, "error": "login_required"}), 401
        try:
            member = db.get_member(_data_user_id(), member_id)
        except Exception:
            app.logger.debug("Blood family lookup failed", exc_info=True)
        if not member:
            return jsonify({"ok": False, "error": "family_member_not_found"}), 404

    entries = []
    auto_age = None
    extracted_text = ""
    source_file_hash = ""
    extraction_meta = {
        "source_type": "confirmed_values" if mode == "analyze_confirmed" else "upload",
        "pages_total": 0,
        "pages_read": 0,
        "vision_audited_pages": 0,
        "image_passes": 0,
        "complete_page_read": True,
        "server_verified": mode != "analyze_confirmed",
        "quality": [],
        "required_review_ids": [],
    }
    report_meta = lab_intake.normalize_report_meta({})
    source_pages = {}
    required_review_ids = []

    if mode == "analyze_confirmed":
        raw_json = request.form.get("confirmed_entries") or "[]"
        try:
            submitted = json.loads(raw_json)
        except (TypeError, ValueError, OverflowError):
            return jsonify({"ok": False, "error": "تعذر قراءة القيم المؤكدة." if lang == "ar" else "Unable to read the confirmed values."}), 400
        if not isinstance(submitted, list):
            return jsonify({"ok": False, "error": "invalid_entries"}), 400
        # V153: completeness metadata is server-issued. Do not trust page counts
        # or complete_page_read values posted by the browser.
        receipt_token = str(request.form.get("extraction_receipt") or "").strip()
        receipt_state = session.get("blood_extraction_receipt_v1")
        valid_receipt = False
        if isinstance(receipt_state, dict) and receipt_token:
            expected_token = str(receipt_state.get("token") or "")
            try:
                created_at = int(receipt_state.get("created_at") or 0)
            except (TypeError, ValueError):
                created_at = 0
            age_seconds = max(0, int(time.time()) - created_at) if created_at else 10**9
            valid_receipt = bool(expected_token) and hmac.compare_digest(receipt_token, expected_token) and age_seconds <= 1800
        if not valid_receipt:
            return jsonify({
                "ok": False,
                "error": ("انتهت صلاحية قراءة الملف أو تعذر التحقق منها. أعد قراءة ملف التحليل ثم راجع القيم من جديد." if lang == "ar" else "The file-reading verification expired or could not be verified. Read the lab file again, then review the values."),
                "error_code": "blood_extraction_receipt_required",
            }), 409
        server_meta = receipt_state.get("meta") if isinstance(receipt_state.get("meta"), dict) else {}
        required_review_ids = [str(x) for x in (server_meta.get("required_review_ids") or []) if str(x).strip()][:160]
        extraction_meta = {
            "source_type": str(server_meta.get("source_type") or "upload")[:24],
            "pages_total": max(0, int(server_meta.get("pages_total") or 0)),
            "pages_read": max(0, int(server_meta.get("pages_read") or 0)),
            "vision_audited_pages": max(0, int(server_meta.get("vision_audited_pages") or 0)),
            "image_passes": max(0, int(server_meta.get("image_passes") or 0)),
            "complete_page_read": bool(server_meta.get("complete_page_read")),
            "extracted_count": max(0, int(server_meta.get("extracted_count") or 0)),
            "server_verified": True,
            "quality": list(server_meta.get("quality") or [])[:lab_intake.MAX_PHOTO_PAGES],
            "required_review_ids": required_review_ids,
        }
        server_report_meta = server_meta.get("report_meta") if isinstance(server_meta.get("report_meta"), dict) else {}
        posted_report_meta = request.form.get("report_meta") or ""
        if posted_report_meta:
            try:
                report_meta = lab_intake.normalize_report_meta(json.loads(posted_report_meta))
            except Exception:
                report_meta = lab_intake.normalize_report_meta(server_report_meta)
        else:
            report_meta = lab_intake.normalize_report_meta(server_report_meta)
        raw_confirmed_reviews = request.form.get("confirmed_review_ids") or "[]"
        try:
            confirmed_review_ids = {str(x) for x in json.loads(raw_confirmed_reviews) if str(x).strip()}
        except (TypeError, ValueError, OverflowError):
            confirmed_review_ids = set()
        unresolved = [x for x in required_review_ids if x not in confirmed_review_ids]
        if unresolved:
            return jsonify({
                "ok": False,
                "error": ("توجد قراءات اختلفت بين مرحلتي التحقق ولم تؤكدها بعد. راجع الأسطر المظللة ثم أكد كل قراءة قبل التحليل." if lang == "ar" else "Some readings disagreed between the two verification passes and are not confirmed yet. Review the highlighted rows and confirm each one before analysis."),
                "error_code": "blood_disagreement_confirmation_required",
                "unresolved_review_ids": unresolved,
            }), 409
        source_file_hash = str(receipt_state.get("file_hash") or "").strip().lower()
        if source_file_hash:
            try:
                saved_duplicate = db.find_blood_test_by_file_hash(
                    _data_user_id(), source_file_hash, member_id
                )
            except Exception:
                saved_duplicate = None
                app.logger.debug("Blood duplicate lookup after confirmation skipped", exc_info=True)
            if saved_duplicate:
                session.pop("blood_extraction_receipt_v1", None)
                return jsonify(_blood_saved_result_response(
                    saved_duplicate, lang, member.get("name") if member else None
                ))
        allowed = set(blood_test.REFS.keys())
        for item in submitted[:160]:
            if not isinstance(item, dict):
                continue
            key = str(item.get("key") or "").strip().lower()
            is_generic = bool(re.fullmatch(r"other_[0-9a-f]{12}", key))
            if key not in allowed and not is_generic:
                continue
            try:
                value = float(item.get("value"))
            except (TypeError, ValueError):
                continue
            if not (-1000000000 < value < 1000000000):
                continue
            unit = str(item.get("unit") or "").strip()[:32]
            name = re.sub(r"\s+", " ", str(item.get("name") or "")).strip()[:180]
            reported_status = str(item.get("reported_status") or "").strip().lower()
            if reported_status not in {"normal", "low", "high"}:
                reported_status = ""
            reported_critical = bool(item.get("reported_critical"))
            def _num(name_key):
                raw = item.get(name_key)
                if raw in (None, ""):
                    return None
                try:
                    n = float(raw)
                except (TypeError, ValueError):
                    return None
                return n if -1000000000 < n < 1000000000 else None
            lo, hi = _num("reference_low"), _num("reference_high")
            if lo is not None and hi is not None and lo > hi:
                lo, hi = hi, lo
            entries.append({"key": key, "name": name, "value": value, "unit": unit, "reference_low": lo, "reference_high": hi, "reported_status": reported_status, "reported_critical": reported_critical})
        if not entries:
            return jsonify({"ok": False, "error": "أضف قيمة واحدة صحيحة على الأقل قبل التحليل." if lang == "ar" else "Add at least one valid value before analysis."}), 400
    else:
        uploads = [x for x in request.files.getlist("files") if x and getattr(x, "filename", None)]
        if not uploads:
            one = request.files.get("file")
            if one:
                uploads = [one]
        if not uploads:
            return jsonify({"ok": False, "error": "لم يتم رفع ملف" if lang == "ar" else "No file was uploaded"}), 400
        if len(uploads) != 1:
            return jsonify({
                "ok": False,
                "error": "ارفع ملف PDF واحدًا في كل مرة." if lang == "ar" else "Upload one PDF at a time.",
                "error_code": "single_pdf_required",
            }), 422

        blood_upload_limit = _bounded_env_int("BLOOD_UPLOAD_MAX_BYTES", 25 * 1024 * 1024, 2 * 1024 * 1024, 25 * 1024 * 1024)
        raw_items = []
        up = uploads[0]
        raw = up.read(blood_upload_limit + 1)
        if len(raw) > blood_upload_limit:
            return jsonify({"ok": False, "error": "حجم ملف PDF أكبر من الحد المسموح (25 ميجابايت)." if lang == "ar" else "The PDF exceeds the 25 MB upload limit.", "error_code": "payload_too_large"}), 413
        if not raw:
            return jsonify({"ok": False, "error": "ملف PDF فارغ." if lang == "ar" else "The PDF is empty."}), 400
        upload_kind = _detect_blood_upload_kind(raw)
        if upload_kind != "pdf":
            return jsonify({
                "ok": False,
                "error": "تحليل الدم يقبل ملف PDF فقط. حوّل التقرير إلى PDF ثم أعد الرفع." if lang == "ar" else "Blood-test analysis accepts PDF only. Convert the report to PDF and upload it again.",
                "error_code": "pdf_only_required",
            }), 415
        raw_items.append({"raw": raw, "kind": "pdf", "name": str(getattr(up, "filename", "") or "")[:180]})

        if len(raw_items) == 1:
            source_file_hash = hashlib.sha256(raw_items[0]["raw"]).hexdigest()
        else:
            hh = hashlib.sha256(b"SSLABMULTI1")
            for item in raw_items:
                raw = item["raw"]
                hh.update(len(raw).to_bytes(8, "big"))
                hh.update(hashlib.sha256(raw).digest())
            source_file_hash = hh.hexdigest()

        try:
            saved_duplicate = db.find_blood_test_by_file_hash(_data_user_id(), source_file_hash, member_id)
        except Exception:
            saved_duplicate = None
            app.logger.debug("Blood exact-file duplicate lookup skipped", exc_info=True)
        if saved_duplicate:
            return jsonify(_blood_saved_result_response(saved_duplicate, lang, member.get("name") if member else None))
        if not _request_allowed("blood_vision", blood_max, blood_window):
            return _rate_limited_response()

        try:
            if len(raw_items) == 1 and raw_items[0]["kind"] == "pdf":
                raw = raw_items[0]["raw"]
                import fitz
                try:
                    pdf_ctx = fitz.open(stream=raw, filetype="pdf")
                except Exception:
                    return jsonify({
                        "ok": False,
                        "error": ("الملف محدد كـ PDF لكن محتواه غير صالح أو تالف. أعد تنزيل التقرير الأصلي ثم ارفعه من جديد." if lang == "ar" else "The file is marked as PDF, but its contents are invalid or corrupted. Download the original report again and re-upload it."),
                        "error_code": "invalid_pdf_content",
                    }), 422
                with pdf_ctx as pdf:
                    if len(pdf) < 1:
                        return jsonify({"ok": False, "error": "ملف PDF فارغ." if lang == "ar" else "The PDF is empty."}), 400
                    # V207 PDF-only intake: valid PDFs are not rejected by page count.
                    # Every page is considered; native-text pages stay local and scanned pages
                    # are rasterized for visual extraction when needed.
                    extraction_meta.update({
                        "source_type": "pdf", "pages_total": len(pdf),
                        "pages_read": 0, "vision_audited_pages": 0,
                        "image_passes": 0, "complete_page_read": False,
                    })
                    chunks = []
                    pdf_evidence_candidates = []
                    client = None
                    status_line_re = re.compile(r"^(?:normal|low|high|critical|abnormal|طبيعي|طبيعية|منخفض|منخفضة|مرتفع|مرتفعة)$", re.I)
                    # V202: parse/render PDF pages locally first, then run only
                    # the pages that truly need visual review through a small
                    # concurrent pool.  This keeps native-text PDFs fast and cuts
                    # the wall time of multi-page scanned lab reports without
                    # weakening the existing page-completeness rule.
                    pending_vision = []
                    for page_index in range(len(pdf)):
                        page = pdf[page_index]
                        try:
                            page_text = (page.get_text("text") or "").strip()
                        except Exception:
                            page_text = ""
                        native_rows, _ = blood_test.parse_blood_text(page_text) if page_text else ([], None)
                        page_img = None
                        if native_rows:
                            try:
                                page_img = _downscale_jpeg(_safe_pdf_page_png(page))
                                source_pages[str(page_index + 1)] = lab_intake.make_page_preview(page_img)
                            except Exception:
                                app.logger.debug("PDF evidence preview skipped", exc_info=True)
                            for native_row in native_rows:
                                evidence_row = dict(native_row)
                                evidence_row["source_page"] = page_index + 1
                                evidence_row["source_bbox"] = None
                                try:
                                    search_terms = []
                                    if native_row.get("name"):
                                        search_terms.append(str(native_row.get("name")))
                                    key = str(native_row.get("key") or "")
                                    search_terms.extend(sorted((blood_test.SYNONYMS.get(key) or []), key=len, reverse=True)[:6])
                                    for term in search_terms:
                                        rects = page.search_for(str(term)) if term else []
                                        if not rects:
                                            continue
                                        rr = rects[0]; pr = page.rect
                                        if pr.width and pr.height:
                                            evidence_row["source_bbox"] = [
                                                max(0, min(1000, int(round((rr.x0-pr.x0)/pr.width*1000)))),
                                                max(0, min(1000, int(round((rr.y0-pr.y0)/pr.height*1000)))),
                                                max(0, min(1000, int(round((rr.x1-pr.x0)/pr.width*1000)))),
                                                max(0, min(1000, int(round((rr.y1-pr.y0)/pr.height*1000)))),
                                            ]
                                        break
                                except Exception:
                                    pass
                                pdf_evidence_candidates.append(evidence_row)
                        if page_text:
                            chunks.append(page_text)
                        status_count = sum(1 for line in re.split(r"[\r\n]+", page_text) if status_line_re.match(str(line).strip())) if page_text else 0
                        page_lower = page_text.lower() if page_text else ""
                        lab_hint = any(token in page_lower for token in ("reference range", "result test", "اسم الفحص", "النتيجة", "cbc", "hemoglobin", "leukocyte", "platelet", "thyrotropin", "ferritin", "vitamin"))
                        missing_row_context = any(
                            isinstance(r, dict) and ((r.get("reference_low") is None or r.get("reference_high") is None) and not r.get("reported_status"))
                            for r in native_rows
                        )
                        needs_vision = (not page_text) or (bool(lab_hint) and ((not native_rows) or status_count > len(native_rows) + 1 or missing_row_context))
                        if needs_vision:
                            try:
                                if page_img is None:
                                    page_img = _downscale_jpeg(_safe_pdf_page_png(page))
                                if str(page_index + 1) not in source_pages:
                                    source_pages[str(page_index + 1)] = lab_intake.make_page_preview(page_img)
                                pending_vision.append({
                                    "page_index": page_index,
                                    "img": page_img,
                                    "page_text": page_text,
                                    "native_rows": native_rows,
                                    "lab_hint": bool(lab_hint),
                                })
                            except Exception as render_exc:
                                app.logger.warning("Blood PDF page render failed; page=%s/%s error_type=%s", page_index + 1, len(pdf), type(render_exc).__name__)
                                if page_text:
                                    extraction_meta.setdefault("vision_audit_failed_pages", []).append(page_index + 1)
                                    extraction_meta.setdefault("text_only_pages", []).append(page_index + 1)
                                else:
                                    extraction_meta.setdefault("unreadable_pages", []).append(page_index + 1)
                                    # Accept the PDF and continue with the remaining pages.
                                    continue

                    if pending_vision:
                        from concurrent.futures import ThreadPoolExecutor
                        try:
                            pdf_workers = int(os.environ.get("LAB_PDF_VISION_MAX_WORKERS", "3") or 3)
                        except (TypeError, ValueError):
                            pdf_workers = 3
                        pdf_workers = max(1, min(4, pdf_workers, len(pending_vision)))

                        def _read_pdf_vision(img):
                            local_client = analysis_core._groq_client()
                            return _extract_blood_from_image(local_client, img, audit_pass=True).strip()

                        with ThreadPoolExecutor(max_workers=pdf_workers, thread_name_prefix="lab-pdf-vision") as pool:
                            pdf_futures = [(item, pool.submit(_read_pdf_vision, item["img"])) for item in pending_vision]
                            for item, future in pdf_futures:
                                page_index = item["page_index"]
                                try:
                                    vision_raw = future.result()
                                    vision_payload = lab_intake.parse_vision_payload(vision_raw)
                                    vision_text = vision_payload.get("clean_text") or ""
                                    if vision_text:
                                        chunks.append(vision_text)
                                        extraction_meta["vision_audited_pages"] += 1
                                        pdf_evidence_candidates.extend(lab_intake.vision_evidence_rows(vision_payload, page_index + 1))
                                    if vision_payload.get("meta"):
                                        report_meta = lab_intake.merge_report_metadata([report_meta, vision_payload.get("meta")], item["native_rows"])
                                    if not vision_text and not item["native_rows"] and item["lab_hint"]:
                                        raise RuntimeError("vision_empty_on_lab_page")
                                except Exception as vision_exc:
                                    app.logger.warning("Blood PDF visual audit failed; page=%s/%s error_type=%s", page_index + 1, len(pdf), type(vision_exc).__name__)
                                    if item["page_text"]:
                                        extraction_meta.setdefault("vision_audit_failed_pages", []).append(page_index + 1)
                                        extraction_meta.setdefault("text_only_pages", []).append(page_index + 1)
                                    else:
                                        extraction_meta.setdefault("unreadable_pages", []).append(page_index + 1)
                                        # Do not reject the whole PDF because one scanned page
                                        # could not be read; continue with other pages.
                                        continue
                    extraction_meta["pages_read"] = len(pdf) - len(set(extraction_meta.get("unreadable_pages") or []))
                    extraction_meta["complete_page_read"] = not bool(extraction_meta.get("unreadable_pages"))
                    extracted_text = "\n".join(chunks).strip()
                entries, auto_age = blood_test.parse_blood_text(extracted_text)
                entries = lab_intake.attach_source_evidence(entries, pdf_evidence_candidates)
                report_meta = lab_intake.merge_report_metadata([lab_intake.extract_report_metadata_from_text(extracted_text, entries), report_meta], entries)
            else:
                # V207 is intentionally PDF-only. This is defense in depth in
                # case an older/custom client bypasses the browser file picker.
                return jsonify({
                    "ok": False,
                    "error": "تحليل الدم يقبل ملف PDF فقط." if lang == "ar" else "Blood-test analysis accepts PDF only.",
                    "error_code": "pdf_only_required",
                }), 415
        except Exception as e:
            request_id = getattr(g, "request_id", "")
            app.logger.warning("Blood report extraction failed; request_id=%s error_type=%s", request_id, type(e).__name__)
            return jsonify({"ok": False, "error": "تعذر قراءة ملف PDF حاليًا. أعد المحاولة بالملف الأصلي من المختبر." if lang == "ar" else "Unable to read the PDF right now. Retry with the original laboratory PDF.", "request_id": request_id}), 422

        if not entries:
            return jsonify({"ok": False, "error": "تم فتح ملف PDF، لكن لم أتمكن من استخراج قيم مخبرية واضحة منه. جرّب التقرير الأصلي من المختبر أو PDF أوضح." if lang == "ar" else "The PDF opened successfully, but no clear laboratory values could be extracted. Try the original laboratory report or a clearer PDF.", "error_code": "pdf_no_lab_values"}), 422

        if auto_age is None and report_meta.get("age_text"):
            auto_age = clinical_text.parse_age_years(report_meta.get("age_text"))

        if mode == "extract":
            app.logger.info("BLOOD_API extracted_entries=%s auto_age=%s", len(entries), bool(auto_age is not None))
            extracted_rows = []
            for e in entries:
                key = str(e.get("key") or "")
                meta = blood_test.REFS.get(key)
                report_name = re.sub(r"\s+", " ", str(e.get("name") or "")).strip()[:180]
                display_name = (meta[0] if lang == "ar" else meta[1]) if meta else (report_name or ("فحص مخبري" if lang == "ar" else "Laboratory test"))
                extracted_rows.append({
                    "key": key,
                    "name": display_name,
                    "report_name": report_name,
                    "value": e.get("value"),
                    "unit": e.get("unit") or "",
                    "reference_low": e.get("reference_low"),
                    "reference_high": e.get("reference_high"),
                    "reported_status": e.get("reported_status") or "",
                    "reported_critical": bool(e.get("reported_critical")),
                    "group": blood_test.test_group(key),
                    "group_label": blood_test.GROUP_LABELS.get(blood_test.test_group(key), ("أخرى", "Other"))[0 if lang == "ar" else 1],
                    "review_required": bool(e.get("review_required")),
                    "review_id": str(e.get("review_id") or ""),
                    "review_reasons": list(e.get("review_reasons") or []),
                    "pass1_value": e.get("pass1_value"),
                    "pass2_value": e.get("pass2_value"),
                    "pass1_unit": e.get("pass1_unit") or "",
                    "pass2_unit": e.get("pass2_unit") or "",
                    "source_page": e.get("source_page"),
                    "source_bbox": e.get("source_bbox"),
                    "page_conflict_value": e.get("page_conflict_value"),
                    "page_conflict_page": e.get("page_conflict_page"),
                })
            supported = []
            for key, meta in blood_test.REFS.items():
                supported.append({"key": key, "name": meta[0] if lang == "ar" else meta[1], "default_unit": meta[2], "group": blood_test.test_group(key)})
            if extraction_meta.get("source_type") == "pdf":
                extraction_message = (
                    "تمت قراءة %d من %d صفحة واستخراج %d فحصًا. راجع القيم والوحدات والنطاق المرجعي قبل التحليل."
                    % (extraction_meta.get("pages_read", 0), extraction_meta.get("pages_total", 0), len(extracted_rows))
                ) if lang == "ar" else (
                    "Read %d of %d pages and extracted %d tests. Review values, units, and laboratory ranges before analysis."
                    % (extraction_meta.get("pages_read", 0), extraction_meta.get("pages_total", 0), len(extracted_rows))
                )
            else:
                page_count = max(1, int(extraction_meta.get("pages_read") or 1))
                extraction_message = (
                    ("تمت مراجعة %d صفحة بقراءتين مستقلتين لكل صفحة واستخراج %d فحصًا. راجع القيم قبل التحليل." % (page_count, len(extracted_rows)))
                    if page_count > 1 else
                    ("تمت مراجعة الصورة بقراءتين مستقلتين واستخراج %d فحصًا. راجع القيم قبل التحليل." % len(extracted_rows))
                ) if lang == "ar" else (
                    ("%d pages were reviewed with two independent reads per page and %d tests were extracted. Review the values before analysis." % (page_count, len(extracted_rows)))
                    if page_count > 1 else
                    ("The image was reviewed with two independent reads and %d tests were extracted. Review the values before analysis." % len(extracted_rows))
                )
            required_review_ids = [str(x.get("review_id")) for x in extracted_rows if x.get("review_required") and x.get("review_id")]
            receipt_meta = dict(extraction_meta, extracted_count=len(extracted_rows), server_verified=True, required_review_ids=required_review_ids, report_meta=report_meta)
            extraction_receipt = secrets.token_urlsafe(24)
            session["blood_extraction_receipt_v1"] = {
                "token": extraction_receipt,
                "meta": receipt_meta,
                "file_hash": source_file_hash,
                "created_at": int(time.time()),
            }
            session.modified = True
            if _analytics_consent_ok():
                best_effort.call(platform_v2.record_usage, 'blood_extract_complete', '/api/blood', lang, request.headers.get('User-Agent', ''), 200, None, service='lab_analysis')
            return jsonify({
                "ok": True, "stage": "confirm", "entries": extracted_rows,
                "auto_age": auto_age, "supported_tests": supported,
                "extracted_count": len(extracted_rows),
                "extraction_meta": receipt_meta,
                "extraction_receipt": extraction_receipt,
                "message": extraction_message,
                "required_review_ids": required_review_ids,
                "report_meta": report_meta,
                "source_pages": source_pages,
                "quality": list(extraction_meta.get("quality") or []),
            })

    if age is None and member and member.get("age"):
        age = clinical_text.parse_age_years(member.get("age"))
    if age is None:
        age = auto_age

    try:
        results, notes, dangers, level, child_note = blood_test.analyze_blood(entries, gender, age)
        if not results:
            return jsonify({"ok": False, "error": "لم تتبق قيم صالحة للتحليل." if lang == "ar" else "No valid values remained for analysis."}), 400
        text_html = blood_test.build_text(results, gender, lang, notes, dangers, child_note)
        indicators = blood_test.describe_results(results, lang)
        patterns = blood_test.build_pattern_insights(results, lang)
        relationships = blood_test.build_relationships(results, lang)
        context_notes = blood_test.build_context_notes(results, clinical_context, lang)
        doctor_questions = blood_test.build_doctor_questions(indicators, clinical_context, lang)
        doctor_summary = blood_test.build_doctor_summary(results, patterns, lang, age, gender, context=clinical_context, level=level, questions=doctor_questions)
        verification = blood_test.build_verification_summary(results, lang)
        medical_sources = blood_test.build_medical_source_summary(indicators, lang)

        previous_tests = []
        latest_symptom_record = None
        context_medications = ""
        if _ss_user_id():
            try:
                # Keep trends scoped to the same person. member_id=0 means the
                # signed-in account holder; None would mix family-member tests.
                previous_tests = db.get_blood_tests(_data_user_id(), limit=8, member_id=(member_id if member_id else 0)) or []
            except Exception:
                app.logger.debug("Blood history lookup skipped", exc_info=True)
            try:
                # The same isolation rule applies to symptom context. Never link
                # a family member's symptoms to another person's lab report.
                recent_records = db.get_records(_data_user_id(), limit=1, member_id=(member_id if member_id else 0)) or []
                latest_symptom_record = recent_records[0] if recent_records else None
            except Exception:
                app.logger.debug("Blood symptom-context lookup skipped", exc_info=True)
            try:
                medication_parts = []
                if member and member.get("medications"):
                    medication_parts.append(str(member.get("medications") or ""))
                elif not member:
                    profile = db.load_profile(_data_user_id()) or {}
                    if profile.get("medications"):
                        medication_parts.append(str(profile.get("medications") or ""))
                if latest_symptom_record and latest_symptom_record.get("medications"):
                    medication_parts.append(str(latest_symptom_record.get("medications") or ""))
                # Medication reminders are another user-entered source of the
                # current medicines list. Scope them to the same member.
                try:
                    active_plans = medication_email.list_plans(_medication_user_id(), member_id=(member_id if member_id else 0), active_only=True) or []
                    medication_parts.extend(str(p.get("med_name") or "") for p in active_plans if p.get("med_name"))
                except Exception:
                    app.logger.debug("Blood medication-plan context lookup skipped", exc_info=True)
                seen_meds = []
                for part in medication_parts:
                    part = re.sub(r"\s+", " ", str(part or "")).strip()
                    if part and part.lower() not in {x.lower() for x in seen_meds}:
                        seen_meds.append(part)
                context_medications = "، ".join(seen_meds)[:800]
            except Exception:
                app.logger.debug("Blood medication-context lookup skipped", exc_info=True)
        trend = blood_test.compare_with_history(indicators, previous_tests, lang, current_report_meta=report_meta)
        health_context_links = lab_intake.build_health_context_links(indicators, latest_symptom_record, context_medications, lang)

        chart_b64 = None
        try:
            chart = blood_test.generate_blood_chart(results)
            if chart:
                chart_b64 = base64.b64encode(chart).decode("ascii")
        except Exception:
            app.logger.warning("Blood chart generation failed", exc_info=True)

        attention = {
            "out_of_range": sum(1 for i in indicators if i.get("status") in {"low", "high"}),
            "urgent": sum(1 for i in indicators if i.get("attention_level") == "urgent"),
            "emergency": sum(1 for i in indicators if i.get("attention_level") == "emergency"),
            "normal": sum(1 for i in indicators if i.get("status") == "normal"),
            "unclassified": sum(1 for i in indicators if i.get("status") == "unclassified"),
        }
        summary_text = blood_test.summary_text(level, lang)
        disclaimer_text = blood_test.disclaimer_text(lang)
        child_note_text = blood_test.child_note_text(lang) if child_note else None
        payload = {
            "gender": gender, "age": age, "level": level,
            "summary": summary_text,
            "indicators": indicators,
            "notes": [n[0] if lang == "ar" else n[1] for n in notes],
            "dangers": [d[1] if lang == "ar" else d[2] for d in dangers],
            "patterns": patterns,
            "relationships": relationships,
            "trend": trend,
            "doctor_summary": doctor_summary,
            "doctor_questions": doctor_questions,
            "clinical_context": clinical_context,
            "context_notes": context_notes,
            "attention": attention,
            "confirmed_by_user": mode == "analyze_confirmed",
            "verification": verification,
            "medical_sources": medical_sources,
            "disclaimer": disclaimer_text,
            "child": bool(child_note),
            "child_note": child_note_text,
            "chart": chart_b64,
            "member_name": member.get("name") if member else None,
            "blood_collection_consent": True,
            "blood_collection_consent_version": BLOOD_COLLECTION_CONSENT_VERSION,
            "blood_collection_consent_at": datetime.now(timezone.utc).isoformat(),
            "source_file_stored": False,
            "source_file_sha256": source_file_hash or None,
            "extraction_meta": dict(extraction_meta, extracted_count=len(entries)),
            "report_meta": report_meta,
            "health_context_links": health_context_links,
        }
        blood_id = None
        if _ss_user_id():
            try:
                blood_id, created = db.save_blood_test_once(
                    _data_user_id(), payload, member_id, file_hash=(source_file_hash or None)
                )
                if not created and source_file_hash:
                    saved_duplicate = db.find_blood_test_by_file_hash(
                        _data_user_id(), source_file_hash, member_id
                    )
                    if saved_duplicate:
                        if mode == "analyze_confirmed":
                            session.pop("blood_extraction_receipt_v1", None)
                        return jsonify(_blood_saved_result_response(
                            saved_duplicate, lang, member.get("name") if member else None
                        ))
            except Exception:
                app.logger.debug("Blood result persistence skipped", exc_info=True)
        if _analytics_consent_ok():
            best_effort.call(platform_v2.record_usage, 'blood_analysis_complete', '/api/blood', lang, request.headers.get('User-Agent', ''), 200, None, service='lab_analysis')
        if mode == "analyze_confirmed":
            session.pop("blood_extraction_receipt_v1", None)
        return jsonify({
            "ok": True, "stage": "result", "text_html": text_html, "chart": chart_b64, "level": level,
            "indicators": indicators,
            "notes": [n[0] if lang == "ar" else n[1] for n in notes],
            "dangers": [d[1] if lang == "ar" else d[2] for d in dangers],
            "summary": summary_text,
            "disclaimer": disclaimer_text,
            "child": bool(child_note), "child_note": child_note_text,
            "blood_id": blood_id, "member_name": member.get("name") if member else None,
            "patterns": patterns, "relationships": relationships, "trend": trend,
            "doctor_summary": doctor_summary, "doctor_questions": doctor_questions,
            "clinical_context": clinical_context, "context_notes": context_notes,
            "attention": attention, "verification": verification,
            "medical_sources": medical_sources,
            "extraction_meta": dict(extraction_meta, extracted_count=len(entries)),
            "report_meta": report_meta,
            "health_context_links": health_context_links,
            "confirmed_by_user": mode == "analyze_confirmed",
        })
    except Exception as e:
        return _mk_error(e, 500)


def register_routes(app, namespace):
    """Inject webapp dependencies, apply the original decorators, and add the URL rules (same endpoint names)."""
    missing = [n for n in DEPS if n not in namespace]
    if missing:
        raise RuntimeError("routes.labs: missing dependencies %s" % missing)
    g = globals()
    for n in DEPS:
        g[n] = _inject.dependency(namespace, n)
    g["app"] = app
    for name, spec in _SPECS.items():
        view = spec["fn"]
        for w in reversed(_WRAPPERS.get(name, ())):
            view = _inject.resolve_wrapper(w, g)(view)
        for rule, opts in spec["rules"]:
            kw = dict(opts)
            endpoint = kw.pop("endpoint", name)
            app.add_url_rule(rule, endpoint=endpoint, view_func=view, **kw)
