"""Routes for group "tracking", moved out of webapp.py (behaviour unchanged).

Dependencies from webapp.py are injected by register(); decorators like login_required are applied there in the
original order. Generated by tools/extract_routes.py.
"""
from routes import _inject
from services.profile_dashboard_service import validate_profile_field
from datetime import datetime
from datetime import timezone
from flask import g
from flask import jsonify
from flask import request
from flask import url_for
import advanced_features
import db
import logging
import privacy_features

DEPS = ("_checkin_api_payload", "_consent_required_json", "_data_user_id", "_family_member_payload", "_followup_local_answer", "_groq_chat_completion_with_retry", "_lang", "_mk_error", "_service_consent_ok", "_site_url", "_ss_user_id", "api_login_required", "login_required", )

_SPECS = {}
_WRAPPERS = {
    "api_health_profile": ('login_required', ),
    "api_delete_health_profile": ('login_required', ),
    "api_update_health_field": ('login_required', ),
    "api_delete_health_field": ('login_required', ),
    "api_user_analysis_item": ('login_required', ),
    "api_analysis_history": (),
    "api_smart_followup": (),
    "api_family": ('api_login_required', ),
    "api_family_one": ('api_login_required', ),
    "api_timeline": ('api_login_required', ),
    "api_handoff_candidates": ('api_login_required', ),
    "api_handoff_create": ('api_login_required', ),
    "api_handoff_revoke": ('api_login_required', ),
    "api_followup": (),
    "api_checkin": (),
    "api_feedback": (),
}


def route(rule, **opts):
    def deco(fn):
        _SPECS.setdefault(fn.__name__, {"fn": fn, "rules": []})["rules"].append((rule, opts))
        return fn
    return deco


@route("/api/health-profile", methods=["GET", "POST"])
def api_health_profile():
    db.init_db()
    uid = _ss_user_id()
    if request.method == "GET":
        profile = db.load_health_profile(uid) or {}
        return jsonify({"ok": True, "profile": profile})
    if not _service_consent_ok():
        return _consent_required_json("/manage")
    try:
        data = request.get_json(force=True)
        if not isinstance(data, dict):
            return jsonify({"ok": False, "error": "invalid_input"}), 400
        existing = db.load_health_profile(uid) or {}
        # This endpoint is used for small incremental updates from the assistant.
        # Merge rather than replacing the full optional health profile, otherwise
        # a one-field update could erase medications/allergies/conditions.
        allowed = {"display_name", "dob", "gender", "height", "weight", "activity_level", "medications", "allergies", "health_conditions", "extra_info", "lang"}
        merged = dict(existing)
        incoming = {k: v for k, v in data.items() if k in allowed}
        for key, raw in list(incoming.items()):
            ok, cleaned = validate_profile_field(key, raw)
            if not ok:
                return jsonify({"ok": False, "error": cleaned, "field": key}), 400
            incoming[key] = cleaned
        merged.update(incoming)
        db.save_health_profile(uid, merged)
        return jsonify({"ok": True})
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/health-profile/delete", methods=["POST"])
def api_delete_health_profile():
    db.init_db()
    try:
        db.delete_health_profile(_ss_user_id())
        return jsonify({"ok": True})
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/health-profile/field", methods=["POST"])
def api_update_health_field():
    db.init_db()
    if not _service_consent_ok():
        return _consent_required_json("/manage")
    uid = _ss_user_id()
    data = request.get_json(force=True)
    field = data.get("field", "")
    value = data.get("value", "")
    allowed = {"display_name", "dob", "gender", "height", "weight", "activity_level", "medications", "allergies", "health_conditions", "extra_info", "lang"}
    if field not in allowed:
        return jsonify({"ok": False, "error": "Invalid field"})
    ok, cleaned = validate_profile_field(field, value)
    if not ok:
        return jsonify({"ok": False, "error": cleaned, "field": field}), 400
    try:
        existing = db.load_health_profile(uid) or {}
        existing[field] = cleaned
        db.save_health_profile(uid, existing)
        return jsonify({"ok": True, "value": cleaned})
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/health-profile/field/delete", methods=["POST"])
def api_delete_health_field():
    db.init_db()
    uid = _ss_user_id()
    data = request.get_json(force=True)
    field = data.get("field", "")
    allowed = {"display_name", "dob", "gender", "height", "weight", "activity_level", "medications", "allergies", "health_conditions", "extra_info"}
    if field not in allowed:
        return jsonify({"ok": False, "error": "Invalid field"})
    try:
        existing = db.load_health_profile(uid) or {}
        existing[field] = ""
        db.save_health_profile(uid, existing)
        return jsonify({"ok": True})
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/analysis/<int:record_id>", methods=["GET", "DELETE"])
def api_user_analysis_item(record_id):
    if request.method == "DELETE":
        ok=advanced_features.delete_user_analysis(_data_user_id(), record_id)
        return jsonify({"ok": ok}), (200 if ok else 404)
    row=advanced_features.get_user_analysis(_data_user_id(), record_id)
    if not row: return jsonify({"ok": False, "error": "not_found"}), 404
    return jsonify({"ok": True, "analysis": row})


@route("/api/analysis-history", methods=["GET"])
def api_analysis_history():
    """Return the logged-in user's recent analyses for profile page."""
    db.init_db()
    uid = _ss_user_id()
    if not uid:
        return jsonify({"ok": True, "records": [], "logged_in": False})
    records = db.get_records(_data_user_id(), limit=10, member_id=0)
    return jsonify({"ok": True, "records": records, "logged_in": True})


@route("/api/smart-followup", methods=["GET", "POST"])
def api_smart_followup():
    """Offer and record a privacy-preserving follow-up for the latest saved analysis."""
    uid = _ss_user_id()
    if not uid:
        return jsonify({"ok": True, "eligible": False, "logged_in": False})
    if not _service_consent_ok():
        if request.method == "POST":
            return _consent_required_json("/chat")
        return jsonify({"ok": True, "eligible": False, "logged_in": True, "reason": "consent_required"})
    db.init_db()
    privacy = db.load_privacy_settings(uid) or {}
    if not privacy.get("use_in_analysis", True):
        return jsonify({"ok": True, "eligible": False, "logged_in": True, "reason": "reuse_disabled"})
    user_key = _data_user_id()
    if request.method == "GET":
        records = db.get_records(user_key, limit=1, member_id=0)
        if not records:
            return jsonify({"ok": True, "eligible": False, "logged_in": True})
        rec = records[0]
        try:
            ts = datetime.fromisoformat(str(rec.get("timestamp") or "").replace("Z", "+00:00"))
            if ts.tzinfo is None:
                ts = ts.replace(tzinfo=timezone.utc)
            age_seconds = max(0.0, (datetime.now(timezone.utc) - ts.astimezone(timezone.utc)).total_seconds())
            age_days = int(age_seconds // 86400)
        except Exception:
            age_seconds = 10**12
            age_days = 9999
        # Do not ask immediately after an assessment; follow-up becomes useful
        # after enough time has passed to notice change, and expires after 30 days.
        if age_seconds < 12 * 3600:
            return jsonify({"ok": True, "eligible": False, "logged_in": True, "reason": "too_soon"})
        if age_days > 30:
            return jsonify({"ok": True, "eligible": False, "logged_in": True, "reason": "too_old"})
        latest_fu = db.get_latest_followup(user_key, rec.get("id"))
        if latest_fu:
            try:
                fu_ts = datetime.fromisoformat(str(latest_fu.get("timestamp") or "").replace("Z", "+00:00"))
                if fu_ts.tzinfo is None:
                    fu_ts = fu_ts.replace(tzinfo=timezone.utc)
                # Avoid prompting repeatedly on every visit after a recent answer.
                if (datetime.now(timezone.utc) - fu_ts.astimezone(timezone.utc)).total_seconds() < 20 * 3600:
                    return jsonify({"ok": True, "eligible": False, "logged_in": True, "reason": "recently_answered"})
            except Exception:
                pass
        return jsonify({"ok": True, "eligible": True, "logged_in": True, "analysis": rec, "age_days": age_days})

    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        return jsonify({"ok": False, "error": "invalid_json_object"}), 400
    try:
        record_id = int(data.get("record_id") or 0)
    except (TypeError, ValueError):
        return jsonify({"ok": False, "error": "invalid_record_id"}), 400
    try:
        outcome, new_sign = db.normalize_followup(data.get("outcome"), data.get("new_sign"))
    except ValueError:
        return jsonify({"ok": False, "error": "invalid_outcome"}), 400
    owned = db.get_record_owned(user_key, record_id)
    if not owned:
        return jsonify({"ok": False, "error": "not_found"}), 404
    db.save_followup(user_key, record_id, outcome, new_sign)
    return jsonify({
        "ok": True,
        "recorded": True,
        "outcome": outcome,
        "new_sign": new_sign,
        "reanalyze_recommended": outcome in {"same", "worse"} or new_sign,
        "analysis": owned,
    })


@route("/api/family", methods=["GET", "POST"])
def api_family():
    try:
        db.init_db()
        uid = _data_user_id()
        if request.method == "POST":
            if not _service_consent_ok(): return _consent_required_json("/family")
            try:
                payload = _family_member_payload(request.get_json(force=True))
            except ValueError as exc:
                return jsonify({"ok": False, "error": exc.args[0] if exc.args else "invalid_input"}), 400
            mid = db.save_member(uid, **payload)
            return jsonify({"ok": True, "id": mid})
        members = db.list_members(uid)
        for m in members:
            m["records_count"] = len(db.get_records(uid, limit=100, member_id=m["id"]))
            m["adherence"] = db.med_adherence(uid, member_id=m["id"])["percent"]
        return jsonify({"ok": True, "members": members})
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/family/<int:mid>", methods=["POST", "DELETE"])
def api_family_one(mid):
    try:
        db.init_db()
        uid = _data_user_id()
        if not db.get_member(uid, mid):
            return jsonify({"ok": False, "error": "family_member_not_found"}), 404
        if request.method == "DELETE":
            db.delete_member(uid, mid)
            return jsonify({"ok": True})
        if not _service_consent_ok(): return _consent_required_json("/family")
        try:
            payload = _family_member_payload(request.get_json(force=True))
        except ValueError as exc:
            return jsonify({"ok": False, "error": exc.args[0] if exc.args else "invalid_input"}), 400
        db.update_member(uid, mid, **payload)
        return jsonify({"ok": True})
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/timeline", methods=["GET"])
def api_timeline():
    try:
        db.init_db()
        member_id = int(request.args.get("member") or 0)
        days = max(1, min(365, int(request.args.get("days") or 30)))
        if member_id < 0:
            raise ValueError("invalid_member")
        events = db.member_timeline(_data_user_id(), member_id, days)
        return jsonify({"ok": True, "events": events})
    except (TypeError, ValueError):
        return jsonify({"ok": False, "error": "invalid_query"}), 400
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/handoff/candidates", methods=["GET"])
def api_handoff_candidates():
    try:
        rows=advanced_features.user_analysis_rows(_data_user_id(),limit=12)
        out=[{"id":r.get("id"),"timestamp":r.get("timestamp"),"symptoms":r.get("symptoms") or [],"risk_level":(r.get("result") or {}).get("risk_level") or r.get("urgency")} for r in rows]
        return jsonify({"ok":True,"analyses":out})
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/handoff/create", methods=["POST"])
def api_handoff_create():
    try:
        data=request.get_json(silent=True) or {}
        result=privacy_features.create_handoff(_data_user_id(),int(data.get("record_id") or 0),data.get("selected") or {},data.get("previous_ids") or [],int(data.get("expires_minutes") or 60))
        payload_lang = "en" if (result.get("payload") or {}).get("lang") == "en" else "ar"
        # Build the QR from the dedicated PUBLIC HTML route only.  Using the
        # canonical public host avoids reverse-proxy/API-path leakage on Railway,
        # and the language query lets a recipient open it without an existing
        # SymptoSense language cookie.
        share_path = url_for("public_health_handoff", token=result["token"], lang=payload_lang)
        share_url = _site_url().rstrip("/") + share_path
        return jsonify({"ok":True,"token":result["token"],"share_url":share_url,"expires_at":result["expires_at"],"qr_data_uri":privacy_features.qr_png_data_uri(share_url)})
    except PermissionError:
        return jsonify({"ok":False,"error":"analysis_not_found","error_code":"analysis_not_found"}),403
    except ValueError as e:
        code = str(e) if str(e) in {"invalid_expiration","select_at_least_one_field","selected_information_empty"} else "invalid_request"
        return jsonify({"ok":False,"error":code,"error_code":code}),400
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/handoff/revoke", methods=["POST"])
def api_handoff_revoke():
    try:
        data=request.get_json(silent=True) or {}
        ok=privacy_features.revoke_handoff(_data_user_id(),str(data.get("token") or ""))
        return jsonify({"ok":bool(ok)}) if ok else (jsonify({"ok":False,"error":"not_found_or_not_owned"}),404)
    except Exception as e:
        return _mk_error(e, 500)


@route("/api/analysis/followup-question", methods=["POST"])
def api_followup():
    if not _service_consent_ok():
        return _consent_required_json("/chat")
    lang = "ar"
    question = ""
    ctx = {}
    try:
        data = request.get_json(silent=True) or {}
        question = (data.get("question") or "").strip()
        ctx = data.get("context") or {}
        lang = "en" if ctx.get("lang") == "en" else "ar"
        if not question:
            return jsonify({"ok": False, "error": "السؤال فارغ" if lang == "ar" else "Empty question"})
        if lang == "en":
            prompt = (
                "You are SymptoSense, a friendly health awareness assistant. Answer in clear, warm English.\n"
                "These are the user's previous analysis summaries:\n"
                f"Symptoms: {ctx.get('symptoms')}\n"
                f"Result: {ctx.get('possible_conditions')}\n"
                f"Urgency: {ctx.get('urgency')}\n"
                f"Recommendations: {ctx.get('recommendations')}\n\n"
                f"The user now asks: {question}\n\n"
                "Answer briefly (150 words max) and remind that this is awareness information, not a final diagnosis."
            )
        else:
            prompt = (
                "أنت SymptoSense، مساعد صحي توعوي. أجب بالعربية بأسلوب سعودي واضح وودود.\n"
                "هذه ملخصات تحليل سابق للمستخدم:\n"
                f"الأعراض: {ctx.get('symptoms')}\n"
                f"النتيجة: {ctx.get('possible_conditions')}\n"
                f"الخطورة: {ctx.get('urgency')}\n"
                f"التوصيات: {ctx.get('recommendations')}\n\n"
                f"سؤال المستخدم الآن: {question}\n\n"
                "أجب بإيجاز (150 كلمة كحد أقصى) وذكّر أن هذه معلومات توعوية وليست تشخيصًا نهائيًا."
            )
        r = _groq_chat_completion_with_retry(
            [{"role": "user", "content": prompt}],
            temperature=0.5, max_completion_tokens=500, timeout=6,
        )
        answer = r.choices[0].message.content.strip()
        if not answer:
            answer = _followup_local_answer(question, ctx, lang)
        return jsonify({"ok": True, "answer": answer})
    except Exception as e:
        app.logger.warning("Follow-up provider unavailable; using local fallback; error_type=%s", type(e).__name__)
        return jsonify({"ok": True, "answer": _followup_local_answer(question, ctx, lang), "fallback": True})


@route("/api/checkin", methods=["GET", "POST"])
def api_checkin():
    # Daily tracking is intentionally account-bound. Guest/session identifiers
    # are not used because the history must follow the signed-in user only.
    if not _ss_user_id():
        return jsonify({
            "ok": False,
            "login_required": True,
            "error": "سجّل الدخول لحفظ ومتابعة حالتك اليومية." if _lang() == "ar" else "Sign in to save and track your daily health status.",
        }), 401

    # Daily tracking intentionally avoids the full database migration pass.
    # Production Railway databases may contain legacy tables whose unrelated
    # migrations can fail even though daily tracking only needs user_data.
    # The db.save/get_web_daily_checkin helpers ensure the minimal user_data
    # storage they need without touching legacy daily_checkins migrations.
    account_id = _ss_user_id()
    if request.method == "POST":
        if not _service_consent_ok():
            return _consent_required_json("/checkin")
        try:
            data = request.get_json(force=True) or {}
            rating = int(data.get("rating"))
            if rating < 1 or rating > 5:
                return jsonify({"ok": False, "error": "التقييم من 1 إلى 5" if _lang() == "ar" else "Rating must be from 1 to 5"}), 400
            day = str(data.get("date") or "").strip()
            try:
                datetime.strptime(day, "%Y-%m-%d")
            except (TypeError, ValueError, OverflowError):
                logging.getLogger(__name__).debug("Handled exception in api_checkin; fallback applied (handler 16983)")
                return jsonify({"ok": False, "error": "invalid_date"}), 400
            saved = db.save_web_daily_checkin(account_id, rating, day)
            payload = _checkin_api_payload(account_id, day)
            payload.update({"created": bool(saved.get("created")), "updated": not bool(saved.get("created"))})
            return jsonify(payload)
        except Exception as e:
            request_id = getattr(g, "request_id", "")
            app.logger.exception("Daily check-in save failed; request_id=%s error_type=%s", request_id, type(e).__name__)
            return jsonify({
                "ok": False,
                "error": "تعذر حفظ تسجيل الحالة الآن." if _lang() == "ar" else "Unable to save the daily check-in right now.",
                "error_code": "checkin_save_failed",
                "request_id": request_id,
            }), 500

    try:
        day = str(request.args.get("date") or datetime.now(timezone.utc).date().isoformat()).strip()
        try:
            datetime.strptime(day, "%Y-%m-%d")
        except (TypeError, ValueError, OverflowError):
            logging.getLogger(__name__).debug("Handled exception in api_checkin; fallback applied (handler 17003)")
            day = datetime.now(timezone.utc).date().isoformat()
        return jsonify(_checkin_api_payload(account_id, day))
    except Exception as e:
        request_id = getattr(g, "request_id", "")
        app.logger.exception("Daily check-in load failed; request_id=%s error_type=%s", request_id, type(e).__name__)
        return jsonify({
            "ok": False,
            "error": "تعذر تحميل تسجيلات الحالة الآن." if _lang() == "ar" else "Unable to load daily check-ins right now.",
            "error_code": "checkin_load_failed",
            "request_id": request_id,
        }), 500


@route("/api/feedback", methods=["POST"])
def api_feedback():
    # Feedback is an explicit user submission, separate from optional analytics consent.
    try:
        data = request.get_json(force=True) or {}
        try:
            rating = int(data.get("rating"))
        except (TypeError, ValueError, OverflowError):
            logging.getLogger(__name__).debug("Handled exception in api_feedback; fallback applied (handler 17024)")
            return jsonify({"ok": False, "error": "rating_must_be_1_to_5"}), 400
        if rating < 1 or rating > 5:
            return jsonify({"ok": False, "error": "rating_must_be_1_to_5"}), 400
        comment = (data.get("comment") or "").strip()[:500]
        public_comment = bool(data.get("public_comment")) and bool(comment)
        allowed_reasons = {"clear", "helpful", "too_short", "too_long", "unclear", "not_relevant", "missing_detail", "other"}
        reason_code = str(data.get("reason_code") or "").strip().lower() or None
        if reason_code is not None and reason_code not in allowed_reasons:
            return jsonify({"ok": False, "error": "invalid_reason"}), 400
        allowed_contexts = {"analysis_result", "assistant", "search", "other"}
        context = str(data.get("context") or "analysis_result").strip().lower()
        if context not in allowed_contexts:
            return jsonify({"ok": False, "error": "invalid_context"}), 400
        record_id = None
        raw_record_id = data.get("record_id")
        if raw_record_id not in (None, "", 0, "0"):
            try:
                candidate_id = int(raw_record_id)
            except (TypeError, ValueError):
                return jsonify({"ok": False, "error": "invalid_record_id"}), 400
            if _ss_user_id():
                if not db.get_record_owned(_data_user_id(), candidate_id):
                    return jsonify({"ok": False, "error": "record_not_found"}), 404
                record_id = candidate_id
        db.init_db()
        db.save_feedback(_data_user_id(), record_id, "star:%d" % rating, comment or None, public_comment=public_comment, reason_code=reason_code, context=context)
        return jsonify({"ok": True, "public_comment": public_comment, "reason_code": reason_code})
    except Exception as e:
        return _mk_error(e, 500)


def register_routes(app, namespace):
    """Inject webapp dependencies, apply the original decorators, and add the URL rules (same endpoint names)."""
    missing = [n for n in DEPS if n not in namespace]
    if missing:
        raise RuntimeError("routes.tracking: missing dependencies %s" % missing)
    g = globals()
    for n in DEPS:
        g[n] = _inject.dependency(namespace, n)
    g["app"] = app
    for name, spec in _SPECS.items():
        view = spec["fn"]
        for w in reversed(_WRAPPERS.get(name, ())):
            view = _inject.resolve_wrapper(w, g)(view)
        for rule, opts in spec["rules"]:
            kw = dict(opts)
            endpoint = kw.pop("endpoint", name)
            app.add_url_rule(rule, endpoint=endpoint, view_func=view, **kw)
