"""Page builders for group "search_answers", moved out of webapp.py (behaviour unchanged).

Dependencies from webapp.py are injected at start-up; decorators like login_required are applied there in the
original order. Generated by tools/extract_routes.py.
"""
from routes import _inject
from datetime import datetime
from datetime import timezone
from search_support import _health_search_topic_meta
import analysis_core
import health_search
import io
import json
import logging
import medical_knowledge
import os
import re

DEPS = ("_assistant_compact_response", "_assistant_contextual_health_answer", "_assistant_phrase_present", "_health_search_medication_context", "_health_search_symptom_for_relation", "_normalize_health_query_text", "_service_consent_ok", "_strip_search_answer_heading", )


def _pdf_report(result, lang="ar"):
    """Create the symptom-analysis PDF from the already-saved analysis result.

    Uses PyMuPDF Story so Arabic shaping/RTL work without relying on a bundled
    application font. No medical values are recalculated here: this function
    only formats the data already stored for the analysis.
    """
    import html as _html
    try:
        import fitz
    except ImportError as exc:
        raise RuntimeError("PDF renderer is unavailable") from exc

    ar = lang != "en"

    def esc(value):
        return _html.escape(str(value if value not in (None, "") else "—"))

    def as_lines(value):
        if value in (None, "", []):
            return []
        if isinstance(value, (tuple, list)):
            out = []
            for item in value:
                if isinstance(item, dict):
                    text = item.get("tip") or item.get("text") or item.get("message") or item.get("name") or item.get("title") or ""
                    if text:
                        out.append(str(text))
                elif item not in (None, ""):
                    out.append(str(item))
            return out
        text = str(value).replace("\r", "\n")
        parts = []
        for line in text.split("\n"):
            line = re.sub(r"^\s*[-•*]+\s*", "", line).strip()
            if line:
                parts.append(line)
        return parts or [text.strip()]

    def data_quality_text():
        dq = result.get("data_quality")
        if isinstance(dq, dict):
            val = dq.get("percentage")
            if val is None:
                val = dq.get("percent")
            if val is None:
                val = dq.get("score")
            label = dq.get("label_ar" if ar else "label_en") or dq.get("label") or ""
            if val is not None:
                try:
                    val = round(float(val))
                    return (f"{val}% - {label}" if label else f"{val}%")
                except (TypeError, ValueError, OverflowError):
                    logging.getLogger(__name__).debug("Handled exception in data_quality_text; fallback applied (handler 16016)")
                    pass
        if isinstance(dq, (int, float)):
            return f"{round(float(dq))}%"
        return "—"

    risk = str(result.get("urgency") or result.get("risk_level") or "low").lower()
    risk_labels = ({
        "low": "خطورة منخفضة", "monitor": "خطورة منخفضة", "medium": "يحتاج مراجعة طبية",
        "review": "يحتاج مراجعة طبية", "high": "طوارئ", "urgent": "طوارئ", "emergency": "طوارئ",
    } if ar else {
        "low": "Low risk", "monitor": "Low risk", "medium": "Needs medical review",
        "review": "Needs medical review", "high": "Emergency", "urgent": "Emergency", "emergency": "Emergency",
    })
    risk_label = result.get("risk_label") or risk_labels.get(risk) or ("تقييم صحي" if ar else "Health assessment")

    symptoms = result.get("symptoms") or []
    if not isinstance(symptoms, list):
        symptoms = as_lines(symptoms)
    symptom_text = ("، ".join(map(str, symptoms)) if ar else ", ".join(map(str, symptoms))) or "—"
    gender_raw = str(result.get("gender") or "").strip().lower()
    if ar:
        gender = {"f":"أنثى", "female":"أنثى", "m":"ذكر", "male":"ذكر"}.get(gender_raw, result.get("gender") or "—")
    else:
        gender = {"f":"Female", "female":"Female", "m":"Male", "male":"Male"}.get(gender_raw, result.get("gender") or "—")

    conditions = result.get("knowledge_matches") or []
    condition_blocks = []
    for item in conditions:
        if not isinstance(item, dict):
            continue
        name = (item.get("name_ar") if ar else item.get("name_en")) or item.get("name") or item.get("disease_name") or ""
        if not name:
            continue
        score = item.get("score")
        if score is None:
            score = item.get("matching_score")
        if score is None:
            score = item.get("match_score")
        score_html = ""
        if score not in (None, ""):
            score_html = f'<span class="pill">{esc("التوافق" if ar else "Match")}: {esc(score)}</span>'
        reason = item.get("why") or item.get("reason") or item.get("match_reason") or ""
        direct_source = item.get("explanation_source")
        if not isinstance(direct_source, dict):
            item_sources = item.get("sources") or []
            direct_source = item_sources[0] if item_sources and isinstance(item_sources[0], dict) else None
        direct_source_html = ""
        if direct_source:
            source_name = direct_source.get("source_name") or direct_source.get("organization") or direct_source.get("name") or ""
            source_title = (direct_source.get("reference_title_ar") if ar else direct_source.get("reference_title_en")) or direct_source.get("reference_title_en") or direct_source.get("reference_title_ar") or source_name
            source_url = direct_source.get("reference_url") or direct_source.get("official_url") or direct_source.get("url") or ""
            source_scope = str(direct_source.get("source_scope") or "")
            source_label = (("مرجع داعم للسياق" if ar else "Supporting context source")
                            if source_scope == "symptom_context_fallback"
                            else ("مرجع هذا التفسير" if ar else "Source for this explanation"))
            source_text = source_title or source_name
            if source_text:
                if source_url:
                    direct_source_html = '<p class="condition-source"><b>%s:</b> <a href="%s">%s</a></p>' % (esc(source_label), esc(source_url), esc(source_text))
                else:
                    direct_source_html = '<p class="condition-source"><b>%s:</b> %s</p>' % (esc(source_label), esc(source_text))
        condition_blocks.append(
            '<div class="condition"><div class="condition-head"><strong>%s</strong>%s</div>%s%s</div>' % (
                esc(name), score_html, ('<p>%s</p>' % esc(reason)) if reason else '', direct_source_html
            )
        )
    if not condition_blocks:
        raw_pc = result.get("possible_conditions") or ""
        if raw_pc:
            condition_blocks.append('<div class="condition"><p>%s</p></div>' % esc(raw_pc))

    recommendations = result.get("recommendations") or []
    rec_lines = as_lines(recommendations)
    danger_lines = as_lines(result.get("danger_signs"))
    home_lines = as_lines(result.get("home_care"))
    seek_lines = as_lines(result.get("when_to_seek_care"))
    doctor_lines = as_lines(result.get("questions_for_doctor"))

    source_cards = []
    for src in (result.get("medical_sources") or []):
        if not isinstance(src, dict):
            continue
        name = src.get("source_name") or src.get("organization") or src.get("name") or ("مصدر طبي" if ar else "Medical source")
        title = (src.get("reference_title_ar") if ar else src.get("reference_title_en")) or src.get("reference_title_en") or src.get("reference_title_ar") or ""
        source_url = src.get("reference_url") or src.get("official_url") or src.get("url") or ""
        source_link = ('<small><a href="%s">%s</a></small>' % (esc(source_url), esc(title or name))) if source_url else (('<small>%s</small>' % esc(title)) if title else '')
        source_cards.append('<div class="source"><strong>%s</strong>%s</div>' % (esc(name), source_link))

    labels = ({
        "title":"تقرير تحليل الأعراض", "subtitle":"SymptoSense - ملخص صحي توعوي",
        "summary":"نتيجة التحليل", "risk":"مستوى الخطورة", "quality":"اكتمال المعلومات المدخلة",
        "entered":"المعلومات المدخلة", "symptoms":"الأعراض", "duration":"المدة", "severity":"شدة الأعراض",
        "age":"العمر", "gender":"الجنس", "conditions":"الاحتمالات المحتملة", "now":"ماذا أفعل الآن؟",
        "warnings":"علامات تستدعي الانتباه", "home":"الرعاية المنزلية", "doctor":"أسئلة للطبيب",
        "sources":"المصادر الطبية", "none":"لم يتم تحديد معلومات إضافية ضمن هذا القسم.",
        "disclaimer":"هذه النتيجة توعوية ولا تقدم تشخيصًا طبيًا، ولا تغني عن استشارة مختص صحي عند الحاجة.",
        "generated":"تاريخ إنشاء التقرير",
    } if ar else {
        "title":"Symptom Analysis Report", "subtitle":"SymptoSense - Educational health summary",
        "summary":"Analysis result", "risk":"Risk level", "quality":"Information completeness",
        "entered":"Information entered", "symptoms":"Symptoms", "duration":"Duration", "severity":"Symptom severity",
        "age":"Age", "gender":"Gender", "conditions":"Possible conditions", "now":"What should I do now?",
        "warnings":"Warning signs", "home":"Home care", "doctor":"Questions for your clinician",
        "sources":"Medical sources", "none":"No additional information was provided for this section.",
        "disclaimer":"This result is educational and does not provide a medical diagnosis or replace professional medical advice when needed.",
        "generated":"Report generated",
    })

    def list_html(lines, empty=False):
        if not lines:
            return ('<p class="muted">%s</p>' % esc(labels["none"])) if empty else ""
        return '<ul>%s</ul>' % ''.join('<li>%s</li>' % esc(x) for x in lines)

    direction = "rtl" if ar else "ltr"
    align = "right" if ar else "left"
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    html_doc = f"""<!doctype html>
<html><head><meta charset="utf-8"><style>
*{{box-sizing:border-box}} body{{font-family:sans-serif;color:#23384A;font-size:10.5pt;line-height:1.55;direction:{direction};text-align:{align};}}
h1{{font-size:22pt;color:#163B5C;margin:0 0 4px}} h2{{font-size:14pt;color:#163B5C;margin:0 0 10px}} p{{margin:4px 0 8px}}
.header{{border-bottom:2px solid #DCE8F0;padding-bottom:14px;margin-bottom:16px}} .muted{{color:#566a7d}} .card{{border:1px solid #DCE8F0;border-radius:12px;padding:14px;margin:0 0 12px;background:#FFFFFF}}
.summary{{background:#F3F9FD}} .risk{{font-size:16pt;font-weight:700;color:#163B5C}} .pill{{display:inline-block;border:1px solid #DCE8F0;border-radius:999px;padding:2px 8px;font-size:8.5pt;color:#566a7d}}
.grid{{display:flex;flex-wrap:wrap;gap:8px}} .field{{width:48%;border:1px solid #E4EDF3;border-radius:9px;padding:8px}} .field b{{display:block;color:#566a7d;font-size:8.5pt;margin-bottom:2px}}
.condition,.source{{border:1px solid #E4EDF3;border-radius:9px;padding:10px;margin:7px 0}} .condition-head{{display:flex;justify-content:space-between;gap:8px;align-items:center}} .condition-source{{font-size:8.7pt;color:#49677D;margin-top:6px}} .condition-source a,.source a{{color:#1f6fae;text-decoration:none}} .source small{{display:block;color:#566a7d;margin-top:3px}}
ul{{margin:4px 0 0;padding-{'right' if ar else 'left'}:20px}} li{{margin:3px 0}} .disclaimer{{border:1px solid #EFDAA7;background:#FFF8E7;border-radius:10px;padding:10px;color:#6F531B;margin-top:15px}}
</style></head><body>
<div class="header"><h1>{esc(labels['title'])}</h1><p class="muted">{esc(labels['subtitle'])}</p><p class="muted">{esc(labels['generated'])}: {esc(generated)}</p></div>
<div class="card summary"><h2>{esc(labels['summary'])}</h2><div class="risk">{esc(labels['risk'])}: {esc(risk_label)}</div><p><b>{esc(labels['quality'])}:</b> {esc(data_quality_text())}</p></div>
<div class="card"><h2>{esc(labels['entered'])}</h2><div class="grid">
<div class="field"><b>{esc(labels['symptoms'])}</b>{esc(symptom_text)}</div>
<div class="field"><b>{esc(labels['duration'])}</b>{esc(result.get('duration'))}</div>
<div class="field"><b>{esc(labels['severity'])}</b>{esc(result.get('severity'))}</div>
<div class="field"><b>{esc(labels['age'])}</b>{esc(result.get('age'))}</div>
<div class="field"><b>{esc(labels['gender'])}</b>{esc(gender)}</div>
</div></div>
<div class="card"><h2>{esc(labels['conditions'])}</h2>{''.join(condition_blocks) or '<p class="muted">'+esc(labels['none'])+'</p>'}</div>
<div class="card"><h2>{esc(labels['now'])}</h2>{list_html(rec_lines + seek_lines, True)}</div>
<div class="card"><h2>{esc(labels['warnings'])}</h2>{list_html(danger_lines, True)}</div>
{('<div class="card"><h2>'+esc(labels['home'])+'</h2>'+list_html(home_lines)+'</div>') if home_lines else ''}
{('<div class="card"><h2>'+esc(labels['doctor'])+'</h2>'+list_html(doctor_lines)+'</div>') if doctor_lines else ''}
{('<div class="card"><h2>'+esc(labels['sources'])+'</h2>'+''.join(source_cards)+'</div>') if source_cards else ''}
<div class="disclaimer">{esc(labels['disclaimer'])}</div>
</body></html>"""

    buf = io.BytesIO()
    writer = fitz.DocumentWriter(buf)
    page = fitz.paper_rect("a4")
    story = fitz.Story(html=html_doc)
    more = True
    page_count = 0
    try:
        while more:
            page_count += 1
            if page_count > 40:
                raise RuntimeError("PDF exceeded safe page limit")
            device = writer.begin_page(page)
            more, _ = story.place(fitz.Rect(42, 42, page.width - 42, page.height - 42))
            story.draw(device)
            writer.end_page()
    finally:
        writer.close()
    buf.seek(0)
    if not buf.getvalue().startswith(b"%PDF"):
        raise RuntimeError("Invalid PDF output")
    return buf



def _assistant_general_local_fallback(text, lang):
    """Demo-safe local fallback for health questions outside the curated index.

    It preserves the user's full query, avoids diagnosis, and gives a relevant
    next step even when the external provider is unavailable.
    """
    query = " ".join(str(text or "").strip().split())[:600]
    if not query:
        return None
    low = query.lower()
    ar = lang != "en"

    # Common real-world demo query: painless knee clicking/crepitus.
    knee = any(k in low for k in ("ركب", "knee"))
    click = any(k in low for k in ("طقط", "فرقع", "صوت", "click", "crack", "pop", "crepitus"))
    no_pain = any(k in low for k in ("بدون ألم", "بدون الم", "ما فيه ألم", "مافي ألم", "no pain", "painless"))
    if knee and click:
        if ar:
            base = (
                "طقطقة الركبة قد تحدث مع حركة الأوتار أو الأنسجة أو فقاعات صغيرة داخل المفصل، "
                "وقد تكون شائعة إذا لم يصاحبها ألم أو تورم أو عدم ثبات. "
            )
            if not no_pain:
                base += "وجود ألم أو تورم أو قفل بالمفصل يغيّر التقييم. "
            return base + "راجع مختصًا إذا بدأت بعد إصابة، أو ظهر ألم/تورم/احمرار، أو صارت الركبة تعلق أو تخونك. هذه معلومات توعوية وليست تشخيصًا."
        base = "Knee clicking can occur from normal movement of tendons/tissues or small gas bubbles in the joint, and it is often benign when there is no pain, swelling, or instability. "
        if not no_pain:
            base += "Pain, swelling, locking, or giving-way changes the picture. "
        return base + "Seek medical review if it followed an injury or you develop pain, swelling, redness, locking, or instability. This is educational information, not a diagnosis."

    # Category-aware fallback: useful without pretending the local KB knows the answer.
    groups = [
        (("دواء", "أدوية", "حبة", "جرعة", "medicine", "medication", "drug", "dose"),
         "سؤالك يبدو متعلقًا بدواء. لا أؤكد جرعة أو تداخلًا دون اسم الدواء والتركيز وما الأدوية الأخرى المستخدمة. اذكر الاسم كما على العبوة، ولا تبدأ أو توقف دواءً موصوفًا من نفسك.",
         "Your question appears medication-related. I cannot safely confirm a dose or interaction without the exact medicine, strength, and other medicines used. Share the label name, and do not start or stop a prescribed medicine on your own."),
        (("تحليل", "مختبر", "cbc", "wbc", "hgb", "سكر", "lab", "test result", "blood test"),
         "سؤالك يبدو متعلقًا بنتيجة تحليل. اكتب اسم الفحص والقيمة والوحدة والمدى المرجعي المكتوب في المختبر؛ التفسير يعتمد على هذه التفاصيل والسياق الصحي.",
         "Your question appears to be about a lab result. Share the test name, value, unit, and the laboratory reference range; interpretation depends on those details and clinical context."),
        (("دورة", "حيض", "حمل", "مهبل", "period", "menstrual", "pregnan", "vaginal"),
         "سؤالك يتعلق بالصحة النسائية. التوقيت بالنسبة للدورة أو احتمال الحمل، شدة الألم أو النزف، ووجود دوخة أو إغماء تفاصيل مهمة. إذا كان هناك نزيف شديد جدًا أو ألم شديد مفاجئ أو إغماء فاطلب تقييمًا عاجلًا.",
         "Your question relates to menstrual/pregnancy health. Timing, pregnancy possibility, pain/bleeding severity, and faintness are important. Seek urgent care for very heavy bleeding, sudden severe pain, or fainting."),
        (("نوم", "أرق", "تعب", "sleep", "insomnia", "fatigue"),
         "سؤالك يتعلق بالنوم أو الإرهاق. المدة، عدد ساعات النوم، الأدوية/الكافيين، ووجود أعراض أخرى مثل ضيق النفس أو فقدان وزن تساعد على فهمه. إذا استمر أو أثر في يومك فراجع مختصًا.",
         "Your question relates to sleep or fatigue. Duration, sleep hours, medicines/caffeine, and other symptoms such as breathlessness or weight loss help clarify it. Seek medical review if it persists or disrupts daily life."),
        (("جلد", "طفح", "حكة", "rash", "skin", "itch"),
         "سؤالك يبدو متعلقًا بالجلد. صف الشكل والمكان والمدة وهل يوجد دواء/طعام جديد. صعوبة التنفس أو تورم الشفاه/اللسان مع طفح تستدعي مساعدة عاجلة.",
         "Your question appears skin-related. Describe appearance, location, duration, and any new medicine/food. A rash with breathing difficulty or lip/tongue swelling needs urgent help."),
        (("بول", "تبول", "urine", "urinary", "pee"),
         "سؤالك يبدو متعلقًا بالمسالك البولية. وجود حرقة أو دم أو حرارة أو ألم بالخاصرة أو صعوبة شديدة في التبول يغيّر درجة الاستعجال؛ اذكر هذه التفاصيل إن وجدت.",
         "Your question appears urinary. Burning, blood, fever, flank pain, or major difficulty urinating changes urgency; include those details if present."),
    ]
    for keys, ara, eng in groups:
        if any(k in low for k in keys):
            return (ara if ar else eng) + (" هذه معلومات توعوية وليست تشخيصًا." if ar else " This is educational information, not a diagnosis.")

    # Reuse the full symptom dictionary when the smaller explanation index has
    # no entry. Do not invent a condition simply to produce a named result.
    symptom_rows = getattr(medical_knowledge, "SYMPTOMS", [])
    recognised = []
    for row in symptom_rows:
        aliases = [row[1], row[2]] + list(row[4]) + list(row[5])
        if any(_assistant_phrase_present(query, alias) for alias in aliases):
            recognised.append(row)
    if recognised:
        names = list(dict.fromkeys(row[1] if ar else row[2] for row in recognised))[:3]
        category = recognised[0][3]
        prompts = {
            "pain": ("أين مكان الألم بالضبط، وهل بدأ فجأة؟", "Where exactly is the pain, and did it start suddenly?"),
            "digestive": ("هل يرتبط بالأكل أو بتغيّر التبرز؟", "Does it relate to meals or a change in bowel habits?"),
            "respiratory": ("هل يحدث في الراحة أم مع المجهود؟", "Does it occur at rest or with activity?"),
            "neurological": ("هل بدأ فجأة أم تدريجيًا، وهل يؤثر في نشاطك؟", "Did it start suddenly or gradually, and does it affect your activities?"),
            "skin": ("أين يظهر، وهل تغيّر شكله أو انتشر؟", "Where is it, and has it changed or spread?"),
        }
        question = prompts.get(category, ("متى بدأ، وهل يستمر أم يأتي على فترات؟", "When did it start, and is it constant or intermittent?"))[0 if ar else 1]
        return (("فهمت أنك تسأل عن «" + query + "»، ويتضمن: " + "، ".join(names) + ". لا تكفي هذه المعلومات لتحديد السبب. " + question +
                 " إذا كان العرض شديدًا أو مفاجئًا أو صاحبه إغماء أو صعوبة تنفس أو ألم صدر، اطلب تقييمًا عاجلًا.") if ar else
                ("Your question “" + query + "” includes: " + ", ".join(names) + ". This is not enough to establish the cause. " + question +
                 " Seek urgent assessment for severe or sudden symptoms, fainting, breathing difficulty, or chest pain."))

    return (
        "أفهم سؤالك: «" + query + "». لا توجد مطابقة موثوقة كافية في قاعدة المعرفة المحلية لأعطي سببًا محددًا دون تخمين. "
        "اذكر متى بدأ، المدة، الشدة، وما الذي يزيده أو يخففه وأي أدوية/أعراض مصاحبة؛ وإذا كان العرض شديدًا أو مفاجئًا أو معه صعوبة تنفس أو ألم صدر أو إغماء فاطلب تقييمًا عاجلًا. هذه معلومات توعوية وليست تشخيصًا."
        if ar else
        "I understand your question: “" + query + "”. The local knowledge base does not have a reliable enough direct match to name a cause without guessing. "
        "Add onset, duration, severity, triggers/relievers, medicines, and associated symptoms; seek urgent care for severe/sudden symptoms, breathing difficulty, chest pain, or fainting. This is educational information, not a diagnosis."
    )



def _health_search_relation_result(query, lang):
    """Build a relationship-first result for medicine + symptom queries.

    If a medicine is present, the search must never fall back to a standalone
    symptom card.  The relationship itself becomes the primary result.
    """
    q = " ".join(str(query or "").strip().split())[:600]
    if not q:
        return None
    ar = lang != "en"
    med = _health_search_medication_context(q, lang)
    if not med:
        return None

    symptom = _health_search_symptom_for_relation(q, lang, med)
    med_name = str((med.get("name_ar") if ar else med.get("name_en")) or ("الدواء" if ar else "the medicine")).strip()
    med_slug = med.get("slug") or ""
    norm = _normalize_health_query_text(q)

    # If no symptom was identified, still preserve the medicine context and
    # answer the complete query rather than allowing a fuzzy unrelated card.
    if not isinstance(symptom, dict):
        return {
            "key": "medicine_context_query",
            "emoji": "💊",
            "category": "medication",
            "title": q,
            "what": (
                f"سؤالك يتعلق بـ {med_name}. سأتعامل مع العبارة كاملة، وليس كبحث عن كلمة واحدة."
                if ar else
                f"Your question concerns {med_name}. The full phrase is treated as the intent, not a single-keyword lookup."
            ),
            "causes_label": "💡 معلومات مرتبطة بالسؤال" if ar else "💡 Relevant information",
            "causes": [],
            "worry": "",
            "doctor": "",
            "sources": med.get("sources") or [],
            "recognized_topics": [med_name],
            "original_query": q,
            "contextual": True,
            "relation_query": True,
            "query_only": False,
        }

    symptom_title = str(symptom.get("title") or ("العرض" if ar else "the symptom")).strip()

    # High-confidence Mounjaro/tirzepatide + dizziness relationship.
    dizziness = ("دوخ" in norm) if ar else any(x in q.lower() for x in ("dizzy", "dizziness", "lightheaded"))
    if med_slug == "mounjaro_tirzepatide" and dizziness:
        if ar:
            return {
                "key": "mounjaro_dizziness_relation",
                "emoji": "💊",
                "category": "medication",
                "title": "الدوخة مع مونجارو (تيرزيباتيد)",
                "what": (
                    "الدوخة قد تظهر مع استخدام مونجارو عند بعض الأشخاص، وغالبًا يكون السبب غير مباشر مثل قلة الأكل أو السوائل، "
                    "الجفاف بسبب الغثيان/القيء/الإسهال، أو انخفاض سكر الدم خصوصًا عند استخدام الإنسولين أو أدوية أخرى تخفّض السكر معه."
                ),
                "causes_label": "💡 ما الذي قد يفسّر الدوخة مع مونجارو؟",
                "causes": [
                    "الجفاف أو نقص السوائل، خصوصًا مع الغثيان أو القيء أو الإسهال",
                    "قلة الأكل أثناء بدء العلاج أو بعد زيادة الجرعة",
                    "انخفاض سكر الدم إذا كان مونجارو مستخدمًا مع الإنسولين أو أدوية محفّزة لإفراز الإنسولين",
                ],
                "worry": (
                    "اطلب مساعدة عاجلة إذا حدث إغماء أو تشوش شديد، صعوبة في التنفس أو البلع، تورم بالوجه/اللسان، "
                    "أو دوخة شديدة مع أعراض انخفاض سكر لا تتحسن وفق خطة علاجك."
                ),
                "doctor": (
                    "إذا بدأت الدوخة بعد بدء مونجارو أو بعد رفع الجرعة، أو تكررت أو أثرت على نشاطك، تواصل مع الطبيب أو الصيدلي "
                    "لمراجعة الجرعة والأدوية الأخرى والسوائل وقراءات السكر. لا توقف أو تغيّر الجرعة الموصوفة من نفسك."
                ),
                "sources": med.get("sources") or [],
                "recognized_topics": [symptom_title, med_name],
                "original_query": q,
                "contextual": True,
                "relation_query": True,
                "query_only": False,
            }
        return {
            "key": "mounjaro_dizziness_relation",
            "emoji": "💊",
            "category": "medication",
            "title": "Dizziness with Mounjaro (tirzepatide)",
            "what": (
                "Dizziness can occur while using Mounjaro in some people, often indirectly because of reduced food/fluid intake, "
                "dehydration from nausea/vomiting/diarrhea, or low blood sugar especially when insulin or another glucose-lowering medicine is also used."
            ),
            "causes_label": "💡 What may explain dizziness with Mounjaro?",
            "causes": [
                "Dehydration or reduced fluid intake, especially with nausea, vomiting, or diarrhea",
                "Eating less around treatment initiation or dose escalation",
                "Low blood sugar when Mounjaro is used with insulin or an insulin secretagogue",
            ],
            "worry": (
                "Seek urgent help for fainting, severe confusion, trouble breathing or swallowing, facial/tongue swelling, "
                "or severe dizziness with low-blood-sugar symptoms that do not improve according to your treatment plan."
            ),
            "doctor": (
                "If dizziness began after starting Mounjaro or increasing the dose, keeps recurring, or affects normal activity, contact your prescriber or pharmacist "
                "to review the dose, other medicines, hydration, and glucose. Do not stop or change a prescribed dose on your own."
            ),
            "sources": med.get("sources") or [],
            "recognized_topics": [symptom_title, med_name],
            "original_query": q,
            "contextual": True,
            "relation_query": True,
            "query_only": False,
        }

    warn = str((med.get("warning_ar") if ar else med.get("warning_en")) or "").strip()
    interact = str((med.get("interact_ar") if ar else med.get("interact_en")) or "").strip()
    if ar:
        what = (
            f"سؤالك عن علاقة {symptom_title} بـ {med_name}. لا ينبغي اختزال السؤال إلى شرح {symptom_title} وحده. "
            + (("من التنبيهات المتاحة عن الدواء: " + warn) if warn else "المعلومات المحلية لا تكفي لتأكيد أن الدواء هو السبب مباشرة.")
        )
        doctor = (
            "إذا بدأ العرض بعد بدء الدواء أو بعد تغيير الجرعة، أو تكرر أو ازداد، تواصل مع الطبيب أو الصيدلي مع ذكر توقيت الجرعة وبقية الأدوية. "
            "لا توقف أو تغيّر دواءً موصوفًا من نفسك."
        )
    else:
        what = (
            f"Your question is about the relationship between {symptom_title} and {med_name}; it should not be reduced to a generic {symptom_title} explanation. "
            + (("Available medicine cautions include: " + warn) if warn else "The local record is not enough to prove the medicine is the direct cause.")
        )
        doctor = (
            "If the symptom began after starting the medicine or after a dose change, or keeps recurring/worsening, contact your prescriber or pharmacist with the timing and your other medicines. "
            "Do not stop or change a prescribed medicine on your own."
        )
    return {
        "key": "medication_symptom_relation",
        "emoji": "💊",
        "category": "medication",
        "title": f"{symptom_title} مع {med_name}" if ar else f"{symptom_title} with {med_name}",
        "what": what,
        "causes_label": "💡 معلومات مرتبطة بالسؤال" if ar else "💡 Relevant information",
        "causes": [interact] if interact else [],
        "worry": str(symptom.get("worry") or "").strip(),
        "doctor": doctor,
        "sources": med.get("sources") or [],
        "recognized_topics": [symptom_title, med_name],
        "original_query": q,
        "contextual": True,
        "relation_query": True,
        "query_only": False,
    }



def _health_search_context_relation_result(query, lang):
    """Build a context-aware result for symptom + circumstance queries.

    Examples: "الدوخة مع الحر", "صداع بعد الرياضة", "دوخة مع الصيام".
    This runs before the fuzzy glossary so the modifier can never be silently
    discarded.  Known contexts get a local safe explanation; unknown relation
    phrases stay query-first and are handed to the AI/fallback as a whole.
    """
    q = " ".join(str(query or "").strip().split())[:600]
    if not q:
        return None
    ar = lang != "en"
    low = q.lower()
    norm = _normalize_health_query_text(q)

    # Only treat the text as a relation query when there is a meaningful
    # modifier/link.  This prevents a simple topic such as "دوخة" from being
    # unnecessarily wrapped in the relation pipeline.
    relation_terms_ar = (" مع ", " بعد ", " قبل ", " وقت ", " اثناء ", " أثناء ", " عند ", " بسبب ", " من ")
    relation_terms_en = (" with ", " after ", " before ", " during ", " when ", " from ", " because of ")
    has_relation = any(x in (" " + low + " ") for x in (relation_terms_ar if ar else relation_terms_en))
    if not has_relation:
        # Natural shorthand often omits the connector entirely: "صداع الصيام",
        # "دوخة الرياضة", "صداع الحر". Preserve these modifiers instead of
        # falling back to the standalone symptom.
        if ar:
            shorthand_terms = ("الحر", "بالحر", "الصيام", "صايم", "صائم", "الرياضه", "الرياضة", "تمرين", "المجهود")
            padded = " " + norm + " "
            has_relation = any((" " + _normalize_health_query_text(x) + " ") in padded for x in shorthand_terms)
        else:
            shorthand_terms = ("hot weather", "heat", "fasting", "exercise", "workout", "exertion")
            padded = " " + low + " "
            has_relation = any((" " + x + " ") in padded for x in shorthand_terms)
    if not has_relation:
        return None

    # Get the most likely symptom/topic only as supporting context.  The full
    # query remains the primary intent/title.
    try:
        candidate = health_search.search_health(q, lang)
    except Exception:
        logging.getLogger(__name__).warning("Handled exception in _health_search_context_relation_result; fallback applied (handler 17444)")
        candidate = None
    if not isinstance(candidate, dict) or candidate.get("category") != "symptom":
        candidate = None

    title = str((candidate or {}).get("title") or ("العرض" if ar else "the symptom")).strip()
    worry = str((candidate or {}).get("worry") or "").strip()
    doctor = str((candidate or {}).get("doctor") or "").strip()

    # Heat / hot weather / sun exposure.  This is intentionally generic enough
    # to work with dizziness, headache, nausea, weakness, etc., while still
    # answering the *relationship* the user asked about.
    heat_terms_ar = ("الحر", "حر", "الجو الحار", "الشمس", "حراره الجو", "حرارة الجو", "الحراره", "الحرارة")
    heat_terms_en = ("heat", "hot weather", "hot day", "sun", "sun exposure")
    has_heat = any(_normalize_health_query_text(x) in norm for x in heat_terms_ar) if ar else any(x in low for x in heat_terms_en)
    if has_heat:
        dizziness = (("دوخ" in norm) or ("دوار" in norm)) if ar else any(x in low for x in ("dizzy", "dizziness", "lightheaded", "vertigo"))
        if ar:
            if dizziness:
                what = (
                    "الدوخة مع الحر قد تكون مرتبطة بالجفاف أو الإجهاد الحراري؛ فالحر يزيد فقدان السوائل وقد يوسّع الأوعية الدموية، "
                    "وهذا قد يسبب خفة الرأس أو عدم الاتزان خصوصًا مع الوقوف أو المجهود. انتقل لمكان أبرد، ارتح، واشرب سوائل على دفعات إذا لم يكن لديك مانع طبي من ذلك."
                )
                causes = [
                    "الجفاف أو قلة شرب السوائل",
                    "الإجهاد الحراري أو التعرض الطويل للجو الحار",
                    "انخفاض الضغط مع الحر أو الوقوف المفاجئ",
                    "قلة الأكل أو المجهود مع الحرارة",
                ]
                worry_text = (
                    "اطلب مساعدة عاجلة إذا صاحبت الدوخة حالة إغماء أو تشوش، صعوبة في الكلام أو التنفس، ضعف شديد، قيء متكرر، "
                    "جلد شديد السخونة مع تدهور الوعي، أو إذا لم تتحسن بعد التبريد والراحة والسوائل."
                )
                doctor_text = (
                    "إذا كانت الدوخة تتكرر كلما تعرضت للحر، أو استمرت رغم التبريد وشرب السوائل، أو لديك أدوية للضغط/السكر أو مرض مزمن، فالأفضل مراجعة مختص."
                )
            else:
                what = (
                    f"سؤالك عن علاقة {title} بالحر. التعرض للجو الحار قد يزيد بعض الأعراض بسبب الجفاف والإجهاد الحراري وتغيّر ضغط الدم، "
                    "لذلك المهم هو التوقيت: هل يبدأ العرض أثناء الحر أو المجهود ويتحسن بعد التبريد والراحة والسوائل؟"
                )
                causes = ["الجفاف", "الإجهاد الحراري", "المجهود مع الحرارة", "تغيّر ضغط الدم مع الحر"]
                worry_text = worry or "اطلب تقييمًا عاجلًا إذا ظهر إغماء، تشوش، صعوبة تنفس، ضعف شديد أو تدهور سريع."
                doctor_text = doctor or "راجع مختصًا إذا تكرر العرض مع الحر أو لم يتحسن بعد التبريد والراحة والسوائل."
            return {
                "key": "heat_context_relation",
                "emoji": "☀️",
                "category": "symptom",
                "title": q,
                "what": what,
                "causes_label": "💡 لماذا قد يحدث مع الحر؟",
                "causes": causes,
                "worry": worry_text,
                "doctor": doctor_text,
                "sources": [],
                "recognized_topics": [x for x in (title, "الحر") if x],
                "original_query": q,
                "contextual": True,
                "relation_query": True,
                "query_only": False,
            }
        else:
            if dizziness:
                what = (
                    "Dizziness in hot weather can be related to dehydration or heat exhaustion. Heat increases fluid loss and can lower blood pressure, "
                    "which may cause lightheadedness, especially with standing or exertion. Move somewhere cooler, rest, and sip fluids if you do not have a medical reason to restrict them."
                )
                causes = ["Dehydration", "Heat exhaustion", "Lower blood pressure in heat or on standing", "Exertion or not eating enough in hot weather"]
                worry_text = (
                    "Seek urgent help for fainting, confusion, trouble speaking or breathing, severe weakness, repeated vomiting, very hot skin with altered awareness, "
                    "or symptoms that do not improve after cooling, rest, and fluids."
                )
                doctor_text = "If this keeps happening in heat, persists despite cooling/hydration, or you take blood-pressure/diabetes medicines or have a chronic condition, seek medical review."
            else:
                what = (
                    f"Your question is about {title} in hot weather. Heat can worsen some symptoms through dehydration, heat strain, and blood-pressure changes; "
                    "the timing and whether it improves with cooling/rest/fluids are useful clues."
                )
                causes = ["Dehydration", "Heat strain", "Exertion in hot weather", "Blood-pressure changes"]
                worry_text = worry or "Seek urgent care for fainting, confusion, breathing difficulty, severe weakness, or rapid deterioration."
                doctor_text = doctor or "Seek medical review if it repeatedly happens in heat or does not improve with cooling, rest, and fluids."
            return {
                "key": "heat_context_relation", "emoji": "☀️", "category": "symptom", "title": q,
                "what": what, "causes_label": "💡 Why it can happen in heat", "causes": causes,
                "worry": worry_text, "doctor": doctor_text, "sources": [],
                "recognized_topics": [x for x in (title, "heat") if x], "original_query": q,
                "contextual": True, "relation_query": True, "query_only": False,
            }

    # Exercise / exertion context.
    exercise_terms_ar = ("رياضه", "رياضة", "تمرين", "التمرين", "مجهود", "المشي", "الجري")
    exercise_terms_en = ("exercise", "workout", "running", "run", "walking", "exertion")
    has_exercise = any(_normalize_health_query_text(x) in norm for x in exercise_terms_ar) if ar else any(x in low for x in exercise_terms_en)
    if has_exercise:
        if ar:
            return {
                "key": "exercise_context_relation", "emoji": "🏃", "category": "symptom", "title": q,
                "what": f"سؤالك عن {title} مع أو بعد المجهود. قد يرتبط ذلك بالجفاف، شدة التمرين، قلة الأكل، أو تغيّر الضغط/السكر أثناء النشاط؛ التوقيت وشدة المجهود والأعراض المصاحبة مهمة.",
                "causes_label": "💡 عوامل مرتبطة بالمجهود", "causes": ["الجفاف", "مجهود أعلى من المعتاد", "قلة الأكل أو انخفاض السكر", "تغيّر الضغط أثناء أو بعد التمرين"],
                "worry": worry or "اطلب رعاية عاجلة إذا صاحب العرض ألم صدر، ضيق تنفس شديد، إغماء، ضعف مفاجئ أو خفقان شديد مستمر.",
                "doctor": doctor or "راجع مختصًا إذا تكرر العرض مع التمرين أو أجبرك على إيقاف نشاطك باستمرار.",
                "sources": [], "recognized_topics": [title, "المجهود"], "original_query": q,
                "contextual": True, "relation_query": True, "query_only": False,
            }
        return {
            "key": "exercise_context_relation", "emoji": "🏃", "category": "symptom", "title": q,
            "what": f"Your question is about {title} with or after exertion. Dehydration, exercise intensity, not eating enough, or blood-pressure/glucose changes can contribute; timing and accompanying symptoms matter.",
            "causes_label": "💡 Exertion-related factors", "causes": ["Dehydration", "Higher-than-usual exertion", "Not eating enough or low glucose", "Blood-pressure changes during/after exercise"],
            "worry": worry or "Seek urgent care for chest pain, severe shortness of breath, fainting, sudden weakness, or persistent severe palpitations.",
            "doctor": doctor or "Seek medical review if it repeatedly occurs with exercise or regularly forces you to stop activity.",
            "sources": [], "recognized_topics": [title, "exercise"], "original_query": q,
            "contextual": True, "relation_query": True, "query_only": False,
        }

    # Fasting / not eating context.
    fasting_terms_ar = ("صيام", "صايم", "صائم", "جوع", "بدون اكل", "بدون أكل")
    fasting_terms_en = ("fasting", "fasted", "not eating", "hungry")
    has_fasting = any(_normalize_health_query_text(x) in norm for x in fasting_terms_ar) if ar else any(x in low for x in fasting_terms_en)
    if has_fasting:
        if ar:
            return {
                "key": "fasting_context_relation", "emoji": "🥤", "category": "symptom", "title": q,
                "what": f"سؤالك عن {title} أثناء الصيام أو مع قلة الأكل. قد يرتبط ذلك بنقص السوائل، انخفاض السكر، قلة النوم أو الكافيين، ويعتمد التقييم على شدته والأدوية والأمراض المزمنة.",
                "causes_label": "💡 عوامل محتملة أثناء الصيام", "causes": ["قلة السوائل", "انخفاض السكر أو تأخر الوجبات", "قلة النوم", "تغيّر تناول الكافيين"],
                "worry": worry or "اطلب مساعدة عاجلة إذا حدث إغماء، تشوش، ضعف شديد أو أعراض انخفاض سكر شديد.",
                "doctor": doctor or "إذا كان لديك سكري أو أدوية للسكر/الضغط أو يتكرر العرض أثناء الصيام، ناقش الأمر مع طبيبك.",
                "sources": [], "recognized_topics": [title, "الصيام"], "original_query": q,
                "contextual": True, "relation_query": True, "query_only": False,
            }
        return {
            "key": "fasting_context_relation", "emoji": "🥤", "category": "symptom", "title": q,
            "what": f"Your question is about {title} while fasting or not eating enough. Reduced fluids, low glucose, sleep changes, or caffeine changes may contribute; severity, medicines, and chronic conditions matter.",
            "causes_label": "💡 Possible fasting-related factors", "causes": ["Low fluid intake", "Low glucose or delayed meals", "Sleep changes", "Caffeine changes"],
            "worry": worry or "Seek urgent help for fainting, confusion, severe weakness, or severe low-blood-sugar symptoms.",
            "doctor": doctor or "If you have diabetes, take glucose/blood-pressure medicines, or this repeatedly happens while fasting, discuss it with your clinician.",
            "sources": [], "recognized_topics": [title, "fasting"], "original_query": q,
            "contextual": True, "relation_query": True, "query_only": False,
        }

    # Unknown multi-part relationship: preserve the complete relationship and
    # never substitute the standalone glossary card.  The AI answer (when
    # permitted) will handle the relation; the local fallback remains honest.
    return {
        "key": "generic_context_relation",
        "emoji": (candidate or {}).get("emoji") or "🩺",
        "category": (candidate or {}).get("category") or "question",
        "title": q,
        "what": "",
        "causes": [],
        "worry": worry,
        "doctor": doctor,
        "sources": [],
        "recognized_topics": [title] if title and title not in ("العرض", "the symptom") else [],
        "original_query": q,
        "contextual": True,
        "relation_query": True,
        "query_only": True,
    }



def _search_contextual_structured_result(query, lang):
    """Return a structured result for context-dependent health queries.

    This runs *before* the generic glossary matcher so a phrase such as
    "الغثيان مع الدورة" cannot be reduced to an unrelated standalone topic.
    The helper is intentionally conservative: it only handles combinations
    where the context materially changes the answer.
    """
    q = " ".join(str(query or "").strip().split())[:600]
    if not q:
        return None
    low = q.lower()
    norm = _normalize_health_query_text(q)
    ar = lang != "en"

    # Relationship queries (for example: symptom + medicine) must be resolved
    # before generic symptom matching so the second entity is never discarded.
    relation = _health_search_relation_result(q, lang)
    if relation is not None:
        return relation

    # V202: common Arabic shorthand can omit a connector entirely (for example
    # "غثيان الحر"). Handle the phrase deterministically before fuzzy matching
    # so users do not need to pick a nearby suggestion first.
    heat_terms_ar = ("الحر", "حر", "الجو الحار", "الشمس", "حراره الجو", "حرارة الجو")
    heat_terms_en = ("heat", "hot weather", "hot day", "sun", "sun exposure")
    nausea_terms_ar = ("غثيان", "الغثيان", "لوعه", "لوعة", "قرفه", "ترجيع", "استفراغ", "قيء")
    nausea_terms_en = ("nausea", "nauseous", "queasy", "vomit", "vomiting", "sick to stomach")
    has_heat = any(_normalize_health_query_text(x) in norm for x in heat_terms_ar) if ar else any(x in low for x in heat_terms_en)
    has_nausea = (("غث" in norm) or any(_normalize_health_query_text(x) in norm for x in nausea_terms_ar)) if ar else any(x in low for x in nausea_terms_en)
    if has_heat and has_nausea:
        if ar:
            return {
                "key": "heat_nausea", "emoji": "☀️", "category": "symptom",
                "title": "الغثيان مع الحر",
                "what": "قد يظهر الغثيان في الجو الحار مع الجفاف أو الإجهاد الحراري، خصوصًا إذا صاحبه تعرّق أو دوخة أو ضعف. انتقل إلى مكان أبرد، ارتح، برّد الجلد، وخذ السوائل على دفعات إذا كنت واعيًا وقادرًا على الشرب.",
                "direct_answer": "الغثيان مع الحر قد يرتبط بالجفاف أو الإجهاد الحراري، خصوصًا مع التعرّق أو الدوخة أو الضعف. انتقل لمكان أبرد، ارتح وبرّد جسمك واشرب سوائل على دفعات إذا كنت قادرًا على الشرب. اطلب مساعدة عاجلة عند التشوش أو الإغماء أو التشنج أو ارتفاع حرارة شديد، أو إذا لم تتحسن بعد التبريد.",
                "curated_answer": True,
                "causes_label": "💡 عوامل قد ترتبط بالحر",
                "causes": ["الجفاف وفقد السوائل مع التعرّق", "الإجهاد الحراري", "المجهود أو الوقوف الطويل في الجو الحار"],
                "worry": "اطلب مساعدة عاجلة إذا ظهر تشوش، إغماء، تشنج، ارتفاع حرارة شديد أو تدهور سريع، أو إذا لم تتحسن الأعراض بعد التبريد.",
                "doctor": "إذا تكرر الغثيان كلما تعرضت للحر أو استمر رغم التبريد والسوائل، فالأفضل مناقشته مع مختص، خصوصًا مع الأمراض المزمنة أو الأدوية التي قد تتأثر بالحر.",
                "sources": [
                    {"name":"Heat exhaustion and heatstroke", "organization":"NHS", "url":"https://www.nhs.uk/conditions/heat-exhaustion-heatstroke/"},
                    {"name":"About Heat and Your Health", "organization":"CDC", "url":"https://www.cdc.gov/heat-health/about/index.html"},
                ],
                "recognized_topics": ["الغثيان", "الحر"], "original_query": q,
                "contextual": True, "relation_query": True, "query_only": False,
            }
        return {
            "key": "heat_nausea", "emoji": "☀️", "category": "symptom",
            "title": "Nausea in hot weather",
            "what": "Nausea in hot weather can occur with dehydration or heat exhaustion, especially with sweating, dizziness, or weakness. Move somewhere cooler, rest, cool the skin, and sip fluids if you are alert and able to drink.",
            "direct_answer": "Nausea in hot weather can be related to dehydration or heat exhaustion, especially with sweating, dizziness, or weakness. Move somewhere cooler, rest, cool your body, and sip fluids if you can drink safely. Seek urgent help for confusion, fainting, seizures, very high temperature, rapid deterioration, or symptoms that do not improve with cooling.",
            "curated_answer": True,
            "causes_label": "💡 Heat-related factors",
            "causes": ["Dehydration and fluid loss from sweating", "Heat exhaustion", "Exertion or prolonged standing in hot weather"],
            "worry": "Seek urgent help for confusion, fainting, seizures, very high temperature, rapid deterioration, or symptoms that do not improve with cooling.",
            "doctor": "If nausea repeatedly occurs in hot weather or persists despite cooling and fluids, discuss it with a clinician, especially if you have chronic conditions or medicines affected by heat.",
            "sources": [
                {"name":"Heat exhaustion and heatstroke", "organization":"NHS", "url":"https://www.nhs.uk/conditions/heat-exhaustion-heatstroke/"},
                {"name":"About Heat and Your Health", "organization":"CDC", "url":"https://www.cdc.gov/heat-health/about/index.html"},
            ],
            "recognized_topics": ["nausea", "heat"], "original_query": q,
            "contextual": True, "relation_query": True, "query_only": False,
        }

    context_relation = _health_search_context_relation_result(q, lang)
    if context_relation is not None and context_relation.get("key") != "generic_context_relation":
        return context_relation

    period_ar = ("الدوره", "الحيض", "الطمث")
    nausea_ar = ("غثيان", "لوعه", "لوعة", "قرفه", "ترجيع", "استفراغ", "قيء")
    period_en = ("period", "menstrual", "menstruation", "menses")
    nausea_en = ("nausea", "nauseous", "vomit", "vomiting", "queasy", "sick to stomach")

    # Stem checks intentionally catch spelling variants such as الدورة/الدوره
    # and phrases like "الغثيان وقت الدورة" without relying on fuzzy glossary ranking.
    has_period = (("دور" in norm and any(x in norm for x in ("مع", "وقت", "اثناء", "قبل", "بعد"))) or
                  any(_normalize_health_query_text(k) in norm for k in period_ar)) if ar else any(k in low for k in period_en)
    has_nausea = (("غث" in norm) or any(_normalize_health_query_text(k) in norm for k in nausea_ar)) if ar else any(k in low for k in nausea_en)
    if has_period and has_nausea:
        if ar:
            return {
                "key": "period_nausea",
                "emoji": "🤢",
                "category": "symptom",
                "title": "الغثيان مع الدورة الشهرية",
                "what": (
                    "قد يحدث الغثيان قبل الدورة أو أثناءها لدى بعض الأشخاص بسبب التغيّرات الهرمونية "
                    "وزيادة مواد مثل البروستاغلاندينات التي ترتبط بتقلصات الدورة. وجود الغثيان مع الدورة "
                    "لا يعني وحده وجود مشكلة خطيرة، لكن شدة الأعراض وتكرارها مهمان."
                ),
                "causes": [
                    "التغيّرات الهرمونية المصاحبة للدورة",
                    "تقلصات الدورة وارتفاع البروستاغلاندينات",
                    "الألم أو الصداع المصاحب للدورة",
                    "قلة الأكل أو الجفاف أثناء أيام الدورة",
                    "حساسية المعدة أو أعراض هضمية تتزامن مع الدورة",
                ],
                "causes_label": "💡 لماذا قد يحدث؟",
                "worry": (
                    "اطلب رعاية عاجلة إذا كان القيء متكررًا لدرجة عدم القدرة على الاحتفاظ بالسوائل، "
                    "أو حدث إغماء، أو ألم شديد وغير معتاد، أو نزيف شديد جدًا، أو ظهرت علامات جفاف واضحة."
                ),
                "doctor": (
                    "راجع مختصًا إذا تكرر الغثيان مع كل دورة وأثر في حياتك اليومية، أو أصبح أشد من المعتاد، "
                    "أو صاحبه ألم شديد أو أعراض جديدة."
                ),
                "sources": [],
                "recognized_topics": ["الغثيان", "الدورة الشهرية"],
                "original_query": q,
                "contextual": True,
            }
        return {
            "key": "period_nausea",
            "emoji": "🤢",
            "category": "symptom",
            "title": "Nausea around your period",
            "what": (
                "Nausea can occur before or during a period for some people because of hormonal changes "
                "and prostaglandins associated with menstrual cramps. The symptom alone does not mean "
                "there is a serious problem; severity and recurrence matter."
            ),
            "causes": [
                "Hormonal changes around menstruation",
                "Menstrual cramps and prostaglandins",
                "Period-related pain or headache",
                "Eating less or becoming mildly dehydrated",
                "Digestive sensitivity that coincides with the period",
            ],
            "causes_label": "💡 Why it can happen",
            "worry": (
                "Seek urgent care if vomiting is repeated and you cannot keep fluids down, you faint, "
                "pain is severe or unusual, bleeding is extremely heavy, or you develop clear signs of dehydration."
            ),
            "doctor": (
                "See a clinician if nausea happens with most periods and disrupts daily life, becomes more severe, "
                "or is accompanied by severe pain or new symptoms."
            ),
            "sources": [],
            "recognized_topics": ["nausea", "menstruation"],
            "original_query": q,
            "contextual": True,
        }

    if context_relation is not None:
        return context_relation
    return None



def _health_search_question_answer(query, lang, search_result=None):
    """Answer the user's *full* health-search question, preserving modifiers.

    The structured glossary result is still returned below for sources and
    topic details; this short answer prevents a natural-language question from
    being reduced to a single symptom keyword.
    """
    q = " ".join(str(query or "").split())[:600]
    if not q:
        return ""
    if isinstance(search_result, dict) and search_result.get("curated_answer"):
        return search_result["direct_answer"]
    # Relationship results always win over standalone symptom handlers.
    if isinstance(search_result, dict) and search_result.get("relation_query"):
        relation_text = str(search_result.get("what") or "").strip()
        if relation_text:
            return _strip_search_answer_heading(_assistant_compact_response(relation_text, lang, "search"), lang)

    contextual = _assistant_contextual_health_answer(q, lang)
    if contextual:
        return _strip_search_answer_heading(_assistant_compact_response(contextual, lang, "search"), lang)

    low = q.lower()
    ar = lang != "en"
    # Treat *every* non-empty health search as a full query. A one- or two-word
    # entry means "explain this health topic" rather than "pick a fuzzy card".

    # First answer common question intents directly from the structured search
    # result.  This keeps the search useful even when no external model is used.
    if isinstance(search_result, dict):
        causes = [str(x).strip() for x in (search_result.get("causes") or []) if str(x).strip()][:5]
        worry = str(search_result.get("worry") or "").strip()
        doctor = str(search_result.get("doctor") or "").strip()
        what = str(search_result.get("what") or "").strip()
        intent = str(search_result.get("search_intent_v4") or "").strip()
        if (intent == "causes" or (ar and any(x in low for x in ("ليش", "لماذا", "ما سبب", "وش سبب", "ايش سبب")))) and causes:
            return (("من الأسباب المحتملة المرتبطة بسؤالك: " + "، ".join(causes) + ". السبب الدقيق يعتمد على السياق ولا يمكن تأكيده من البحث وحده.") if ar else
                    ("Possible causes related to your question include: " + ", ".join(causes) + ". The exact cause depends on context and cannot be confirmed by search alone."))
        if intent == "urgency" or (ar and any(x in low for x in ("متى أراجع", "متى اروح", "متى أروح", "متى يحتاج", "هل خطير"))) or ((not ar) and any(x in low for x in ("when should", "when do i", "when to see", "is it serious"))):
            detail = worry or doctor
            if detail:
                return detail
        if intent == "care" or (ar and any(x in low for x in ("وش اسوي", "وش أسوي", "ماذا أفعل", "ايش اسوي", "كيف اتصرف"))) or ((not ar) and any(x in low for x in ("what should i do", "what can i do", "how should i"))):
            detail = doctor or what
            if detail:
                return detail
        if intent == "normality" or (ar and any(x in low for x in ("هل طبيعي", "طبيعي؟", "هل هذا طبيعي"))) or ((not ar) and any(x in low for x in ("is this normal", "is it normal"))):
            if what:
                return what + ((" راجع مختصًا إذا استمر العرض أو ساء." if ar else " Seek medical review if it persists or worsens."))
        if intent == "meaning" and what:
            return what

    # V202: if the local structured knowledge already answers the query, keep
    # the wording stable across repeated searches. The external model is used
    # only for genuine content gaps / query-only cases.
    if isinstance(search_result, dict) and not search_result.get("query_only"):
        what = str(search_result.get("what") or "").strip()
        self_care = str(search_result.get("self_care") or "").strip()
        if what:
            stable = what
            if self_care:
                stable += ((" ما يمكنك فعله الآن: " if ar else " What you can do now: ") + self_care)
            return _strip_search_answer_heading(_assistant_compact_response(stable, lang, "search"), lang)
        topics = [t for t in (search_result.get("matched_topics") or []) if isinstance(t, dict)]
        if topics:
            names = [str(t.get("title") or "").strip() for t in topics[:3] if str(t.get("title") or "").strip()]
            if names:
                return (("يعرض البحث المعلومات الموثقة المرتبطة بـ " + "، ".join(names) + ". راجع البطاقات أدناه لكل موضوع على حدة." ) if ar else
                        ("The search shows trusted information related to " + ", ".join(names) + ". Review the cards below for each topic separately."))

    context = ""
    if isinstance(search_result, dict):
        safe = {
            "title": search_result.get("title"),
            "what": search_result.get("what"),
            "causes": (search_result.get("causes") or [])[:5],
            "worry": search_result.get("worry"),
            "doctor": search_result.get("doctor"),
            "matched_topics": [
                {"title": t.get("title"), "what": t.get("what"), "causes": (t.get("causes") or [])[:4], "worry": t.get("worry")}
                for t in (search_result.get("matched_topics") or [])[:3] if isinstance(t, dict)
            ],
        }
        context = json.dumps(safe, ensure_ascii=False)[:5000]
    try:
        # Only send the exact free-text question to the external assistant when
        # the user has already allowed service processing.
        if not _service_consent_ok():
            raise RuntimeError("service_consent_required_for_external_search_answer")
        client = analysis_core._groq_client()
        prompt = (
            ("أنت مساعد بحث صحي توعوي داخل SymptoSense. أجب عن سؤال المستخدم كاملًا كما كُتب، ولا تختزل السؤال إلى اسم العرض فقط. "
             "اعتبر كل كلمات السياق جزءًا أساسيًا من السؤال: التوقيت، المكان، العمر، الحمل أو الدورة، الطعام، النوم، الأدوية، التحاليل، الأمراض المزمنة والمدة. "
             "يمكن أن يكون السؤال عن عرض، مرض، دواء، تحليل، تغذية، نوم، صحة نفسية، حمل/دورة، إسعاف أو معلومة صحية عامة. "
             "استخدم السياق الطبي المنظم فقط إذا كان مرتبطًا فعلًا بالسؤال، ولا تخترع تشخيصًا أو جرعة دوائية ولا تطلب إيقاف/بدء دواء موصوف. "
             "إذا لم تعرف المصطلح أو لم تكن المعلومات كافية، قل ذلك بوضوح ثم أعطِ أقرب إرشاد آمن متعلق بالسؤال نفسه؛ لا تُرجع إجابة فارغة ولا تستبدل الموضوع بموضوع مختلف. "
             "أجب مباشرة في 2-4 جمل قصيرة، واذكر علامة خطر فقط إذا كانت مرتبطة بالسؤال.\n"
             if ar else
             "You are SymptoSense's educational health-search assistant. Answer the user's complete health query exactly as asked; never reduce it to one fuzzy symptom keyword. "
             "Treat timing, location, age, pregnancy/period context, food, sleep, medicines, lab tests, chronic conditions, and duration as essential modifiers. "
             "The query may concern a symptom, condition, medicine, lab test, nutrition, sleep, mental wellbeing, pregnancy/periods, first aid, or general health information. "
             "Use structured context only when it is truly relevant; do not diagnose, prescribe doses, or advise starting/stopping prescribed medication. "
             "If the term is unknown or information is insufficient, say so clearly and give the closest safe guidance that still addresses the same query; never return a blank answer or substitute an unrelated topic. Answer directly in 2-4 short sentences.\n")
            + ("سؤال المستخدم: " if ar else "User question: ") + q + "\n"
            + ("سياق البحث المنظم: " if ar else "Structured search context: ") + context
        )
        r = client.chat.completions.create(
            model=os.environ.get("GROQ_TEXT_MODEL", "openai/gpt-oss-120b").strip() or "openai/gpt-oss-120b",
            messages=[{"role":"user","content":prompt}],
            temperature=0.25,
            max_completion_tokens=220,
            timeout=8,
        )
        answer = str(r.choices[0].message.content or "").strip()
        if answer:
            return _strip_search_answer_heading(_assistant_compact_response(answer, lang, "search"), lang)
    except Exception:
        logging.getLogger(__name__).warning("Handled exception in _health_search_question_answer; fallback applied (handler 17801)")
        pass

    # Local fallback: a non-empty health search must always return a useful,
    # honest result even when the external AI service is unavailable. Never
    # substitute an unrelated fuzzy topic merely to avoid an empty response.
    if isinstance(search_result, dict):
        topics = search_result.get("matched_topics") or []
        if topics:
            names = [str(t.get("title") or "").strip() for t in topics[:2] if str(t.get("title") or "").strip()]
            if names:
                return (("سؤالك يجمع بين " + " و".join(names) + ". المعلومات أدناه تشرح الأجزاء المرتبطة، لكن لا يمكن تأكيد العلاقة بينها من البحث وحده. إذا ذكرت التوقيت والمدة والأدوية أو النتائج المرتبطة يمكن تضييق الإجابة أكثر.") if ar else
                        ("Your question combines " + " and ".join(names) + ". The information below explains the related parts, but the relationship cannot be confirmed from search alone. Adding timing, duration, medicines, or related results can make the answer more specific."))
        what = str(search_result.get("what") or "").strip()
        if what:
            return what

    # Universal safe fallback for queries that are not covered by the structured
    # search index. Reuse the curated local assistant fallback first so common
    # natural-language questions (for example painless knee clicking) still get
    # a directly useful answer when the external provider is offline.
    local_general = _assistant_general_local_fallback(q, lang)
    if local_general:
        return _strip_search_answer_heading(_assistant_compact_response(local_general, lang, "search"), lang)
    emoji, category = _health_search_topic_meta(q, lang)
    if ar:
        if category == "medication":
            return (f"بحثك هو: «{q}». لم أجد في قاعدة المعرفة المحلية معلومة موثوقة كافية عن هذا الدواء أو العلاقة المذكورة، لذلك لن أستبدلها بمعلومة عن دواء آخر. "
                    "اكتب اسم الدواء كما يظهر على العبوة مع العرض أو السؤال الذي تريد معرفته، وإذا كانت خدمة المساعد الذكي مفعّلة فسيجيب عن العلاقة كاملة.")
        if category == "test":
            return (f"بحثك هو: «{q}». لا توجد لدي حاليًا بيانات محلية كافية لتفسير هذه النتيجة بدقة من الاسم وحده. "
                    "أضف اسم الفحص والقيمة والوحدة والمدى المرجعي إن وُجد، وسأتعامل معها كسؤال واحد بدل تخمين نتيجة غير مرتبطة.")
        return (f"بحثك هو: «{q}». لم أجد تطابقًا موثوقًا كافيًا في قاعدة المعرفة المحلية، لذلك لن أعرض موضوعًا مختلفًا لمجرد أنه قريب في الاسم. "
                "إذا كانت خدمة المساعد الذكي مفعّلة فسيجيب عن السؤال كاملًا؛ ويمكنك أيضًا إضافة العمر، المدة، التوقيت، الأدوية أو الأعراض المصاحبة للحصول على إجابة أدق.")
    if category == "medication":
        return (f"Your search is: “{q}”. I do not have enough trusted local information about this medicine or the relationship you mentioned, so I will not substitute an unrelated medicine. "
                "Enter the medicine name as shown on the package together with the symptom or question; when the AI assistant is enabled it can answer the full relationship.")
    if category == "test":
        return (f"Your search is: “{q}”. I do not have enough local information to interpret this result accurately from the name alone. "
                "Add the test name, value, unit, and reference range when available so the whole question can be interpreted together.")
    return (f"Your search is: “{q}”. I could not find a sufficiently reliable local match, so I will not show an unrelated topic just because its wording is similar. "
            "When the AI assistant is enabled it can answer the full question; adding age, duration, timing, medicines, or accompanying symptoms can also make the answer more specific.")


def bind(namespace):
    """Inject the webapp helpers this module needs (proxies, resolved lazily on every call)."""
    missing = [n for n in DEPS if n not in namespace]
    if missing:
        raise RuntimeError("services.search_answers: missing dependencies %s" % missing)
    g = globals()
    for n in DEPS:
        g[n] = _inject.dependency(namespace, n)
