#!/usr/bin/env python3
"""Regenerate trusted_sources_v251.py from verified source JSON files.

Input (one dir): out_dis_*.json, out_kb_*.json, out_blood.json, each produced by a run that fetched every
URL and confirmed the page matches the topic.  Usage: python tools/build_trusted_sources.py <dir>
"""
import glob
import json
import pprint
import sys
import urllib.parse

DOMAIN_ORG = {
    "medlineplus.gov": "medlineplus", "www.mayoclinic.org": "mayo-clinic", "my.clevelandclinic.org": "cleveland-clinic",
    "health.clevelandclinic.org": "cleveland-clinic", "www.cdc.gov": "cdc", "www.who.int": "who", "www.nhs.uk": "nhs",
    "www.hopkinsmedicine.org": "johns-hopkins", "www.testing.com": "testing-com", "www.kidney.org": "national-kidney-foundation",
    "www.healthychildren.org": "aap-healthychildren", "diabetes.org": "ada", "ods.od.nih.gov": "nih-ods",
    "www.acog.org": "acog", "www.heart.org": "aha", "www.aad.org": "aad", "www.niddk.nih.gov": "niddk",
    "www.nhlbi.nih.gov": "nhlbi", "www.ninds.nih.gov": "ninds", "www.niams.nih.gov": "niams", "www.nidcr.nih.gov": "nidcr",
    "www.nimh.nih.gov": "nimh", "www.nidcd.nih.gov": "nidcd",
}


def _rows(items):
    out, seen = [], set()
    for it in items or []:
        url = (it.get("url") or "").strip()
        host = urllib.parse.urlparse(url).netloc
        if not url.startswith("https://") or host not in DOMAIN_ORG or url in seen:
            continue
        seen.add(url)
        out.append((DOMAIN_ORG[host], it.get("title_ar") or it.get("title_en") or "", it.get("title_en") or "", url))
    return out


def main(src):
    dis, kb, blood = {}, {}, {}
    for f in sorted(glob.glob(f"{src}/out_dis_*.json")):
        for slug, items in json.load(open(f, encoding="utf-8")).items():
            if _rows(items):
                dis[slug] = _rows(items)
    for f in sorted(glob.glob(f"{src}/out_kb_*.json")):
        for key, items in json.load(open(f, encoding="utf-8")).items():
            if _rows(items):
                kb[key] = _rows(items)
    for key, v in json.load(open(f"{src}/out_blood.json", encoding="utf-8")).items():
        entry = {}
        for part in ("primary", "secondary"):
            r = _rows([v.get(part)] if v.get(part) else [])
            if r:
                entry[part] = r[0]
        if entry:
            blood[key] = entry
    with open("trusted_sources_v251.py", "w", encoding="utf-8") as fh:
        fh.write('"""Verified additional authoritative sources (V251). GENERATED by tools/build_trusted_sources.py.\n\n'
                 'Every URL was fetched and matched to its topic on 2026-10-07. Rows are (org, title_ar, title_en, url).\n'
                 'Re-verify with tools/check_sources.py; clinician sign-off is still required (MEDICAL_REVIEW_NEEDED.md)."""\n'
                 'LAST_VERIFIED = "2026-10-07"\n\n')
        for name, obj in (("DISEASE_SOURCES", dis), ("SEARCH_SOURCES", kb), ("BLOOD_SOURCES", blood)):
            fh.write(f"{name} = " + pprint.pformat(obj, width=140, sort_dicts=True) + "\n\n")
    print(len(dis), len(kb), len(blood))


if __name__ == "__main__":
    main(sys.argv[1])
